### ISSUE TITLE
[FR] Allow pages to be statically rendered without a web server

### ISSUE THREAD

**Issue by lyptt** [sveltejs/sapper#1003]
**Is your feature request related to a problem? Please describe.**
With SSR, one trend that seems to be growing in popularity is build-time rendering, i.e. statically rendering all of your pages and storing them in an S3 bucket or some other form of blob storage, rather than relying on a web server to render pages on the fly.

This has the benefit of not having to pay for any infrastructure whatsoever beyond static file hosting costs, and if your site doesn't change that often, you can heavily cache the resulting files.

**Describe the solution you'd like**
Either via a build flag, or separate configuration, build a bundled NodeJS script containing a function which can be invoked with various initial props for your application root (e.g. current URL, default data, etc), which will in turn spit out the HTML for the page.

**Describe alternatives you've considered**
One alternative would be to spawn the Sapper web server as a child process of a NodeJS script, make a bunch of requests to it, and store the output in S3 buckets, but this feels a bit hacky.

**How important is this feature to you?**
This is basically the main thing holding me back from using Sapper in production. I don't want to be running NodeJS web services when an S3 bucket is so much cheaper and basically maintenance-free.

**Comment by nickolasgregory** [comment]
I think that what Sapper [Exporting](https://sapper.svelte.dev/docs#Exporting) is intended to do.

**Comment by lyptt** [comment]
Interesting! I asked if this was possible on Discord and I was told in no uncertain terms it wasn't.

**Comment by nickolasgregory** [comment]
Though you'll still need a webserver of some sort. Apache/nginx or Node etc...

**Comment by lyptt** [comment]
It's just a one shot command to run right? I'm assuming that'll work fine within a CI environment, i.e. it won't require management via child_process or something.

**Comment by pngwn** [comment]
Yup. Should work fine in CI then you’ll have a completely static site. Not sure who told you it isn’t possible but it definitely is.
