### ISSUE TITLE
Refresh of some pages shows 404

### ISSUE THREAD

**Issue by oren** [sveltejs/sapper#1009]
I am hosting my svelte on github pages. why refreshing this page (https://oren.github.io/food/manage-food/export) show 404 and this page (https://oren.github.io/food/manage-food/import) is fine?

How to ensure refresh works in every page of my app?

my code is here: https://github.com/oren/food

**Comment by Kiho** [comment]
In my case I had to implement these
https://github.com/Kiho/smelte-crud-app/blob/master/docs/index.html
https://github.com/Kiho/smelte-crud-app/blob/master/docs/404.html

**Comment by Conduitry** [comment]
Presumably you don't have a link to the export page from anywhere in server-rendered HTML, which is what export uses when crawling your app. Please don't use github issues for support requests.

**Comment by oren** [comment]
Thank you!

I have a few follow up questions:
1. I forgot to mention that this behavior also reproducible on my local dev. Does it changes the answers I got here?
2. Where should I make the code changes above? I don't have index.html or 404.html. Maybe index.html is [src/template.html](https://github.com/oren/food/blob/master/src/template.html) and 404.html is a file I am suppose to create inside the static folder?
3. You mentioned that github issues is not the right place for this question. What alternative do you suggests? I tried the Discord chat but they suggested it might be an issue with sapper. Also if it's not on github, how else others will learn about this issue and the solution? (unless this was part of the official docs)

**Comment by Conduitry** [comment]
https://sapper.svelte.dev/docs#How_it_works describes how export works. If you think you have a situation where the served HTML for your site isn't being crawled correctly, please do open an issue, and include a minimal repro.

**Comment by oren** [comment]
I think the problem was I had multiple files under /manage-food folder: import.svelte, export.svelte and a few others. I just moved everything to the top level folder and the issue was resolved. 

Thanks!

**Comment by oren** [comment]
nope. it seems like even after `rm -r manage-food` and moving the files to the route folder I still get 404 on the export page. I see it both when running `npx serve __sapper__/export/` and on github pages. I'll keep digging before submitting another issue with reproducible steps.

**Comment by oren** [comment]
I was able to reproduce the issue on a new repository. It looks like the issue is related to the fact that my site on github pages is on `/food` and not on `/` but I don't know how to fix it. The problem disappear if I remove `'/food',` line from server.js and run `npx sapper export`. Here is the repository to reproduce it: https://github.com/oren/test-sapper

## 1. The problem:
refresh http://localhost:5000/food/export shows 404

## 2. Step to Reproduce:

```
git clone git@github.com:oren/test-sapper.git
cd test-sapper
npm install
npx sapper export --basepath /food
npx serve __sapper__/export/
```

## 3. Note:
The problem disappear if I remove `'/food',` line from server.js and run `npx sapper export`.

**Comment by oren** [comment]
Should I keep it here or create a new issue?

**Comment by Conduitry** [comment]
`sapper export` only crawls the server-rendered versions of the pages. There is no link to the 'export' page from the 'manage-food' page until `food.length !== 0`, which doesn't happen until code is run on the client.

**Comment by oren** [comment]
Very interesting! 

I added hidden links to the 3 pages that showed the 404 and it's working now: (almost)
```
<a style="visibility: hidden;" href="/food/eat">Choose Food</a>
<a style="visibility: hidden;" href="/food/update-food">Update Food</a>
<a style="visibility: hidden;" href="/food/export">Export Food</a>
```

It's working fine now for the last two links but not for the first one. I noticed that when I hit /food/export with the browser, the browser is adding a slash - /food/export/. This doesn't happened with /food/eat. I solved it by adding a slash to the first link to this:
```
<a style="visibility: hidden;" href="/food/eat/">Choose Food</a>
```
Why do I have to add that slash?

**Comment by theholograms** [comment]
@oren I would suggest this is (and continues to be) a support question to pursue over at discord.

**Comment by oren** [comment]
I figured it out. I had a missing closing <a> tag! Thank you! 

I'll mention my problem and my workaround in the discord chat but unfortunately a chat is not good at archiving finding old information. The next person with this issue will have to spend a lot of time figuring this out. What's your opinion of adding my workaround to the official docs?

**Comment by theholograms** [comment]
The docs already state clearly...

> any pages you want to be included in the exported site must be reachable by <a> elements. Additionally, any non-page routes should be requested in preload, not in onMount or elsewhere

**Comment by oren** [comment]
The problem with this sentence is it make a few assumptions on the knowledge of the reader:
1. what does 'reachable' mean?
1. what does preload means? ("load some data that the page depends on. This is similar to getInitialProps in Next.js or asyncData in Nuxt.js." - what are getInitialProps and asyncData?)
