### ISSUE TITLE
Debug server side

### ISSUE THREAD

**Issue by elPesecillo** [sveltejs/sapper#1013]
Hello,

I am trying to figure it how to debug the server side to do some modifications to the default sapper template, I followed the instructions to debug the server side from the docs, and the ndb opens correctly, but the only file that appears loaded in the gui is the webpack.config.js file:

![image](https://user-images.githubusercontent.com/41170549/69979998-f8fb0e80-14f4-11ea-902a-50684de737b0.png)

There is something else that I need to configure to debug the server.js file?

**Comment by antony** [comment]
@elPesecillo you asked in the correct place first. As the issue template states, this is not a help forum.

Please close this issue and wait for somebody to answer in discord, or ask on stackoverflow using the `svelte` / `sapper` tags.

Your question will not be answered here.

**Comment by elPesecillo** [comment]
@antony Ok sorry
