### ISSUE TITLE
npx degit fails

### ISSUE THREAD

**Issue by edoloughlin** [sveltejs/sapper#1015]
**Describe the bug**

'Get started' instructions fail.

Running `npx degit "sveltejs/sapper-template#rollup" my-app` produces an error:

`! could not download https://github.com/sveltejs/sapper-template/archive/4e0face1bb1988c7a14668798b6258e3514409ae.tar.gz`

**Logs**

n/a

**To Reproduce**

n/a

**Expected behavior**

Clone template from github and degit.

**Stacktraces**

n/a

**Information about your Sapper Installation:**

n/a

**Severity**

Medium

**Additional context**

**Comment by Conduitry** [comment]
Presumably a network error. I'm able to download that URL. If you are having trouble with degit, you can just download a .zip of the rollup branch manually from https://github.com/sveltejs/sapper-template/archive/rollup.zip
