### ISSUE TITLE
Export Error

### ISSUE THREAD

**Issue by jzkitchen** [sveltejs/sapper#102]
As i run "npx sapper export", there is an error "no such file or directory, open '/Users/xxxxx/sapper-pwa/.sapper/service-worker.js'"

It seems that no service-worker.js is generated using "npm run build"..

I wanna try "Export to a static web app"

**Comment by jzkitchen** [comment]
I freshly cloned the repository, then installed all independencies. Also I verified that sapper was 0.5 version. After building and exporting, the error still occurred.

**Comment by jzkitchen** [comment]
After running "npm run build", there is no service-worker.js inside .sapper or dist

**Comment by nolanlawson** [comment]
Found the same issue, can confirm pinning to 0.5.0 fixes it.

**Comment by Rich-Harris** [comment]
Closing as this is fixed in more recent versions — thanks
