### ISSUE TITLE
Is there a way to inject custom variables in the sapper temaplate.html

### ISSUE THREAD

**Issue by ramiroaisen** [sveltejs/sapper#1023]
I have a multi lang site, i wanna to inject the lang in the html tag, something like <html lang="%_sapper_lang_%>

is there a way to do this?

**Comment by antony** [comment]
Hi @ramiroaisen - github isn't the right place for usage questions. If you don't mind closing this issue and come and find me in the [Svelte Discord](https://discordapp.com/invite/yy75DKs) I'll talk you through exactly how I handle this.
