### ISSUE TITLE
this.fetch should { credentials: "include" } per default, if it's an internal resource.

### ISSUE THREAD

**Issue by MatthiasGrandl** [sveltejs/sapper#1026]
On SSR the preload always threw an error and it took me quite a while to figure out, that it's because my credentials didn't get send for the auth middleware. I really think this should be the default for `this.fetch` on internal routes. Opinions?

**Comment by benmccann** [comment]
Agree. It is the default on the browser. It's a bug that the server doesn't match the browser. There's a pending PR for it: https://github.com/sveltejs/sapper/pull/882

**Comment by Conduitry** [comment]
Duplicate of #881, which has been fixed on master by #882.
