### ISSUE TITLE
Make goto work with relative routes

### ISSUE THREAD

**Issue by verschmelzen** [sveltejs/sapper#1033]
When using `goto` method from `'@sapper/app'` on relative paths, i.e. starting with `./`, navigation is made relative to root.

I expect it to work as href in case when route is inside sapper application.

Now for every page that has relative navigation I have to implement `prefetch` and manualy store current path in component variable or reach for `window.location.pathname`.

I am using SSR mode and didn't test behavior in other cases.

**Comment by thgh** [comment]
Related to #984, my preferred workaround is using `$page.path` and `$page.params` however

**Comment by Conduitry** [comment]
Yeah I'd say this is a duplicate of #904.
