### ISSUE TITLE
Able to export page to file instead of directory that can support github page 404

### ISSUE THREAD

**Issue by nghenglim** [sveltejs/sapper#1043]
**Is your feature request related to a problem? Please describe.**
Currently I rewrite my blog with sapper, and host it with github page. however there is a problem that github page require 404.html and not 404/index.html

**Describe the solution you'd like**
when run `sapper export`, provide a way to export svelte page in file whenever possible

**Describe alternatives you've considered**
currently I manually copy paste 404/index.html to 404.html, however I believe due to this reason, some feature like routing will be broken (therefore I make a redirection on this page >.<).

**How important is this feature to you?**
Mainly I need this feature to perform redirection based on the blogpost slug, [example](https://leliam.com/blogposts/rewriting-the-blog-in-sveltejs-@7jnR89DGyH1tRLdznWMTTN/) , currently due to the custom way I do it, seems like it is buggy intermittently

**Additional context**
seems like code inside the `<script></script>` tag in 404.svelte is not working too [in route that redirected to github 404.html](https://leliam.com/route_that_does_not_exist) , I need to add custom script below template.html to simulate a script behavior in 404.svelte, which is not ideal

**Comment by chuvikovd** [comment]
Maybe it is possible to add extra step to `export` crawling process, where script opens `/404` page and saves it to export folder root? This way we can ensure that `_error.svelte` default is used when `404.svelte` not exist.

**Comment by sw-yx** [comment]
i think this can be automated with a bash script, unless the sapper maintainers want to explicitly support a github build target.

**Comment by Conduitry** [comment]
Fixed in 0.27.13 via #1049.
