### ISSUE TITLE
sapper export doesn't export static site

### ISSUE THREAD

**Issue by enkos** [sveltejs/sapper#1044]
I got wordpress posts through api on localhost site

```js
// index.svelte

<script context="module">
	export async function preload(page) {
		const query = page.query
		const postsRes = await this.fetch(`http://temadev_wp.test/wp-json/wp/v2/posts?${queryString}`)

		let posts = await postsRes.json()

		return {posts}
	}
</script>
```

I got `/blog/[slug].svelte`, where i get post by slug

```js
 <script context="module">
 	export async function preload({params}) {
 		const res = await this.fetch(`http://temadev_wp.test/wp-json/wp/v2/posts?slug=${params.slug}`)
 		const post = await res.json()

 		return { post: post[0] }
 	}
 </script>
```

I want to export static site and deploy it to `now` without any api calls on static site. But when I export static site and deploy it to `now`, it makes api calls to my localhost wordpres site. Why?

I can't go to post page. Always get error `500 Failed to fetch`. And i need to refresh browser to load page currectly. Something wrong with links in sapper

Video: https://youtu.be/SKfazX22jo8

**Comment by Conduitry** [comment]
`export` only saves to files the results of requests to the same origin as the main Sapper site (so no rewriting of the fetched URLs needs to happen). You'll need a local endpoint that proxies to your API for these responses to be saved.

GitHub issues aren't the right place for support questions like this, so if you need more help, please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).

**Comment by ConProgramming** [comment]
@Conduitry Even when Sapper saves the results of requests from the same origin in an exported  static site, it refetches the data again. Shouldn't we be able to disable this? If it's saved in the exported html file I don't see a need in Sapper requesting the same data again runtime.

**Comment by Conduitry** [comment]
It doesn't re-run the preload function for the initial page. It does run the preload function on subsequent navigation so you get the SPA-like effect.

**Comment by ConProgramming** [comment]
Yes, I've noticed this, but is it possible to make it not call the preload function at all on subsequent navigation too? Or not call certain functions in it? These fetches seem unnecessary especially when they cause problems in my app when they attempt to fetch data from an endpoint that isn't running in export mode

**Comment by Conduitry** [comment]
If it doesn't run preload, it's not going to have the data needed to render the page. If you're looking for a static site generator that doesn't hydrate into an SPA, Sapper isn't it.

**Comment by iFwu** [comment]
Next.js is doing well for this case. It just generates JSON files for each fetch invocation and you can enjoy a SPA experience without any real API call.
