### ISSUE TITLE
Can't find any help why nodemailer does not work with sapper.js

### ISSUE THREAD

**Issue by mylastore** [sveltejs/sapper#1048]
I got this error by just using nodmailer
```
Unexpected token (Note that you need rollup-plugin-json to import JSON files)
1: {
2:   "_args": [
            ^
3:     [
4:       "nodemailer@6.4.2",

```

I try this subgestion of adding rollup-plugin-json to rollup.config.js file
```
import json from 'rollup-plugin-json';
json();
```
and now I get this error
``TypeError: Error resolving module specifier: events``

**Comment by Conduitry** [comment]
It sounds to me like you're trying to run Node-only code on the browser, where the `events` module doesn't exist. But GitHub issues aren't the right place for support questions like this.
