### ISSUE TITLE
`node_modules` in `src` side-effect after build

### ISSUE THREAD

**Issue by kluplau** [sveltejs/sapper#1053]
**Describe the bug**

A `node_modules` folder is created into `src` when `build` script is run.

**To Reproduce**

1. `npx degit "sveltejs/sapper-template#rollup" my-app`
2. `npm install `
3. `npm run build`
4. Locate `src/node_modules/@sapper`

**Expected behavior**

I didn't expect a new node_modules folder inside my `src` folder.

**Information about your Sapper Installation:**
- Chrome Version 79.0.3945.88 (Official version) (64-bit)
- MacOS Catalina
- Local
- Sapper version 0.27.0
- Svelte version 3.0.0
- If it is an exported (npm run export) or dynamic application: Just ran `npm run build`

- Whether your application uses Webpack or Rollup
Rollup

**Severity**
Annoying

**Comment by Conduitry** [comment]
This is by design. See #551, You can use the `--output` flag in `sapper` to control the directory these intermediate files are written to, but you'll need to update any imports from `@sapper/...` accordingly.

**Comment by kluplau** [comment]
Sorry for noise then. Never seen this practice before, so I figured it was a bug.
