### ISSUE TITLE
refire onMount if navigating to the current page?

### ISSUE THREAD

**Issue by ispyinternet** [sveltejs/sapper#1057]
similar to https://github.com/sveltejs/sapper/issues/748

When on the current page, if you click a link that IS the current page, I would like it to either:

1. do a full reload if `target=_self` as per issue #748
2. re-fire onMount without `target=_self`

Thoughts?

**Comment by benmccann** [comment]
Closing as duplicate of https://github.com/sveltejs/sapper/issues/1278
