### ISSUE TITLE
onMount not fired

### ISSUE THREAD

**Issue by davidcallanan** [sveltejs/sapper#1058]
**Describe the bug**
My head is fried, I think this is a bug.

`onMount(() => { /* ... */ })` is not being called inside any component.

**Logs**

No logs

**To Reproduce**

`test.svelte`:
```
<script>

	import { onMount} from 'svelte';

	onMount(() => {
		console.log("FOO")
	});

</script>
```

**Expected behavior**

`onMount` to be fired; to see `FOO` in the console.

**Stacktraces**
![image](https://user-images.githubusercontent.com/40340425/72622768-cfc6fe00-393b-11ea-9fb6-ed744d615e64.png)

**Information about your Sapper Installation:**
- Your browser and the version: Both Chrome 79.0.3945.117, and Dissenter v 0.68.131

- Your operating system: Windows 10

- Your hosting environment: `yarn dev`

- Sapper version: ^0.27.0

- Svelte version: ^3.0.0

- If it is an exported (npm run export) or dynamic application: dynamic application, ran using `yarn dev`

- Whether your application uses Webpack or Rollup: Rollup

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Sapper entirely?

Well, yeah, it's blocking me from progressing my project. But just a side project so doesn't matter too much.

**Additional context**

**Comment by davidcallanan** [comment]
This seems to be a sapper issue only. It's working fine on svelte repl. https://svelte.dev/repl/009b3d0f6c0849ad98a76aea5ba4e601?version=3.17.1

**Comment by davidcallanan** [comment]
Updated to sapper `^0.27.9` and svelte `^3.17.1`, still not working

**Comment by artur-sim** [comment]
Check client.js file there is a target object pointing to #sapper div, in template html, may be you some how accidentally modified something there  

in your client js shoud be like this 

```
import * as sapper from '@sapper/app';

```
sapper.start({
	target: document.querySelector('#sapper')
});
```

**Comment by davidcallanan** [comment]
Thanks @artur-sim !! That was the problem.
