### ISSUE TITLE
Passport req.user is not deserialized 

### ISSUE THREAD

**Issue by artur-sim** [sveltejs/sapper#1060]
Passport is successfully connected, after successful login i see req.user in my navigated get route "/foo". but when i refresh page req. user is lost it is just not being serialized.  If i navigate to another route from  /foo to /bar lets say,  i can see req.user in get /bar route, so if i refresh /bar req.user is lost "undefined" again, go back to /foo it is there and so on... 

I think this have to do something with sapper configs but im not sure

**Comment by antony** [comment]
This has nothing to do with Sapper, and is a support question, for which github is not the correct place. I suggest you look at examples of how to integrate passport with express/polka.
