### ISSUE TITLE
_layout usage with CSS Grid

### ISSUE THREAD

**Issue by marcusique** [sveltejs/sapper#1068]
I'm playing around with Sapper template and can't wrap my head around how styles behave in both global.css and _layout.svelte.

I'm using grid layout to wireframe a page, so currently it looks like [this](https://preview.redd.it/my63jgdh9qb41.png?width=2880&format=png&auto=webp&s=a6a406f929d44e9ec4ad9b8e7cb1c8df0761245c), achieved with [this](https://pastebin.com/t4d4Nt9C) (in global.css).
What I'm trying to do is to place the navbar in its own section and I want it to be present on all pages of the website. According to the docs, it can be achieved by using _layout.svelte, but every time I add Nav.svelte there it appears [on top of my page](https://preview.redd.it/dx1l9ic6aqb41.png?width=2880&format=png&auto=webp&s=75b460a0823e8579d99a65772b7b7eec9a19f41e).
If I place Nav component on every page and assign a nav class to it – everything works just fine.

How do I make it fit into nav section and be present on all pages of a website without importing the Nav component on every page?

**Comment by vipero07** [comment]
Does your nav.svelte have the class of nav on its parent element? Like:
`<nav class="nav">` alternatively is it outside of the element with the class of site in layout?

something like
```
<script>
	import Nav from '../components/Nav.svelte';
	export let segment;
</script>

<Nav {segment}/>

<main class="site">
	<slot></slot>
</main>
```
If its the second, you just need to move it before the slot. If you could make a repl it would be easier to diagnose.

**Comment by antony** [comment]
Hi @marcusique - Github is not the place to ask support or usage questions, it is for issues and feature requests for Sapper itself. Come and [chat to us on discord](https://svelte.dev/chat) or ask on Stackoverflow with the tag Sapper for help and support.
