### ISSUE TITLE
Solution for complex router path

### ISSUE THREAD

**Issue by Losses** [sveltejs/sapper#1073]
**Is your feature request related to a problem? Please describe.**
Yep, I'm migrating my blog from hexo to sapper, the original path definition looks like: `//example.com/2019/10/07/spotify-offline/`, but it's pretty hard to make same router works in a neat way with sapper.

(may be create a bunch of directory works, but really dirty...)

**Describe the solution you'd like**
A default router may works? if no router matches, jump to default router page, and let the default router page judge if the page is really not found.

**Describe alternatives you've considered**
Maybe a separate router config file, map rule to svelte components, like:
```
export const router = [
  {
    test: '/(\d+)\/(\d+)\/(\d+)\/(\S+)/',
    component: PageX,
  }, 
  {
    rule: '[:year]/[:month]/[:day]/[:id]',
    component: PageX,
  }
]
``` 
Here, we'll gain another benefit: Controlling the match order of routers.

**How important is this feature to you?**
I think the current router solution has a lot of limitation, it's not very import, but it may make router in sapper less painful under really complex context.

**Some other context.**
Say, if a developer want to design a CMS with Sapper, He want to make the format of URL be able to configure, We can do nothing with current router solution, the problem need to be solved, maybe.

**Comment by rudywaltz** [comment]
Hi @Losses ,
this is already working.
my URL path:
`/shows/[:slug]/[:year]/[:quarter]
and the folder structure:
```
shows
  |
  | [...slug].svelte
  | index.svelte
```

the [...slug].svelte you can extract all nested URL params like this
```
    export async function preload({ params }) {
      let [showSlug, year, quarter] = params.slug;
[...]
```

I don't know this is helpful for you but I hope so

Best,
rudywaltz

**Comment by Losses** [comment]
@rudywaltz Wow, it's pretty cool!
