### ISSUE TITLE
Not all json files exported `sapper export`

### ISSUE THREAD

**Issue by mhkeller** [sveltejs/sapper#1078]
**Describe the bug**

I have a project with a route like `src/routes/example/[slug].svelte` and ` src/routes/example/[slug].json.js` but when I run `sapper export --legacy` in my project, it doesn't always export every json file for every slug. It seems like there's a race condition of some kind because sometimes it exports three, sometimes it exports all five.

**To Reproduce**

I made a branch called `bug` [on this repo](https://github.com/mhkeller/layercake.graphics/tree/bug).

```
degit mhkeller/layercake.graphics#bug test-bug
cd test-bug
npm install
npm run export
```

Check out the folder `docs/example/`and you will see maybe all five json files corresponding to the exported folders.

**Expected behavior**

I expect all json files to be baked for every corresponding slugged route.

**Information about your Sapper Installation:**

- Sapper version 0.27.9

- Svelte version 3.18.1

- Running rollup

**Severity**

I think this is pretty severe since it leads to some pages 404'ing in certain scenarios. I've fixed it temporarily by copying the exported json files when it does work and manually putting them in my export folder.

**Comment by bummzack** [comment]
Seems like this is a duplicate of #893. 
Somebody already provided a PR (#869) that should fix this, but it's yet to be merged.

**Comment by sw-yx** [comment]
yea try using `@ssgjs/sapper`

i dont intend to maintain this much longer, probably gonna drop sapper entirely

**Comment by mhkeller** [comment]
@bummzack thanks I missed that in my search! I'll close this one
