### ISSUE TITLE
/build/ is dependent on project dir

### ISSUE THREAD

**Issue by KristerV** [sveltejs/sapper#1084]
**Describe the bug**
`node __sapper__/build/` gives error (following) if it's not in the project directory.

**Logs**

```
➜  front-build node index.js 
Starting server on port 3000
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'sirv'
Require stack:
- /home/krister/code/bashboard/front-build/server/server.js
- /home/krister/code/bashboard/front-build/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/krister/code/bashboard/front-build/server/server.js:1:1204)
    at e (/home/krister/code/bashboard/front-build/server/server.js:1:124)
    at Module.<anonymous> (/home/krister/code/bashboard/front-build/server/server.js:1:1483)
    at e (/home/krister/code/bashboard/front-build/server/server.js:1:124)
    at /home/krister/code/bashboard/front-build/server/server.js:1:923
    at Object.<anonymous> (/home/krister/code/bashboard/front-build/server/server.js:1:933) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/krister/code/bashboard/front-build/server/server.js',
    '/home/krister/code/bashboard/front-build/index.js'
  ]
}

```

**My debugging process**

1. On Arch linux it builds and `node __sapper__/build` works fine.
1. On docker container `node:slim` (v10) it builds, then scp to actual debian server (v10) and it fails with error `Error: Cannot find module 'sirv'`
1. All of the 3 (local, docker, debian) Node.js versions are 13.
1. `grep -r sirv` returns identical results on Arch and Debian.
1. Neither have `NODE_ENV='production'` (since Sapper is under devDependencies anyway).
1. Diff of two built codebases returns no differences.
1. So now I moved my local build out of the project dir and tried running with node, same error: `Error: Cannot find module 'sirv'`

**Expected behavior**
Server is supposed to run

**System**
- Deployment chain: Arch Linux -> GitLab runner on docker `image: node:slim` -> Debian
- Sapper 0.27.9
- Webpack
- Node.js 13

**Other**
I got the server running by also `scp`-ing the code folder and node_modules (node_modules was important, I checked separately).

If you say this is the intended way of working, I'll add a note to the docs.

**Comment by thgh** [comment]
This might help your cause:

```diff
// rollup.config.js
-		external: Object.keys(pkg.dependencies).concat(
+		external: [].concat(
			require('module').builtinModules || Object.keys(process.binding('natives'))
		),
```

**Comment by artemjackson** [comment]
@KristerV don't you forget to copy `node_modules` alongside you `build`?
`sirv` is a server-side module which is a runtime dependency of sapper so you have to ship too.
Your docker/Debian workspace should look like
```
my-project/
  node_modules/
  build/
    client/
    server/
    ...
    index.js
    template.html
```

**Comment by KristerV** [comment]
oooh.. I guess this makes sense in that case.
