### ISSUE TITLE
Pass data from server to client before any rendering takes place

### ISSUE THREAD

**Issue by antony** [sveltejs/sapper#1086]
**Is your feature request related to a problem? Please describe.**
We're trying to allow whitelabeling of our site. This would involve determining the subdomain the app runs on, and loading a bunch of whitelabel data, and then injecting it into the application prior to rendering.

With Sapper, I can get the subdomain in `server.js` using `req.headers.host` and I can then load whitelabel data. However other than `session`, there is no way to pass that whitelabel data to the layout/other pages, and `session` doesn't seem like an appropriate place for it.

I could load it in `_layout.svelte` and use preload to pass it to the client-side to be placed in a store. However in `_layout.svelte` I don't have access to find out the hostname, so I can't do that either.

**Describe the solution you'd like**
Another store in middleware, where you could pass data from server to client whilst having access to request data, or perhaps an ability to contribute to the `page` store.

**Describe alternatives you've considered**
I've listed them all above. There isn't a suitable way that I can determine.

**How important is this feature to you?**
It's critical to me, as I can't think of a good workaround at the moment.

**Comment by antony** [comment]
Of course, the moment I write this I remember that the page store contains `host`. I'll report back if this works.

**Comment by jjmax75** [comment]
Hi @antony I'm looking to do this too, can you point me towards documentation or where to get started with setting and accessing data in stores in the server.js and client.js files
