### ISSUE TITLE
non-page route should not set content-type

### ISSUE THREAD

**Issue by samhatchett** [sveltejs/sapper#109]
https://github.com/sveltejs/sapper/blob/master/lib/index.js#L200

... does not check for route type. by setting a default type of `text/html`, Sapper ends up overriding useful auto-checking of mime types by express, especially for download content.

**Comment by EmilTholin** [comment]
Hi @samhatchett! That's a very good point. That line of code you linked should possible be [**moved here**](https://github.com/sveltejs/sapper/blob/master/lib/index.js#L142) instead?

**Comment by samhatchett** [comment]
looks right to me. mind if I open a PR?

**Comment by EmilTholin** [comment]
I think that would make Rich a very happy man.

**Comment by jacobmischka** [comment]
I think a similar change should also be made [here](https://github.com/sveltejs/sapper/blob/master/lib/index.js#L95). This forcing of js content-type is the only thing stopping custom assets by webpack from working (extract-text-plugin for css or file-loader for font assets, for examples).

**Comment by samhatchett** [comment]
primary issue fixed via #111 - similar change from @jacobmischka not yet addressed.

**Comment by Rich-Harris** [comment]
The core issue here is fixed so I'll close this, but I've opened a new ticket (#116) for the related issue @jacobmischka found
