### ISSUE TITLE
Possibility to always render actually conditional content server-side

### ISSUE THREAD

**Issue by silllli** [sveltejs/sapper#1091]
**Is your feature request related to a problem? Please describe.**
I'm concerned to make content on websites as available as possible without JavaScript (because it's disabled, certain features are missing, JS files were partially loaded… or I'm a search engine or crawler). That's why I love Sapper and its simple SSR functionalities.

I also like the ease of adding and removing content based on conditions. But let's say I have a long text with a teaser. Beneath the teaser is a button to "read more". When I click that button, a condition is met and the element containing the remaining text is added by Svelte / Sapper.

As far as I know, this "full" content is hidden from clients without JS.

**Describe the solution you'd like**
I could imagine an element directive like `always-render-this-server-side`.

**Describe alternatives you've considered**
Always render everything—but with else statements this leads to chaos.

**How important is this feature to you?**
It is somewhat important because SSR misses (in my view) a part of its point if content is not reachable without JavaScript.

**Additional context**
In plain HTML / CSS / JavaScript projects I usually use a ".no-script" class on the `<html>` or `<body>` element in order to show elements that otherwise would be hidden.

---

Maybe this is already available, but I could not find it in the docs.

**Comment by antony** [comment]
You have control over what is rendered server, and client-side, if you want all content to be rendered server-side, simply set the conditional which hides the content to show it by default, and then hide it inside `onMount` or `if (process.browser) { ... }`.

You could also simply include the content in `<noscript>` tags as you've already mentioned, but this will result in duplicating content.

You should be aware that showing something in SSR mode and then immediately hiding it with Javascript will cause a slight flicker as the page loads. You can probably avoid this by using a loading screen, but you're then reducing the overall usability of your site.

**Comment by silllli** [comment]
That makes sense. Thank you!
