### ISSUE TITLE
Catch all routes ex. [...slug].svelte

### ISSUE THREAD

**Issue by rlindskog** [sveltejs/sapper#1092]
**Is your feature request related to a problem? Please describe.**
I'd like the ability to have catch all functionality for scenarios where I don't know the number of parameters ahead of time.

**Describe the solution you'd like**
Ability to create a catch-all route by naming a file.
Example:
- `/src/routes/posts/[...slug].svelte`
- user navigates to `/posts/a/b`
- `page.params` would then contain `{ "slug": ["a", "b"] }`

**Additional context**
Inspired by next.js: https://nextjs.org/docs/routing/dynamic-routes#catch-all-routes

**Comment by Conduitry** [comment]
These already exist - #545 / #607 - but we still haven't gotten around to documenting them yet 😬

**Comment by kevmodrome** [comment]
I made a PR for this: #1077

**Comment by Conduitry** [comment]
Thanks! Made a couple of adjustments, merged, and deployed.

**Comment by rlindskog** [comment]
Excellent, thanks everyone!
