### ISSUE TITLE
'sapper' is not recognized as an internal or external command in VS Code

### ISSUE THREAD

**Issue by ansarnisargill** [sveltejs/sapper#1097]
I have created sapper project using following commnds from official sapper blog:
npx degit "sveltejs/sapper-template#rollup" my-app
# or: npx degit "sveltejs/sapper-template#webpack" my-app
cd my-app
npm install
npm run dev

but when I run 'npm run dev' it throws error

**'sapper' is not recognized as an internal or external command,**

anything I am doing wrong.

**Comment by Conduitry** [comment]
GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).
