### ISSUE TITLE
Exported server routes returning binary files get corrupted

### ISSUE THREAD

**Issue by aloker** [sveltejs/sapper#1103]
**Describe the bug**
When a route points to a server route that emits a binary file (pdf, image etc.) and the site is `export`ed, the files on disk get corrupted because export only supports text results from server routes.

**To Reproduce**
- Create a server route that returns a binary file (image, PDF)
- Link to the server route inside a Svelte component
- Export the site
- Find the exported file of the server route on disk

Result: the file is corrupt and cannot be opened.

**Expected behavior**
The result of server routes emitting binary data should be properly stored on disk when exporting.

**Information about your Sapper Installation:**
- Sapper master branch (v0.27.10)
- Exported site
- Checked with rollup, but should be same for webpack

**Severity**
Blocking my attempt to load all data including binary assets (documents, images) from a headless CMS.

**Comment by sw-yx** [comment]
this seems pretty serious. can you move the work to clientside? or must it be in a server route?

**Comment by aloker** [comment]
I'm the API routes, pull in images from a CMS and transform them using Sharp, so yes, it has to be server side.

**Comment by jrob-io** [comment]
I ran into this issue, too. I realized that `this.fetch` uses [`proc.send`](https://nodejs.org/api/process.html#process_process_send_message_sendhandle_options_callback) to send the response body in a JSON object to the export CLI.
https://github.com/sveltejs/sapper/blob/5e2c68606124a7c4407250c2889a7e23cf2c3d73/runtime/src/server/middleware/get_server_route_handler.ts#L40

JSON is `utf8` which results in binary data being lost, so I `base64` encoded it before and after the message was sent. After this, binary files started appearing normally in my `__sapper__/export` folder.

**Comment by dennybritz** [comment]
Is there any news on this getting fixed? It seems like I cannot export binary files and this is blocking me.
