### ISSUE TITLE
<svelte:window bind:scrollY /> breaks chaging the page when scrolled down

### ISSUE THREAD

**Issue by Mycl95** [sveltejs/sapper#1107]
**Describe the bug**
I am using the scrollY binding of svelte:window. If scrollY equals 0 the page change is working as expected. But if I scroll down it break everything. The page1 does not get destroyed and remains on top of page2. If I go back, page1 from the beginning still remains and the "new" page1 gets rendered below. 

**To Reproduce**
Create two routes and add `<svelte:window bind:scrollY />` (and `let scrollY`), some content that overflows the screen and a link to page2 to page1. Scroll down and click the link to page2.

**Expected behavior**
The old page should get destroyed on page change.

**Information about your Sapper Installation:**
- Tested in Firefox 73.0.1 and Chrome 79.0.3945.130

- Ubuntu Linux 18.04

- Local

- Sapper 0.27.10 (latest)

- Svelte 3.19.2 (latest)

- Not exported

- Webpack

**Severity**
It's blocking the usage of Sapper almost entirely.

EDIT:
I tested if the same behavior exists with using window.addEventListener. The problem seems to be the assignment of the scroll value to the property. Because the page gets automatically scrolled to the top while changing the page. That fires the scroll event and the value gets assigned to the property. And that in turn blocks the page from being destroyed or causes the page to be rerendered respectively.

EDIT:
Hence I am using the scrollY prop in my template the rerender is triggerd.

**Comment by Mycl95** [comment]
I tested if the same behavior exists with using `window.addEventListener`. The problem seems to be the assignment of the scroll value to the property. Because the page gets automatically scrolled to the top while changing the page. That fires the scroll event and the value gets assigned to the property. And that in turn blocks the page from being destroyed or causes the page to be rerendered respectively.

**Comment by Mycl95** [comment]
That seems to be a general problem with rerendering. I have encountered that problem at another place where a page change causes a store to update. That causes a page to rerender and not being destroyed.

**Comment by matt3224** [comment]
I think this should be reopened, as i run into this on almost all projects resulting in these merged pages

**Comment by cinatic** [comment]
Scrolling cuts the code content,output content itself is fine

![Screenshot_20210115-204039](https://user-images.githubusercontent.com/2721787/104771417-8f7aa580-5772-11eb-81ce-d81f1adba724.jpg)
![Screenshot_20210115-204051](https://user-images.githubusercontent.com/2721787/104771420-90abd280-5772-11eb-919f-220afbbc505a.jpg)
