### ISSUE TITLE
Sapper export: when copying static files, also set a(ccess)time and m(odification)time for the files

### ISSUE THREAD

**Issue by ribizli** [sveltejs/sapper#1110]
**Is your feature request related to a problem? Please describe.**
During export static files are copied using Node.js `fs` module (into `__sapper__` folder). To optimize sync to a deployment copying `atime` and `mtime` should be done.

**Describe the solution you'd like**
Use `fs.utimesSync` to preserve static file's access and modification times. Extending the `copy` function in utils is good to go.

**Describe alternatives you've considered**
None

**How important is this feature to you?**
Quite important, my FTP sync tool supports using only `mtime` (no hashing, etc).

**Additional context**
None

**Comment by Conduitry** [comment]
Implemented in 0.27.13.
