### ISSUE TITLE
How to add svelte transition to dynamic route <main> component?

### ISSUE THREAD

**Issue by Joci933** [sveltejs/sapper#1114]
I have a dynamic routing with `[slug].svelte`. 
I was added a svelte transition to <main> element, and it's working fine on first page load, but it's never fire again. Only the children component data change.

```
<main transition:fly="{{ y: 100, duration: 1000 }}"  class="prezentation-wrapper">
  <svelte:component this={dynamicComponent}/>
</main>
```

The `main` section is the main wrapper around the whole site.

**Comment by artemjackson** [comment]
Could you please provide a repo with a reproduction so that we are better able to help you?

**Comment by artemjackson** [comment]
@Joci933 Oh, I see. You just need to specify a transition on each possible `dynamicComponent` not on the parent. See the example: https://svelte.dev/repl/e4870d65a1d64418af63d11d5d33ee1c?version=3.20.1

**Comment by artemjackson** [comment]
Or even this one: https://dev.to/buhrmi/svelte-component-transitions-5ie

**Comment by Conduitry** [comment]
GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).
