### ISSUE TITLE
Export not crawling through links in transitioned components

### ISSUE THREAD

**Issue by ignatiusmb** [sveltejs/sapper#1116]
**Describe the bug**
I created a transition component to wrap all my routes in it so it can have a transition on every page change like [this video](https://www.youtube.com/watch?v=UUX5vpwpnrE). It works the dev server as expected but it doesn't crawl through the links when I try to export it and just exported the Navigation links from `_layout.svelte`

**Logs**
There's no error in the logs, it just generated those these from my Nav bar
![image](https://user-images.githubusercontent.com/8156777/76538689-4868b780-64b2-11ea-9523-05e18dc0502d.png)

**To Reproduce**
1. Use the sapper template
2. Here's my transition component that I used, copy this template
```svelte
<script>
  import { onMount } from 'svelte';
  import { fly } from 'svelte/transition';

  let mounted = false;
  onMount(() => {
    mounted = true;
  });
</script>

{#if mounted}
  <main in:fly={{ x: -200, duration: 300 }} out:fly={{ x: 200, duration: 300 }}>
    <slot />
  </main>
{/if}
```

3. Use it in any of the page
```svelte
<script>
  import FlyWrapper from '../../components/transition/Fly.svelte';
</script>

<FlyWrapper>
  <!-- any elements with links on it -->
  <a href="other-page">Other</a>
</FlyWrapper>
```

4. Run `npm run export` and the page in the link inside the `<FlyWrapper>` would not exist

* If possible, we recommend creating a small repo that illustrates the problem.
* Reproductions should be small, self-contained, correct examples – http://sscce.org.

Occasionally, this won't be possible, and that's fine – we still appreciate you raising the issue. But please understand that Svelte is run by unpaid volunteers in their free time, and issues that follow these instructions will get fixed faster.

**Expected behavior**
All of the links navigable through the home page to be exported

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

  Stack trace goes here...
</details>

**Information about your Sapper Installation:**
- Your browser and the version: Chromium Edge 80

- Your operating system: Tested on Windows 10 and Ubuntu

- Your hosting environment: Netlify

- Sapper version ^0.27.10

- Svelte version ^3.19.2

- **Exported** application.

- Using Rollup

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Sapper entirely?

This is blocking an upgrade for me since having transition/animation between page changes would be a lot more intriguing than just a plain page jump. I use Svelte + Sapper for a lot of my projects, hobby and work, so it really slows down the workflow and I haven't been able to showoff what Svelte + Sapper could do because of all this debugging.

Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**
My current workaround is to just not use any transition.

**Comment by Conduitry** [comment]
This is expected, as `sapper export`'s crawl only follows links that are visible in the server-rendered HTML, which those won't be, as they're not added until mount. You could use a CSS animation to achieve the same effect, while still having the links in the server-rendered HTML, or you can manually set more `--entry` point for the export. https://sapper.svelte.dev/docs#How_it_works
