### ISSUE TITLE
%sapper.scripts% should be in <head>

### ISSUE THREAD

**Issue by iOiurson** [sveltejs/sapper#1121]
Unless there is something i totally misunderstand about the use of `defer`, i don't really get why scripts are still being placed at the end of the body.
[CanIUse](https://caniuse.com/#search=defer) shows a 98% compatibility rate of the `defer` attribute, the remaining 2% being mostly Opera mini.

In `template.html`, `%sapper.scripts%` should be located inside the `<head>` tag, with a `defer` attribute.

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <meta name="theme-color" content="#333333" />

    %sapper.base%

    <link rel="stylesheet" href="global.css" />
    <link rel="manifest" href="manifest.json" crossorigin="use-credentials" />
    <link rel="icon" type="image/png" href="favicon.png" />

    %sapper.styles%
    %sapper.head%
    %sapper.scripts%
  </head>

  <body>
    <div id="sapper">%sapper.html%</div>
  </body>
</html>
```

**Comment by artemjackson** [comment]
@iOiurson the only one difference is IE9 which actually is not important in 2020.
The proposed change is nice and pretty simple, could you please submit a PR?

**Comment by iOiurson** [comment]
Looking at the code, i noticed some parts of the inserted scripts are inlined, in particular when using Rollup as the bundler:
https://github.com/sveltejs/sapper/blob/master/runtime/src/server/middleware/get_page_handler.ts#L270-L290.

Inline scripts are not affected by `defer`. So it might not be as good an idea to move scripts to <head>.

But it seems in this case the inline scripts mainly import the main script dynamically, in which case the main script will be executed asynchronously.

I opened a PR for maintainers to review, feel free to give your opinion.
