### ISSUE TITLE
The easiest way to render all subpages?

### ISSUE THREAD

**Issue by Iwaniukooo11** [sveltejs/sapper#1129]
I need a way to render on the SSR routes from this this repo: 
https://github.com/Iwaniukooo11/agata-photography
I can't find any solution to do this, there is nothing about it docs.

All I need is to made subpages likes /graphic and /copywriting working on the SSR side, but it's not known how does the node.js deal with sapper

**Comment by antony** [comment]
@Iwaniukooo11 Please use https://svelte.dev/chat for support requests, and the github issues template for everything else.
