### ISSUE TITLE
Easy way to automatically preload index from /client?

### ISSUE THREAD

**Issue by timoanttila** [sveltejs/sapper#1133]
Is there easy way to automatically include `/client/index.c7c5d451.js` (the file name is different each time(?)) to preload? Google's dev says that I could load the website faster with that.

`<link rel="preload" href="/client/index.c7c5d451.js" as="script">`

My website is [https://timoanttila.com](https://timoanttila.com) (exported to Netlify) and the source code can be found at [Github](https://github.com/timoanttila/timoanttila-sapper). I'm a new dev and would like to learn to optimize my projects as well as possible. Right now that file is blocking rendering way too long.

Another problem is that component's styles are made twice for some reason ([Line.svelte](https://github.com/timoanttila/timoanttila-sapper/blob/master/src/components/Line.svelte)). First `<style>` and then `<style id="svelte-3i35sa-style">`.

Using [Rollup](https://github.com/timoanttila/timoanttila-sapper/blob/master/rollup.config.js) (however, I don't understand the difference between rollup and webpack).

Some of you may wonder why I use a style tag inside `<svelte:head>`, but that's only because I want all my styles loaded inline (no external files) and some of the tags are not visible in that page when exporting (coming from components or other source) and those styles are deleted automatically (ex. socialmedia has different styles in footer (_layout) than hero and line).

**Comment by antony** [comment]
Hi @timoanttila

Please come and chat to us at https://svelte.dev/chat for support questions where we can better help you. There may be value in adding a feature to Sapper to preload the client.js - we can determine this in chat and raise the appropriate feature request.

Additionally, please don't bundle multiple questions into a single issue, as it makes things very hard to address.

**Comment by timoanttila** [comment]
> Please come and chat to us at https://svelte.dev/chat for support questions where we can better help you.

There is no way to automatically preload the client file right now? It is just one of the most important thing to think when developing fast webapps. How to optimize delivery. Mobile takes 520 ms to load it and developers.google.com said that I could save 330 ms if preload.

Discord's chat does not seem to be very active. There are 893 users online, but nobody talks.

**Comment by garciadiazjaime** [comment]
hey @antony I noticed this issue was closed; I'm experiencing the same issue, google suggests to `preload` client js, is there any way to do this?

Thanks!

**Comment by antony** [comment]
@garciadiazjaime not yet, feel free to open a PR, or recycle the one which was mysteriously closed by the author.

**Comment by garciadiazjaime** [comment]
@antony thanks fo the quick response, I ended it up hardcoding a line like this one on my `template.html`

```
<link rel="modulepreload" href="/client/index.54942379.js">
```

Adding `modulepreload` fixed the issued detected by lighthouse.

however is not ideal giving the "signature (sha)" changes, do you know if there's a way to extract it?

so I could have something like:
```
<link rel="modulepreload" href="/client/index.%sapper.signature%.js">
OR
<link rel="modulepreload" href="%sapper.indexPath%.">
```

Happy to open a PR, if would help if you could point me into which files I should look at.

Cheers!

**Comment by benmccann** [comment]
I have a PR pending that will preload the JavaScript: https://github.com/sveltejs/sapper/pull/1269

**Comment by antony** [comment]
Looks good, have reviewed @benmccann
