### ISSUE TITLE
mime-types.md is missing mime-type for wasm file type

### ISSUE THREAD

**Issue by sajuthankappan** [sveltejs/sapper#1136]
**Describe the bug**
mime-types.md is missing mime-type for wasm file type. This causes 404 error when responding to .wasm files

**Logs**
No errors in console

**To Reproduce**
Try importing any wasm files. e.g., 
    const { greet } = await import("xyz-wasm");
    greet();

**Expected behavior**
responding with 200 code with the wasm file

**Information about your Sapper Installation:**
- Your browser and the version: FF74

- Your operating system: Ubuntu Linux 19.10

- Your hosting environment: Local

- Sapper version: 0.27.11

- Svelte version: 3.0.0

- Whether your application uses Webpack or Rollup: Webpack

**Severity**
blocking your usage of Sapper entirely?

**Additional context**
I checked by adding the following line to mime-types.md, and the wasm file is loaded successfully, in my local cloned code.
```
application/wasm				wasm
```

**Comment by Conduitry** [comment]
Fixed in 0.27.12.
