### ISSUE TITLE
Route with address "/client/" is not working

### ISSUE THREAD

**Issue by MrSrsen** [sveltejs/sapper#1142]
**Describe the bug**
When I use `/client/*` route in Sappers file-system routing I am getting plain text error `not found`.

**To Reproduce**

0. Launch Sapper in `dev` mode (I didn't test this with other then `dev`)
1. Create file in `/routes/client/new.svelte` with some content
2. Visit this route in browser as `localhost:3000/client/new`
3. You will see mentioned plain text error

**Expected behavior**
I see contents of `new.svelte` page.

**Information about your Sapper Installation:**
- Sapper: 0.27.9
- Svelte: 3.13
- Browser: Firefox 74.0
- OS: Kubuntu 18.04

**Severity**

Low - annoying.

**Additional context**

I think this is because of `/client` native Sappers files that are automatically generated by compilation but if this is the case i think some compile-time error or warning would be appropriate.

If this is intended behavior I think this needs to be documented in the docs. I didn't see any "reserved" route names there (https://sapper.svelte.dev/docs/).

**Comment by antony** [comment]
Confirmed. And your supposition is correct!

**Comment by Conduitry** [comment]
I believe this would be fixed by changing the exception handling [here](https://github.com/sveltejs/sapper/blob/facbd96e0bd2539acf32c5ac14cd9478c7c635e5/runtime/src/server/middleware/index.ts#L124) to call `next()` to continue with the next middleware rather than immediately returning a 404.

**Comment by m-dary-nur** [comment]
I also confused before, when i use routes /client/input and /client/input/id, its work fine, but after reload browser on this route i got not found, its fine in otherroute case like /user/input or /user/input/id.
