### ISSUE TITLE
add support svelte-pagejs

### ISSUE THREAD

**Issue by mehdiraized** [sveltejs/sapper#1145]
i need one file.svelte load for 2 route
sample blog/index.js and blog/[paged([0-9]+)].svlete

but not found solution !

**Comment by Conduitry** [comment]
You can do this by extracting the page into another component, which you import and use from both routes.

In the future, GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).

**Comment by mehdiraized** [comment]
component not support 
```
<script context="module">
```
not support
```
export async function preload(page)
```

**Comment by mehdiraized** [comment]
i have this error
```
throw new Error(`Function called outside component initialization`);
        ^

Error: Function called outside component initialization
```

**Comment by antony** [comment]
@mehdiraized github issues is not the place for support. Please read the original reply to your issue.
