### ISSUE TITLE
Go backend

### ISSUE THREAD

**Issue by pjebs** [sveltejs/sapper#1146]
I want to use a go backend.

Is there official instructions on how to use sapper just for client side? (None of the node based initial server side rendering)

**Comment by Conduitry** [comment]
See also #383, but no this isn't possible currently.

**Comment by pjebs** [comment]
What is it about sapper that prevents a non-node backend?

**Comment by dalu** [comment]
What would be required to render a svelte component?
You have to compile it first, and then?
Internally pre-render, and once the pre-rendered is loaded by the client?
A way to go full SPA?

Sucks that Svelte has no official router.
Or at least support for a multi page app without the express backend.

And what's the point? Do you think otto or goja are faster than node?
Does the Svelte compiler compile to es5.1?
