### ISSUE TITLE
Refactor Exports

### ISSUE THREAD

**Issue by lukeed** [sveltejs/sapper#115]
Piping all exports to/from [`core/index.ts`](https://github.com/sveltejs/sapper/blob/master/src/core/index.ts) results in _all_ of core being used everywhere. 

As with #114, because of the scope/import-hoisting, all files' immediate prep work is called instantly, regardless of what the CLI or runtime actually wants.

In practice, this means that something like `core/export.ts` is ***always*** initiated & running, even during production-mode as a middleware!!!

> AKA, something as big/heavy as Express is always running, even if you don't want it!

<img width="635" alt="screen shot 2018-02-05 at 4 17 43 pm" src="https://user-images.githubusercontent.com/5855893/35835542-1be0c3b6-0a90-11e8-9b3c-627f068153f7.png">

As much as I love Rollup (seriously, it's the best!), I don't believe it should be used in compiling Node.js CLIs and runtimes. I see this issue happen _a lot_ and often. 

Opinions aside, this can be solved by removing the `core/index.ts` aggregator in favor of direct imports &mdash; we _are_ using Rollup, so why not? We should also be moving most/all of the prep-work _inside_ the actual export. This will prevent things from being called & prepped until we actually want them to.

> I don't have time to do this today, sorry! But happy to tackle it, if no one else has, once my schedule opens up~!

**Comment by Rich-Harris** [comment]
Gah, whoops. Good catch, thanks. Aside from TypeScript, one of the reasons I moved towards bundling was for marginally faster startup times, so it's ironic if I inadvertently made things slower.

**Comment by lukeed** [comment]
Haha, yeah, it happens! Export all the things™
