### ISSUE TITLE
Don't assume /client/** assets are JS

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#116]
Moving https://github.com/sveltejs/sapper/issues/109#issuecomment-362298418 into its own separate issue — [this line](https://github.com/sveltejs/sapper/blob/7a2ed16884ebfbe4497f2bc2b458ad7dc66f95d7/src/middleware/index.ts#L63) (and the related line in `connect_prod`) prevents certain webpack plugins from being used

**Comment by EmilTholin** [comment]
Could this be solved by removing that line of code you linked, and [make `opts.type` optional](https://github.com/sveltejs/sapper/blob/7a2ed16884ebfbe4497f2bc2b458ad7dc66f95d7/src/middleware/index.ts#L140), or is that to naive?

**Comment by Rich-Harris** [comment]
Related: Sapper will actually generate a script tag for all route assets, even non-JS ones...

https://gitter.im/sveltejs/svelte?at=5a99baf56fba1a703abf5043

**Comment by jacobmischka** [comment]
Is this indeed fixed in #153? Should this be closed now?
