### ISSUE TITLE
Run transition on page load (intro: true)

### ISSUE THREAD

**Issue by rahulserver** [sveltejs/sapper#1160]
In svelte we can set transitions to run on component load by intro: true. But I am not sure how to do that in sapper. Couldn't find in docs anywhere about this setting.

Currently what I have is a text in routes/index.svelte which must have a fade transition.

`<span in:fly out:fade>text</span>`

But this transition only appears after page load is over. I would like it to run from the moment this text is visible. So what is the way to do it?

**Comment by Conduitry** [comment]
See also #1106. In-transitions with SSR don't really make a lot of sense.
