### ISSUE TITLE
Sapper export: missing closing body and html tag

### ISSUE THREAD

**Issue by ohheyitsdave** [sveltejs/sapper#1161]
After inspecting the output of HTML generated by `sapper export`, there are some missing closing tags: `body`and `html`.
This behavior is not happening on `sapper dev`, when I view the source code in the browser.

Is this an optimization option and is there a way to deactivate it or a bug?

**Comment by Conduitry** [comment]
Not a bug, see #1061. Not currently a way to deactivate it, see #348.
