### ISSUE TITLE
Secret Session Data is embedded into client

### ISSUE THREAD

**Issue by sksar** [sveltejs/sapper#1168]
This may be a feature request, or maybe something entirely different.
But while building an app, i have came to notice that the session **data which is being passed from express server.js to sapper middleware, is exposed in the scripts of the page rendered.**

My server.js:
```
app.use(sapper.middleware({
 session: (req, res) => ({
   user: req.user,
   someData: `Some Secret Data XYZ123`
   })
}))
```

In the HTML of a page:
```
<script>
__SAPPER__ = {
   baseUrl: "",
   preloaded: [void 0, {}],
   session: {
      user: void 0,
      someData: "Some Secret Data XYZ123"
   }
};
</script>
```

What should i do to pass secret data from server.js to sapper, but prevent it from appearing anywhere on the client side. Or am i doing something wrong entirely and there is a good way to handle this. Or is this feature not yet implemented.

**Comment by Conduitry** [comment]
During the subsequent SPA-like navigation after hydration, all page routes are rendered on the client, and so any of the data they directly use is going to be visible to the client. If you have something that needs to be secret, it can't live in the session. If there's something you need to do using some secret data that the client shouldn't know about, it can happen in a server route - which are always run on the server, unlike page routes.
