### ISSUE TITLE
</body> and </html> missing when running built version

### ISSUE THREAD

**Issue by jinxmcg** [sveltejs/sapper#1171]
**Describe the bug**
When running 
```
npm run build
node __sapper__/build
```
the resulted HTML is missing the ending tags for 
```
</body>
</html>
```
the code ends with 
```
</script>
```
appears in any built Sapper project even the official Sapper site:
[https://sapper.svelte.dev/](https://sapper.svelte.dev/) the html code ends in </script>

(there are no issue while run dev)

**To Reproduce**

To help us help you, if you've found a bug please consider the following:

```
npx degit "sveltejs/sapper-template#rollup" my-app-test
cd my-app-test/
npm install
npm rum build
node __sapper__/build
```
view source or curl shows that the code ends in </script>

* If possible, we recommend creating a small repo that illustrates the problem.

check the official repo [sveltejs/sapper-template#rollup](sveltejs/sapper-template#rollup) they have the error too

**Expected behavior**

built html should have the ending tags
```
</body>
</html>
```

**Information about your Sapper Installation:**

All sapper. even on the official sapper website you can see it:
[https://sapper.svelte.dev/](https://sapper.svelte.dev/)

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Sapper entirely?
Not a big issue.

**Comment by Conduitry** [comment]
sapper.svelte.dev is an exported site, which isn't a good example because its HTML is minified (#1061), but I think I would expect the `</body></html>` to be there on dynamic, non-exported sites. I see they're missing on svelte.dev.

**Comment by Conduitry** [comment]
Never mind, this isn't a bug, this is the same issue as #1061. During building, `src/template.html` is minified and written to `__sapper__/build/template.html`, where it is then loaded at runtime. Closing.
