### ISSUE TITLE
Add doNavigate property to goto options

### ISSUE THREAD

**Issue by rosslh** [sveltejs/sapper#1172]
**Is your feature request related to a problem? Please describe.**

I want to implement hybrid modal/standalone pages in my application. It should work the same way posts do on "new reddit":

- Clicking a post loads it as a modal and pushes the post URL to your history
- Navigating to the post URL directly loads the post as a standalone page

This seems to be impossible with the `goto` function because if the route exists, you are automatically redirected there.

[From the docs](https://sapper.svelte.dev/docs#goto_href_options):

> If the destination is a Sapper route, Sapper will handle the navigation, otherwise the page will be reloaded with the new href.

**Describe the solution you'd like**

I would like there to be an option for `goto` which says not to navigate, just to update the URL.

**Describe alternatives you've considered**

I have considered using the native `history.pushState` function, but [that appears to be discouraged](https://stackoverflow.com/questions/57340608/sapper-back-button-not-working-after-history-pushstate-function).

**How important is this feature to you?**

This feature is important to me and I'm sure other users would find it helpful.

**Comment by mquandalle** [comment]
Is this issue of an hybrid modal/standalone page solved?

**Comment by PatrickG** [comment]
I resolved it by giving the modal an own route.

For example:
`pages/posts/_layout.svelte` -> posts list
`pages/posts/index.svelte` -> empty file
`pages/posts/[id].svelte` -> modal
