### ISSUE TITLE
Non-latin route not recognized

### ISSUE THREAD

**Issue by datio** [sveltejs/sapper#1174]
Hello, I couldn't make the router to accept Greek characters.

The following router path works:
./src/routes/consent/gdpr.svelte

This one doesn't (_getting 404_):
./src/routes/**συναίνεση**/gdpr.svelte

I have tried to URL encode that filename on Ubuntu 18.04 which didn't fix the problem.

**Comment by benmccann** [comment]
Related to or possibly duplicate of https://github.com/sveltejs/sapper/issues/1002

**Comment by benmccann** [comment]
Closing in favor of https://github.com/sveltejs/kit/issues/2000
