### ISSUE TITLE
SSR and GraphQL: how to avoid the loading state if no javascript is present (async calls rendering)?

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/sapper#1177]
I'm trying Sapper and SSR (server-side-rendering) for the first time today.

I need to use it with NO-Javascript browsers along with standard ones.

In my Svelte/Sapper app I'm using GraphQL (Apollo, URQL or SVQL doesn't matter).

### QUESTION

Whatever the GraphQL client I choose I can't understand how to manage the loading of the call to the GraphQL endpoint.

I mean that since we are not in an environment where I can use the reactivity to an event to rewrite part of the DOM (I am rendering in the nodejs server) every time a user (or a bot: search engine) browses the site (without javascript) will only see the wait state for the GraphQL call: "Loading todos ...".

Am I brutally wrong?

### CODE EXAMPLE

```svelte
<script>
  import { initClient, query } from '@urql/svelte';

  initClient({ url: "https://0ufyz.sse.codesandbox.io" });

  const todos = query({
    query: `
      query {
        todos {
          id
          text
          complete
        }
      }
    `
  });
</script>

{#if $todos.fetching} <!-- This is the only state I see in my server rendered response -->
  Loading todos...
{:else}
  <ul>
    {#each $todos.data.todos as todo}
      <li>{todo.text}</li>
    {/each}
  </ul>
{/if}
```

Even if I manage to wait for the GraphQL response in the express server and to render the data instead of the loading message, the problem is that the times are much longer (if the GraphQL endpoint is slow) and the user experience is depressing, especially for the standard user with the browser and javascript.

Maybe I am missing something in the reasoning.

But what?

### UPDATE

Great guys at `Routify` use something called `$ready()` (https://routify.dev/docs/helpers#ready) to handle async calls.

I don't know what is wrong with me or if there is already something in Sapper to handle this case.

Maybe we can "differentiate" usesrs base on some headers values.

Can you point me in the right direction on this? I read all the Sapper docs!

**Comment by frederikhors** [comment]
Maybe related to https://github.com/sveltejs/sapper/issues/952?

**Comment by Conduitry** [comment]
With or without GraphQL, the only way to do this in Sapper currently is to have a `preload` that returns the actual data, and to have your page components accept this as props.

If you want this to be rendered on the server side, of course the responses are going to have to wait for the endpoints they get their data from. Nothing's going to be able to get around that.
