### ISSUE TITLE
Sapper framework error in Edge only: "unable to get property 'default'"

### ISSUE THREAD

**Issue by thinkloop** [sveltejs/sapper#1180]
Loading my site in chrome or firefox works fine, but loading in Microsoft Edge 44.18362.449.0 flashes the site correctly for an instant then switches to the sapper error page to display the following error:

```
TypeError: Unable to get property 'default' of undefined or null reference
   at Anonymous function (blob:http://localhost:3000/db3025e8-ba11-4321-8981-2f44248b012b:2:1)
   at Anonymous function (http://localhost:3000/client/shimport@1.0.1.js:1:6663)
```

Triggered by line 331 in file `@sapper/app.mjs`:
```
const { default: component, preload } = await load_component(components[part.i]);
```

Any ideas why?

**Comment by Conduitry** [comment]
Without a small reproduction of the issue, no.

**Comment by antony** [comment]
Also @thinkloop we don't support legacy Edge 44 directly, you need to use Babel and Polyfills in order to get Edge to work. See https://github.com/antony/sapper-ie for more details.

**Comment by thinkloop** [comment]
> 
> 
> Also @thinkloop we don't support legacy Edge 44 directly, you need to use Babel and Polyfills in order to get Edge to work. See https://github.com/antony/sapper-ie for more details.

This might be the issue. The exact problem is proving awkward to track down, but I do see various advanced syntaxes causing problems. I confirm everything works in new Edge. Isn't "legacy" Edge still the default for Windows?

**Comment by thinkloop** [comment]
Closing due to it working in New Edge and Legacy Edge not being supported.

**Comment by dennis-f** [comment]
I don't know why this is closed. Couldn't track down the issue yet but if you try wo have a look at https://svelte.dev/repl/hello-world?version=3.23.2 it will show the same behaviour.

**Comment by quantuminformation** [comment]
Edge 44, just came across this from my clients today to support this
