### ISSUE TITLE
rich-filemanager, elfinder - could not be resolved

### ISSUE THREAD

**Issue by Mlocik97** [sveltejs/sapper#1183]
from https://github.com/Rich-Harris/shimport/issues/29

Hello,

When I'm using these libs in Svelte/Sapper, and use `await import('rich-filemanager')` (in `onMount` func) I get error:
`'rich-filemanager' is imported by src/routes/disky.svelte, but could not be resolved – treating it as an external dependency`
same with elfinder and few other,... I have these libs correctly installed and I use rollUP template for sapper.

**Comment by Mlocik97** [comment]
it seems like `await import('rich-filemanager/src/js/filemanager.min.js')` is working, but I'm getting error ```
Uncaught (in promise) ReferenceError: jQuery is not defined
    at filemanager.min.js:3
```
I have jquery imported, what should I do?

**Comment by antony** [comment]
Please use [discord](https://svelte.dev/chat) for support issues.
