### ISSUE TITLE
onMount not firing on initial page load

### ISSUE THREAD

**Issue by boojum** [sveltejs/sapper#1186]
**Describe the bug**
During the first page load `onMount()` is not being triggered, works fine after the initial load.

**To Reproduce**
Component with a simple animation:

```
<script>
  import { onMount } from 'svelte';

  onMount(() => {
      console.log("foobar") 
  });
</script>
```
`console.log` won't run on initial page load. More realistic example is `window.matchMedia()`:

```
import { onMount } from 'svelte';

let onMobile

onMount(() => {
  const mql = window.matchMedia('(max-width: 767px)')
  mql.addEventListener('change', (e) => {
    if (e.matches) {
      onMobile = true
    } else {
      onMobile = false
    }
  })
})
```
`onMobile` is not being set when page loads initially, afterwards it works as expected.

**Expected behavior**
In the first example, 'foobar' being printed to the console on initial page load. Second: `onMobile` being set to the device screen size on initial page load.

**Information about your Sapper Installation:**
- Firefox 76.0

- Ubuntu 20.04

- Local

- Sapper version: 0.27.12

- Svelte version: 32.22.2

- dynamic application.

- Rollup

**Severity**
The issue impacts media queries which, in my use case, is a show stopper.

**Comment by antony** [comment]
@boojum can you provide a simple reproduction so that we can see this issue please?

**Comment by nickbencino** [comment]
@boojum Did you fix this I am having the same issue?
