### ISSUE TITLE
Export fails if html has no <base>

### ISSUE THREAD

**Issue by wyozi** [sveltejs/sapper#1202]
**Describe the bug**
Export will fail with a bad error message if Svelte has a route serving .html that does not contain `<base>` tag.  

The problematic code is https://github.com/sveltejs/sapper/blob/4a0ffd1b10604812657d8842058e9bc24e516134/src/api/export.ts#L188-L190

If there is no `base_match`, there won't be `base_href` either so `resolve` will receive `undefined` as the second argument.

I think it might be safe to replace `base_href` with `basepath` received from options, but not sure.

**Comment by Conduitry** [comment]
I believe this is the second of the two issues that #1118 is intended to address.
