### ISSUE TITLE
Importing Web Component

### ISSUE THREAD

**Issue by diegosanchezp** [sveltejs/sapper#1214]
Hello!
I'm trying to use web components in sapper with the _sapper-template-rollup_ , in this case I'd like to use one of the [Material Web Components](https://github.com/material-components/material-components-web-components) (**mwc**)

Sapper docs says that i've should install external components as a devDependencies, so i'm doing it that way. For example to install `<mwc-button>`, i execute `yarn add @material/mwc-button --dev`, I've also followed all the installations steps in the mwc docs.

Now when I import the `mwc-button` in `src/routes/index.svelte`

```
<script>
  import '@material/mwc-button';
</script>
...
<mwc-button id="myButton" label="Click Me!" raised></mwc-button>
```
I get the following error
```
if (typeof window.ShadyCSS === 'undefined') {
^
ReferenceError: window is not defined
    at Object.<anonymous> (/media/diego/Windows/Users/diego/Documents/Web Development/Svelte/sapper-material-webcomponents/__sapper__/dev/server/server.js:1608:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

```
In think what's happening is that the `mwc-button` is not defined when the svelte components mounts. So can you import the web component onMount function?

Or otherwise what would be the best way to do this?

Thanks!

**Comment by Conduitry** [comment]
That package depends on `lit-element` which assumes the existence of the `window` global, which will not be the case on the server. As with any import that can only run on the browser, you will need to wrap it in `onMount` or `if (process.browser)`. But also keep in mind that will never render correctly in SSR, and will not display anything until javascript has been executed.

**Comment by kylecordes** [comment]
Here's a bit of hope for the future... There is an effort underway (appears to be under active development) to support SSR for lit-element, eventually there may be a path to combine server-side rendering across different component framework/tools.

https://github.com/PolymerLabs/lit-ssr
