### ISSUE TITLE
Handling configuration in Sapper

### ISSUE THREAD

**Issue by benmccann** [sveltejs/sapper#1216]
## Background

There are a number of PRs or open issues that would require providing a configuration option. We should handle configuration in a well-thought out and consistent manner.

[language-tools already uses a `svelte.config.js`](https://github.com/sveltejs/language-tools/blob/3139ccd5b4306a914be4ba64b0c036fcd8888f78/packages/svelte-vscode/README.md#generic-setup) and [Svelte was considering adopting it more widely](https://github.com/sveltejs/svelte/issues/1101).

I'm assuming that we would use a `.config.js` because it's inline with the existing `svelte.config.js` and also because it's more flexible and allows providing additional types (e.g. `function`)

## RFC

Please see [the RFC](https://github.com/sveltejs/rfcs/pull/23) for a proposed implementation and list of Sapper PRs that might be affected

**Comment by antony** [comment]
Dare I say this sounds a bit like an RFC?

**Comment by benmccann** [comment]
RFC submitted!

**Comment by benmccann** [comment]
SvelteKit has a `svelte.config.cjs` file to address this
