### ISSUE TITLE
sapper export doesn't look for goto() so it doesn't include assets for hrefs from goto()

### ISSUE THREAD

**Issue by hypersundays** [sveltejs/sapper#1220]
**Describe the bug**
I have a success page in my app that is a sapper route. Since it is not something I link directly to, I go to it after a promise resolves using `goto('success')`.

When I run `export`, the assets for success page aren't included in the build.

**Logs**
After export, when I navigate to `/success` to test, I get a `404`.

In production, I get the `500` error page saying, `Failed to fetch dynamically imported module: ...`

**To Reproduce**
1. Start from the sapper template
2. Create `test.svelte` in `/routes` and add content
3. Add a button to `index.svelte` that triggers a function that includes `goto('test')` 
4. `npm run export` <--- you'll notice the link wasn't included when the command finishes
5. `npx serve __sapper__/export` and navigate to `localhost:5000/test` <--- you will get a `404` here but if you're deployed on Netlify, you'll get the `500` I mentioned earlier

**Expected behavior**
`sapper export` should look for not only `<a>` tags but also `goto()` calls

**Information about your Sapper Installation:**
- Your browser and the version: Firefox 76

- Your operating system: OS X 10.14.6

- Your hosting environment: Local & Netlify

- Sapper version 0.27.13

- Svelte version 3.22.3

- exported

- Rollup

**Severity**
I probably should've checked the success page sooner but I just assumed that since I didn't hear much about it, it was fine. I finally got around to it tonight and verified the problem then read the docs to find my answer. Annoying but honestly easy to see how the mistake could be made.

**Comment by Conduitry** [comment]
This is out of scope for what export does. Exporting doesn't run any of the js in your built site - it just crawls the static HTML that was created via SSR, and doing anything else would be massively more complicated. If you need to add specific pages to start crawling from during export, you can use the `--entry` command line option.
