### ISSUE TITLE
Inline style nonce

### ISSUE THREAD

**Issue by pgjones** [sveltejs/sapper#1231]
**Is your feature request related to a problem? Please describe.**
Yes, I would like to set a nonce on all inline style tags.

**Describe the solution you'd like**
See #1232 - use the same nonce that already exists for style tags.

**Describe alternatives you've considered**
Alternatives are to add `unsafe-inline` to the CSP, but this is much less preferable. 

**How important is this feature to you?**
Style is not as worrying as script tags (feature already exists). Yet still this is a good to have.

**Additional context**
My previous issue content,
```
Is it possible to configure or set a nonce for the inline styles?

I've not found anything searching, so maybe this is also a feature request.
```

**Comment by antony** [comment]
@pgjones if it's a feature request, please update this issue to use the provided template, so that it can be actioned.

**Comment by pgjones** [comment]
Updated with a PR implementation.

**Comment by Conduitry** [comment]
This has been added in 0.28.9.
