### ISSUE TITLE
client.connect is not a function

### ISSUE THREAD

**Issue by mishrasatyam** [sveltejs/sapper#1233]
**Describe the bug**
Issue fixes itself on refresh
Uncaught (in promise) TypeError: client.connect is not a function at manifest-client.mjs:230

**Logs**
In /src/node_modules/@sapper/internal/manifest-client.mjs
if (typeof window !== 'undefined') {
	import("/home/ubuntu/svelte-coldboachain/node_modules/sapper/sapper-dev-client.js").then(client => {
		client.connect(10000);
	});
}

**Comment by Conduitry** [comment]
How can we reproduce this? I'm not seeing it with the default Rollup or webpack templates.

**Comment by mishrasatyam** [comment]
I cannot reproduce it. I am using latest version of sapper
