### ISSUE TITLE
RollupResult.to_json corrupts images

### ISSUE THREAD

**Issue by benmccann** [sveltejs/sapper#1245]
Took me awhile to figure out that a method called `to_json` would be doing this until I opened it up:

https://github.com/sveltejs/sapper/blob/674727587bc0b5f28352443e2d9f999d27da66d7/src/core/create_compilers/RollupResult.ts#L92

Something bad is happening here:

https://github.com/sveltejs/sapper/blob/674727587bc0b5f28352443e2d9f999d27da66d7/src/core/create_compilers/extract_css.ts#L227

It appears to be overwriting my images. We should probably add a filter to make it operate only on `.js` files

**Comment by Conduitry** [comment]
Fixed in 0.27.14.
