### ISSUE TITLE
How to properly require __sapper__/build/server/server.js in a google cloud function

### ISSUE THREAD

**Issue by jp3492** [sveltejs/sapper#1247]
I am trying to deploy a Sapper SSR app to a google cloud function (NOT firebase cloud function). Im onstantly running into this error:

Detailed stack trace: Error: Cannot find module './__sapper__/build/server/server.js'

In my index.js
`const app = require('./__sapper__/build/server/server.js');
exports.app = app;`

I run npm run build before i deploy the function.
my package.json:
`{
  "name": "TODO",
  "description": "TODO",
  "version": "0.0.1",
  "engines": {
    "node": "10"
  },
  "scripts": {
    "dev": "sapper dev",
    "build": "sapper build",
    "export": "sapper export",
    "start": "node __sapper__/build",
    "cy:run": "cypress run",
    "cy:open": "cypress open",
    "test": "run-p --race dev cy:run"
  },
  "dependencies": {
    "compression": "^1.7.1",
    "express": "^4.17.1",
    "sirv": "^0.4.0"
  },
  "devDependencies": {
    "npm-run-all": "^4.1.5",
    "sapper": "^0.27.0",
    "svelte": "^3.0.0",
    "svelte-loader": "^2.9.0",
    "webpack": "^4.7.0"
  }
}
`

I dont understand how i cannot normall import the build sapper app.
the function cannot recognize the module and nothing from sapper is deploy with the function.

I would love to get some feedback on that because online there is no occurence of this scenario and i think it can be very helpful.

**Comment by antony** [comment]
Hi @jp3492 - please ask usage/support questions [in chat](https://svelte.dev/chat) where we will be better able to help you.
