### ISSUE TITLE
How to use Store

### ISSUE THREAD

**Issue by vladejs** [sveltejs/sapper#125]
I created a router/_store.js file and tried to use it inside a component.
It gave me errors trying to call _init of undefined on the compiled code.

Can anyone help me in how to use state management with sapper properly?

**Comment by Rich-Harris** [comment]
Each top-level page component (i.e. `routes/index.html`, `routes/about.html`, or whatever) that uses the store (or contains components that use the store) will need to add a reference to it like so:

```html
<!-- routes/index.html -->
<p>a store prop: {{$someprop}}</p>

<script>
  import store from './_store.js';

  export default {
    store: () => store
  };
</script>
```

Note that when you're using Store, there's only one instance for the server, so you need to ensure that you don't (for example) put personal information on the store unless you're in the browser!

**Comment by vladejs** [comment]
Thanks, will try that. I come back later with my results
I opened the issue because after getting that error and completely removing store references, o still get it. The only way to get back to normal is by setting store:false on webpage config.

**Comment by vladejs** [comment]
It worked, thanks!
