### ISSUE TITLE
Fresh sapper project with lodash import crashes

### ISSUE THREAD

**Issue by thomastilkema** [sveltejs/sapper#1281]
**Describe the bug**
Fresh sapper (`0.27.16`) project with Rollup crashes when importing `lodash` (function).

_In for example `src/routes/_layout.svelte`_:
```
<script>
  import Nav from '../components/Nav.svelte';
  
  // When importing lodash or one of its functions, it crashes (like the line below)
  import trimEnd from 'lodash/trimEnd';

  export let segment;
</script>
```

**Logs**
```
var freeGlobal = typeof commonjsGlobal == 'object' && commonjsGlobal && commonjsHelpers.commonjsGlobal.Object === Object && commonjsGlobal;
                                                                        ^
ReferenceError: commonjsHelpers is not defined
    at /[some-path]/fresh-sapper-lodash-error/__sapper__/dev/server/server.js:790:75
```

**To Reproduce**
1. `npx degit "sveltejs/sapper-template#rollup" fresh-sapper-lodash-error`
2. `cd fresh-sapper-lodash-error`
3. `npm i`
4. `npm i lodash`
5. `npm run dev` (everything works like a charm)
6.  in `_layout.svelte` for example, add `import trimEnd from 'lodash/trimEnd';` (it now crashes)

[Check my repo](https://github.com/thomastilkema/fresh-sapper-lodash-error)

**Expected behavior**
It should not crash

**Stacktraces**

<details>
  <summary>Stack trace</summary>

```
ReferenceError: commonjsHelpers is not defined
at /[some-path]/fresh-sapper-lodash-error/__sapper__/dev/server/server.js:790:75
    at /[some-path]/fresh-sapper-lodash-error/__sapper__/dev/server/server.js:17472:3
    at createCommonjsModule (/[some-path]/fresh-sapper-lodash-error/__sapper__/dev/server/server.js:375:5)
    at Object.<anonymous> (/[some-path]/fresh-sapper-lodash-error/__sapper__/dev/server/server.js:382:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
```
</details>

**Information about your Sapper Installation:**
- Your operating system: macOS Catalina 10.15.2

- Your hosting environment: Local

- Sapper version: 0.27.16

- Svelte version: 3.23.2

- Rollup

**Severity**
Annoying

**Comment by antony** [comment]
Certainly odd, and I don't dispute the issue. I'll try to recreate it  

however be aware that importing all of Lodash into your project will cause huge bundle bloat. Try angus-c's "just" modules as a tiny, light alternative.

**Comment by thomastilkema** [comment]
> however be aware that importing all of Lodash into your project will cause huge bundle bloat. Try angus-c's "just" modules as a tiny, light alternative.

Yes, I'm aware. Just wanted to keep things simple in this example. Updated the code to reproduce a little bit.

**Comment by s0kil** [comment]
@thomastilkema This issue can be resolved by doing an `npm update` in your project. Could not track down which dependency this problem arises from.

**Comment by thomastilkema** [comment]
That indeed fixes the issue @s0kil, thanks!
