### ISSUE TITLE
Documentation bookmarks not working

### ISSUE THREAD

**Issue by benmccann** [sveltejs/sapper#1290]
**Describe the bug**
When I go to https://sapper.svelte.dev/docs#this_error it usually leaves me at the top of the page instead of scrolling down to the appropriate section of the page. This does not seem to always happen, so perhaps its a race condition

**To Reproduce**
It doesn't work more than it does for me, but you may need to refresh a few times to see it

**Expected behavior**
I'm taken to the appropriate section of the docs

**Information about your Sapper Installation:**
- Your browser and the version: Chrome 83
- Your operating system: Ubuntu

**Severity**
Just a little annoying if it's only a bug with the documentation website. More serious if it's a bug that affects all Sapper applications

**Comment by antony** [comment]
@benmccann I have a feeling that this is a Sapper bug which I can't locate right now.

**Comment by Conduitry** [comment]
Hopefully this would be fixed by #1139 but I haven't tried. The version of Sapper that the Sapper site is built with is a bit old.

**Comment by benmccann** [comment]
Ah, thanks! You probably just saved me a bunch of time trying to track this down

**Comment by Conduitry** [comment]
:+1: Thanks! I've merged #1292 and redeployed the site.

**Comment by benmccann** [comment]
thanks!!
