### ISSUE TITLE
Server restart required to pick up TypeScript changes

### ISSUE THREAD

**Issue by benmccann** [sveltejs/sapper#1293]
From @awmcclain on Discord:

I'm seeing a weird behavior where it looks like svelte-preprocessor's typescript transpiling is only getting run when the sapper server first runs. If I make a change to a .ts file, it gets picked up by the file watcher in run dev (I see src/api/meeting.ts changed. rebuilding...) but the generated .js doesn't reflect my changes until i kill sapper and restart.

After a LOT of digging, I think what is happening is that there is a mis-sync between the sapper watcher, the rollup watcher, and the rollup-typescript watcher.

I'm seeing rollup trigger the typescript plugin on rebuild, but it's generating an old version of the code. It's unclear right now whether this is an issue between rollup and rollup-typescript, or it's the way that sapper is initializing rollup.watch
Next step would be probably creating a bare minimum test case but I've got to do other stuff today -- I'll see about looking into this another time.

@babichjacob and b-fuze (Mike32) confirmed seeing the same issue

**Comment by babichjacob** [comment]
[Minimal reproduction repo.](https://github.com/babichjacob/sapper-ts-mismatch)

Steps:
1. Clone and install
2. Run `dev` package script
3. Make a GET request, such as by visiting in the browser `/example`, and see the result `1`
4. Modify `src/routes/example.ts` and change `1` to `2`. The change will be picked up and "rebuild"
5. Do 3 again but still see `1` instead of the new `2`

**Comment by benmccann** [comment]
More info from Jacob on Discord:
> it's not a problem for me in .svelte files, just .ts, whether or not that .ts file is imported into a .svelte file or is only being used on the server side (e.x. server routes)
i.e. svelte-preprocess is irrelevant

**Comment by benmccann** [comment]
Working with @babichjacob we figured out that something changed in `@rollup/plugin-typescript` 4.1.2 because things work in 4.1.1

**Comment by benmccann** [comment]
I'm going to close this since it doesn't appear to be a bug in Sapper, but rather in the Rollup TypeScript Plugin
