### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by evgenylink** [sveltejs/sapper#1295]
I'm getting this in both firefox and chrome just from starting clean webpack template:

![image](https://user-images.githubusercontent.com/65871782/85846530-a2199700-b7ae-11ea-844f-a6efeec53036.png)

**Comment by antony** [comment]
This isn't reproducible on any of my machines, so I think it is specific to your machine, Please try the [Discord](https://svelte.dev/chat) for support with diagnosing your error.

**Comment by dselim** [comment]
I actually have the same problem. Steps to reproduce :

```sh
npx degit "sveltejs/sapper-template#rollup" my-app
cd my-app
npm install
npm run dev
```

It is my understanding that ` sapper dev` runs both the actual server (by default on port `3001`) and a development server (by default on port `10000`). I believe the problem stems from the development server not providing the required CORS response headers allowing calls from the page served by `localhost:3001` to call.

Wouldn't adding a CORS middleware with `Access-Control-Allow-Origin: *` to the development server solve the problem ? (There wouldn't be any security issue for development environments I suppose ?)

**Comment by dselim** [comment]
Actually my problem came from connecting to a distant machine using ssh port forwarding. A process was already running on port 10000 on this machine (which didn't respond with CORS headers), and it seems the sapper dev server silently failed to listen to that port.

My bad !
