### ISSUE TITLE
Parsing cookies headers bug or feature

### ISSUE THREAD

**Issue by jinxmcg** [sveltejs/sapper#1299]
**Is your feature request related to a problem? Please describe.**
Long story short

External GDPR script set cookie and includes in the cookie a timezone. The time zone has weird characters but the browser adds it as a cookie anyways : 
GDPRconsent=Global=false&datestamp=Mon+Jun+29+2020+22:58:36+GMT+0200+(Hora+**d’estiu**+del+Centre+**d’Europa**)&version=6.2.0&

Please notice the weird quote that got through browsers when setting a cookie. What happens next is that the browser sends the cookie to sapper which triggers exception and crashes with 500 for alll the following requests of the user. because sapper is right and maybe this " **is not a legal HTTP header value**" however 500 is overkill and the user cannot visit the website at all because his timezone is not url friendly and this cookie will be sent at every request, and because of an external script all his visits are killed until that cookie is removed.

**Describe the solution you'd like**
Allow the other cookies, but drop the one with not legal HTTP header value.

**Describe alternatives you've considered**
drop all cookies or verify **why** the browser let the script set this character in the cookie, maybe it is valid ???? and sapper did not (the accent in "d'estiu" )

**How important is this feature to you?**
Well, I was developing a sapper project (btw I loved developing using sapper) for a major brand who wanted to include their global GDPR cookie script...that did not go well for hundred of users around the world who complained

Thank you.

**Comment by antony** [comment]
Sapper doesn't do any parsing of cookies, this is handled by Polka. I would suggest switching from `polka` to `express` and seeing if the bug still exists, and if so, raising an issue in [Polka](https://github.com/lukeed/polka) to get this addressed.

In any respect, it's extremely difficult for anybody to fix this without a reproduction, so that would be a good first step.

**Comment by zolotokrylin** [comment]
I have pretty much the same issue. And I think the problem is with node-fetch version. Here is a potential fix: https://github.com/node-fetch/node-fetch/commit/feae6d6ec83de4bef57ffa0a3fe42bcd91d1922b
