### ISSUE TITLE
Support for "@/component" root imports

### ISSUE THREAD

**Issue by AnandChowdhary** [sveltejs/sapper#1314]
**Is your feature request related to a problem? Please describe.**
Currently, you need to manually provide relative imports, like:

```js
import Component from "../../components/Component.svelte";
```

**Describe the solution you'd like**
It would be nice if we could support `@/` absolute imports like other frameworks:

```js
import Component from "@/components/Component.svelte";
```

**Describe alternatives you've considered**
In our very specific use case, we have built a custom build system that supports `@/` imports by first replacing `@/` with `../../../` based on the file's location, and then uses the Sapper/Svelte build system.

**How important is this feature to you?**
It's not super important because we already have make-do support for this, but it'd be nice to see.

**Comment by antony** [comment]
Please see this issue - https://github.com/sveltejs/sapper/issues/551
