### ISSUE TITLE
scrolling to middle of page after navigation

### ISSUE THREAD

**Issue by jakecoffman** [sveltejs/sapper#1317]
**Describe the bug**

Scroll down on a long page, click a link to another long page. Once the new page loads you will be part of the way down the page already. 

Pinning to sapper to 0.27.7 seems to fix it. 

**Logs**

No errors.

**To Reproduce**

- go here https://stldevs.com/developers
- scroll down a bit
- click on someone

Source is here https://github.com/jakecoffman/stldevs-sapper

**Expected behavior**

I should be at the top of the next page, not the middle/bottom.

**Stacktraces**

No stacktraces.

**Information about your Sapper Installation:**

- Edge 83.0.478.61
- Windows
- Local, VPS
- Sapper version 0.27.16
- Svelte version 3.24.0
- not exported
- Rollup

**Severity**

Workaround pinning to previous version is acceptable, no rush.

**Additional context**

Svelte and Sapper are awesome!

**Comment by jakecoffman** [comment]
Actually pinning to an old version doesn't fix it, seems to happen randomly after navigating back and forth.

**Comment by habibrosyad** [comment]
Could confirm this. If you scroll down and click on the link fast enough (before the prefetch complete/kick in) then you will get the correct behaviour. However, once you open a page then you navigate back and click on the same link again (resources already cached for the page), then the scroll will not reset to the top of the page (unless you remove the cache).

**Comment by jakecoffman** [comment]
I removed prefetch and it fixed it, thanks @habibrosyad.

**Comment by jakecoffman** [comment]
Turns out removing prefetch didn't fix it all the time. 

I finally tracked down the issue. It was due to `height: 100%;` on `html, body` in my `global.css`.
