### ISSUE TITLE
this.redirect does not work in slug in subfolder

### ISSUE THREAD

**Issue by Gh05d** [sveltejs/sapper#1318]
**Describe the bug**
I created a folder called subroute with a file [slug].svelte. It contains this code:
```
<script context="module">
  export async function preload(page, session) {
    return this.redirect(400, "/");
  }
</script>
```
The intention is catching all requests to the subroute and redirect them, for example: https://myhomepage/subroute/not-there

**Logs**
I get a page with this:
This page isn’t working. If the problem continues, contact the site owner.
HTTP ERROR 400

Exchanging the 400 in my code with a 200 leads to the rendering of a blank page.

**Expected behavior**
The user should get redirected to the index.svelte page (aka the home route).

**Information about your Sapper Installation:**
- Your browser and the version: Chrome 83.0.4103.116 (Official Build) (64-bit)

- Your operating system: Linux

- Your hosting environment: Local

- Sapper version 0.27.16

- Svelte version 3.23.2

- If it is an exported (npm run export) or dynamic application.

- Whether your application uses Webpack or Rollup: Rollup

**Severity**
It is annoying as it can be circumvented by using a redirect in the onMount function. Nevertheless, this feels cumbersome.

**Comment by antony** [comment]
400 is a status code of Bad Request. https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

The app is returning the exact error you are telling it to.

If you want to redirect, use a 308, 302, or 301, all of which are documented at the above URL.
