### ISSUE TITLE
Flexible choice of rendering (SSR, SSG, incremental SSG)

### ISSUE THREAD

**Issue by websocket98765** [sveltejs/sapper#1324]
Currently, Svelte/Sapper appear to only offer all SSR (via `build`) or all static (via `export`).

In contrast, Next.js routes can be SSR, [SSG](https://nextjs.org/blog/next-9#automatic-static-optimization), or [incremental SSG](https://nextjs.org/blog/next-9-4#incremental-static-regeneration-beta), and are not required to all be the same.

- SSR: built when requested by a user.
- SSG: built during build step.
- Incremental SSG: first request by user fetches data & builds static version, subsequent requests receive static version.

This allows a site's marketing pages to use SSG, a dashboard to use SSR, and a blog to use incremental SSG.

**Describe the solution you'd like**

It'd be useful if Sapper allowed a way to choose which method is used per route.

**How important is this feature to you?**

It's not urgent. But I think it will be important long term for a framework to offer this to be competitive.

Adding this issue to track/follow this. 

**More info**

- [Blog post describing Next.js' solution.](https://nextjs.org/blog/next-9-3#next-gen-static-site-generation-ssg-support)
- [Link to Next.js's RFC discussing why and how this was implemented.](https://github.com/vercel/next.js/issues/9524)

**Comment by antony** [comment]
This is something that we're definitely interested in, but not something we have a plan for. We're open to ideas, thoughts, RFCs etc.

**Comment by firrae** [comment]
Currently Svelte seems like where I want to be, but I feel stuck between choosing the optimal path for my web app in incremental static gen, and using a tool I think is the better overall framework.

I will say I will be watching this as I might begin with NextJS but I'd be willing to jump to Sapper if this was brought in. I'm not big, but I feel it's becoming more popular across the board and I can bet NuxtJS picks up the feature son as well.

**Comment by antony** [comment]
This is related to https://github.com/sveltejs/sapper/issues/1346 and related to the RFC I'm working on. I think adamb on discord is also doing something along these lines.

I'll try to publish the RFC as soon as possible to try to bring all efforts into a single place.

**Comment by ajbouh** [comment]
Is distinguishing between the need for SSG and SSR really as simple checking whether a page lacks/has a preload function?

**Comment by pixelbucket-dev** [comment]
To be clear, I am absolutely new to Svelte/Sapper. I was just intrigued by the concept of starting of with it and do a blog with SSG and I wrongly assumed Sapper supports this already (after all the rave in the media :-P). However, after realising this is not supported (yet) I searched around a bit and found ElterJS https://github.com/elderjs/elderjs. This seems to do exactly what is asked of here. Maybe there can be some synergies.

**Comment by Catsvilles** [comment]
I really hope Incremental Static Regeneration will come to the new SvelteKit project! :)

**Comment by benmccann** [comment]
SvelteKit has `prerendering`: https://github.com/sveltejs/kit/blob/master/documentation/docs/10-prerendering.md

It also has `maxage`: https://github.com/sveltejs/kit/blob/master/documentation/docs/03-loading.md#maxage

Hopefully that solves most of this issue. I'm going to go ahead and close this since all development effort is focused on SvelteKit

**Comment by olimination** [comment]
Similar issues handled here:

https://github.com/sveltejs/kit/issues/661

https://github.com/sveltejs/kit/issues/2369
