### ISSUE TITLE
How to get .env file values in server.js passed to any js file that can read these values on the fly and not when built/rolledup

### ISSUE THREAD

**Issue by sainzg** [sveltejs/sapper#1327]
Does svelte have a way of making any .env variable become available not only from .svelte files using stores, but any js file that instead of having the code markedup as process.env.Variable which gets replaced at built time by rollup; instead get the value as for example session[variableName] in any js file.

In server.js the .env file can be read and hydrated as sapper.middleware session: vars. So from that point on how this session can be read from js files once all is client side, without rollup?

**Comment by Conduitry** [comment]
GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).

**Comment by sainzg** [comment]
But this is a problem, sapper to svelte there is no way to get environment
vars on the client side when it is supposed to be able to post to api from
it
