### ISSUE TITLE
Entry module "rollup.config.js" is implicitly using "default" export mode

### ISSUE THREAD

**Issue by rococosans** [sveltejs/sapper#1332]
**Describe the bug**
Updating to rollup 2.x causes  the follow to print to console on startup.

Entry module "rollup.config.js" is implicitly using "default" export mode, which means for CommonJS output that its default export is assigned to "module.exports". For many tools, such CommonJS output will not be interchangeable with the original ES module. If this is intended, explicitly set "output.exports" to either "auto" or "default", otherwise you might want to consider changing the signature of "rollup.config.js" to use named exports only.

This happens with a the default sapper install aswell

Reproduce:
npx degit sveltejs@sapper-template#rollup

npm i

npm run dev

I'm just looking for some clarification on how I can clean this up?

Thanks!

**Comment by benmccann** [comment]
There is a PR pending to fix this: https://github.com/sveltejs/sapper/pull/1326
