### ISSUE TITLE
Tutorial does not work

### ISSUE THREAD

**Issue by SteffRainville** [sveltejs/sapper#1333]
**Describe the bug**
Tried the LEARN sapper path found at https://sapper.svelte.dev/docs/

npx degit "sveltejs/sapper-template#rollup" my-app
or: npx degit "sveltejs/sapper-template#webpack" my-app
cd my-app
npm install
npm run dev

Went to localhost:3000 and got

500
Cannot read property 'map' of undefined

TypeError: Cannot read property 'map' of undefined
    at load_component (http://localhost:3000/client/client.6eb8927e.js:2093:75)
    at http://localhost:3000/client/client.6eb8927e.js:2044:50
    at Array.map (<anonymous>)
    at hydrate_target (http://localhost:3000/client/client.6eb8927e.js:2028:42)
    at navigate (http://localhost:3000/client/client.6eb8927e.js:1894:3)
    at handle_click (http://localhost:3000/client/client.6eb8927e.js:2211:3)

The OR path of the tutorial seem to work
npx degit "sveltejs/sapper-template#webpack" my-app

Windows 10 64 bit
Node v14.5.0

**Comment by benmccann** [comment]
I just tried and it worked fine for me on Ubuntu and Node 12.

**Comment by SteffRainville** [comment]
Just tested on Mac 10.15.6 with node 14.5.0 and it works so the problem seems to be limited to Windows

**Comment by nickolasgregory** [comment]
Working OK for me on
* Windows 10 64 bit
* Node v12.18.3

**Comment by antony** [comment]
Working ok for me on Ubuntu 20.04
Node v14

**Comment by SteffRainville** [comment]
Different message this morning on a different Windows 10 computer using node 14.6.0

c:\TMP>npx degit "sveltejs/sapper-template#rollup" my-app
npx: installed 1 in 2.407s
! could not fetch remote https://github.com/sveltejs/sapper-template
! could not find commit hash for rollup

c:\TMP>npx degit "sveltejs/sapper-template#webpack" my-app
npx: installed 1 in 2.602s
! could not fetch remote https://github.com/sveltejs/sapper-template
! could not find commit hash for webpack

**Comment by antony** [comment]
I feel like that computr is a degit issue when the computer is not authenticated (Even though it's a public repo). See https://github.com/Rich-Harris/degit/issues/37

**Comment by SteffRainville** [comment]
Confirmed ! The could not fetch issue was git related.

**Comment by SteffRainville** [comment]
Since it worked on another computer I upgraded to node 14.6.0 and npm cache clean -force and now the rollup version works.

**Comment by Shackless** [comment]
I have the same problem on my laptop. Upgraded from Node 12 to Node 14.6.0 and cleaned the npm cache but that didn't fix it. I have another Windows PC running the same version of Node 12 as before on my laptop and that works fine. 
In Firefox, you get slighty more information on the error than in Chrome which brought me to https://github.com/sveltejs/sapper/issues/1256. This seems to be the same error.

**Comment by benmccann** [comment]
I sent a fix for this issue: https://github.com/sveltejs/sapper/pull/1338

Thanks to @Shackless for remote debugging this with me!
