### ISSUE TITLE
Add typescript integration to sapper template repo

### ISSUE THREAD

**Issue by andrewragy** [sveltejs/sapper#1340]
**Is your feature request related to a problem? Please describe.**
As Svelte now supports typescript, please to integrate easy typescript for sapper

**Describe the solution you'd like**
add a script to the sapper template repos that automatically that turns the project to typescript like with the svelte template.

**Describe alternatives you've considered**
none

**How important is this feature to you?**
Very important! It will encourage me to work on more sapper projects

**Comment by Conduitry** [comment]
It doesn't fully work yet. #760
