### ISSUE TITLE
Destructured variables from props do not change value when route changes

### ISSUE THREAD

**Issue by plibither8** [sveltejs/sapper#1352]
**Describe the bug**

Premise:
* The current/active page is a dynamic route ([slug].svelte)
* There is a `details` object defined that changes value when the route changes.
* For this example, consider `let details = { page: 'Hello' }`, and component named `Inner.svelte`

Suppose we pass `details` completely as a prop to a component: `<Inner {details} />`. I can then access the `page` key of `details` from inside the component in two ways:
1. by destructuring `details`: `const {page} = details`, and then `<p>{page}</p>`
2. or by directly accessing it: `<p>{details.page}</p>`.

When using the first method, the para element will get rendered with the inital value `page` took (of the first page/route the user visits), and will *not* change if the user navigates to another route by suppose clicking on a link to another path (but same, dynamic route).

The second method works as expected, with details.page changing when the route changes.

**To Reproduce**

Repo: https://github.com/plibither8/sapper-prop-destructuring-bug
* [Inner.svelte component](https://github.com/plibither8/sapper-prop-destructuring-bug/blob/master/src/components/Inner.svelte)
* [[slug] route](https://github.com/plibither8/sapper-prop-destructuring-bug/blob/master/src/routes/%5Bslug%5D/index.svelte)

Live demo: http://sapper-prop-destructuring-bug.vercel.app/

**Expected behavior**
`page` should take up the new, updated, changed, mutated, modified value from `details`, and render it, like how method 2 does it.

**Information about your Sapper Installation:**

- The output of `npx envinfo --system --npmPackages svelte,sapper,rollup,webpack --binaries --browsers`
```
  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.41 GB / 7.53 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 78.0.2
  npmPackages:
    rollup: ^2.23.0 => 2.23.0 
    sapper: ^0.27.16 => 0.27.16 
    svelte: ^3.24.0 => 3.24.0 
```

- Your browser
Chrome: 84.0.4147.89

- Your hosting environment (i.e. Local, GCP/AWS/Azure, Vercel/Begin, etc...)
Local/Vercel

- If it is an exported (`npm run export`) or dynamic application
Buggy on both: exported and dynamic

**Severity**
Since there is a clear and easy workaround for the issue (method 2, directly accessing), it won't cause me much pain in the future (until this is fixed). But to debug where it was going wrong it took me an hour of extra work which sucked :/

**Additional context**
I've tried it without using a dynamic route, and the issue no longer appears. So this does prove that it is a dynamic route issue, and that it is an _issue_ (because of inconsistencies).

**Comment by ignatiusmb** [comment]
This is an expected behavior of Svelte and Sapper. A dynamic route is considered as one component, thus it mounts once when the page is opened, and because you used the de-structuring method with `const`, it only gets executed once when it mounts.

To get it working properly, Svelte provides the reactive label syntax `$:` to update the destructured variables every time `details` changes.
```svelte
<script>
  export let details;
  $: ({ page } = details);
</script>
```

**Comment by plibither8** [comment]
Hmm that's interesting. So I guess this is then closely related to #1278, not as a bug but the reason behind it behaving this way? In any case, I believe this should have better documentation because from first look this doesn't seem apparent.

**Comment by ignatiusmb** [comment]
Yeah, it took me a while to figure it out too. I would love to give the docs some love too, but I feel we'll have to wait for their (maintainers) take and decision on that issue.

**Comment by clockelliptic** [comment]
This shouldn't be closed until it is in the docs.
