### ISSUE TITLE
`$$props.$$slots` unexpectedly undefined during SSR

### ISSUE THREAD

**Issue by englishmatt** [sveltejs/sapper#1356]
**Describe the bug**
`$$props.$$slots` is unavailable in a component during SSR. It is currently not possible to render conditional slots, based on whether the slot was used, e.g.:

```
<!-- index.svelte -->
<Foobar>
    <p>Bazquz</p>
</Foobar>

<!-- components/Foobar.svelte -->
<script>
    let slots = $$props.$$slots; <-- Unexpectedly undefined
</script>

{#if slots.default}
    <div><slot></slot></div>
{/if}
```

This results in any/all components inside the conditional slot to not be rendered in SSR and _silently_ fail.

**Logs**
```
✔ server (1.8s)
✔ client (1.9s)
✔ service worker (52ms)
> Listening on http://localhost:3000
undefined
undefined
```

**To Reproduce**
Minimal reproduction [available here][1].

```
git clone https://github.com/englishmatt/sapper-minimal-solts-undefined-reproduction.git .
npm install
npm run dev
```

1. Navigate to [http://localhost:3000][2]
2. Observe Sapper logs in CLI, note the output of multiple `undefined` statements (see logs above). When loading the page with JavaScript disabled the slot is not rendered.

**Expected behavior**
For `$$props.$$slots` to have references to the slots when the component was referenced during SSR.

**Actual behavior**
`$$props.$$slots` is `undefined` when rendered using SSR. (`$$props.$$slots` is defined and available during CSR.)

**Information about your Sapper Installation:**
Output of `npx envinfo --system --npmPackages svelte,sapper,rollup,webpack --binaries --browsers`

 System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
    Memory: 3.61 GB / 15.91 GB

  Binaries:
    Node: 12.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD

  Browsers:
    Chrome: 84.0.4147.105
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
    Firefox 78.0.2 (but this wasn't discovered by the above)

Hosted locally; issue is present using Chrome or Firefox (which is not surprising as this appears to be an issue with server.js).

**Severity**
Blocking use of Sapper SSR (however CSR still works with Svelte).

**Additional context**
I'm building a personal site, with little resting on it. However, I would very much like to take full advantage of the progressive enhancement that Sapper conveniently provides, which is why I am filing this issue.

[1]: https://github.com/englishmatt/sapper-minimal-solts-undefined-reproduction.git
[2]: http://localhost:3000

**Comment by Conduitry** [comment]
This isn't a public API. There are discussions within Svelte of exposing this information in some official way, and once it is, it will be available in both browser and SSR builds.

**Comment by englishmatt** [comment]
That's good to know (and makes sense given the current syntax). Then I guess consider this a +1 for exposing the slot-context to the component.
