### ISSUE TITLE
Error: Cannot find module '../models/User'

### ISSUE THREAD

**Issue by fredrikaurdal** [sveltejs/sapper#1359]
**Describe the bug**
I'm importing a module in my Sapper application, but I'm getting the error `Cannot find module '../models/User'`

Imported with `const User = require('../models/User');`

Exported as `module.exports = mongoose.model('User', UserSchema);`

I haven't been able to resolve this on discord, gitter or stackoverflow so far. Therefore, I'm not sure if this is an issue with Sapper: https://stackoverflow.com/questions/63256124/error-cannot-find-module-models-user-mongoose-schema

**Logs**
```
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module '../models/User'
Require stack:
- D:\Storage\Business\Projects\Project\Web application\project\__sapper__\dev\server\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\Storage\Business\Projects\project\Web application\novelchart\__sapper__\dev\server\server.js:59953:14)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Storage\\Business\\Projects\\Project\\Web application\\project\\__sapper__\\dev\\server\\server.js'
  ]
}
```

**To Reproduce**
[Repository](https://github.com/fredrikaurdal/sapper-application-test)

**Expected behavior**
Import my mongoose schema in server.js from a separate file.

**Information about your Sapper Installation:**

- Local development

**Severity**
It makes development more difficult if I can't import modules.

**Comment by benmccann** [comment]
This isn't an issue with Sapper. You can definitely import modules.

You can see examples of importing code in the sample apps:
https://github.com/sveltejs/hn.svelte.dev/blob/871430356cdc244b9ea8091e4541b62b98e5eccd/src/routes/_layout.svelte
https://github.com/sveltejs/hn.svelte.dev/blob/f8852125d95a3d1b70260fc7f67918fcb822d476/src/server.js

**Comment by fredrikaurdal** [comment]
npm modules work fine, but I can't get .js files to work.

I did some testing with a new `sveltejs/sapper-template#rollup` project, and I'm getting the same error if I try to require a .js file that is not relying on any dependencies. The `config` import is a json file, which does work.

As you can see the path is correct: https://www.screencast.com/t/losqYdBAhBv

I didn't install any dependencies, only added two files and tried to require them.

**Comment by fredrikaurdal** [comment]
This has now been resolved: https://stackoverflow.com/questions/63256124/error-cannot-find-module-models-user-mongoose-schema
