### ISSUE TITLE
node_modules in src folder is not beautiful at all :)

### ISSUE THREAD

**Issue by plashenkov** [sveltejs/sapper#1371]
Hi there!

Some opinion here about discovering a `node_modules` folder in a `src` folder.
The `src` folder is our very own folder where we write the code.
That's really strange to see some generated artifacts here.

Why not to place autogenerated files to `__sapper__/lib` by default, for example? I can't see any downsides of doing this. And `client.js`, `server.js` and `service-worker.js` can simply import from there.

P.S. Came to Sapper and Svelte from Vue, and then Next.js world and... Sapper is absolutely clean and awesome.

**Comment by Conduitry** [comment]
It's so that you can easily import things from it from anywhere using regular Node module resolution rules. If you don't like this, you can use the `--output` option on `sapper dev`/`sapper build`/`sapper export` to write these files to a different directory.
