### ISSUE TITLE
Introduce better error handling

### ISSUE THREAD

**Issue by mweststrate** [sveltejs/sapper#138]
Exposing the following api isn't handled neatly (which is accessed through form submission)

```
export function post(req, res, next) {
   throw new Error("oops")
}
```

This will serve the internal server error page. That page itself will crash though, because the endpoint url doesn't have a page in the router (which makes sense because it is an api endpoint, not a page). In the following snippet from the runtime `target` will be undefined:

```
   return Promise.resolve().then(function () {
        var _a = window.location, hash = _a.hash, href = _a.href;
        var deep_linked = hash && document.getElementById(hash.slice(1));
        scroll_history[uid] = deep_linked ?
            { x: 0, y: deep_linked.getBoundingClientRect().top } :
            scroll_state();
        history.replaceState({ id: uid }, '', href);
        var target = select_route(new URL(window.location.href));
        return navigate(target, uid);
```

Causing this code block from the runtime to throw (`Cannot read property 'route' of undefined`):

```
    var loaded = prefetching && prefetching.href === target.url.href ?
        prefetching.promise :
        target.route.load().then(function (mod) { return prepare_route(mod["default"], target.data); });
```

Secondly, I doubt that rendering the internal server error page is the right approach for failing api requests; I think just preserving the default of express makes it clearer; it would reveal useful details about the error, rather than burying it in a generic html response

**Comment by Rich-Harris** [comment]
Changed the behaviour in 0.7.6 — I think this probably makes a bit more sense. Thanks
