### ISSUE TITLE
Upgrading to 0.28.0 from 0.27.x - new warnings 'preload' is not exported by 'src/routes/_layout.svelte'                                           │

### ISSUE THREAD

**Issue by samccone** [sveltejs/sapper#1380]
`'preload' is not exported by 'src/routes/_layout.svelte'   `
```
333: 
334:   if (!root_preloaded) {
335:     const root_preload = root_comp.preload || (() => {});
                                        ^
336:     root_preloaded = initial_data.preloaded[0] || root_preload.call(preload_context, {
337:       host: page.host,
```

Inside of `_layout.svelte`
```
<main>
  <slot />
</main>
```

**Comment by Conduitry** [comment]
This is expected until you update Rollup's `onwarn` filter as described in https://sapper.svelte.dev/migrating#0_27_to_0_28

**Comment by samccone** [comment]
Thanks for the note, I have sent a PR to clarify the instructions. I did see this note but did not find it clear exactly what needed to be upgraded. https://github.com/sveltejs/sapper/pull/1382

Thanks @Conduitry

**Comment by GiorgosK** [comment]
Rollup users should update the `onwarn` filter in `rollup.config.js` to match [the change made in `sapper-template`](https://github.com/sveltejs/sapper-template/pull/246/files).
