### ISSUE TITLE
Provide TypeScript declarations out-of-the-box

### ISSUE THREAD

**Issue by benmccann** [sveltejs/sapper#1381]
Right now people have to copy the below file into their project. We should generate it automatically:

https://github.com/babichjacob/sapper-typescript-graphql-template/blob/main/types/%40sapper/index.d.ts

**Comment by babichjacob** [comment]
Is it the right idea to make this only be done after running a Sapper-oriented fork of [`scripts/setupTypeScript.js`](https://github.com/sveltejs/template/blob/master/scripts/setupTypeScript.js) that gets bundled with the default Rollup and Webpack templates?

**Comment by benmccann** [comment]
I was thinking that it could live in something like [`create_app`](https://github.com/sveltejs/sapper/blob/master/src/core/create_app.ts) and always happen. People don't generally open up their `src/node_modules/@sapper` directory, so it will be hidden from them and not affect them if they're not using TypeScript

**Comment by benmccann** [comment]
I sent https://github.com/sveltejs/sapper/pull/1402 to provide TypeScript declarations automatically

We did get [a request to add a `scripts/setupTypeScript.js` to sapper-template](https://github.com/sveltejs/sapper-template/issues/251). That might not be a bad idea to do as a next step if anyone wants to take a stab at it

**Comment by martonlederer** [comment]
I might take a look at it and see if I can do it @benmccann
