### ISSUE TITLE
Generates CSS for components that are not included.

### ISSUE THREAD

**Issue by TheComputerM** [sveltejs/sapper#1384]
I imported my components into a JS file and then exported it from there
[File](https://github.com/TheComputerM/sapper-template-rollup/blob/master/src/components/all.js)
```js
export {default as Show} from "./Show.svelte";
export {default as DoNotShow} from "./DoNotShow.svelte";
```

There is a single global style present in [`DoNotShow.svelte`](https://github.com/TheComputerM/sapper-template-rollup/blob/master/src/components/DoNotShow.svelte):
```html
<style>
    :global(.doNotShow) {
        font-size: 100px;
    }
</style>

<h1>I should not be there</h1>
```

Meanwhite [`Show.svelte`](https://github.com/TheComputerM/sapper-template-rollup/blob/master/src/components/Show.svelte) is just a normal svelte file:
```html
<h1>Boiiii</h1>
```

This is my [`index.svelte`](), I have deleted all styles from all routes:
```html
<script>
    import {Show} from "../components/all.js";
</script>

<Show />
```

However when I look at the [generated CSS file](https://github.com/TheComputerM/sapper-template-rollup/blob/master/__sapper__/export/client/index.7d2cc45d.css)
```css
.doNotShow{font-size:100px}
```

This is a bug because I have never used DoNotShow.svelte in any of my routes or components, the global styles of the component still render into my final CSS file.

**To Reproduce**
https://github.com/TheComputerM/sapper-template-rollup

**Expected behavior**
The CSS should not be shown unless I used the component in the markup

**Information about your Sapper Installation:**
v0.28.0

**Severity**
This is really annoying for projects with large nested components, layouts and routes.

_Thanks_

**Comment by benmccann** [comment]
This would probably be fixed by either https://github.com/sveltejs/rollup-plugin-svelte/pull/79 or https://github.com/sveltejs/sapper/pull/1415

**Comment by TheComputerM** [comment]
Fixed by https://github.com/sveltejs/sapper/pull/1415
