### ISSUE TITLE
css files have incorrect hashes

### ISSUE THREAD

**Issue by benmccann** [sveltejs/sapper#1388]
The CSS files are getting the hash for the JS files.

E.g. `npm run build` on `hn.svelte.dev` returns:
```
__sapper__/build/client/[id].1ed50b8f.js
__sapper__/build/client/[id].1ed50b8f.css
```

The name for CSS is chosen by replacing the .js of the JavaScript file path with .css:

https://github.com/sveltejs/sapper/blob/a5d8cafc5c2d80ee8849c838c416c6ea6c60e7c5/src/core/create_compilers/extract_css.ts#L148

**Comment by ajbouh** [comment]
To fix this (assuming it's actually a bug) we need to stop blindly replacing .js with .css in the extract_css codepath

**Comment by ArekBartnik** [comment]
@benmccann why is this an error?

**Comment by benmccann** [comment]
If you change only the css and not the js I believe the file hash will not change as it should
