### ISSUE TITLE
Speed up sapper build time

### ISSUE THREAD

**Issue by ssrjs** [sveltejs/sapper#1400]
Sorry, if it has been already discussed, anyway - I didn’t find it outlined so clearly, but

It becomes impossible to "develop like a beast" (especially complex UI), while compile time is 3.5 seconds:

```
../routes/_layout.svelte changed. rebuilding...
✓ server (3.5s)
✓ client (3.5s)
✓ service worker (14ms)
```

I love Svelte/Sapper, but it is the biggest concern about using it for now, because it really affects business very hard

I'll be extremely glad and happy to hear, that it is known by core developers, and, probably get an official statement about current thoughts and priority in a roadmap)

**EDIT**

Just discovered, there are already several somehow related discussions:

- Snowpack (or ESM) for dev mode: https://github.com/sveltejs/sapper/issues/1204 (and best attempt made by https://github.com/sveltejs/sapper/issues/1204#issuecomment-647553216 - 350ms with pure installation, but no hot/regular reload at all - improvements still also needed anyway)
- Use nollup in development mode: https://github.com/sveltejs/sapper/issues/1207 (https://github.com/rixo/sapper-template-hot slightly reduces pain, but still significant build time - 2.1s on working project)
- Consider making Snowpack V2 the recommended way to develop Svelte apps: https://github.com/sveltejs/svelte/issues/4898 (not about Sapper)
- Also, as suggested in https://github.com/sveltejs/sapper/issues/239 changing `devtool: 'inline-source-map'` to `devtool: 'inline-cheap-module-source-map'` also makes some positive effect (fastest for now is `eval-cheap-source-map`)

**Comment by antony** [comment]
Closing this as it doesn't really contain anything actionable. Obviously HMR is something that we are actively moving towards and something highly desirable, but creating an issue to point to another bunch of issues to "raise awareness" isn't really moving us any further towards that goal.

Assisting others via the issues above, opening RFCs to discuss approaches, upsides, downsides, fixing issues with various implementations, testing, benchmarking, cleaning up and making PRs merge-able is. All of these tasks can be done on the relevant issues.

**Comment by sebastienbarre** [comment]
Thanks @ssrjs, raising awareness is a good thing, as it helps other developers make informed decisions.

**Comment by benmccann** [comment]
If this is something that anyone would like to contribute towards, I put some additional suggestions on how to improve this in https://github.com/sveltejs/sapper/issues/1460#issuecomment-683476642

**Comment by thousandsofraccoons** [comment]
How do I improve rebuild time with Rollup?
