### ISSUE TITLE
Rename rel=prefetch to sapper:prefetch

### ISSUE THREAD

**Issue by benmccann** [sveltejs/sapper#1401]
Sapper overrides the browser's default `rel=prefetch` behavior. There seemed to be agreement that we should stop doing this.

**Comment by ArekBartnik** [comment]
I think it would also be good to change the `rel=external`. It feels weird to use existing attributes for different behaviors.

**Comment by Conduitry** [comment]
`rel="external"` is a real thing though, which already means precisely what Sapper is using as. https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel The problem with `rel="prefetch"` is that it looks like a real thing but it is not.

**Comment by ArekBartnik** [comment]
@Conduitry what would you do if you had an sapper app on a [domain] with links to [domain]/[category] but [category] wasn’t part of your sapper app? Logically, all referenced resources are part of the site but not part of the sapper app. Using `rel=external` for these links is a “feel weird” part for me.
