### ISSUE TITLE
Combining hash and query params in url causes page store to have empty query object

### ISSUE THREAD

**Issue by matt3224** [sveltejs/sapper#1404]
**Describe the bug**
If you do something like `https://mysite.com/mypage#myanchor?myparam` the page store query property `$page.query` will be an empty object and the page won't scroll to the anchor

Both the anchor and param work fine independently however
`https://mysite.com/mypage#myanchor`
`https://mysite.com/mypage?myparam `

**Logs**
No errors or warnings are thrown

**To Reproduce**
Tested with Sapper 0.28 and Svelte 3.24.1

**Expected behaviour**
I would expect the page to scroll down to the anchor and do whatever the query param does

**Stacktraces**
N/A

**Information about your Sapper Installation:**

  System:
    OS: macOS 11.0
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 713.18 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.7.0 - /usr/local/bin/node
    npm: 6.14.7 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 84.1.11.104
    Firefox: 79.0
    Safari: 14.0
  npmPackages:
    rollup: ^2.23.1 => 2.23.1 
    sapper: 0.28.0 => 0.28.0 
    svelte: ^3.24.1 => 3.24.1 

**Severity**
Blocking the functionality of using those two items together which on the project i'm currently working on is a thing. It's not a show stopper but would be useful for the client

**Additional context**
Really appreciate everyones time, and happy to answer more questions!

**Comment by antony** [comment]
Have you tried it by passing the an actual value for the parameter? `myparam=myvalue` to check it's not that?

**Comment by matt3224** [comment]
I have tried `https://mysite.com/mypage#myanchor?myparam=true` for example

**Comment by Conduitry** [comment]
Query parameters need to come before hash fragments. That's how URLs work. Severs are never even sent the part after the `#`.

**Comment by matt3224** [comment]
Thanks, for setting me straight @Conduitry
