### ISSUE TITLE
WSL 2 Breaks livereload and reduces compile speed

### ISSUE THREAD

**Issue by tippexx** [sveltejs/sapper#1405]
**Describe the bug**
When using Ubuntu wsl2 livereload stops working and compile speeds are very slow. No issues using wsl1

**Severity**
Very low

**Additional Information**

This might be the Problem:
>- A project which requires cross-compilation using both Windows and Linux tools on the same files.
>- File performance across the Windows and Linux operating systems is faster in WSL 1 than WSL 2, so if you are using Windows applications to access Linux files, you will currently achieve faster performance with WSL 1.

_source: [Microsoft Docs](https://docs.microsoft.com/en-us/windows/wsl/compare-versions)_

I will try to put it in the Linux file system and see if it changes anything later and post the update here. For now all my projects are stored on the Windows side.

**Comment by tippexx** [comment]
Yes, when using WSL2 you need to be working inside the Linux file system, everything works as expected there.

**Comment by Conduitry** [comment]
See also #1150 - this is a current known limitation of WSL 2.

**Comment by tippexx** [comment]
> See also #1150 - this is a current known limitation of WSL 2.

Sorry, didn't see that one. @Conduitry
