### ISSUE TITLE
Export support for `/index.html` rather than `/`?

### ISSUE THREAD

**Issue by spsaucier-bakkt** [sveltejs/sapper#1406]
Is there a way to get `yarn export` to output files that work with the `index.html` file? Currently at the index.html link, it renders mostly correct but doesn't work properly.

My client's hosting setup doesn't allow `/`, sadly.

**Comment by antony** [comment]
Hi @spsaucier-bakkt - please come to [discord](https://svelte.dev/chat) for support questions, rather than github issues.

**Comment by benmccann** [comment]
I'm relatively sure there's an issue for this already in the issue tracker, so this one's a duplicate

**Comment by spsaucier-bakkt** [comment]
@benmccann Do you know where that issue is? I'd like to follow it.
