### ISSUE TITLE
`npm run dev` hangs after `created dist in <X>ms`

### ISSUE THREAD

**Issue by regnaio** [sveltejs/sapper#1409]
**Describe the bug**
Following Development section in Readme from https://github.com/sveltejs/sapper:

`npm run dev` hangs after `created dist in <X>ms`

on latest master (fa65a7a6c36d01af23f649c359923fb98e8300a2)

For reference:
$ npm -v
6.14.7

$ node -v
v14.8.0

**Logs**
$ npm run dev

> sapper@0.28.0 dev C:\dev\sapper
> rollup -cw

rollup v2.23.1
bundles runtime/src/app/index.ts → runtime\app.mjs...
(!) Circular dependency
runtime\src\app\app.ts -> runtime\src\app\goto\index.ts -> runtime\src\app\app.ts
created runtime\app.mjs in 300ms
bundles runtime/src/server/index.ts → runtime\server.mjs...
created runtime\server.mjs in 746ms
bundles src/api.ts, src/cli.ts, src/core.ts, src/config/rollup.ts, src/config/webpack.ts → dist...
(!) Entry module "src\config\rollup.ts" is implicitly using "default" export mode, which means for CommonJS output that its default export is assigned to "module.exports". For many tools, such CommonJS output will not be interchangeable with the original ES module. If this is intended, explicitly set "output.exports" to either "auto" or "default", otherwise you might want to consider changing the signature of "src\config\rollup.ts" to use named exports only.
https://rollupjs.org/guide/en/#outputexports
src\config\rollup.ts
(!) Entry module "src\config\webpack.ts" is implicitly using "default" export mode, which means for CommonJS output that its default export is assigned to "module.exports". For many tools, such CommonJS output will not be interchangeable with the original ES module. If this is intended, explicitly set "output.exports" to either "auto" or "default", otherwise you might want to consider changing the signature of "src\config\webpack.ts" to use named exports only.
https://rollupjs.org/guide/en/#outputexports
src\config\webpack.ts
created dist in 825ms

**To Reproduce**
Please make sure you've tested with the latest versions of Svelte and Sapper.

To help us help you, if you've found a bug please consider the following:

* If possible, we recommend creating a small repo that illustrates the problem.
* Reproductions should be small, self-contained, correct examples – http://sscce.org.

Occasionally, this won't be possible, and that's fine – we still appreciate you raising the issue. But please understand that Svelte is run by unpaid volunteers in their free time, and issues that follow these instructions will get fixed faster.

**Expected behavior**

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

  Stack trace goes here...
</details>

**Information about your Sapper Installation:**

- The output of `npx envinfo --system --npmPackages svelte,sapper,rollup,webpack --binaries --browsers`

- Your browser

- Your hosting environment (i.e. Local, GCP/AWS/Azure, Vercel/Begin, etc...)

- If it is an exported (`npm run export`) or dynamic application

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Sapper entirely?

Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by benmccann** [comment]
Mine says "[2020-08-14 16:37:42] waiting for changes..." after printing the messages you shared. Yours doesn't say that?

This would be almost impossible for me to debug since it doesn't happen on my machine. I'd recommend maybe just not using `npm run dev` and using `npm run build` instead.

**Comment by regnaio** [comment]
Mine doesn't say "waiting for changes..."

I'm trying to use `github.com/sveltejs/sapper` for the latest Sapper for Typescript support. This is because I don't see the latest Typescript support additions in `github.com/sveltejs/sapper-template` or after running
`npx degit "sveltejs/sapper-template#rollup" my-app`

Do you know how I can go about using your latest Typescript support changes?

Thank you for your time and help, @benmccann!

**Comment by benmccann** [comment]
You only need to use Sapper 0.28. I definitely would not try to use the code in `master` if that's all you need

The default template is just JavaScript. There are some templates that community members have created for TypeScript:
https://github.com/babichjacob/sapper-typescript-graphql-template
https://github.com/Zimtir/SENT-template

We'll be working on additional improvements and documentation, but in the meantime you can questions in Discord
