### ISSUE TITLE
Why client bundle in v0.7 weights 200kb and 20kb on previous 0.6.x?

### ISSUE THREAD

**Issue by vladejs** [sveltejs/sapper#141]
I just upgraded to v0.7 and executed both `sapper export` and `sapper build` commands. The result? 
Client bundle, specifically the file `client/main.js` weights `200kb`

Is because source mapping support?

**Comment by thgh** [comment]
I noticed the same, solution: `NODE_ENV=production sapper export`

**Comment by Rich-Harris** [comment]
whoops! fixed in 0.7.4, thanks
