### ISSUE TITLE
How to get all routes to export into static html?

### ISSUE THREAD

**Issue by martonlederer** [sveltejs/sapper#1419]
When I run `yarn run export` / `npm run export`, only one of my routes get exported as a separate static html file. I want all of them to get exported, into their own `.html` files.
Am I missing a setting?
The only route exporting is `/login`. 
You can check this in this repo: https://github.com/useverto/verto

**Comment by Conduitry** [comment]
Exporting works by crawling the site along links that are visible in the server-rendered HTML, as explained in https://sapper.svelte.dev/docs#Exporting . But GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).
