### ISSUE TITLE
ENAMETOOLONG error on webpack build

### ISSUE THREAD

**Issue by ralexrdz** [sveltejs/sapper#1422]
I was getting an error when running `npm run dev` for some slugs chunk files 
more than 255 characters long
`
ENAMETOOLONG: file name too long client/...index.js
`

adding this code to `webpack.config.js` fixed it

```
module.exports = {
    client: {
        optimization: {
            splitChunks: {
                name: false,
            },
        },
```

in case somebody else suffer the same

**Comment by bakkerthehacker** [comment]
This fix no longer works on webpack 5 due to changes in split chunks.  Changing [optimization.chunkIds](https://webpack.js.org/configuration/optimization/#optimizationchunkids) to something other than `'named'` does work with webpack 5
