### ISSUE TITLE
Possible service worker issue, causing fetch error

### ISSUE THREAD

**Issue by matt3224** [sveltejs/sapper#1432]
**Describe the bug**
After a period of time between running a sapper project (even a new one all clean and nice) in Safari (atleast) the service worker seemingly becomes corrupt or erroneous and will inform you that FetchEvent.respondWith received an error and that it's response is null. I have seen this on 2 different projects now, a test repo i made and a bigger client site which has led me to believe it's highly unlikely that my questionable code is causing it.

Here's the test repo that is exhibiting it https://github.com/matt3224/svelte-head/tree/without-%40html too

**Logs**
![Screenshot 2020-08-23 at 11 54 26](https://user-images.githubusercontent.com/2401925/90976956-86760700-e539-11ea-99ea-d06af0939965.png)

**To Reproduce**
Not sure this is going to be a simple one to reproduce, as i say it seems that if you run the repo and then leave it a few days and fire it back up you can get the error above in Safari, I do most of my dev in Safari (i know) but will switch to chrome for a bit to see if i can get it to happen there too.
https://github.com/matt3224/svelte-head/tree/without-%40html

**Expected behaviour**
I expect pre sapper 0.28 behaviour of no crashing, the only way to rectify it is to clear the website data, clearing caches does not solve it, like this:
![Screenshot 2020-08-23 at 11 55 42](https://user-images.githubusercontent.com/2401925/90977000-ee2c5200-e539-11ea-935c-6ca1c9d8a8ea.png)

**Information about your Sapper Installation:**
```
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
    Memory: 1.99 GB / 24.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.8.0 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 84.1.12.112
    Chrome: 84.0.4147.105
    Firefox: 79.0
    Safari: 13.1.2
    Safari Technology Preview: 14.0
  npmPackages:
    rollup: ^2.3.4 => 2.26.4 
    sapper: ^0.28.0 => 0.28.0 
    svelte: ^3.17.3 => 3.24.1
```

**Severity**
Definitely on the more severe side this one, i've not heard a client complain about it yet, that would certainly kick it up a notch. It's important to note that i'm seeing this in dev and prod

**Additional context**
Thanks for looking at this, really appreciate it!

**Comment by matt3224** [comment]
I tried with the debug lines, btw and didnt see any logs which i thought was odd, surely i would have seen something?

**Comment by acoyfellow** [comment]
+1.. I'm seeing new errors with the sapper service worker i've not seen before.
![image](https://user-images.githubusercontent.com/1666099/93523052-70712180-f900-11ea-93d5-b674870660e7.png)

**Comment by acoyfellow** [comment]
Downgrading from ^0.28 to ^0.27 has fixed it temporarily

**Comment by matt3224** [comment]
I stumbled on a way to reproduce this in Safari, despite now seeing the issue in chrome a couple times this repro doesnt work there.

If you head to a sapper site like https://bullet.design or https://mosaicmiddleeast.org or https://thechemistrygroup.com and clear the cache with `cmd + option + e` then refresh the site will be broken and the console will complain about fetch event stuff

To get the site to work again you need to go into Preferences > Privacy > Manage Website Data and clear it for the domain

I have also tried this on an older project using sapper 0.27 and i don't get the issue there
