### ISSUE TITLE
Pass polka.Request to preload()

### ISSUE THREAD

**Issue by hydroper** [sveltejs/sapper#1436]
**Is your feature request related to a problem? Please describe.**
intl. I need to clone a translator across requests. I'm able to map to which  request the cloned translator belongs during a middleware, but I'm not able to access this request on preload().

**Describe the solution you'd like**
Third parameter on preload(), polka.Request, or `undefined` on browsers.

**Describe alternatives you've considered**
It's not possible.

**How important is this feature to you?**
A bit.

**Additional context**

**Comment by antony** [comment]
Is this something you could seed the session with?

**Comment by hydroper** [comment]
@antony Probably yes, I'll try it soon.
