### ISSUE TITLE
accessing session data from server route

### ISSUE THREAD

**Issue by tvardy** [sveltejs/sapper#1437]
I'm not really sure (and had not yet found it in written) how could I access the session data from inside the servers routes.
For the `fileName.svelte` routes it's clearly said how to get such data from both, the preload function, and the component's script...
But what about the `fileName.js` route? I was initially expecting to have something like `req.session` available in my `get(req, res)` or `post(req, res)` functions... but... unfortunately, it's not there... :(

**Comment by antony** [comment]
Hi @tvardy - please ask support questions on [discord](https://svelte.dev/chat) as it is a better medium to help you - github issues is for bug reports and feature requests only. Thanks!

**Comment by danawoodman** [comment]
@tvardy or anyone else finding this via Google (like me), have a look at this article I just put together, think it may help 🤩

https://dev.to/danawoodman/getting-session-data-in-your-sapper-server-routes-51md
