### ISSUE TITLE
No way to change default Page content-type header

### ISSUE THREAD

**Issue by kohsah** [sveltejs/sapper#1442]
The page content type header is always sets as "text/html". 

There is no clear way to serve for e.g. XHTML which requires setting the content-type header to `application/xhtml+xml`. For various technical reasons i need to serve the pages as XHTML rather than HTML5. The only way at the moment seems to be to hack the code to replace instances of `text/html` with the XHTML content-type header.

**Comment by antony** [comment]
Since this is kinda an edge case, changing it with `sed` or similar after build seems like a reasonable way to do this.

Does this work as a long term solution for you? or are you expecting a feature/config to control the content type?

**Comment by Conduitry** [comment]
Another possibility would be to put some middleware before Sapper that monkey patches `req` so as to set the desired content-type whenever it's called with `text/html`.

**Comment by kohsah** [comment]
> Since this is kinda an edge case, changing it with `sed` or similar after build seems like a reasonable way to do this.

@antony Thanks, I tried this approach now and that seems workable.  Besides replacing `text/html` with `application/xhtml+xml`, I also had to change the way some elements in `<head>` were being generated e.g. `<base>` and `<link>` with element closures i.e.  `<link rel="" ... />` instead of `<link rel=""  >`

> 
> Does this work as a long term solution for you? or are you expecting a feature/config to control the content type?

Agreed that its an edge case, so don't really expect it as a feature. Though having it as a config would be nice

**Comment by kohsah** [comment]
> Another possibility would be to put some middleware before Sapper that monkey patches `req` so as to set the desired content-type whenever it's called with `text/html`.

Thanks, just tried this method and it works, if not a bit hackish -- coupled with the earlier reply, it basically solves the problem 

```

function overrideContentTypeHeader (req, res, next) {
	const modSetHeader = res.setHeader
	const refr = req.headers.referer;

	res.setHeader = function (key, value) {
		if (refr) {
			if (refr.search(/\/doc\//) !== -1) {
				if (key === "Content-Type") {
					if (value === "text/html") {
						return modSetHeader.apply(this, ['Content-Type', 'application/xhtml+xml']);
					}
				}
			}
		}

	  return modSetHeader.apply(this, arguments)
	}
	return next()
  }

polka() // You can also use Express
	.use(
		compression({ threshold: 0 }),
		sirv('static', { dev }),
		overrideContentTypeHeader,
		sapper.middleware()		
	)
	.listen(PORT, err => {
		if (err) console.log('error', err);
	});

```

**Comment by antony** [comment]
I'm not sure it's hackish per-se, it's just using the server-part of Sapper to modify output, which is pretty much the intention.

Either way - glad you could find a way to do what you needed. It probably won't be added as a feature unless there is significant demand, so closing this for now!
