### ISSUE TITLE
Some CSS Missing since 0.28.1

### ISSUE THREAD

**Issue by benmccann** [sveltejs/sapper#1446]
**Reproduction 1**
https://github.com/juho/sapper-rollup-css-strip

**Reproduction 2**
On Sapper v0.28.0: https://svelte-materialify.vercel.app/components/alerts/
On Sapper v0.28.2: https://svelte-materialify-g0c0gdngr.vercel.app/components/alerts/

Alert styles aren't being rendered. This is the scss file: https://github.com/TheComputerM/svelte-materialify/blob/sapper%400.28.1/packages/svelte-materialify/src/components/Alert/Alert.scss

**Additional Info**
Components which are not part of the _layout.svelte or are not included by components in _layout.svelte do not have their CSS generated.
Meaning components only included in routes do not have their CSS generated

**Comment by antony** [comment]
That's why I couldn't recreate the issue!

**Comment by juho** [comment]
adding these in rollup config makes the repro work:
`preserveEntrySignatures: false` in the client section and `preserveEntrySignatures: "strict"` in the server section

**Comment by Jayphen** [comment]
You can reproduce this by cloning the default sapper template and removing `preserveEntrySignatures` from the rollup conf

I made a repro here: https://github.com/Jayphen/sapper-preload-repro/tree/broken-css and deployed it here https://sapper-preload-repro-git-broken-css.jayphen.vercel.app/blog/why-the-name

**Comment by TheComputerM** [comment]
Here is the reproduction: https://github.com/TheComputerM/sapper-bug

**Comment by benmccann** [comment]
Thanks. I can reproduce using juho/sapper-rollup-css-strip. I don't have `yarn` installed and have never used it so I will use juho/sapper-rollup-css-strip to test since TheComputerM/sapper-bug is heavily reliant on `yarn`

**Comment by TheComputerM** [comment]
@benmccann I have updated my repo to use npm.

**Comment by kaipaysen** [comment]
A Workaround would be to add the component to _layout.svelte and wrap it within display:none like this:
```html
<!-- workaround until https://github.com/sveltejs/sapper/issues/1446 is fixed -->
<div style="display: none">
    <KontaktBar />
</div>
```
