### ISSUE TITLE
Route chunks are not included in preload headers

### ISSUE THREAD

**Issue by Jayphen** [sveltejs/sapper#1448]
Preload headers are included for all JS/CSS chunks loaded on any route, except for the route chunk itself.

For example, these are the preload headers for the document at https://sapper-preload-repro.vercel.app/blog/why-the-name

`</client/client.1af273ec.js>;rel="modulepreload";as="script", </client/assets/client-24271426.css>;rel="preload";as="style", </client/assets/[slug]-17a7b34f.css>;rel="preload";as="style"`

Note that the `[slug]-[hash].css` chunk from the route is preloaded, but not the `.js` file.

If you run Pagespeed against the above page (https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fsapper-preload-repro.vercel.app%2Fblog%2Fwhy-the-name), you'll get the following message indicating that the performance score has been reduced because of this:

![CleanShot 2020-08-26 at 23 53 24](https://user-images.githubusercontent.com/329184/91360765-56f42280-e7f7-11ea-85cc-6c0f8c5789ed.png)

The reproduction is here - it's just the base sapper template configured to deploy to vercel, and a couple of styles added https://github.com/Jayphen/sapper-preload-repro

**Comment by benmccann** [comment]
Hmm. `[slug].hash.js ` is not listed in `__sapper__/dev/build.json` under the route `blog/[slug].svelte` as I would expect it to be. That's where the preload headers are pulled from

**Comment by benmccann** [comment]
Ah, it seems this is a result of calculating the dependency tree in a new way and I didn't notice this line:

https://github.com/sveltejs/sapper/blob/de87668c9c9429f2033d249b52a9cae5c4d4b7f9/src/core/create_compilers/RollupCompiler.ts#L132
