### ISSUE TITLE
How can I preload client js?

### ISSUE THREAD

**Issue by vndre** [sveltejs/sapper#1456]
I'm exporting a small static site, but I'm having some weird flashes when the page first loads, it seems the default behaviour of Sapper is to inject the css and js code _after_ the html loads, making all text appear unformatted for a short period.

I feel the site loads a little faster and better when I enable the option `emitCss: true` in rollup config but now the logic goes like this:

page load -> parse css < links> -> downloads couple of small assets -> < link> with client.[hash].js get injected in head -> client js gets executed

I guess that happens because Sapper injects this piece of code at the end of the file:

```
var s=document.createElement("script");try{new Function("if(0)import('')")();s.src="/client/client.4c73d00e.js";s.type="module";s.crossOrigin="use-credentials";}catch(e){s.src="/client/shimport@1.0.1.js";s.setAttribute("data-main","/client/client.4c73d00e.js")}document.head.appendChild(s)
```

In my case I would like to execute client js early in the waterfall, so I think a < link preload> _already_ injected in the html would do the trick...

I have tried removing the `--legacy` flag from the export script but nothing seems to change? shouldn't it remove the above code and inject the script directly since we don't need to evaluate import() anymore?

I noticed there is a merged [PR](https://github.com/sveltejs/sapper/pull/1269) related to this but it also seems to not be working in exported sites?

_Sapper 0.28.2_

**Comment by benmccann** [comment]
You can control where in the file the scripts are injected. If you're using the latest version of the template they will be injected into the `head` element. I'm guessing you might have created your project before this update was made to the template. You should check that yours matches this latest version: 
https://github.com/sveltejs/sapper-template/blob/master/src/template.html

**Comment by vndre** [comment]
> You can control where in the file the scripts are injected. If you're using the latest version of the template they will be injected into the `head` element. I'm guessing you might have created your project before this update was made to the template. You should check that yours matches this latest version:
> https://github.com/sveltejs/sapper-template/blob/master/src/template.html

oh my gosh, I feel so dumb, its just moving `%sapper.scripts%` to the head heh. I thought Sapper handled the injection a little deeper behind, thank you.
