### ISSUE TITLE
Ability to add 'rel=prefetch' (functionality) to any element

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/sapper#1458]
**Is your feature request related to a problem? Please describe.**
Our app has buttons and some `<divs>` with variable `goto( '/whatever' )` click event handlers.
If we want to prefetch these url's, we can't, because `rel=prefetch` is only supported on `<a>` elements.

**Describe the solution you'd like**
What would be ideal is that we can just add `rel=prefetch` to any html element we want and have the compiler take care of the 'what URL' part. An easy alternative would be that we can pass a variable that contains the url. Something like:

```
<script>
let url = '/whatever'
</script>

<div rel=prefetch{url} on:click={() => goto( url )}>Something</div>
```

Maybe it would be better to change the `rel=prefetch` to something like `sapper:prefetch={}` instead, but i'll leave that to the wizards that will be able to actually make this feature request reality.

**Describe alternatives you've considered**
None

**How important is this feature to you?**
It would be very nice, especially when you're dealing with an application that uses actual buttons and other kinds of elements instead of heavily stylized hyper links.

**Comment by Conduitry** [comment]
I don't think using elements other than `<a>`s for links is something we want to make easier. There are already ways to programmatically prefetch the data for a page ( https://sapper.svelte.dev/docs#prefetch_href ) which you can call on mouseover. You could even write a Svelte action that encapsulates the onmouseover and onclick behavior into a single reusable unit.

**Comment by UltraCakeBakery** [comment]
> I don't think using elements other than `<a>`s for links is something we want to make easier. There are already ways to programmatically prefetch the data for a page ( https://sapper.svelte.dev/docs#prefetch_href ) which you can call on mouseover. You could even write a Svelte action that encapsulates the onmouseover and onclick behavior into a single reusable unit.

This approach doesn't add the logic `rel=prefetch` adds in terms of the added delay before actually calling rel=prefetch. We would have to write that ourselves, no?

Besides that, I think allowing this handler to be added on any element would be a great addition. What negatives do you see with implementing something like this?

**Comment by UltraCakeBakery** [comment]
I would like this issue to be re-opened for further discussion. I want to hear some more opinions on this.

**Comment by UltraCakeBakery** [comment]
@Conduitry please see my previous comment.
