### ISSUE TITLE
Proposal: prefix reserved keywords such as "segment"

### ISSUE THREAD

**Issue by riccardolardi** [sveltejs/sapper#1469]
As a newcomer it felt a bit awkward not knowing where `segment` was being actually set. It's consumed inside `_layout.svelte` and in `about.svelte` but it's nowhere been set? I had to figure out it was a "built-in" prop. If it was somehow prefixed (like  _layout.svelte and _error.svelte components) it would've indicated much better that it's not a usual prop.

I'm not sure this has been discussed before?

**Comment by antony** [comment]
There's a proposal to remove it entirely, which I think is a better idea. https://github.com/sveltejs/sapper/issues/824
