### ISSUE TITLE
Scroll position is not reset after a redirect

### ISSUE THREAD

**Issue by Jayphen** [sveltejs/sapper#1470]
When using `this.redirect` in a `preload` block, the scroll position is not reset after clicking a link that should redirect.

[Here's a reproduction](https://sapper-scrollto.vercel.app/about)

Scroll down and click on the link at the bottom, and notice that your scroll position does not get reset.

The redirect is being made here: https://github.com/Jayphen/sapper-noscroll-redirect-bug/blob/master/src/routes/%5B...path%5D.svelte

I simply have a catch-all route that redirects if the path is `/blah`.

**Comment by Jayphen** [comment]
Just to add to the above: presumably redirects should always result in scroll restoration, since the primary use case is patching up old links after a site migration. I can't think of any reason you would not want to scroll to 0,0, but if there is some reason perhaps this could be an option to `this.redirect`

**Comment by benmccann** [comment]
Yeah, I agree it should take you to the top of the page. If this is something you want to send a PR for, I would review it and help you get it in

**Comment by Jayphen** [comment]
Sure, can you please assign me here so I don't forget?

**Comment by benmccann** [comment]
done

**Comment by Conduitry** [comment]
This should be fixed in 0.28.4

**Comment by Jayphen** [comment]
Indeed it is!
