### ISSUE TITLE
_layout styles don't get applied on _error pages

### ISSUE THREAD

**Issue by IcyFoxe** [sveltejs/sapper#1480]
After cloning and installing the Sapper Rollup template, _layout styles don't get applied on _error pages, resulting in broken appearance. This however is not a problem in the Webpack template.

Any clue what could be the issue and how to fix it?

**Comment by rodoch** [comment]
I believe this is a duplicate of  #1472 and a fix has been merged to master with #1474.

**Comment by Jayphen** [comment]
This should be fixed in the recent 0.28.4 release.

**Comment by IcyFoxe** [comment]
I just updated and everything looks good! Awesome!
