### ISSUE TITLE
No CSS is being added to the bundles

### ISSUE THREAD

**Issue by yuliankarapetkov** [sveltejs/sapper#1481]
**Describe the bug**
No CSS is being added to the bundle, except for global CSS. The resulting project is HTML and JS only (and some global CSS).

**To Reproduce**
Update `0.28.2` to `0.28.3` and run a Sapper project that has component-level CSS.

**Expected behavior**
All component-level CSS should be included in the bundles, as in `<0.28.3`

**Information about your Sapper Installation:**

- Browser: Chrome 85.0.4183.83
- Environment: Windows 10 / localhost
- Sapper version: `0.28.3`

**Severity**
Critical, because I need to rollback to `0.28.2` in order for the project to work/look as expected.

**Comment by benmccann** [comment]
The CSS is being included for most project. I would need a sample project that reproduces it

There are a few CSS bug fixes that have gone into `master` since 0.28.3. Can you check if those fixes address your issue?

**Comment by benmccann** [comment]
I'm going to close this since I haven't heard anything back. Please let me know if it's still an issue and you can share more information with me and I will take a look
