### ISSUE TITLE
Resolve codeQL analysis warning

### ISSUE THREAD

**Issue by jsbase** [sveltejs/sapper#1490]
**Describe the bug**

githubs codeQL runnner warns with:

> This does not escape backslash characters in the input.

on:

```
var route_0 = /*#__PURE__*/Object.freeze({
    __proto__: null,
    get: get
});
```

**Links**

* [Screenshot](https://imgur.com/a/aMGFSDG)
* [Runner](https://github.com/blogmops/blogmops/security/code-scanning/1?query=ref%3Arefs%2Fheads%2Fmaster)

**To Reproduce**
Run the code-analysis.yml

**Comment by Conduitry** [comment]
I don't know what this is saying. Why are you running a code quality checker on built output? What backslashes is this referring to? Is there a real bug?

**Comment by jsbase** [comment]
i'm running the GitHub beta code scanning CI runner (codeQL) runner for my sapper project which is promting the warning for the server.js. I can't 
really tell what's the problem here cause i'm not a bug hunter. I also ignored the __sapper__ folder in the code scanning process because i can't see any weird behavior in the site. If you can't see any issue here go ahead and close this one 👍
