### ISSUE TITLE
Will Sapper attempt to serialize the resolved value from a page's preloading function?

### ISSUE THREAD

**Issue by d4rekanguok** [sveltejs/sapper#1491]
Hey folks — Sapper is wonderful. Saw this in [the docs](https://github.com/sveltejs/sapper/blob/71d47b059f397cfb943bf470032efbd86ed94ec3/site/content/docs/04-preloading.md#return-value):

> When Sapper renders a page on the server, it will attempt to serialize the resolved value (using devalue) and include it on the page, so that the client doesn't also need to call preload upon initialization.

Is this still true? I couldn't make this happen on an exported app (no reproduction at the moment, my apologies). A quick search for `devalue` on the codebase shows that it is only used in the middleware.

Thanks!

**Comment by benmccann** [comment]
Please ask questions on StackOverflow or Discord. Exported apps export the server rendered values
