### ISSUE TITLE
Question: Sapper for statically exported portfolio SPA?

### ISSUE THREAD

**Issue by riccardolardi** [sveltejs/sapper#1500]
I'm planning to build a single page app portfolio type website where all content should be on one page and visible by scrolling from one "chapter" to another. Still, I'd like to have routes so that you can share links to specific parts of the page. Also, so crawlers can find each "page" with no need for CSR and index them easily. Is Sapper suitable for this by exporting a static page? Is there any SPA example for static rendering in Sapper?

**Comment by Conduitry** [comment]
GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).
