### ISSUE TITLE
How can I use icomoon in sapper?

### ISSUE THREAD

**Issue by fran1990Web** [sveltejs/sapper#1511]
Im using node-sass

I dont know where I can use the folder font in sapper and i dont know where i have to use the folder generated by https://icomoon.io/....
I cant see the icons...

<img width="1301" alt="Captura de pantalla 2020-09-14 a las 15 56 58" src="https://user-images.githubusercontent.com/66871629/93095713-bed5b480-f6a3-11ea-8e6f-d37921087159.png">

<img width="33" alt="Captura de pantalla 2020-09-14 a las 16 03 07" src="https://user-images.githubusercontent.com/66871629/93095789-d9a82900-f6a3-11ea-8fb2-6f17c990b5b5.png">

<img width="163" alt="Captura de pantalla 2020-09-14 a las 16 03 19" src="https://user-images.githubusercontent.com/66871629/93095798-dca31980-f6a3-11ea-9eb4-a260ddd79d8a.png">

Does anyone have an example? 

Thanks you very much!

**Comment by antony** [comment]
Hi @fran1990Web - github issues is for reporting bugs or requesting feature enhancements to Sapper. For support, please chat to us [in discord[(https://svelte.dev/chat)

**Comment by fran1990Web** [comment]
thank you @antony
