### ISSUE TITLE
Remove circular dependency

### ISSUE THREAD

**Issue by benmccann** [sveltejs/sapper#1527]
> Circular dependency: src/node_modules/@sapper/app.mjs -> src/node_modules/@sapper/internal/App.svelte -> src/routes/_layout.svelte -> src/node_modules/@sapper/app.mjs

We should fix this. `_layout` doesn't need to depend on the whole app. Only on the `stores` for example. We could refactor out the `stores` such that the layout and app can both import them independently without the need for this circular dependency

**Comment by ehrencrona** [comment]
You mentioned this results in a warning. Where can I see this warning?

**Comment by benmccann** [comment]
It's been silenced in the Rollup config, so you would need to remove that: https://github.com/sveltejs/sapper-template/blob/b756d9df6157bb13611e53627ddeecd440432121/rollup.config.js#L16

**Comment by SystemDZ** [comment]
@benmccann it didn't work

**Comment by SystemDZ** [comment]
@benmccann How ready is sveltekit so far? to handle routing, ssr etc ?

**Comment by benmccann** [comment]
Yes, it does that already

**Comment by SystemDZ** [comment]
do you recommend using sveltekit then for a large ecommerce project, or sapper is more stable so far?

**Comment by benmccann** [comment]
SvelteKit had more functionality and better development experience. It is more likely to introduce bugs or API changes though if you lock to a working version hopefully you can address those in your own time. There's also the question of whether you'd want to start a new project in Sapper only to migrate later

**Comment by SystemDZ** [comment]
I understand! so i will keep using sapper, and upgrade later to sveltekit.
i'm sure the process will be easy!
