### ISSUE TITLE
FOUC (flash of unstyled content) when using sapper>0.28.0

### ISSUE THREAD

**Issue by martingraf4** [sveltejs/sapper#1531]
**Describe the bug**
There is a flash of unstyled content when using sapper version 0.28.1 or later (setting `emitCss: false`).

**To Reproduce**
1. Clone Sapper project template rollup `npx degit "sveltejs/sapper-template#rollup" my-app`
2. Change package.json to install sapper version 0.28.1 `"sapper": "0.28.1"` (the error also occurs in 0.28.7, the current version at the time of this writing, but 0.28.1 is the earliest version I could find in which the error occurs)
3. Install dependencies `npm i`
4. Change `rollup.config.js` so that svelte does not emit css `emitCss: false`
5. Run the template `npm run dev`
6. Open chrome, enable developer options and look at the network tab
7. Visit `localhost:3000`
8. The first loaded page is not styled
![image](https://user-images.githubusercontent.com/49309285/93667381-c0c5bc00-fa85-11ea-9f1a-f9990a085e01.png)

Rolling back to sapper version 0.28.0 solves this issue.
![image](https://user-images.githubusercontent.com/49309285/93667406-dcc95d80-fa85-11ea-83db-0c468722a38d.png)

**Expected behavior**
The general layout of the page should not change after loading more resources / the first loaded page should contain inlined css.

**Severity**
Blocking an upgrade to sapper versions greater than 0.28.0

**Comment by njbotkin** [comment]
For my project (with `emitCss: true`), the issue appears to begin in 0.28.7.

**Comment by benmccann** [comment]
@njbotkin your issue is a different one if you have `emitCss: true`. I found the issue with `emitCss: false` and have sent a PR to fix it. I have not seen any issues with `emitCss: true`. Can you file a new issue with a way to reproduce or share a sample site where this is happening or give more details of some sort?

**Comment by benmccann** [comment]
@njbotkin 0.28.8 has been released with additional fixes. If you are still having an issue with the latest version please let me know and give me more details about how I can see the issue
