### ISSUE TITLE
Duplicate CSS

### ISSUE THREAD

**Issue by benmccann** [sveltejs/sapper#1535]
Reported by @thecomputerm

https://svelte-materialify.vercel.app/getting-started/installation/ has:

```
<link href="client/client-d9450e49.css" rel="stylesheet">
<link rel="stylesheet" href="https://svelte-materialify.vercel.app/client/client-d9450e49.css">
```

I'm guessing we need to change this line:
https://github.com/sveltejs/sapper/blob/8c8d5fc407ba97434656fdf80c2ba7c53702ab02/src/core/create_compilers/RollupCompiler.ts#L28

We will need to check relative URL + base as well as absolute URL

Site to test against: https://github.com/TheComputerM/svelte-materialify/tree/master/packages/docs

**Comment by GitGangGuy** [comment]
Haha, just noticed this as well. Thank you for taking care of it!
