### ISSUE TITLE
inject_styles.js is not preloaded in v0.28.8 when site exported

### ISSUE THREAD

**Issue by TheComputerM** [sveltejs/sapper#1541]
As stated in this [PR](https://github.com/sveltejs/sapper/pull/1537), inject_styles.js is said to be preloaded but when run lighthouse on [svelte-materialify](https://svelte-materialify.vercel.app/) running sapper v0.28.8, is says:
![image](https://user-images.githubusercontent.com/24741538/93717455-a1b55000-fb93-11ea-8214-185dd6a2af31.png)

**Comment by benmccann** [comment]
I do see `inject_styles` being preloaded on the HN sample site. I don't see any scripts being preloaded on your site though. I'm guessing this is a site you host via `export`? If so, then this was actually just fixed today in https://github.com/sveltejs/sapper/pull/1539 and will be part of the next release
