### ISSUE TITLE
0.29 planning

### ISSUE THREAD

**Issue by benmccann** [sveltejs/sapper#1545]
I would like to propose the following breaking changes for 0.29:
* Remove `segment` prop from layouts (https://github.com/sveltejs/sapper/issues/824)
* Fix https://github.com/sveltejs/sapper/issues/1441 / https://github.com/sveltejs/sapper/issues/1538 / https://github.com/sveltejs/sapper/issues/1692. One possible fix might be to revert https://github.com/sveltejs/sapper/pull/1244 though I'm not quite sure how the `service-worker.js` in the template would need to be updated. Or possibly we could prepend the basepath in the manifest which would not be a breaking change and would not require the template to be updated. That might be easier/safer, but could result in a slightly larger manifest (though I'm not sure it'd matter after compression)
* ~~Remove Rollup CSS handling plugin. It's now nicely contained in a plugin that doesn't touch any other code. I recently 
converted [rollup-plugin-css-chunks](https://github.com/domingues/rollup-plugin-css-chunks) to TypeScript and would like to take a look at integrating our plugin there. See the RFC for full details: https://github.com/sveltejs/rfcs/pull/29~~ - SvelteKit as planned will not allow this. Better to keep Sapper aligned
* DONE - Upgrade `rollup-plugin-css-chunks` (https://github.com/sveltejs/sapper/pull/1666)
* DONE - `sapper:prefetch` (https://github.com/sveltejs/sapper/pull/1566)

**Comment by Conduitry** [comment]
I believe there are people currently using the fact that `segment` is undefined on error pages as a workaround for detecting that situation, so I think it would be nice to expose this information officially on the `$page` store in the same version as we remove `segment`. There's a PR open for this, but I have not looked at what it does or how it does it.

**Comment by benmccann** [comment]
Ah, good call out. That PR looks pretty solid. I had suggested at one point earlier that we include `status` there as well, but am now wondering if I didn't think that all the way through and it's not a good idea. E.g. it's probably not relevant in client-side navigation. I'd be interested in what you think: https://github.com/sveltejs/sapper/pull/1498/files#r492144537. Other than that it looks pretty good to me

**Comment by UltraCakeBakery** [comment]
Please leave #824 open for discussion. Maybe even move this to the next release. I think we should first see some real world examples, side by side, to make sure this change doesn't unnecessarily increase the codebase of your average (and/or more complex) sapper application.

**Comment by TheComputerM** [comment]
The segment prop is useless and can be easily replaced with $page.path which has nested route support (such as '/path1/path2').

**Comment by UltraCakeBakery** [comment]
> The segment prop is useless and can be easily replaced with $page.path which has nested route support (such as '/path1/path2').

When marketing Svelte people often make the point that the amount of bugs in your project increases as your codebase grows. This is why I would like to see a real world example before we make changes like this. If this way of doing things increases the amount of code we have to write, removing the `segment` prop would be a total waste. Its presence is and/or does not have to hurt anyone.

NASA wouldn't launch a rocket without testing each individual part and group of parts separately. We shouldn't either. 
Especially when it is a breaking change like this one that will require people to possibly rewrite a lot of small parts of code.

**Comment by TheComputerM** [comment]
Here: https://svelte-materialify.vercel.app/getting-started/installation/
The highlighting of left navigation items is taken care of using this.

**Comment by UltraCakeBakery** [comment]
> Here: https://svelte-materialify.vercel.app/getting-started/installation/
> The highlighting of left navigation items is taken care of using the page store.

In some other components of the docs you still use 'segment'. Idk if you've committed the changes already.
https://github.com/TheComputerM/svelte-materialify/blob/master/packages/docs/src/routes/_layout.svelte 

Imagine a application with a sidebar, a top navigator, secondary top navigator, both navigators having multiple modals and dropdowns each being their own component, a secondary dropdown, a footer with differently styled sitemaps, bla bla.
One simple sidebar isn't a good example because often applications have more than that.

Ofc there is also the fact that if you have an application like this `segment` may not always be sufficient. I get that. But that is exactly why I want to see a real world example of an application that has slightly more going on. The changes being in 1 simple commit would be ideal so we can compare the amount of code and if the tradeoff is worth it.

**Comment by jwrunner** [comment]
I upvote the "Remove trailing slash from service worker manifest" as it has broken my references to global.css, as I reference them like this global.css?v=TIMESTAMP. My stylesheets don't load anymore after the service worker has been activated. The bug can reproduced by simply adding on "?v=2" to the reference to global.css in template.html.

**Comment by ArekBartnik** [comment]
@benmccann how about https://github.com/sveltejs/sapper/pull/1427 ? :)

**Comment by UltraCakeBakery** [comment]
> @benmccann how about #1427 ? :)

Looking forward to this one too. Also the other pull that adds the 'focus' event listener.

**Comment by b1m1nd** [comment]
Remove leading slash from service worker manifest by reverting  <-- please and thank you ! 👍 

Needs to base it self off the url given in server.js

**Comment by tohodakilla** [comment]
👎 for removing segment

**Comment by TheComputerM** [comment]
Also, after working with both rollup and webpack in sapper, better support for webpack would be beneficial as webpack provides inbuilt HMR and better bundling.
Even Rich Harris suggests that [Use webpack for apps, and Rollup for libraries](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c)

**Comment by UltraCakeBakery** [comment]
https://github.com/sveltejs/svelte/pull/5428 would it be possible to get this merged in this update too? Or will this be a 0.30 change? (assuming it is ready for merging now) https://github.com/sveltejs/language-tools/issues/540

**Comment by benmccann** [comment]
sveltejs/svelte#5428 is not part of Sapper. It's part of Svelte which is released and upgradeable independently

**Comment by UltraCakeBakery** [comment]
> [sveltejs/svelte#5428](https://github.com/sveltejs/svelte/pull/5428) is not part of Sapper. It's part of Svelte which is released and upgradeable independently

Whoops! I read my personal open issues list wrong 🙈. Consider that question never asked!

**Comment by pngwn** [comment]
@TheComputerM That article is no longer correct in any way, Rich's view have changed since then. And his views have also changed since his view changed. That article was written over 3 years ago.

**Comment by daxxog** [comment]
@benmccann Do you think moving segment to a utility would be a good idea? I agree that it is a bit funky with how it currently works with layouts, but I understand there are some people who currently rely on the feature and like the minimal code.

Was thinking a utility that worked something like this might be a good middle ground -->
```javascript
import { pageSegment } from '@sapper/app';
const segment = pageSegment();
```

https://github.com/sveltejs/sapper/issues/824#issuecomment-716760125

**Comment by x-ror** [comment]
Do you continue to make changes to the sapper? but we never will see the v1.0?

**Comment by antony** [comment]
Sapper will likely go into a maintenance mode. Svelte Kit is the primary development focus. See [this video](https://www.youtube.com/watch?v=qSfdtmcZ4d0) for details.

**Comment by benmccann** [comment]
Sapper 0.29 is out with quite a few fixes. We didn't get done with everything on the list above with SvelteKit on the way, but still got lots of good improvements in anyway
