### ISSUE TITLE
CSS not applied to route child components when JS is disabled

### ISSUE THREAD

**Issue by rodoch** [sveltejs/sapper#1546]
**Describe the bug**
When JavaScript is disabled in the browser certain child components of the layout may be left unstyled.

**To Reproduce**
- Clone sapper-template.
- Update Sapper to v0.28.8, build and run.
- Disable JS in your browser.

Observe how the list of blog posts under /blog remains unstyled. I have observed this behaviour on larger apps of my own also.

![Screengrab of sapper-template blog page with unstyled list](https://user-images.githubusercontent.com/5305694/93815638-38464780-fc4e-11ea-9eb7-327b3f6e4072.png)

**Expected behavior**
The server-generated page should possess all CSS necessary to style its child components.

**Information about your Sapper Installation:**

- Tested Chrome, latest.
- Dynamic application

**Severity**
I understand that the range of scenarios where users of Sapper apps would have JS disabled is limited but this feels like a regression as it was not the case in versions < 0.28.0.

**Additional context**
Stab in the dark here but is there any sense in which `__inject_styles` runs client-side only?

**Comment by benmccann** [comment]
I'm not sure I'm seeing any issue here. What's pictured in the screenshot is what I see with or without JavaScript enabled. Can you post a screenshot of the working and non-working versions and describe what the difference is?

Yes, `Inject_styles` runs only on the client. But `index.[hash].css` should be included from the server, so that shouldn't matter.

**Comment by rodoch** [comment]
Thanks @benmccann. Here is the styled version:

![pic](https://user-images.githubusercontent.com/5305694/93819995-6595f400-fc54-11ea-877a-f52a94ff224b.png)

Notice in the sample in issue above the links have `text-decoration: underline` removed. I should have mentioned in reproducing this that you need to navigate from homepage to the blog. If you open /blog initially the appropriate styles will be loaded.

**Comment by Conduitry** [comment]
If you navigate from the homepage to the blog with js disabled, you will get an entirely new server-rendered page, as the SPA-link-click-interception relies on js. If you're selectively disabling certain js (e.g., if you're allowing the SPA code but not the inject_styles code) then I don't think that's a case we really want to solve for.

**Comment by rodoch** [comment]
> If you navigate from the homepage to the blog with js disabled, you will get an entirely new server-rendered page, as the SPA-link-click-interception relies on js.

This is the behaviour I expect.

> If` you're selectively disabling certain js (e.g., if you're allowing the SPA code but not the inject_styles code) then I don't think that's a case we really want to solve for.

I have globally disabled JS. This is why I am reporting it as a bug.

**Comment by benmccann** [comment]
[The only `text-decoration` CSS I see in the template is in the `Nav` component](https://github.com/sveltejs/sapper-template/blob/23e90f063757ad629f138f75028e9d8ed24f35fe/src/components/Nav.svelte#L45). I feel like you must have modified the template in some way because I can't reproduce this issue. I do get a new server rendered page with all CSS present when navigating between pages

**Comment by Conduitry** [comment]
I'm also unable to reproduce this. When I put some styles on the blog page, load up the home page with disabled javascript, and then navigate to the blog page, this happens via an old-fashioned page navigation, and the server-rendered blog page has those styles.

> I should have mentioned in reproducing this that you need to navigate from homepage to the blog. If you open /blog initially the appropriate styles will be loaded.

This sounds suspiciously like you're not getting a server-rendered copy of the blog page. If what you're getting for the server-rendered version of one page depends on what page you just came from, something very weird is going on - and it's something I haven't seen a reproduction for.

**Comment by rodoch** [comment]
Mea culpa, cleaned node_modules and not able to reproduce myself today. Still seeing the issue in a non-trivial app but I will see if this is a bug in my code and if not isolate and open a separate issue. Closing this for now.
