### ISSUE TITLE
Detect use of window/document on the server and provide a friendlier message

### ISSUE THREAD

**Issue by antony** [sveltejs/sapper#1554]
**Is your feature request related to a problem? Please describe.**

See https://github.com/sveltejs/sapper/issues/1226

Just be more helpful when people attempt to use window/document in server-side code

**Describe the solution you'd like**

1. A FAQ item on the Sapper docs
2. A way of detecting `window`/`document` usage (when undefined, in case somebody is doing something quite odd) on the server which points to the FAQ
3. The FAQ referencing [this docs page](https://sapper.svelte.dev/docs#Making_a_component_SSR_compatible)

**Describe alternatives you've considered**

Letting people suffer

**How important is this feature to you?**

It comes up a *lot*, it could reduce the support/help overhead and repetition.

**Comment by emirotin** [comment]
Solution proposal: in dev mode in the non-browser environment they can be defined as getters on the global object that print the helpful message.
