### ISSUE TITLE
Improve TypeScript type definition for stores

### ISSUE THREAD

**Issue by albertms10** [sveltejs/sapper#1556]
**Is your feature request related to a problem? Please describe.**
The `stores` function from `@sapper/app` has an `unknown` return type, although there is a known object returning some predefined values such as `preloading`, `page`, `session`, as seen in the [Sapper Docs](https://sapper.svelte.dev/docs#Stores).
```svelte
<script>
  import { stores } from '@sapper/app';
  const { preloading, page, session } = stores(); // => `unknown`, destructured items are `any`

  const delayedPreloading = derived(
    preloading,
    (currentPreloading, set) => { // as preloading is treated as `any`, TypeScript cannot infer types for fn parameters
      // ...
    }
  );

  // ...
</script>
```

**Describe the solution you'd like**
Adding types for these stores would improve DX.

**Describe alternatives you've considered**
Just ignore TypeScript warning about the `any` type in use cases.

**Comment by benmccann** [comment]
This is defined here:

https://github.com/sveltejs/sapper/blob/f5032a524e2b674e7c81a1f5606314b8af474289/runtime/index.d.ts#L15

**Comment by TheComputerM** [comment]
Can I try to fix this issue and open a PR?

**Comment by albertms10** [comment]
Of course!
