### ISSUE TITLE
Allow multiple CSP nonces

### ISSUE THREAD

**Issue by benmccann** [sveltejs/sapper#1565]
According to https://github.com/sveltejs/sapper/issues/1248#issuecomment-699442197 `replace` is only getting called for the first occurrence and we should be allowing multiple occurrences.

The line of code to change is here: https://github.com/sveltejs/sapper/pull/1249/files#diff-9c713b090053bf2158dc7db4484fb401R332

**Comment by Conduitry** [comment]
This should be fixed in 0.28.10.
