### ISSUE TITLE
Sapper 0.28 support for query parameters for static files is broken

### ISSUE THREAD

**Issue by iash44** [sveltejs/sapper#1587]
**Describe the bug**
After update to Sapper 0.28 links to static files are broken if link has request parameters.
Useful for custom fonts or images caching.

**Logs**
Please include browser console and server logs around the time this bug occurred.

**To Reproduce**
Create new project with 
npx degit "sveltejs/sapper-template#webpack" my-app

run test app and try to open 
http://localhost:3000/successkid.jpg?test

works only once or after hard reload (CtrF5), i.e. trying to refresh using (CtrR or F5) shows page:
This site can’t be reached
The webpage at http://localhost:3000/successkid.jpg?test might be temporarily down or it may have moved permanently to a new web address.

in the same time
http://localhost:3000/successkid.jpg
works fine

The same on sapper 0.27 works fine

**Expected behavior**
Expected to properly work with query params for static files.

**Severity**
Issue blocking update from 0.27 to to 0.28

**Comment by benmccann** [comment]
Is this broken with `0.28.0` or only starting on a later version? (Remove the `^` from `package.json` and run `npm install` again to test a specific version)

**Comment by iash44** [comment]
> Is this broken with `0.28.0` or only starting on a later version? (Remove the `^` from `package.json` and run `npm install` again to test a specific version)

The issue reproduced from 0.28.0, current version 0.28.10 also affected

**Comment by ignatiusmb** [comment]
Query params won't be passed without a value, have you tried with `?test=true`?

**Comment by iash44** [comment]
> Query params won't be passed without a value, have you tried with `?test=true`?
> 
> Edit: Wait nvm, I read it wrong. Although, I don't seem to have this issue with my app running `0.28.10`

same with param value

http://localhost:3000/successkid.jpg?d=de

note that first time it opens correctly, but when you try to refresh (response in browser cache I guess) it happens

PS: checked on last Chrome an last FF on Windows

**Comment by seppegadeyne** [comment]
I am also having troubles with accessing page.query in a preload function of a route. It works when you are on the website and click a link for example the pagination at https://nieuwbouwinspanje.com/te-koop below. But when you want to surf directly to https://nieuwbouwinspanje.com/te-koop?p=2 it doesn't work. The object query from page is empty in the preload function. 

Happens when the website has been exported.

**Comment by seppegadeyne** [comment]
I did a workaround for this issue by using `import { stores } from '@sapper/app';` in the `<script></script>` there I compare the exported query object from the preload function, if not the same as with this one from the stores I repeat the thing what preload needed to do ... links above are now working with this strategy.

**Comment by iash44** [comment]
> I did a workaround for this issue by using `import { stores } from '@sapper/app';` in the `<script></script>` there I compare the exported query object from the preload function, if not the same as with this one from the stores I repeat the thing what preload needed to do ... links above are now working with this strategy.

problem described in issue is not about accessing page.query, but about getting static files with params (for instance for caching). maybe they have same source not sure.

**Comment by ehrencrona** [comment]
I can reproduce this on Chrome, but not on Safari or Firefox. Chrome gives an `ERR_FAILED` without even reissuing the request. I suspect there is some kind of Chrome bug related to caching.

**Comment by ehrencrona** [comment]
Ok, I think I found it. What I can't quite explain is what changed between 0.27 and 0.28...

**Comment by seppegadeyne** [comment]
> > I did a workaround for this issue by using `import { stores } from '@sapper/app';` in the `<script></script>` there I compare the exported query object from the preload function, if not the same as with this one from the stores I repeat the thing what preload needed to do ... links above are now working with this strategy.
> 
> problem described in issue is not about accessing page.query, but about getting static files with params (for instance for caching). maybe they have same source not sure.

Indeed, thanks for pointing out.
