### ISSUE TITLE
Cannot use rollup plugin dynamic-import-vars with sapper

### ISSUE THREAD

**Issue by TheComputerM** [sveltejs/sapper#1596]
**Describe the bug**
Actually I am not too sure that this is a bug of sapper but I am pretty sure it is. I just cannot use [@rollup/plugin-dynamic-import-vars](https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars) with sapper. I just do not get what is the problem.

**Logs**
Browser says:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

**To Reproduce**
https://github.com/TheComputerM/sapper-dynamic-imports

**Expected behavior**
No error should occur. and output should be according to [this](https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#how-it-works)

**Stacktraces**
<details>
  <summary>Stack trace</summary>

  ✗ client
Identifier directly after number (1:11)
✔ server (4.2s)
✔ service worker (2.2s)
</details>

**Severity**
It is pretty important for my use case.

**Additional context**
I think the output of sapper is in ESM so I do not think there is any problem, that is why I am so confused. First I thought the problem was with rollup but it is not.

**Comment by TheComputerM** [comment]
Fixed the problem: add dynamic imports inside onMount

**Comment by benmccann** [comment]
Perhaps https://github.com/sveltejs/sapper/pull/1595 will help here too since it was a problem with dynamic imports
