### ISSUE TITLE
Store can leak between pages

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#16]
A (unlikely but possible) security issue — if a page sets a value on `store`, it will be present when that page (or any other page also using the store) is re-rendered for another request. In extreme cases this could result in personal information being shared.

Not totally sure what the best solution is.

**Comment by LorbusChris** [comment]
Adding a Content Security Policy to ensure talking to the right server(s) might help mitigate this.
https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
https://developers.google.com/web/fundamentals/security/csp

**Comment by Rich-Harris** [comment]
this can be closed; as of 0.10, a store can be created per-request
