### ISSUE TITLE
SCRIPT445: Object doesn't support this action

### ISSUE THREAD

**Issue by silvioprog** [sveltejs/sapper#1605]
This error is returned in browsers like Opera/Samsung for TV and IE11 even compiling my Sapper app with legacy support.

Steps to reproduce:

```bash
npx degit "sveltejs/sapper-template#rollup" my-app
cd my-app
npm install
```

Chance the `index.svelte` by adding a button and handling its click event:

```diff
...
<h1>Great success!</h1>

<figure>
  <img alt='Success Kid' src='successkid.jpg'>
  <figcaption>Have fun with Sapper!</figcaption>
</figure>

<p><strong>Try editing this file (src/routes/index.svelte) to test live reloading.</strong></p>

+<script>
+function handleClick() {
+  alert('clicked')
+}
+</script>
+
+<button on:click={handleClick}>
+  Click me
+</button>
```

Export the project with legacy support (the `package.json` already declares `sapper build --legacy` on its `export` script):

```bash
npm run export
```

Copy the generated files to your favorite HTTP server (e.g. nginx), access the app page, and try to click the button. It will return the following error without showing the alert with `clicked` message:

```
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
my-app.silvioprog.vercel.app
HTML1300: Navigation occurred.
my-app.silvioprog.vercel.app
SCRIPT445: Object doesn't support this action
shimport@2.0.4.js (1,6959)
```

You can check the generated app here: https://my-app.silvioprog.vercel.app/

**Comment by Conduitry** [comment]
All Sapper's doing is giving you the normal or legacy build depending on whether your browser supports async functions. If you need more transpiling to happen or you need certain polyfills, you're responsible for adding those to your project.

**Comment by silvioprog** [comment]
But I'm not using any async function, it is just a normal function in an `onclick` event. Could you please teste it?

**Comment by benmccann** [comment]
Here's an example if you need help setting up IE support: https://github.com/antony/sapper-ie

**Comment by silvioprog** [comment]
@benmccann, you solved a big problem! I almost switched my project to VueJS due to this problem, however, after your indication, everything works fine now. Thank you very much! 👍
