### ISSUE TITLE
I can't get hash string from url using sapper stores()

### ISSUE THREAD

**Issue by niklasgrewe** [sveltejs/sapper#1607]
Hi, i have a url like this `http://localhost:3000/sub#item-1` 

I try to get the hash from the url with `const { page } = stores()` like this:

```js
import { stores } from '@sapper/app';

const { page } = stores();
console.log($page.path); // output: /sub
```
But i only get `/sub` as path and not `sub#item-1` - why?
I also try to use `window.location.hash` - it works but it isn't reactive, when i am using it like this

```html
<a aria-current={window.location.hash === '#item-1' ? 'page' : undefined} href="/sub#item-1">Item 1</a>
```

How can i get this working?

**Comment by Conduitry** [comment]
The server can't see the hash, so this isn't something that `$page` would be able consistently expose.

It might be a reasonable feature request to expose this on the client, with the understanding that it will be missing/null/whatever when read on the server.

There are events you can listen to that fire when the hash changes, and you could build your own store that works only on the client.

**Comment by niklasgrewe** [comment]
@Conduitry ok thanks for the quick answer. I would be very happy if `@sapper/stores` would support hashes on the client side in the future 👍 For now i will create my own store() and update the hash manually.
