### ISSUE TITLE
On Firefox browser, Sapper web page doesn't load on the first try

### ISSUE THREAD

**Issue by IcyFoxe** [sveltejs/sapper#1608]
Not sure if this is a Firefox bug or Sapper bug, but when I try to open the website I'm working on in Firefox, it always loads only after I hit enter twice. I tested it on fresh install of Sapper using Rollup or Webpack and it still does it.

### How to reproduce:
Run a Sapper dev server, open fresh instance of Firefox **with no other tabs opened before** and paste or type the address of the server and hit enter. Page should open only after second try.

If you opened a different tab before opening your page, it will load on the first try.

Tested on Windows 7 x64, latest version of Firefox.

**Comment by UltraCakeBakery** [comment]
I can't reproduce this issue. I highly recommend reinstalling the latest version of Firefox completely. Also maybe upgrading to windows 8.1 or 10 as windows 7 is no longer supported by Microsoft itself.

Does this still happen to you?

**Comment by IcyFoxe** [comment]
Reinstalling Firefox certainly did help. Which is interesting, because not so long ago, I installed fresh version of it..
Either way, thanks for your help!
