### ISSUE TITLE
Bundle multiple sapper pages / svelte applications together

### ISSUE THREAD

**Issue by floratmin** [sveltejs/sapper#1609]
**Objective**
When creating websites often there are different needs where some parts of the website are static, others dynamic or work like a SPA. We can already set sapper and svelte up to be served from sub paths. The drawback is that a lot of functionality gets duplicated and therefore a lot of files will get downloaded multiple times. So it could be extremely beneficial to have the possibility to bundle all the parts together and share components and modules (or even when using a scss framework the css generated by the framework) between the applications.

**Solution**
The easiest way would be to instruct sapper to use different entry points for different routes. We could e.g. have the following instructions (where shop could be served by a server, the app being a svelte SPA):
```
{
  "/": {
    entry: "src",
    app: "sapper/export"
  },
  "shop": {
    entry: "src-shop",
    app: "sapper/build"
  },
  "app": {
    entry: "src-app",
    app: "svelte"
  }
}
```
This approach would not complicate sappers build process very much. Links in each part relating to another part would have to have `rel="external"` and each application has to live in their own folder structure containing the routes. Then we restrict each installation (except the root application) to one root folder. With the `--routes` flag we could even have, if desired, a folder structure as if it was one application. This change could be made with minor changes to sapper.

An other approach could be to define which routes belong to which part of the application and let sapper make the splitting. Sapper could also then set the `rel="external"` tags to links automatically. Refactors of routes between the different parts would be very easy. The application to every route could be set individually. This would be a bigger effort and would require some major changes.

**Showcase**
I made it conceptually work with two exported sapper pages and one svelte app [(see repository)](https://github.com/floratmin/sapper-svelte-multiple-installations-example). I did not change anything in sapper, instead i used the rollup config settings (I had to disable the newly added @rollup/plugin-url to get the same bundles from the different builds of sapper) and a post export script to repair the html files after exporting. I made some tests; components and imported packages get automatically shared between the applications. The only missing thing would be to collect all the scoped css into one file per app, extract the shared css from the scss framework treeshaked into one bundle and then import these files directly from the html files. I made this work when separately bundling the applications. But in a single build the scoped css would be mixed with each other.

**Results**
I imported some lodash functions into each part and saw that the main import chunk and the imports shared in both applications get bundled into one file. The functions imported into one part get bundled together with the bundle of this part of the application. The same holds for components which are shared between the applications. The savings for the navigation menu included in the template was  8000 bytes, the savings for one button was 2000 bytes, the savings of one shared lodash function (including lodash's boilerplate) was 17000 bytes per additional application (all sizes without applying terser minification).

**Discussion**
This feature was before reported as an issue at [#686](https://github.com/sveltejs/sapper/issues/686), but closed. So I saw the best fit to open this request as a feature proposition. If this feature should be considered important, than I would be happy to contribute.

**Comment by benmccann** [comment]
We are working on a new version of Sapper called Svelte Kit that will allow you to prerender selected pages while leaving others to be dynamic
