### ISSUE TITLE
Using sapper export for an unknown basepath

### ISSUE THREAD

**Issue by martonlederer** [sveltejs/sapper#1611]
I want to export a Sapper application to an unknown basepath. The reason behind this is that I want to deploy it on a crypto-deploy system, which basically hosts the app in a subdirectory, named after the transaction ID of the deploy. (Example URL: `url.com/transaction-id-here`)

I already figured out how to replace basepaths in the exported code to the transaction IDs, but I have a problem:

When I use `sapper export --basepath my-basepath` and set the `server.ts` file to host from the `/my-basepath` path, the routes still redirect to the base dir of the site. Now I do use absolute paths in redirects/links and `goto()`s (with slashed before the routes), but **is there a way to tell Sapper to place the basepath before these links/redirects and `goto()`s?**

**Comment by ehrencrona** [comment]
I'm not very familiar with that part of Sapper, but it looks like `goto` does prepend the basepath and it is in turn [retrieved from a tag called `base`](https://github.com/sveltejs/sapper/blob/master/runtime/src/app/goto/index.ts). That tag is added to your application through your `template.html` where `%sapper.base%` is replaced by the base tag. If you want to manipulate it you can presumably replace it by generated it yourself instead.

**Comment by martonlederer** [comment]
Alright, thank you :)
