### ISSUE TITLE
Folder naming of "static" and "__sapper__"

### ISSUE THREAD

**Issue by Zerotask** [sveltejs/sapper#1616]
At first it was a bit confusing with the folder names static and `__sapper`__ since you are used to specific conventions. Therefore I'd suggest to rename those folders:
- static to assets
- `__sapper`__ to dist

Besides that, I noticed that there are 2 node_modules folders (root and in src). It would be easier if there is just 1 node_modules folder like in a regular Svelte project (and same as in Vue or Angular).

**Comment by antony** [comment]
Sapper is no longer being actively developed, and will be a series of modules which allow you to produce Sapper-esque apps. The `__sapper__` directory will no longer be used. The existing folder names are, however, better at representing their purpose (static is literally served up as-is, and being static in nature.

The `node_modules` decision is very well documented and discussed, it's in the FAQ here https://sapper.svelte.dev/faq#why-is-there-a-node_modules-folder-in-src and is not going to change.
