### ISSUE TITLE
Change default server from polka to express

### ISSUE THREAD

**Issue by Zerotask** [sveltejs/sapper#1617]
Since most people in a JS / NodeJS environment know Express, it would be easier to start with Sapper if they see known things and I guess Polka is maybe a good alternative, but with just about 4k GitHub stars not really a big thing (compared to Express with 50k stars).

**Comment by peopledrivemecrazy** [comment]
Sorry, but polka just works fine. Stars don't usually define any standards (code quality, performance, etc., ). Moreover, the syntax is not that different https://github.com/lukeed/polka#middleware

**Comment by patrick-hintermayer** [comment]
I didn't say that Polka isn't working good, but Express is a standard for webservers, Polka isn't and GitHub Stars is a representing number (it often correlates with the amount of people who use it).
It shouldn't be the only reason to choose a package, sure, but it's definetely something you should be aware of.

**Comment by Zerotask** [comment]
I didn't say that Polka isn't working good, but Express is a standard for webservers, Polka isn't and GitHub Stars is a representing number (it often correlates with the amount of people who use it).
It shouldn't be the only reason to choose a package, sure, but it's definetely something you should be aware of.

**Comment by Conduitry** [comment]
We tend to like to steer people towards more lightweight packages. For many things, people won't even notice the difference between the two. Polka can be swapped out for Express in individual projects if that's what is wanted or needed.
