### ISSUE TITLE
Imports of Typescript files not working

### ISSUE THREAD

**Issue by RodPaDev** [sveltejs/sapper#1623]
**Describe the bug**
Tried to import a typescript file into a svelte component and it didn't resolve the module. Plain JS files work without any issue.

Importing regular

**Logs**
`Could not resolve '../../includes/TButterCMS' from src\routes\blog\index.svelte`

**To Reproduce**
Import typescript file into svelte component
https://github.com/RodPaDev/rodpadev/tree/v2

**Expected behavior**
ButterCMS module should've been imported without throwing an error

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

  throw err;
  ^

Error: Cannot find module 'C:\Users\RodPa\Desktop\Dev\rodpadev\__sapper__\dev\server\server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
</details>

**Information about your Sapper Installation:**

- The output of `npx envinfo --system --npmPackages svelte,sapper,rollup,webpack --binaries --browsers`
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 2.32 GB / 7.89 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.111
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    rollup: ^2.33.1 => 2.33.1
    sapper: ^0.28.10 => 0.28.10
    svelte: ^3.29.4 => 3.29.4
- Your browser
 Edge, Chrome
- Your hosting environment (i.e. Local, GCP/AWS/Azure, Vercel/Begin, etc...)
Windows 10, Powershell, Local

**Severity**
This isn't breaking, but I would like to include typescript on the helper modules to keep the repo consistent.

**Additional context**
![image](https://user-images.githubusercontent.com/47316946/97887404-27e3bb00-1d2a-11eb-8216-f791f657e8bf.png)

**Comment by dummdidumm** [comment]
You config looks unusual. I suggest to try recreate the bug with a clean sapper template which contains a Typescript setup script now if I'm not mistaken. If you cannot recreate the bug then, it's something with your config, at which point you are better off asking this question on Stackoverflow.

**Comment by RodPaDev** [comment]
I'll try that and come back with results

**Comment by RodPaDev** [comment]
Turns out it was my config.
