### ISSUE TITLE
How to conditionally import a module?

### ISSUE THREAD

**Issue by vedmant** [sveltejs/sapper#1629]
How to conditionally import a module?
In my case I have a module that works only in browser, I wanted to conditionally import it with require() but have error that `require is not defined`. If I import that module with `import` it fails with `window is not defined`. Is there no way to conditionally import browser only module?

**Comment by vishal423** [comment]
Have you tried with `process.browser && xxx` to check browser mode?

**Comment by Conduitry** [comment]
GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).

You can use a dynamic `import()` inside of an `if` that will only run on the browser.

**Comment by vedmant** [comment]
> You can use a dynamic import() inside of an if that will only run on the browser.

Tried it, also doesn't work, for some reason it imports undefined:

```
let Masonry
if (process.browser) {
	Masonry = await import('masonry-layout')
	console.log({Masonry})
}

```
