### ISSUE TITLE
Latest master has regression when running `sapper dev`

### ISSUE THREAD

**Issue by jrschumacher** [sveltejs/sapper#1634]
**Describe the bug**

Latest master has a regression which throws an error when `sapper dev` is called. Version 0.28.10 works fine.

**Logs**

```
> sapper dev

(node:29297) UnhandledPromiseRejectionWarning: TypeError: Class extends value [object Object] is not a constructor or null
    at Object.<anonymous> (/web/node_modules/sapper/dist/CheapWatch.es.js:31:26)
```

**To Reproduce**

Use `"sapper": "sveltejs/sapper#master",` in package.json

**Expected behavior**

Server runs without throwing an error.

**Stacktraces**

If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

(node:29297) UnhandledPromiseRejectionWarning: TypeError: Class extends value [object Object] is not a constructor or null
    at Object.<anonymous> (/web/node_modules/sapper/dist/CheapWatch.es.js:31:26)
</details>

**Severity**

Blocker.

**Comment by benmccann** [comment]
Pretty much nothing has change since 0.28.10, so I would be surprised if there was any regression introduced

**Comment by Conduitry** [comment]
I can reproduce this. To remove the variable of having the npm CLI build the package on the fly vs. using the prebuilt package on the npm registry, I pointed to both `sveltejs/sapper#master` and to `sveltejs/sapper#v0.28.10` (so that both were getting built locally), and I see the exception with master but not with the latest tagged version.

**Comment by Conduitry** [comment]
The commit that seems to have done it is 141f65fd4342b339a7f487cf5d3fdce3609128f7, which is peculiar.

**Comment by benmccann** [comment]
Hmm. Very odd. It appears to work with Rollup with 2.23.1, but not with any version newer than that
