### ISSUE TITLE
New rollup-plugin-svelte@7.0.0 not compatible with Sapper

### ISSUE THREAD

**Issue by igolkotek** [sveltejs/sapper#1651]
**Describe the bug**
After upgrade to rollup-plugin-svelte@7.0.0, brand new sapper app fails to start with a message "App.render is not a function".

**Logs**
`[rollup-plugin-svelte] Unknown "dev" option. Please use "compilerOptions" for any Svelte compiler configuration.
[rollup-plugin-svelte] Unknown "hydratable" option. Please use "compilerOptions" for any Svelte compiler configuration.
[rollup-plugin-svelte] Unknown "generate" option. Please use "compilerOptions" for any Svelte compiler configuration.
[rollup-plugin-svelte] Unknown "hydratable" option. Please use "compilerOptions" for any Svelte compiler configuration.
[rollup-plugin-svelte] Unknown "dev" option. Please use "compilerOptions" for any Svelte compiler configuration.
✔ server (2.4s)
✔ client (2.4s)
✔ service worker (34ms)
> Listening on http://localhost:3000
TypeError: App.render is not a function
    at /home/aiia/projects/vchasno/testJs/__sapper__/dev/server/server.js:6285:49
    at Generator.next (<anonymous>)
    at fulfilled (/home/aiia/projects/vchasno/testJs/__sapper__/dev/server/server.js:1728:58)
TypeError: App.render is not a function
    at /home/aiia/projects/vchasno/testJs/__sapper__/dev/server/server.js:6285:49
    at Generator.next (<anonymous>)
    at fulfilled (/home/aiia/projects/vchasno/testJs/__sapper__/dev/server/server.js:1728:58)
    at runNextTicks (node:internal/process/task_queues:58:5)
    at processImmediate (node:internal/timers:436:9)
`

**To Reproduce**
Just create a new project and upgrade all outdated plugins to the last versions.

**Information about your Sapper Installation:**
- Ubuntu 20.04

**Severity**
Crash

**Comment by Conduitry** [comment]
rollup-plugin-svelte@7 is, as semver implies, a breaking change, and you shouldn't expect to be able to just update to the new version. The errors you are getting are because in version 7 the plugin expects a new layout for its options, as mentioned in its changelog and as described in its readme. The official Sapper template has not yet been updated to rollup-plugin-svelte@7.

**Comment by didiermunezero** [comment]
so what for project we have been trying to work on?
