### ISSUE TITLE
Sapper procces suddenly starts to get killed after npm run dev 

### ISSUE THREAD

**Issue by codewithpatelo** [sveltejs/sapper#1653]
**Describe the bug**
Suddenly I cannot run npm run dev anymore:
![image](https://user-images.githubusercontent.com/16574952/100813272-c2b0e180-341d-11eb-8dba-6b4108e72c83.png)

**Expected behavior**
Run the app

**Severity**
Critical because I cannot run the app.

**Additional context**
No major changes has been made to the app since last commit.

**Comment by antony** [comment]
This issue doesn't include any useful information, and therefore we aren't able to do anything with it other than close it.
