### ISSUE TITLE
Modules are being evaluated before preload function finishes

### ISSUE THREAD

**Issue by GCastilho** [sveltejs/sapper#1657]
**Describe the bug**
If a component imports a module (js/ts) it's contents are being evaluated and executed before the preload function finishes

**To Reproduce**
So, if in index.svelte we have

```svelte
<script lang="ts" context="module">
	export function preload() {
		console.log('inside preload')
	}
</script>

<script>
	import { sayHi } from '../utils/hello'

	sayHi()
</script>
```

And on the module hello:

```typescript
console.log('inside hello module')

export function sayHi() {
	console.log('inside sayHi function')
}
```

The console will print
```
inside hello module
inside preload
inside sayHi function
```

So the module is being evaluated before the preload function finishes (or starts?) executing, which is a problem if you have a module that is a singleton that depends on initialization by the preload function (for example)

**Expected behavior**

I thought that the more reasonable behavior would be to evaluate the imports _after_ the preload function finishes executing,  but idk, it might be by design

In my case, I have a store that uses an object that is initialized in the preload function. I store that object in a module to be globally accessible and the store imports it and use it for initialization, which can fail if the code is run before the preload function finishes

So, is this a bug or that's the intended behavior?

**Comment by thgh** [comment]
Static imports in ES modules are only valid at the toplevel of a module, so behind the scenes the Svelte compiler moves all imports to the context="module" script. So it probably makes sense.

**Comment by GCastilho** [comment]
Oh. In that case it totally make sense this behavior. Thanks!
