### ISSUE TITLE
Hot reload does not work when starting the standard template on WSL2

### ISSUE THREAD

**Issue by niqitosiq** [sveltejs/sapper#1662]
**Describe the bug**
Hot reload does not work when starting the [standard template ](https://github.com/sveltejs/sapper-template)(rollup and webpack) on WSL2. Connection errors are displayed on the main page in the console. 

**Logs**
When the file changes, the terminal displays:
![изображение](https://user-images.githubusercontent.com/15576320/101482530-4a43a680-3970-11eb-8750-2e34d11d25cb.png)
In the browser console: 
![изображение](https://user-images.githubusercontent.com/15576320/101482325-00f35700-3970-11eb-803b-06f1a41161fd.png)

**To Reproduce**
Perform actions from [readme](https://github.com/sveltejs/sapper-template#getting-started) and edit `index.svelte`

**Expected behavior**
The browser will reload the page

**Information about your Sapper Installation:**
```
npx: installed 1 in 1.253s

  System:
    OS: Linux 4.19 Ubuntu 18.04.1 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz
    Memory: 864.71 MB / 5.80 GB
    Container: Yes
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 12.18.4 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  npmPackages:
    rollup: ^2.3.4 => 2.34.2 
    sapper: ^0.28.0 => 0.28.10 
    svelte: ^3.17.3 => 3.31.0
```
- Chrome

- WSL2

**Severity**
Interferes with comfortable development.

**Additional context**
found this by [issue](https://github.com/sveltejs/sapper/issues/210), but did not receive any useful information

**Comment by Conduitry** [comment]
Are you running this from your Windows filesystem mounted under /mnt? WSL2 has a known bug where it does not report file changes from there, and the workaround is to run from the virtual Linux filesystem instead.

**Comment by niqitosiq** [comment]
No, I'm running out of the path `/home/niqitosiq/test-svelte`. 
The file change is processed (compilation passes), but the browser page is not refreshed. If manually updated, then new content will appear

**Comment by jeffreycahyono** [comment]
@niqitosiq  in order hot reload worked, port 10000  should be forwarded correctly from the remote (or WSL2) to your local. check if there is a process already listening using 10000, that would prevent the 10000 port being frwarded. I personally don't use WSL2, but uses Vscode remote SSH development for everyday work. In VSCode `ms-vscode-remote.remote-ssh` plugin there is a feature to easily forward port from remote to local machine. When I forward  the 10000 port, the hot reload worked
![image](https://user-images.githubusercontent.com/1821605/102567731-b5317200-4114-11eb-8a5c-57784208c7a8.png)

**Comment by niqitosiq** [comment]
It finally works. I guessed that the matter was in a closed port, but for some reason in the past, I was not lucky to find a [solution](https://gist.github.com/xmeng1/aae4b223e9ccc089911ee764928f5486).
