### ISSUE TITLE
Sapper is persisting store data for different requests on the server

### ISSUE THREAD

**Issue by GCastilho** [sveltejs/sapper#1672]
**Describe the bug**
If I have a store exported by a module and that store is updated outside an onMount block the value is also stored on the server

So if I have a preload function that returns some data and on the component body (outside the preload) I update the store, that value will persist on the server. That also can lead to those values "leaking" to future requests if that store is used to render some data, since the store from _the server_ will be used on the SSR phase

Upon hydration, the store is initialized client-side, which "resets" the HTML with the value of the store on the client. That also can cause the page to flicker just after loading

**To Reproduce**
I have setted up a small demo repository on github [HERE](https://github.com/GCastilho/sapper-store-bug). The repo also contains a README with more detailed information about the behavior for this specific reproduction

**Expected behavior**
The store should not persist data on the client for multiple requests, so it's value should be resetted on a "per request basis" to avoid data leakage between the requests (related to #917) since any change to the store that happens on the prerendering phase (like setting the store with a value returned by the preload function) will also be stored on the server as well

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Sapper entirely?

I think it's very severe, since (in my case) I use the preload to return user data and store it on a store. On that scenario there is a risk that data may be wrongly used to render a page in SSR with data from a different user

Another problem is inconsistent data. If the developer is not careful enough to clear the store on each request (like on my demo example) the store may send invalid or incorrect data from a previous request

**Comment by Conduitry** [comment]
If you have a single store instance in your app, it's going to a single instance for your whole server, across all requests. There's no way for Sapper to intuit that this one module should be re-run per request, and no way for it to tie the store instance to particular requests, and no way for changes on the client to persist back to the server.

If you need any of these features, you should use Sapper's session functionality (possibly along with your own session middleware), which does let you persist data for separate users on the server.

**Comment by GCastilho** [comment]
>If you need any of these features, you should use Sapper's session functionality (possibly along with your own session middleware), which does let you persist data for separate users on the server.

Right. I'll try to use that. Thanks!
