### ISSUE TITLE
Render error with latest versions of Sapper, Svelte and Rollup Plugin Svelte

### ISSUE THREAD

**Issue by paulopath** [sveltejs/sapper#1688]
**Describe the bug**
App Render error occurs when using the latest versions of Sapper (0.28.10), Svelte (3.31.1) and rollup-plugin-svelte (5.0.1).

**Logs**
Server:
[rollup-plugin-svelte] Unknown "dev" option. Please use "compilerOptions" for any Svelte compiler configuration.
[rollup-plugin-svelte] Unknown "hydratable" option. Please use "compilerOptions" for any Svelte compiler configuration.
[rollup-plugin-svelte] Unknown "generate" option. Please use "compilerOptions" for any Svelte compiler configuration.
[rollup-plugin-svelte] Unknown "hydratable" option. Please use "compilerOptions" for any Svelte compiler configuration.
[rollup-plugin-svelte] Unknown "dev" option. Please use "compilerOptions" for any Svelte compiler configuration.
Please include browser console and server logs around the time this bug occurred.

Browser - Console: 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**To Reproduce**
Run "sapper dev" with latest version of Sapper, Svelte and Rollup Plugin Svelte

**Expected behavior**
Run "sapper dev" using latest versions without error

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

  App.render is not a function
</details>

**Information about your Sapper Installation:**
 System:
    OS: Linux 4.19 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
    Memory: 10.81 GB / 12.43 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    npm: 6.14.9 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Chrome: 86.0.4240.183
  npmPackages:
    rollup: ^2.35.1 => 2.35.1 
    sapper: ^0.28.10 => 0.28.10 
    svelte: ^3.31.1 => 3.31.1 

**Severity**
Not at all severe... just a curiosity.

Addtional Context:
When using Svelte 3.29.0 the issue is not reproducible.

**Comment by Conduitry** [comment]
5.0.1 is not the latest version of rollup-plugin-svelte, but judging by those error messages, you're not using version 5 anyway. And I highly doubt that this would be related to what version of Svelte you are using.

https://github.com/sveltejs/rollup-plugin-svelte/blob/master/CHANGELOG.md describes what changes you need to make to your Rollup config when updating to later versions.

https://github.com/sveltejs/sapper-template/tree/rollup contains the latest official version of the Sapper template, updated for rollup-plugin-svelte version 7.

For further support, please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).
