### ISSUE TITLE
select available port

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#169]
It would make sense if Sapper automatically selected an available port (starting at 3000, since that's what we're currently using) when doing `sapper dev` or `sapper start`.

I have a situation though where I have multiple Sapper apps that need to communicate with each other, so the ports need to be known ahead of time. For that reason it would also make sense if we could select a port with `sapper dev --port 4567` (or `-p 4567`), and Sapper would bail if it wasn't available.

**Comment by thgh** [comment]
I'm running multiple sapper instances with `"dev": "PORT=4000 sapper dev"`. It works properly 👍  a

Can those occurences of 3000 be replaced by `process.env.PORT || 3000` ? Or is that not needed?

**Comment by Rich-Harris** [comment]
ah yeah, there's a couple of places where things are hardcoded that shouldn't be. Good catch. And yeah, I guess we may as well treat `PORT=4000 sapper dev` as equivalent to `sapper dev -p 4000`. Reopening this

**Comment by Rich-Harris** [comment]
Fixed by #184
