### ISSUE TITLE
Occasionally getting the error 'target is a required option' from SvelteComponentDev

### ISSUE THREAD

**Issue by mnlsrv** [sveltejs/sapper#1698]
I have a very basic project based on the sapper template with an unchanged client.js and server.js. Only modified rollup.config.js to include SCSS support using svelte-preprocess.

I have noticed that when I run `npm run dev` I often get the attached error on reloads. It's more frequent when the reload is triggered by saving changes on vsc, but not nearly as much when refreshing the page on the browser. 

I can reproduce it consistently by either doing a browser hard reload or commenting out `target: document.querySelector('#sapper')` in client.js.

Any idea what could be causing this? 

![Screenshot 2021-01-14 at 14 06 41](https://user-images.githubusercontent.com/5843370/104601123-c4eb9a00-5671-11eb-8958-32c47900d0a5.png)

---

Edit: this also happens every time I start the server, so it's breaking my production environment :/

**Comment by 15210633458** [comment]
麻烦问一下这个问题解决了吗
