### ISSUE TITLE
sapper export does the same as sapper build on latest release

### ISSUE THREAD

**Issue by vladejs** [sveltejs/sapper#171]
`sapper export` command no longer export the site to a static version in latest release.

**Comment by Rich-Harris** [comment]
Can you try with 0.8.3? It might have been fixed already — thanks

**Comment by vladejs** [comment]
It doesn't work. What i'm seeing is that is not generating the entry `index.html` file

**Comment by Rich-Harris** [comment]
I can't reproduce this — I wonder if it's related to https://github.com/sveltejs/sapper/issues/174 in that this is a Windows thing? Do you get an error message saying it timed out waiting for a port?

**Comment by mspanish** [comment]
could be a windows thing as I'm on Windows 10 with a failing export - will look at the above tag to see if I can troubleshoot!

**Comment by Rich-Harris** [comment]
It seems there's a bug in https://github.com/Rich-Harris/port-authority that only affects some platforms, and Windows 10 appears to be one of them. I haven't been able to reproduce it (don't have a Windows 10 VM to hand), but others (inc @Conduitry) have

**Comment by mspanish** [comment]
well, since sapper looks like the end all be all of JS "non framework" frameworks, I will  keep working on this until I find a way to make it work or I run out of time!

**Comment by mspanish** [comment]
@Rich-Harris for now is there a previous build that I could use, or the "windows fix" repos I see here?

**Comment by Rich-Harris** [comment]
0.8.2 was the last release that didn't use port-authority, that might work until we can get this fixed!

**Comment by mspanish** [comment]
You know I'm not sure it's the same issue with the port authority - the error @vladejs was getting on Windows when doing `yarn dev`  - I don't get any errors from this. I get all clear and can see the site on the server using localhost:3000

**Comment by mspanish** [comment]
mine seems to have something to do with webpack not saving the html files/routes

**Comment by mspanish** [comment]
I'm willing to try reinstalling v 0.8.2 of sapper, but want to make sure - does it contain the export feature? All server stuff works great for me, just can' t export going. @Rich-Harris

**Comment by Rich-Harris** [comment]
yep, it includes `sapper export` — there's a list of new stuff between 0.8.2 and the current version on the [changelog](https://github.com/sveltejs/sapper/blob/master/CHANGELOG.md). mostly just quality-of-life improvements (startup performance, better logging etc), no big features

**Comment by mspanish** [comment]
sorry for the crossposting - as I said in #198 - v 0.8.2 still has export problems on Windows - I'm hacking around in your cli.js to see if there's anything I can fix for paths or something, but I must say your exporter() fn uses a lot of funky scripts I don't use in my own Node.js apps that copy dirs and files, so it's a bit tough going - will see if I can figure anything out though.

**Comment by mspanish** [comment]
Sorry for another nooby question but I don't see where you are copying the routes in this fn, I just see the ./client folder (which copies) and the service-worker.js - which also copies to ./export. But it seems maybe this fn could be a bit simpler and get the route files copied over or altered and then copied - sorry if this is a vast oversimplification!

**Comment by mspanish** [comment]
The   `proc.on('message', function (message) {}` doesn't return a value at all for me, so the scripts below it don't copy anything

**Comment by mspanish** [comment]
Ok this may be the worst question of all - but if there would be a way to write out what needs to be done by the exporter?  Maybe that way I could try hacking up my own version - I've developed my own CMS using Node.js and Dust.js, so I'm pretty familiar with basic file creation, JSDOM for altering stuff before writing/copying with fs-extra, etc.

**Comment by Rich-Harris** [comment]
One thing you could try is reverting to the current version and changing [this line](https://github.com/sveltejs/sapper/blob/37d3d576942dc9d8d929e8374c8d45db3627e849/src/cli/export.ts#L92) in `src/cli/export.ts` (or the equivalent line in `node_modules/sapper/dist/exports.ts.js` if you don't want to rebuild Sapper — it's right at the bottom):

```diff
-	return ports.wait(port)
+	return new Promise(fulfil => setTimeout(fulfil, 2000))
		.then(() => handle(new URL(origin))) // TODO all static routes
		.then(() => proc.kill());
```

If my hunch that `ports.wait` is failing is correct, then doing that instead — waiting a couple of seconds for the server to start up — would be a workaround (albeit a hacky one!).

Basically, the way this all works is this: Sapper builds a production version of the app, and copies over everything in `assets` and the `client` folder of your build directory (which defaults to `.sapper/.export/client` when exporting). That explains why you're seeing those files.

But then in order to render the individual pages, it starts the server and visits `http://localhost:3000` and downloads the rendered HTML as though it were a browser using the app. It scans for links to other pages (using `cheerio`), and requests those too. While that's going on, the server (which is running in a child process) is emitting messages to say which files have been requested, so that it also saves e.g. JSON responses from server routes.

**Comment by mspanish** [comment]
Ah right that's why this looks so crazy to me! I guess I would do that via JSDOM in the system I've got for my CMS, but sounds like this has no problems other than what you've stated - even if it's a hack, it's just for the export - and right now I just want to start building with Svelte & Sapper! So no problem. Thanks for your responses and your time today - I really appreciate it.

**Comment by mspanish** [comment]
In Sapper v0.9.6 I have this line instead

`return [2 /*return*/, ports.wait(port)`

**Comment by Rich-Harris** [comment]
Yep, that's the built file, after Rollup and TypeScript have converted/optimised the code in `src` and written it to `dist`. The same change should work —

```diff
-return [2 /*return*/, ports.wait(port)
+return [2 /*return*/, new Promise(fulfil => setTimeout(fulfil, 2000))
```

**Comment by mspanish** [comment]
nope, no html files being written. Still has no message from the   proc.on('message', function (message) {} - so it's failing someplace. I may try to hack it up via my own node modules from my cms, as long as the exporter just needs the HTML with some parsing, and not special packing or chunking or whatever, I can probably get that done.

**Comment by mspanish** [comment]
I've got a hacked up script to pull and parse the pages, and that is all working fine - for example I can find the basic routes via request & JSDOM by just doing 
`const links = window.document.querySelectorAll('nav > ul > li > a'); `
Nav is pretty easy to identify, but internal links will be trickier. Do all of them have the rel="prefetch" attribute?  Or do you just check for anything inside an a tag that starts with '/'?

**Comment by mspanish** [comment]
I realize this is quite naive compared to yours - but fs-extra has some really nice async features - I wonder if that would negate the need for quite so many promises? I am not near done but here is what I have so far, will have to grab the rest of your stuff for the correct filenames, saving to ./.sapper first, etc. (also still need to go through links outside of the ones in nav > ul > li.

```
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var jsdom = require("jsdom")
const { JSDOM } = jsdom;
var fs = require("fs-extra");
var path = require('path')
var _ = require("lodash")
var request = require("request");
var pagesWritten = [];

var url = "http://localhost:3000"

function exporter(export_dir) {
    console.log('url is '+url)
    runPage('/');
}

function runPage(page) {
 
  if (_.includes(pagesWritten, page)) return

  var page_url = url+page;
  request(page_url, function (error, response, body) {
    if (!body) return
    const { window } = new JSDOM(body)
    //console.log('lets look at body' +body)
    const links = window.document.querySelectorAll('nav > ul > li > a');
    console.log('links length: '+links.length);
    console.log('export page url is '+'./export'+page)
    fs.outputFile('./export'+page+'/index.html', body, (err, data) => {
       if (err) console.log('no file output: err= '+err)
        pagesWritten.push(page)
    })

    for (var i=0; i < links.length; i++) {
        var href = links[i].href;
        console.log('href is '+href)
        runPage(href);
    }
  });    
}

exports.exporter = exporter;
//# sourceMappingURL=./export.ts.js.map
```

**Comment by mspanish** [comment]
yikes my bad I see that you wrote [sander](https://www.npmjs.com/package/sander) and it looks a lot more powerful than fs-extra!

I have all the files copying, just need to figure out where you're setting the string name for each new package dir.

**Comment by mspanish** [comment]
my exporter is almost done, but right now I'd have to manually hack the JS file to remove references to '/client/[chunk id here]' - as I flattened everything into the ./export folder, and manually updated the script references to remove those paths. Any change you could make that optional for export? For me I'd much rather keep all of my app files in the ./export folder rather than using the client and the chunked id - it'd just be cleaner and easier to navigate. I don't plan on having multiple versions of my app - and any export would replace the previous, and git would manage all versions anyway.  If that's a pain please disregard, I should be able to hack it up as it is :)

**Comment by mspanish** [comment]
This is a lot bigger problem than I thought - right now looks as if removing those and trying to re-route all references would cause many headaches. But I have another problem with the exporter - it's not saving any of the .json files, like the one needed for the blog page. Since this file is referenced by the blog.1.js file and not an HTML file parsed by the exporter - how does your exporter know to save these files? Without the .json file, the export site throws errors that the blog.json file is missing.

**Comment by mspanish** [comment]
I'm still working on the workaround for the /client/[chunk_id] references, but I can get the .json files via the code below. Not pretty but will get the files!

```
function cleanChunkReferences(export_dir){
    glob(export_dir+'/*.js', function (er, files) {
      console.log('files are '+files)
      for (var i=0; i < files.length; i++) {
        var the_file = './'+files[i];
        let js = fs.readFileSync(the_file);
        js = js.toString();
        stripChars(the_file,js)
        checkForFetches(the_file,js)
        //console.log('js is > '+js);
      }
    })
   // runPage('');
}

function checkForFetches(the_file,js) {
    var regex = /fetch\("\/[a-z0-9]*.json"\)/
    var match = regex.exec(js);
    if (match) {
        console.log('we have a fetch! '+match[0]) 
        for (var i = 0; i < match.length; i++) {
            let json_url = match[i].split('"')
            json_url = json_url[1]
            var urly = url+json_url;
            request(urly, function (error, response, body) { 
              if (error) console.log('err finding '+urly+ ' '+error)
              console.log('our json is '+JSON.stringify(body))
              fs.writeFile('./export/'+json_url,body, (e) => {
                if(e) {console.error(e)}
                else console.log(json_url + ' written');
            })             
            })       
        }
    }
}
```

**Comment by mspanish** [comment]
Another problem is how to get the .json files referenced in thhe blog_$slug$.0.js file - 
```
return fetch(`/blog/${slug}.json`).then(r => r.json()).then(post => {
	return { post };
});
```
I could raw hack this like I've done the other stuff, but there must be an elegant way to get these...

**Comment by mspanish** [comment]
Caramba after rebooting, moving from bash to windows command - and doing a fresh install of the my-app starter - the export works all perfectly now.

Forget all the posts above - yours is much better!

**Comment by Rich-Harris** [comment]
Woo-hoo! That sounds like it might be related to [this crazy bug](https://github.com/Rich-Harris/port-authority/pull/5) that affects Windows Subsystem for Linux, if it's working after switching to the default command prompt. It *should* now work in WSL (i.e. bash) if you update all dependencies, as a new version of port-authority was just published, but if not then at least there's a workaround.

Sorry I missed the updates to this issue at the weekend, it sounds like you got pretty deep in the weeds!

@vladejs if you get a moment, any chance you could try a fresh install to see if it's working for you? If so we can close this issue — thank you

**Comment by vladejs** [comment]
I just tested @Rich-Harris :
```
degit sveltejs/sapper-template theapp
cd theapp
yarn install
yarn export
```
I still get this error at the end of the process:
```
Entrypoint service-worker = service-worker.js
   [0] ./app/service-worker.js + 1 modules 3 KiB {0} [built]
       | ./app/service-worker.js 2.3 KiB [built]
       | ./app/manifest/service-worker.js 716 bytes [built]

> Built in 13s. Crawling site...
Error: timed out waiting for connection
    at Timeout._onTimeout (Z:\waps\revolao\bugexport-svelte\node_modules\port-authority\dist\port-authority.cjs.js:109:20)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

No luck so far :(

**Comment by vladejs** [comment]
Also, HMR doesn't work either.
Used my laptop *Windows 10 Home Edition*, AMD A8, HP

I also have Deepin installed (a debian based distro) and everything works, from HMR to `sapper export`

**Comment by Rich-Harris** [comment]
Gah, nightmare. Thanks for testing. I'd downloaded a Win10 VM so I could try and debug it myself, but my laptop died this morning so that'll have to wait...

**Comment by Conduitry** [comment]
FWIW, I'm not able to reproduce this on Windows 10 Bash. I tried with a freshly degit-ed sapper-template, yarn installed, and ran export and had no problems. And judging by the line number of the exception @vladejs is seeing, that is indeed the new 1.0.3 version of port-authority. So I have no idea ☹️

**Comment by mspanish** [comment]
@Rich-Harris I'll let you know if I have any other problems! Yeah I learned just how much I don't know! But was fun looking through the innards, and as for the [kwippe](https://kwippe.com) conversion so far the things I've begun converting are working in Svelte with far less code than I've used before. I'm getting used to the mental shift of manipulating the SVGs via the data, not the dom, and that's going to be a great thing in the end.

**Comment by vladejs** [comment]
@Conduitry , I'm getting errors on normal Window's command line tool (CMD/PowerShell)

**Comment by Conduitry** [comment]
@vladejs What specific errors are you getting? If you run `npm ls port-authority` what version does it say you have?

**Comment by vladejs** [comment]
`1.0.2`

**Comment by vladejs** [comment]
mmm.. not relevant anymore. Closing this
