### ISSUE TITLE
pages clash

### ISSUE THREAD

**Issue by TsrCodes** [sveltejs/sapper#1720]
error on creating dynamic routes !! says ✗ manifest
The [lang].svelte and [categ].svelte pages clash  ! any Solution for that

**Comment by antony** [comment]
Hi @TsrCodes 

They clash because Sapper wouldn't know which route to use, i.e. whether `en-US` was a category or a lang.

As detailed in the bug template which you sadly deleted, we don't provide support via github issues. Please come and chat on [discord](https://svelte.dev/chat).

**Comment by TsrCodes** [comment]
understood :+1:  : ) @antony
