### ISSUE TITLE
npx degit rollup pull errors

### ISSUE THREAD

**Issue by michaelcuneo** [sveltejs/sapper#1721]
`npx degit "sveltejs/sapper-template#rollup" my-app`

is returning 
```
! could not fetch remote https://github.com/sveltejs/sapper-template
! could not find commit hash for rollup
```

**Comment by antony** [comment]
This is usually because you need to be logged in to github, even for anonymous checkouts over HTTPS. In any case it has nothing to do with Sapper. See https://github.com/Rich-Harris/degit/issues/37

**Comment by michaelcuneo** [comment]
Oh interesting... yeah, the new SSL Key thingo... sorted.
