### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by IanKir** [sveltejs/sapper#1730]
Hi there!
I want to make a pull-request for this project. I have found some bug or something. 
I typed command below
```bash
npx degit "sveltejs/sapper-template#rollup" name-of-my-app
```
But when I go to `package.json` file the "name" value is "TODO" not the "name-of-my-app". I want to fix this. How can I fix this?

**Comment by antony** [comment]
It's todo because you need to change it. Just open the file in a text editor and change it to anything you like, and then save it :)

for further usage questions, please use [chat](https://svelte.dev/chat).
