### ISSUE TITLE
javacript:history.back() is not a valid href attribute (lie!)

### ISSUE THREAD

**Issue by mikeoptics** [sveltejs/sapper#1736]
**Describe the bug**
`<a href="javascript:history.back()" class="underline">homepage</a>
`
causes a console error:
`A11y: 'javascript:history.back()' is not a valid href attribute`

But it is valid as its used to go back.

**To Reproduce**
[See Here](https://svelte.dev/repl/c6112853d6e04b5b8108998a6eb4ef26?version=3.35.0)

**Expected behavior**
No error.

**Information about your Sapper Installation:**

Not relevant as it can be reproduced in REPL

**Severity**
Not even slightly

**Additional context**
Not just sapper but svelte too.

**Comment by Conduitry** [comment]
This was specifically added in #4733. That's not to say this won't be reconsidered, but at one point this was considered a feature and not a bug.

**Comment by mikeoptics** [comment]
How ironic. I get it though and Il try using a11y ignore.
