### ISSUE TITLE
Lost HMR in Sapper v0.8.1-0.8.3

### ISSUE THREAD

**Issue by vladejs** [sveltejs/sapper#174]
Steps to reproduce:
```
npx degit sveltejs/sapper-template withsvelte
cd withsvelte
yarn install
yarn dev
```
Changed the text in home page and nothing happens. This is the console output (it throws a warning):
```
✔ client (858ms)
✔ server (968ms)
✔ service worker (62ms)
listening on port 3000
(node:5624) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: timed out waiting for connection
```

**Comment by arxpoetica** [comment]
It's working for me in 0.8.3 -- is it an environmental issue? I know I've had occasional other problems with HMR (not sure it's fully stable yet). One thing that has helped is to delete the `.sapper` folder (it gets rebuilt) and do a hard refresh in my browser.

**Comment by vladejs** [comment]
I forgot yo say that Im using windows and node 8

**Comment by arxpoetica** [comment]
Cygwin or Window's subsystem for Linux?

**Comment by Rich-Harris** [comment]
Based on the error message, this looks like a bug in https://github.com/Rich-Harris/port-authority. Not sure why it's not recognising the connection on Windows

**Comment by vladejs** [comment]
Im not using cwing or the linux subsistem, just the windows cmd.
I believe that the break was after updating to webpack 4 and sapper 0.8.
Did you were able to reproduce it on windows @Rich-Harris ?

**Comment by Rich-Harris** [comment]
Afraid I can't reproduce this at all. I've added Windows tests to port-authority, and they're all passing, and I just tried creating a new project from scratch in a Windows VM — HMR works perfectly for me.

**Comment by vladejs** [comment]
Strange. To made sure it wasn't my machine, I did the steps above on a new
Tablet PC with Windows 10 Home edition. It didn't work either.

Did you used windows 10 for the test?
I dont know if it's a windows process blocking or something else.

Is worth mentioning that in both cases I used different node versions,
v8.4.1 and the latest stable v9.8.0

**Comment by mspanish** [comment]
I am using a Dell touch PC with Windows 10 home, Node v9.4.0 - I can try with an earlier version as I have maybe 5 or 6 installed too

**Comment by Rich-Harris** [comment]
The most recent version has a more generous timeout — could you see if you're still getting these errors? Thanks

**Comment by vladejs** [comment]
Finally, it WORKS!!!

Thanks @Rich-Harris, Im closing it.

**Comment by andreujuanc** [comment]
Confirmed, it works :) 🍻
