### ISSUE TITLE
npm security warning

### ISSUE THREAD

**Issue by weshuiz** [sveltejs/sapper#1744]
1 critical severity vulnerability        

To address all issues, run:
  npm audit fix
Severity: critical
Path Traversal - https://npmjs.com/advisories/1494
fix available via `npm audit fix`

**Comment by weshuiz** [comment]
it would be nice if you would give more content why this issue was closed?

**Comment by benmccann** [comment]
The link you shared said it only affects versions of Sapper prior to 0.27.11 so I'm not really sure what this issue is about?

It would be nice if you could give more content why this issue was opened :smile: Haha, sorry - couldn't resist :wink:

**Comment by weshuiz** [comment]
the link came from the log and is not acurate here's my package.json devDependencies

{
  "name": "TODO",
  "description": "TODO",
  "version": "0.0.1",
  "scripts": {
    "dev": "sapper dev",
    "build": "sapper build --legacy",
    "export": "sapper export --legacy",
    "start": "node __sapper__/build"
  },
  "dependencies": {
    "compression": "^1.7.1",
    "polka": "next",
    "sirv": "^1.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/runtime": "^7.0.0",
    "@rollup/plugin-babel": "^5.0.0",
    "@rollup/plugin-commonjs": "^14.0.0",
    "@rollup/plugin-node-resolve": "^8.0.0",
    "@rollup/plugin-replace": "^2.4.0",
    "@rollup/plugin-url": "^5.0.0",
    "rollup": "^2.3.4",
    "rollup-plugin-svelte": "^7.0.0",
    "rollup-plugin-terser": "^7.0.0",
    "sapper": "^0.28.0",
    "svelte": "^3.17.3"
  }
}

**Comment by Conduitry** [comment]
This came up before too - #1728 - if npm/snyk/whoever is giving an erroneous security warning, that's not something we have any control over, and should be taken up with them.

**Comment by benmccann** [comment]
What's the issue that you're concerned about? How can it be reproduced? The only details you have given are a link that you said is not accurate. In what way is it not accurate?

**Comment by weshuiz** [comment]
my apoligize for the lack of context
this is just a clean new install of sapper
this error came up after i did the first npm install
nothing was done at that point of time yet

**Comment by weshuiz** [comment]
for some odd reason this seems to be resolved now

**Comment by weshuiz** [comment]
i was so kind to make a recording of it and and upload it to youtube

**Comment by benmccann** [comment]
According to the link Conduitry posted above, the correct place to file this issue would be https://github.com/npm/cli/issues

**Comment by weshuiz** [comment]
so i can asume this warning is false and i can safely ignore it?

**Comment by weshuiz** [comment]
> According to the link Conduitry posted above, the correct place to file this issue would be https://github.com/npm/cli/issues

so i can asume this warning is false and i can safely ignore it?
