### ISSUE TITLE
writable array of objects

### ISSUE THREAD

**Issue by apoorvamanjunath** [sveltejs/sapper#1752]
Hello all,
I want to make a few variables as writable in svelte. Instead of subscribing to them each one individually. I want to add all these into an object and make that object writable so that I can access them by just subscribing to the object. Currently, I am doing this [find code here](https://svelte.dev/repl/b1e2bccce0b4405eb28d0448646e65be?version=3.35.0) This works perfectly fine. 

But when I try something like this. [Find code here](https://svelte.dev/repl/b26d3868a36c41a7a7b28350b3e8647e?version=3.35.0) It is giving me an error. how can I solve this?

The whole idea is to take image URL and image bounds from the user in the Resetter component and use these values to plot a map in the App component.

I am very new to web development. Sorry if my question looks silly.

Thank you

**Comment by Conduitry** [comment]
GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).
