### ISSUE TITLE
HMR hot module reload interfering with other sockets

### ISSUE THREAD

**Issue by arxpoetica** [sveltejs/sapper#176]
I have livereload working simultaneously with HMR (I use it for any global CSS changes), and when I'm saving something in a Sapper file, the HMR update interferes / breaks the livereload connection rendering it useless.

I'm wondering if this problem would extend to other socket connections.

**Comment by ekhaled** [comment]
I think you need a HMR aware css loader.
Maybe `style-loader`. But I use this for my global css needs [css-hot-loader](https://github.com/shepherdwind/css-hot-loader)

**Comment by arxpoetica** [comment]
@ekhaled — livereload does exactly what I want/need it to do. No problems there. The problem lies with Sapper's HMR interference with the socket. It interrupts it *every* time I save a route .html file.

Since sockets are also a common tool to use in apps, we ought to triple check that HMR isn't interfering in **general** with socket connections, let alone livereload. I'm going to test this with a socket.io connection and report.

**Comment by Rich-Harris** [comment]
Recent versions of Sapper let you enable/disable livereload/HMR with `--live`, `--hot`, `--no-live` and `--no-hot`, so I'll close this.
