### ISSUE TITLE
Webpack crash to console will keep sapper dev running in background

### ISSUE THREAD

**Issue by naturalethic** [sveltejs/sapper#177]
Repro:

1. `sapper dev`
2. Introduce a webpack error, for example I introduced a syntax error in a json file I was requiring
3. Sapper crashes to terminal with webpack error
4. `ps ax | grep sapper` -- it's still running
5. Run another `sapper dev` -- no port conflict announced
6. Boggle at why an older broken version of sapper is delivering you the wrong `.sapper/client/<uid>/*.js` files

**Comment by Rich-Harris** [comment]
I think this is a webpack bug — it's not calling the callback with an error like it's supposed to. I think the best workaround is to kill the child process if the main process dies — #182.

Luckily this seems to be limited to JSON parsing (and perhaps some other cases, but not JavaScript files or Svelte components)
