### ISSUE TITLE
export not working

### ISSUE THREAD

**Issue by mspanish** [sveltejs/sapper#198]
Hey I installed and ran everything as per the instructions in the Sapper docs, then tried to do an export - instead of html, I get this screen here. (I'm on Windows 10, Node 9.4.0).  When running build I get a folder of .js files w/ no html.

Any ideas?  Thanks!
 
Here is the screen I get at localhost:5000 when running `npx serve export`
![sapper](https://user-images.githubusercontent.com/206150/37486151-7c825890-2842-11e8-912e-e7b0da0f862f.PNG)

**Comment by Rich-Harris** [comment]
Interesting — what commands did you type to get there? It looks like you've ended up serving the build directory, rather than the export directory. If I do the following from scratch...

```
degit sveltejs/sapper-template test-project
cd test-project
yarn
yarn export
npx serve export
```

...I see the demo site. Did you do something like `sapper build export` by any chance?

**Comment by mspanish** [comment]
I didn't use yarn - just npm, via bash - I can also try the regular command console.  Let me run this exact stuff and get back to you.

**Comment by mspanish** [comment]
sorry, still no html files in the /export folder, and just files under serve - I used the command console with the exact command above. If you need more sys info let me know - I'm windows 10, node 9.

**Comment by mspanish** [comment]
sorry didn't close not sure what I clicked!

**Comment by Rich-Harris** [comment]
ah, wait — you might be experiencing a bug we're trying to fix with Windows. It's probably failing to find the port that the server is running on (it builds the app, serves it, then crawls it to write the files out). 

[goes to find a similar issue to link to it here, sees that you already posted in #171 😀 ]

**Comment by mspanish** [comment]
ok will look now

**Comment by mspanish** [comment]
I tried removing sapper and installing v0.8.2 - and that did not fix the export issue. Still getting nothing but .js files in the ./export/client/weirdnumbershere/ folder

**Comment by mspanish** [comment]
are you sure there isn't a windows specific issue in the exporter() fn in the cli.js file? I will add a bunch of useless console logs to see if I can catch anything...
