### ISSUE TITLE
Exception thrown if project directory contains things that look like slugs

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/sapper#211]
Kind of an edge case, and apparently [Nuxt has this issue too](https://github.com/nuxt/nuxt.js/issues/2953), but -

If the path of the project directory contains things that look like `[slugs]` Sapper throws an error from within `snapdragon` (from within `braces`, presumably from within `chokidar`) about `Error: no parsers registered for: ...`.

**Comment by Rich-Harris** [comment]
Since we no longer use chokidar I'm going to be optimistic and assume this is fixed
