### ISSUE TITLE
Service worker 'side rendering'

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#22]
I hadn't encountered this phrase before, but @dfabulich has an [interesting suggestion](https://twitter.com/dfabu/status/942784382066081792) — the service worker could perform 'SSR' if it had the necessary code to hand.

Not quite sure how practical that is (we'd basically need to load and run the entire server webpack bundle in the service worker, which probably means generating a separate productionised version that doesn't assume any Nodeisms), but it *could* be a performance win? Am not quite sure, need to think through all the ramifications.

**Comment by dfabulich** [comment]
Google documents a sample of it here: https://developers.google.com/web/fundamentals/instant-and-offline/offline-cookbook/#serviceworker-side-templating They call it "ServiceWorker-side templating" but it's the same idea.

**Comment by dfabulich** [comment]
If I were implementing this, I'd run the SW code on the server side.

**Comment by njbotkin** [comment]
Cloudflare workers use a set of APIs that are similar to what service workers use, so if there were separate `sapper sw-build` its output could probably be adapted to enable Cloudflare Worker "originless" deployments.

**Comment by tomByrer** [comment]
Yes, I was hoping for Cloudflare Worker compatibility also.

**Comment by GitGangGuy** [comment]
I know this feature request has gotten a little old by now, but to me this would be very important since I'm deploying over Cloudflare Workers currently and such an approach would allow me to work originless. That would be awesome - yes please!

**Comment by mathiasrw** [comment]
Any progress with supporting cloud flare workers?

**Comment by dephiros** [comment]
I just saw cloud flare announced https://blog.cloudflare.com/rendering-react-on-the-edge-with-flareact-and-cloudflare-workers/amp/. Maybe there is se inspiration we can take from this project?

**Comment by antony** [comment]
Closing as the proposal is no longer relevant for kit

**Comment by danawoodman** [comment]
@antony just curious, how is it no longer relevant? Will Kit support CloudFlare Workers out-of-the-gate? If so, AMAZING!
