### ISSUE TITLE
`preload` inside components not firing

### ISSUE THREAD

**Issue by Snugug** [sveltejs/sapper#221]
I have a Filter component that I'd like to respond to query parameters in the URL. When I add a `preload({ params, query })` function to my component and try to pull the query parameters. Unfortunately, it doesn't fire. Is it possible to get these query parameters from within a component that's not directly a top-level route?

**Comment by Rich-Harris** [comment]
You have to pass them down as props:

```html
<!-- somepage.html -->
<NestedComponent query={{query}} params={{params}} /> 

<script>
  import NestedComponent from './_components/NestedComponent.html';

  export default {
    components: { NestedComponent }
  };
</script>
```

Note that only page-level components can use `preload`, *not* child components.

**Comment by Snugug** [comment]
Ok, that's what I've been doing, but was hoping for a better solution. Thanks!
