### ISSUE TITLE
store.compute in oncreate data not loading initial value

### ISSUE THREAD

**Issue by btakita** [sveltejs/sapper#223]
```html
<div class="Message">
  <header>{{$message_header}}</header>
</div>

<script>
  export default {
    oncreate() {
      this.store({person: {name: 'John Smith'}))
      this.store.compute('message_header', ['person'], person => (person && person.name) || '')
    }
  }
</script>
```

The first rendered value of `$message_header` will be `''`. Any subsequent changes to `person` in the store will show up in the UI.

Something that causes the initial render to occur is to set `message_header` in the store before `compute('message_header', ...)`

```javascript
      this.store.set({message_header: (person && person.name) || ''})
      this.store.compute('message_header', ['person'], person => (person && person.name) || '')
```

**Comment by Rich-Harris** [comment]
Is this the same bug that was recently fixed in Svelte itself?

**Comment by btakita** [comment]
Yes it is the same issue as https://github.com/sveltejs/svelte/issues/1327
