### ISSUE TITLE
Error in preload Promise chain doesn't give much feedback.

### ISSUE THREAD

**Issue by neoel** [sveltejs/sapper#224]
In clientside preload, when the an uncaught error is raised in the promise. The sapper app shows 'INTERNAL SERVER ERROR', and no output in the console is logged.

**Comment by ehrencrona** [comment]
I suspect this has been fixed. If I try loading the following page:

```
<script context="module">
	export function preload() {
    Promise.reject(new Error('does this show?'))
	}
</script>
```

on master I get a printout in the browser console (Chrome 85.0):

```
Uncaught (in promise) Error: does this show?
    at Object.preload (throw.svelte:3)
```

**Comment by benmccann** [comment]
Ok, I'll go ahead and close this then
