### ISSUE TITLE
Service Worker doesnt work on Firefox. It throws errors

### ISSUE THREAD

**Issue by vladejs** [sveltejs/sapper#232]
Firefox 51.

These are the errors given at the console:
```
SyntaxError: invalid property id  main.js:1:13556
SyntaxError: missing ) after argument list  service-worker.js:1:60
TypeError: ServiceWorker script at https://enterese.now.sh/service-worker.js for scope https://enterese.now.sh/ encountered an error during installation.  (desconocido)
```

It's also worth noticing that the store doesn't work and link to other pages do a full reload, like a PHP site.

**Comment by andreujuanc** [comment]
Firefox 59
Windows 10
`TypeError: ServiceWorker script at http://localhost:3000/service-worker.js for scope http://localhost:3000/ encountered an error during installation.`

**Comment by Rich-Harris** [comment]
AFAICT service workers work with the current template, in the current version of Firefox — is this still an issue? If so is there a repro I can look at? Thanks

**Comment by vladejs** [comment]
I believe this is no longer an issue.
