### ISSUE TITLE
Type error in runtime.js::handle_click for <a> without href

### ISSUE THREAD

**Issue by samhatchett** [sveltejs/sapper#235]
if no href is set in the client html - as in, 
```
<a role="button" on:click="do_something()">click</a>
```

this results in a type error in runtime.js - because href will be null here:

https://github.com/sveltejs/sapper/blob/e60714bb983d71b5c34362063bc4fe6be9ef88bf/src/runtime/index.ts#L167

**Comment by silentworks** [comment]
You probably want to use an `<button>` instead, seen as you are defining the role as a button.

**Comment by Rich-Harris** [comment]
Fixed in 0.19.2
