### ISSUE TITLE
Dynamic multiple level menu/url

### ISSUE THREAD

**Issue by demas159** [sveltejs/sapper#237]
Hello,
Started learning Svelte and have some questions.
I have CMS system with API, how i can use route for url's like /news/:slug, /blog/:slug, /products/category/:slug or /:page_type/:subpage/:category/:slug...etc. Urls generated in backend and getting by API, JSON list with different paramaters/slug/content/titles/types...
So i want to created some universal templates for pages and subpages, how to do what in routes, something like:
/routes/[pages]/[template1].html, 
/routes/[pages]/[template2].html
template is getting by page type, I know what we can create folder for every type, like /blog/[template].html etc, but page types creating in admin panel, so need universal templates for what.
Also i try to include Component by page parameters/content, but for what we need to import it already in template, in my case we creating and getting page content from admin panel, so we dont know what to need import, can we load component by some dynamic variables ?. Also <:Component {dynamic_var_from_preload}/> not working.
  Any ideas, suggestions, examples ?

Sorry for my bad english.
Thanks.

**Comment by Rich-Harris** [comment]
This is supported via [layouts](https://sapper.svelte.technology/guide#layouts), so I'll close this issue
