### ISSUE TITLE
404 on `sapper export --basepath staging`

### ISSUE THREAD

**Issue by arxpoetica** [sveltejs/sapper#246]
Exporting appears to be broken on different bast paths.

I tried digging into the code a little bit, and it might be related to [this line](https://github.com/sveltejs/sapper/blob/master/src/middleware.ts#L378), but I haven't completely isolated it. Just that `(!route.error && route.pattern.test(req.path))` returns `true` without a basepath for `index.html` and `false` with a basepath.

In any case, none of the files appear to be getting generated.

I tried this on both my repo and a fresh install.

**Comment by Rich-Harris** [comment]
Are you mounting the app to `/staging`? `--basepath` doesn't change how your app is served, it merely tells the exporter where the app is mounted. You need to have something like this in your `app/server.js`:

```js
polka()
  .use(compression({ threshold: 0 }))
  .use('/staging', serve('assets'))
  .use('/staging', sapper({ routes }))
  .listen(process.env.PORT);
```

**Comment by arxpoetica** [comment]
Okay, yeah, that seemed to do the trick.

I'm going to leave this open until we get something clear in the docs about this, because it's been a recurring problem (I've noticed) with several people. Anyone who ever uses the default `Up` out of the box will run into AWS's default `/staging` url. I'll try to remember to add something to the docs when I have a moment.

@silentworks ^^^ remember how it wasn't working? Add the above to your server.js file (if you're still trying to make this happen).

**Comment by arxpoetica** [comment]
Just a thought, @Rich-Harris—any way we could just automate that URL in the `.use` statements, at least out of the box? That might solve a couple problems...just a thought...

**Comment by silentworks** [comment]
@Rich-Harris is that not just the longform version of

```js
polka()
  .use(
    '/staging'.
    compression({ threshold: 0 }),
    serve('assets'),
    sapper({ routes })
  )
  .listen(process.env.PORT);
```

If yes then that doesn't work either, you will get an extra `/staging/staging` when using `up`. I need to try an workout if this is an Polka issue.

**Comment by arxpoetica** [comment]
@silentworks

> I think we need to find out if Up has a dynamic way of getting that part of the URL

Up docs:

> UP_STAGE – stage name such as “staging” or “production”

**Comment by silentworks** [comment]
@arxpoetica so the issue isn't up nor Polka, the issue is how API Gateway does its routing. I am yet to find a solution, but the `/staging` path that API Gateway creates is a virtual path, not a physical one, its not the actual web server root.

In order to get this to work with Sapper we would have to create absolute path to all assets and routes in Sapper, which doesn't feel right to me. I am still reading up and will get back if I find a more suitable solution.

**Comment by arxpoetica** [comment]
@silentworks it's been a while since we've discussed this-- do you know where this stands? Is this an actual bug, or can we close? (I know I'm the one who opened it, but trying to glean insights, thx. 😄 )

**Comment by Rich-Harris** [comment]
Is this issue still live or can we close it?

**Comment by arxpoetica** [comment]
Good Q. I haven't had to worry about it. We can close it (aggressively) and reopen it later if it crops up again with someone else, but it certainly hasn't been an issue for me because I always have a fixed domain.

If someone feels this ticket needs reopening, just let us know.
