### ISSUE TITLE
how to add navigator progress。

### ISSUE THREAD

**Issue by MiYogurt** [sveltejs/sapper#248]
I have a special love for navigator progress。how to Implement? i try use AOP program type override history.pushState but i find could not，error forbidden me to do that。Did not found router lifecycle hooks when i reading source code. emmm.... did you have any idea to solve it。

i think use setInterval listen the location.href is not good idea。 because i want show preload return data status 。eg. success is green style, error is red style。

**Comment by silentworks** [comment]
Currently there are no hooks for the router, but this is something that is being discussed. You can follow this issue https://github.com/sveltejs/sapper/issues/157.

**Comment by Rich-Harris** [comment]
This can be done with the top-level `preloading` property, which is `true` when you start navigating and `false` once it succeeds. In your root [layout component](https://sapper.svelte.technology/guide#layouts) you could do something like this:

```html
// routes/_layout.html
{#if preloading}
  <Preloading/>
{/if}

<svelte:component this={child.component} {...child.props}/>
```

Typically you would only want to show a preloading indicator after ~250ms — many navigations will complete in under that time, and will feel instant, in which case an indicator feels unnecessarily jarring.
