### ISSUE TITLE
Don't tie `mode` to `NODE_ENV` in Webpack config

### ISSUE THREAD

**Issue by arxpoetica** [sveltejs/sapper#261]
Was getting the following bug when `NODE_ENV` was set to `staging`:

```
$ sapper build
> Building...
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.mode should be one of these:
   "development" | "production" | "none"
```

[In other words, `mode` is not vis-a-vis the same as `NODE_ENV` in Webpack land](https://medium.com/webpack/webpack-4-mode-and-optimization-5423a6bc597a). So this won't fly:

```
const mode = process.env.NODE_ENV;
```

Gosh. 🙃

We **could** in theory do something like the following:

```
const mode = process.env.NODE_ENV === 'production' ? 'production' : 'development';
```

But that's pretty limiting. CLI option? ENV var? https://webpack.js.org/concepts/mode/ mentions passing as config:

```
webpack --mode=production
```

**Comment by kalashnikovisme** [comment]
Wrong place, but this hint is very useful. thanks)
