### ISSUE TITLE
 Some vulnerabilities require your attention to resolve           

### ISSUE THREAD

**Issue by codeyash** [sveltejs/sapper#266]
Some vulnerabilities require your attention to resolve             
                                                                                
          Visit https://go.npm.me/audit-guide for additional guidance           
                                                                                
                                                                                
  low             Prototype Pollution                                           
                                                                                
  Package         deep-extend                                                   
                                                                                
  Dependency of   sapper                                                        
                                                                                
  Path            sapper > chokidar > fsevents > node-pre-gyp > rc >            
                  deep-extend                                                   
                                                                                
  More info       https://nodesecurity.io/advisories/612                        
                                                                                
                                                                                
  low             Prototype Pollution                                           
                                                                                
  Package         deep-extend                                                   
                                                                                
  Dependency of   webpack                                                       
                                                                                
  Path            webpack > watchpack > chokidar > fsevents > node-pre-gyp >    
                  rc > deep-extend                                              
                                                                                
  More info       https://nodesecurity.io/advisories/612                        
                                                                                

[!] 2 vulnerabilities found - Packages audited: 5071 (3671 dev, 194 optional)
    Severity: 2 low

[yash@yashpc users]$ node -v
v10.0.0
[yash@yashpc users]$ npm -v
6.0.0
[yash@yashpc users]$ lsb_release -rd
Description:    Manjaro Linux
Release:        17.1.10
[yash@yashpc users]$

**Comment by Rich-Harris** [comment]
this appears to have been resolved upstream
