### ISSUE TITLE
Use ansi-colors instead of clorox and and parseurl instead of url-parse

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#267]
A few dependencies that can be replaced for smaller/faster/etc alternatives:

* clorox --> ansi-colors
* url-parse --> parseurl
* glob --> tiny-glob

cc @lukeed

**Comment by lukeed** [comment]
Want me to do this? I have a few minutes now

**Comment by lukeed** [comment]
Can be closed~
