### ISSUE TITLE
goto should return Promise

### ISSUE THREAD

**Issue by tevel** [sveltejs/sapper#270]
It seems like there is **no way** to navigate page and **get notified when it done**.

It would be great if sapper/runtime.js/goto will return promise as it done in other frameworks (e.g. angular2.router.navigate())

**Comment by tevel** [comment]
my use case: navigate to the page wait until it finished and then scroll down

**Comment by silentworks** [comment]
I had a chat with @Rich-Harris on gitter and he said that this should change to return a Promise, if you want, you can create a PR for it or someone will get to it at some point.

**Comment by tevel** [comment]
create what? what is PR?

**Comment by silentworks** [comment]
A Pull Request (PR).

**Comment by Rich-Harris** [comment]
fixed in 0.14 — thanks
