### ISSUE TITLE
v0.13.0 __sapper__ EventStream seems to be borked

### ISSUE THREAD

**Issue by arxpoetica** [sveltejs/sapper#276]
It's dumping `null` messages every so many milliseconds.

See screen recordings:

* http://recordit.co/8zk3wcxEwC and:
* http://recordit.co/7SZiRsz9PQ

I went back and forth determining if it was my project or could be reproduced in https://github.com/sveltejs/sapper-template <- quick note, it can't be reproduced *UNLESS YOU UPDATE* `sapper-template` to `sapper@0.13.0`. Right now it's on v .12: https://github.com/sveltejs/sapper-template/blob/master/package.json#L17

Once you update the Sapper version, `sapper-template` EventStream `__sapper__` network connection gets borked too.

**Comment by Rich-Harris** [comment]
Absolute facepalm. I rewrote some stuff for 0.13 to break some CLI functionality out into an API that could be used by other clients (i.e. Sapper Studio), and managed to write the following code:

```js
setInterval(() => {
  this.send(null);
}); // <-- look ma, no second argument!
```

Surprised TypeScript didn't yell at me. Fixed in 0.13.1.
