### ISSUE TITLE
0.13.0 - HMR seems to be firing as server reloads

### ISSUE THREAD

**Issue by btakita** [sveltejs/sapper#277]
I'm getting a timeout error with the HMR `*.hot-update.json` request.

![sapper-hmr-reload-bug](https://user-images.githubusercontent.com/3664/40880933-61f5ab2e-6688-11e8-821b-8806aee19da2.png)

I was able to fix the issue by adding a timeout to `check` in `sapper-dev-client.js`

`setTimeout(() => check(), 250)` instead of `check()` in the connect method.

```
export function connect(port) {
	if (source || !window.EventSource) return;

	source = new EventSource(`http://${window.location.hostname}:${port}/__sapper__`);

	window.source = source;

	source.onopen = function(event) {
		console.log(`[SAPPER] dev client connected`);
	};

	source.onerror = function(error) {
		console.error(error);
	};

	source.onmessage = function(event) {
		const data = JSON.parse(event.data);
		if (!data) return; // just a heartbeat

		if (data.action === 'reload') {
			window.location.reload();
		}

		if (data.status === 'completed') {
			setTimeout(() => check(), 250)
		}
	};
}
```

**Comment by btakita** [comment]
Here's the network output, in which the connection hangs:

![sapper-hmr-reload-bug2](https://user-images.githubusercontent.com/3664/40880950-dec95b64-6688-11e8-9806-e3aa897fb89f.png)

**Comment by btakita** [comment]
The timeout is a kludge as it's dependent on the timing of the restart. Perhaps there could be a way to keep a proxy service up while the development service is restarting?

**Comment by Rich-Harris** [comment]
> Perhaps there could be a way to keep a proxy service up while the development service is restarting?

I think that's the best solution, yeah

**Comment by Rich-Harris** [comment]
The HMR thing is fixed in recent versions, so I'll close this, though in the longer term it might still be good to keep a server up and running between builds
