### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by JoeLanglois** [sveltejs/sapper#278]
When cloning the sapper-template project, HMR is not working and outputs the following errors in the browser's console. No error in the dev server's output, it correctly detects the change.

<img width="719" alt="capture d ecran 2018-06-04 a 08 14 02" src="https://user-images.githubusercontent.com/4594265/40916855-4f96b2b4-67cf-11e8-89fe-c91a90c73960.png">

**Comment by JoeLanglois** [comment]
In the network tab, all I can see is the body for the xxx.hot-update.json file is "Something went wrong" with a 500 error code.

**Comment by JoeLanglois** [comment]
This is on Node 10.3 on Mac Sierra.
Tested on latest Chrome, Safari and Firefox, all the same.

Where can I find the server error logs?

**Comment by JoeLanglois** [comment]
Dang it! Found the issue. Had a rogue process starting on boot listening on port 3000 messing things up for Sapper. Sorry about the inconvenience.

**Comment by Conduitry** [comment]
Hm. I am a little surprised that Sapper didn't recognize that something was already using port 3000, and switch to using another port. It's supposed to do this - I just started up another TCP server on port 3000 before starting `npm run dev` and Sapper ran on 3001. Do you have any idea how Sapper would have been able to bind to the port if you already had something else there? Different network interfaces?

**Comment by JoeLanglois** [comment]
Maybe it was the websocket server? Would that make any difference?
