### ISSUE TITLE
page 404 is broken!

### ISSUE THREAD

**Issue by tevel** [sveltejs/sapper#279]
Problem: **when opening not existing url of app I get**: TypeError: Cannot read property 'route' of undefined

<img width="1082" alt="screen shot 2018-06-04 at 4 26 45 pm" src="https://user-images.githubusercontent.com/4141385/40920151-5ddeb1ce-6814-11e8-88b7-c3d529e80d58.png">

**Steps to reproduce**
I followed to instructions to create new app:
npm install -g degit
degit sveltejs/sapper-template my-app
cd my-app
npm install
npm run dev

done!
now just open http://localhost:3000/qisqsq

**Comment by arxpoetica** [comment]
@tevel not sure this is related (maybe not?) but there are a few other weird behaviors w/ 404: https://github.com/sveltejs/sapper/issues/290

**Comment by Rich-Harris** [comment]
thanks, this is fixed in 0.14
