### ISSUE TITLE
differential bundling

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#280]
this is a great idea, let's steal it

https://twitter.com/benjamn/status/1003735863921082370

**Comment by MaxMilton** [comment]
That sounds amazing! Would probably be fun implementing in https://github.com/sveltejs/sapper-template eventually too.

**Comment by Rich-Harris** [comment]
This is implemented in 0.18.7. Currently it only works for Rollup apps — here's a template: https://github.com/sveltejs/sapper-template-rollup/tree/babel (it might make sense for that to be the master branch, haven't decided).

Documentation to come (https://github.com/sveltejs/sapper.svelte.technology/issues/30) but it's pretty simple — vary the client build config based on `process.env.SAPPER_LEGACY_BUILD` and use the `--legacy` flag, and Sapper takes it from there. It will use the modern build for apps that support async functions, and the legacy build for everything else.

**Comment by Conduitry** [comment]
Might it even make sense to have the webpack and rollup templates in the same repo on different branches? I'm assuming there are quite a few files that are identical among all versions (webpack/rollup and regular/legacy). We could master be just purely the app and assets and a readme, and put all the actual build stuff in different branches on top of that. Then we just tell people to `npx degit sveltejs/sapper-template#rollup-legacy` or whatever.

**Comment by Rich-Harris** [comment]
Probably, yeah... in fact you can even have `webpack` and `rollup` in the same project, and do `sapper build --bundler webpack` or `sapper build --bundler rollup` if you're the kind of person who struggles with commitment. Though separate branches in the same repo is probably the right approach

**Comment by arxpoetica** [comment]
Said this in the forum:

> FWIW, I find it confusing to tag `--legacy` on a build -- makes it seem like it's only doing something old
