### ISSUE TITLE
Server crash, error message error

### ISSUE THREAD

**Issue by destructobeam** [sveltejs/sapper#289]
The `event` object doesn't seem to have a member `error` here on server crash, `event.message` seems to work, but doesn't give any reason as to why the server crashed, just that it did in fact crash.

https://github.com/sveltejs/sapper/blob/611dc4f6be2aefd478e8e941676ad3a83fd79f58/src/cli/dev.ts#L43

**Comment by Rich-Harris** [comment]
thanks! fixed in 0.13.5
