### ISSUE TITLE
Programmatic navigation

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#29]
At some point we'll need to be able to do this sort of thing:

```js
import { goto } from 'sapper/runtime/app.js';

goto('/a?b=c').then(() => {
  // navigation succeeded
});

goto('/d', { replaceState: true }).then(...)
```

Presumably it would only fail if the `href` matched some route and there was an error during preload or render.

Open question whether or not it should navigate if no route is matched (i.e. just doing `window.location.href = href`). I suppose probably yes.

**Comment by fugroup** [comment]
For anyone searching for how to redirect sapper applications:
```javascript
import { goto } from '@sapper/app'
goto('your/path')
```

**Comment by QuantumInformation** [comment]
Thanks for the goto, is this for non preload stuff vs the 			this.redirect(302, `/`);

**Comment by kantord** [comment]
I feel like it would be super cool to have something reactive for this?

Something like being able to change `window.location.href` and causing a navigation in Sapper

**Comment by darryl-snow** [comment]
Unfortunately Jest fails with `Cannot find module '@sapper/app'` when I `import { goto } from '@sapper/app'` :(

**Comment by Rodrigoplp** [comment]
Is there a way to do `goto('your/path', { target: '_blank' })`?

**Comment by antony** [comment]
This issue is 3 years old. To get help with `goto`, come and [https://svelte.dev/chat](chat to us)
