### ISSUE TITLE
Basepath crops a letter of basepath when not using trailing slash

### ISSUE THREAD

**Issue by neoel** [sveltejs/sapper#296]
I've added the basepath to the server config, and when calling `sapper export --basepath blog` 
It's raising some 404 errors: 
```
> Received 404 response when fetching /blo/
> Received 404 response when fetching /blo/blog
```

It does work when adding a trailing slash to basepath `sapper export --basepath blog/`

**Comment by Rich-Harris** [comment]
Thanks — fixed in 0.13.6
