### ISSUE TITLE
`console.log` no longer emits from app/server.js compile

### ISSUE THREAD

**Issue by arxpoetica** [sveltejs/sapper#305]
On latest sapper upgrade, I can no longer `console.log(...)` from the `app/server.js` file.

The breaking change appears to be between sapper `v0.13.3` and `v0.13.4` (works in `.3`, but not `.4`).

**Comment by arxpoetica** [comment]
Small stab in the dark, but this might be the breaking change: https://github.com/sveltejs/sapper/commit/0800fa016b315b2dc9e7d48c872a2bfd66446faa

**Comment by arxpoetica** [comment]
A little more info, it appears to be a timing issue. If I wrap console.log in a setTimout call, stuff starts showing up...

```js
setTimeout(() => console.log('yolo!'), 100)
```

**Comment by shijiezhou1** [comment]
I'm having this issue these day my sapper just no longer console.log on any js file
