### ISSUE TITLE
Routing regression

### ISSUE THREAD

**Issue by antonheryanto** [sveltejs/sapper#311]
after nested router implemented ^0.15.0

expected
user/edit/[id].html => /user/edit, user/edit/1
user/[id].html => /user/1

actually
user/edit/[id].html => user/edit/1
user/[id].html => /user/edit, /user/1

**Comment by Rich-Harris** [comment]
Do you mean to say that `/user/edit` should be a page in its own right? If so, there should be a separate page for that:

```
routes/user/edit/index.html
```

Previously, `routes/user/edit/[id].html` would accept `/user/edit`, with `params.id === null`. That was sort of a hack that was necessary to enable any kind of nested routing in 0.14 and earlier. It's something we should probably mention in the docs.

Or did you mean that routes are being sorted incorrectly?

**Comment by antonheryanto** [comment]
thank for amazing projects and with quick reply

> Previously, routes/user/edit/[id].html would accept /user/edit, with params.id === null

yup, so that ```user/edit``` and ```user/edit/1``` will be similar page but with different params.id

>Or did you mean that routes are being sorted incorrectly?

i think yes, because its should put ```user/edit/[id].html``` above ```/user/[id].html``` as previous version route sorting, but if my analysis is incorrect and above happen because loop hole or hack for previous version what is correct behavior?

**Comment by Rich-Harris** [comment]
It *does* match `routes/user/edit/[id].html` before attempting to match `routes/user/[id].html` (literal path segment always beats dynamic parameter), but it won't match `/user/edit` — you'll need to create the `routes/user/edit/index.html` file for that.

Most likely, you'd want to create a shared component, e.g. `routes/user/edit/_Edit.html`, and import that into both `routes/user/edit/[id].html` and `routes/user/edit/index.html`.

**Comment by antonheryanto** [comment]
Ok will do, thanks
