### ISSUE TITLE
Interactive stack traces

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#32]
In dev mode, it'd be nice if the stack trace contained links that took you to the lines in question. (In prod mode maybe we don't want to show the stack trace?)

**Comment by Crisfole** [comment]
Is there an onerror hook. Connecting a tool like rollbar, sentry, or bugsnag is important IMO. An error hook would allow sending better error reports

**Comment by thelittlebug** [comment]
something like this would help me:

```js
sapper.start({
    target: document.body,
    onError: (e) => {
        // my custom sentry/bugsnag/someotherthing error handling logic
    }
})
```

if i had just a little bit more frontend/typescript/<add swapper core technologies here> experience i would try to add this feature, but for that to happen, we have to wait some more weeks ^^

**Comment by antony** [comment]
Closing as the proposal is no longer relevant for kit
