### ISSUE TITLE
Documentation init incomplete (and outdated?)

### ISSUE THREAD

**Issue by louwers** [sveltejs/sapper#324]
Right now, the [documentation for init](https://sapper.svelte.technology/guide#init-target-routes-) mentions target and routes, but it doesn't mention that a store object can be passed, that is explained elsewhere. Looking at the source code it seems that the 'routes' object is now 'legacy'? The example shown (two arguments) is also not congruent with the template (an object is passed).

Anyway, the documentation for `init` is all over the place. I think it should be updated to be complete and accurate!

**Comment by Rich-Harris** [comment]
Whoops! [Fixed now](https://github.com/sveltejs/sapper.svelte.technology/commit/65d46db4c2a273e813cc797734c024fb7a003a96), site has been updated https://sapper.svelte.technology/guide#init-target-manifest-

Thanks!
