### ISSUE TITLE
Idiomatically handle websocket pub/sub

### ISSUE THREAD

**Issue by arxpoetica** [sveltejs/sapper#340]
This was bounced around a bit on Discord, so opening up to discussion here.

The first question would be, should it even be something Sapper takes into consideration, i.e., have official support for.

If the answer is maybe or even no, should it (however) be handled as part of a branch or template or tutorial somewhere as "best practices" and method to madness / idiomatic-ness. (bad grammar, I know)

Discuss.

**Comment by antony** [comment]
There is a new discussion on kit regarding how we handle websockets, especially in a serverless world, so deferring to that discussion.
