### ISSUE TITLE
Access to res.locals in Sapper store

### ISSUE THREAD

**Issue by briancray** [sveltejs/sapper#344]
I noticed you have access to a req object in the server side Sapper middleware, but I'd love to see access to `res.locals`, which is where we traditionally store stuff to be rendered to the view. We have several middleware that add information to `res.locals` as the request travels through our response pipeline.

**Comment by Rich-Harris** [comment]
Yeah, that sounds like a good idea, thanks. Would you be up for making a pull request? I think it'd just be a case of changing [this line](https://github.com/sveltejs/sapper/blob/master/src/middleware.ts#L329) (and the associated TypeScript declarations) and augmenting/adapting [this test](https://github.com/sveltejs/sapper/blob/master/test/common/test.js#L567-L577).

**Comment by briancray** [comment]
This is great, thank you!
