### ISSUE TITLE
How to use Unicode in slugs

### ISSUE THREAD

**Issue by aubergene** [sveltejs/sapper#347]
Using the sample app, if I create a blog post with the slug `unïcode-test` then it currently 404s for that page. If I change `[slug].json.js` to url decode the slug then it works okay.

```js
	let { slug } = req.params;
	slug = decodeURIComponent(slug)
```

However the output for the files is inconsistent, the JSON is url encoded and the HTML isn't.

```
   1.35 kB   blog/un%C3%AFcode-test.json
   4.97 kB   blog/unïcode-test/index.html
```

Tested using Sapper 0.15.6, node v8.1.4

**Comment by Rich-Harris** [comment]
Reopening — I completely misunderstood the issue here and fixed a different bug instead...

**Comment by Rich-Harris** [comment]
Ok, this should all work now — files have their filenames decoded before they're written during `sapper export` and (breaking change in 0.20!) you no longer need to do `decodeURIComponent(slug)`; it comes to you in decoded form as it would with e.g. Express and `/blog/:slug`.

**Comment by aubergene** [comment]
Confirmed fix. Thank you!
