### ISSUE TITLE
Feature request - include a svelte.config.js

### ISSUE THREAD

**Issue by kylecordes** [sveltejs/sapper#353]
It appears that, to work with various other tools, a `svelte.config.js` file is needed. For example it is discussed in the Svelte repo:

https://github.com/sveltejs/svelte/issues/1101

... And I first ran across it in the repo for the VSCode plug-in:

https://github.com/UnwrittenFun/svelte-vscode/issues/1#issuecomment-386035232

Therefore, a feature request: that the Sapper starting point example include `svelte.config.js`.

**Comment by antony** [comment]
Kit now uses a svelte.config.js!
