### ISSUE TITLE
SyntaxError: Cannot declare a let variable twice

### ISSUE THREAD

**Issue by amadeu2** [sveltejs/sapper#360]
Console error at https://svelte-realworld.now.sh running from Iphone 5, Safari 10.
![image](https://user-images.githubusercontent.com/7059509/44168861-fd55ab00-a0a8-11e8-925c-aac7243d59db.png)

Maybe is an ES6 bug in Safari 10:
https://bugs.webkit.org/show_bug.cgi?id=171041

**Comment by Rich-Harris** [comment]
Oh, weird. Any idea where specifically it's happening (in the code, or in the app i.e. what page)? Not sure there's anything we can do if it's a browser bug 😬

**Comment by Conduitry** [comment]
I sort of recall there being an Uglify option to work around a Safari bug that sounded similar to this one;. But I can't locate it right now.

**Comment by amadeu2** [comment]
It happens just after sapper build, but not in local dev server.
I think Conduitry is right, I was also looking at the webpack configs to add the option like:
https://github.com/mishoo/UglifyJS2/issues/1753#issuecomment-324814782

but I could not find it either.

**Comment by Conduitry** [comment]
Oh right! This is an ES6-specific bug. That means it's mentioned in the [uglify-es docs](https://github.com/mishoo/UglifyJS2/tree/harmony) and the [terser docs](https://github.com/fabiosantoscode/terser), not in the uglify-js docs.

**Comment by Rich-Harris** [comment]
Yikes, seems like a lot of people have run into it. I guess it's necessary to set the https://webpack.js.org/configuration/optimization/#optimization-minimizer option manually 😬

**Comment by amadeu2** [comment]
Great now works! you right Rich 😀 just added to my client.config.js this:
```
module.exports = {
	...
	optimization: {
		minimizer: [
		  new UglifyJsPlugin({ uglifyOptions: { safari10: true } })
		]
	},
```

**Comment by nsivertsen** [comment]
This just bit me as well. Is it worth adding a note about this to `sapper-template`?

**Comment by gsc89** [comment]
@amadeu2 I just wanted to say thank you for your snippet with the safari option, I am not using sapper but I am using the uglify plugin which was causing me no end of issues on iOS till I added this so thank you!
