### ISSUE TITLE
Page/server route conflicts

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/sapper#362]
Sapper will currently happily let you create an html file and a js file that create a page route and a server route at the same path. When loading a new page, the server route takes precedence, but if you are navigating to a new page from the client, the page route takes precedence.

This is confusing, and Sapper should at least display a warning and probably even refuse to compile the app in this case.

**Comment by Rich-Harris** [comment]
This was introduced a while back as a way to allow a server route to intercept requests based on accept headers - I was thinking that it could also be used to handle post requests but still render a page, though I don't think that currently works. Basically the server route handler needs to call `next()` to 'fall through' to a page.

It could definitely be clearer. I don't think I've ever actually used this feature...

**Comment by Rich-Harris** [comment]
We're not currently doing any analysis of route files at the point at which we create the manifest, but if we were then we could identify server route handlers that weren't accepting the `next` argument, which would indicate a conflict rather than a fall through. That's a possibility. Though it would probably make life harder if we were to also support non-Connect-style frameworks (eg Koa) etc

**Comment by btakita** [comment]
I'm getting a 404 error when there's `items/index.html`

`items/index.mjs`
```javascript
export async function get(req, res, next) { next() }
export async function post(req, res) {}
```

The `items/index.mjs` server handler is run but `next()` does not seem to pass the request along to the component `items/index.html`.

**Comment by nsivertsen** [comment]
I'm getting the same error. If this worked as described in @Rich-Harris first comment, I would actually find this very useful. The main use case I have in mind is something like the following:

Say I have a separate API server that provides content for a Sapper route. I could just query that API in my route's `preload` function, but if the content changes rarely, I don't want to incur that cost for every page load and would much rather cache responses from the API on the Sapper side. So I could do something like:

```js
// app/middleware/cache.js,`use`ed in app/server.js
import LRU from 'lru-cache';
const _cache = new LRU({ max: 500, maxAge: 1000 * 60 * 60 });

async function cache(req, res, next) {
  req.cache = _cache;
  next();
}
```

```js
// routes/posts/[slug].js
export async function get(req, res, next) {
  const { slug } = req.params;
  const cached = req.cache.get(slug);

  if (!cached) {
    const data = await fetchFromApi(slug);
    req.myData = data;
    next();
    req.cache.set(slug, data);
  } else {
    req.myData = cached;
    next();
  }
}
```

And then I have a store that can fetch from the API _or_ from a local cache, and this local cache is instantiated with `request.myData` in `server.js`, and is used when preloading `routes/posts/[slug].html`.

So, to re-iterate, I would be very much in favour of keeping/fixing this functionality. (Unless the above is not how you're supposed to do things in Sapper? I'm trying to avoid proxying the API in Sapper, which would make this cleaner, but would incur an extra network hop.)
