### ISSUE TITLE
Drop source-map-support?

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#366]
Currently, source-map-support is installed by default when you use the middleware. This probably doesn't make sense. It *is* useful to have sourcemapped stack traces (notwithstanding that it doesn't currently apply to components — see #117), but the middleware feels like the wrong place for it.

A few options:

* Expect app authors to include it (and put it in sapper-template)
* Keep it, but only activate if `process.env.NODE_ENV` is 'development' (not sure if there's really much point to that)
* Add it in dev mode via `sapper dev` (if that's possible, given that it's a child process?)
* Scrap it, and handle errors in the child process differently inside `sapper dev`

**Comment by fusionstrings** [comment]
Not sure I understood correctly but if this is about not to generate sourcemaps at all then I would like to have the possibility to emit sourcemaps into a separate directory, which can be stored in protected environments.

**Comment by Rich-Harris** [comment]
This happened a few released ago so I'll close this. @fusionstrings this isn't about not generating sourcemaps, it's about not *automatically* consuming them on the server

**Comment by benmccann** [comment]
The dependency was removed in https://github.com/sveltejs/sapper/commit/cfd10c6f61a861f9b29081915085add31d7ca7fc#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 as being unused. It's hard to tell where the change actually occurred unfortunately
