### ISSUE TITLE
Replace `url-parse` with native `url.parse`

### ISSUE THREAD

**Issue by lukeed** [sveltejs/sapper#370]
The `url-parse` is sorta meant as a `url.parse` for the browser. The only added feature we're really using during `export` is the relative basepath, which can be easily done with string replacement:

https://github.com/sveltejs/sapper/blob/72b265a35fe39e7b3695c2b15332c9fcd5f6b2a6/src/api/export.ts#L54

https://github.com/sveltejs/sapper/blob/72b265a35fe39e7b3695c2b15332c9fcd5f6b2a6/src/api/export.ts#L87

https://github.com/sveltejs/sapper/blob/72b265a35fe39e7b3695c2b15332c9fcd5f6b2a6/src/api/export.ts#L142

The dependency adds 3 nodes total to our tree, including itself.

And since `sapper export` is just a Node process (no browser runtime), we don't really need this.

**Comment by Rich-Harris** [comment]
huh. trying to think what reason there could have been for it

**Comment by Rich-Harris** [comment]
fixed in https://github.com/sveltejs/sapper/commit/e170e4af9b170559aebf0b9a8e546cbd6babe19a
