### ISSUE TITLE
Webpack help

### ISSUE THREAD

**Issue by mapmeld** [sveltejs/sapper#38]
Hi - I've been using basic Express and Koa for some time and missed the boat on a few generations of Node tech (particularly Webpack).  Trying to catch up with this and/or Svelte framework.

When I run ```node server.js``` I am expected to have made a ```webpack.client.config.js``` and ```webpack.server.config.js``` already. I see some sample JSON configs for these in other repos (such as https://github.com/sveltejs/template-webpack ). What's the right way to set these up so that I am webpack-ing all the files of a sapper app?

**Comment by Rich-Harris** [comment]
There's a [dedicated starter template](https://github.com/sveltejs/sapper-template) for use with Sapper. It's still under development, and a couple of things may change before version 1.0.0, but to get started with it you can do this:

```bash
npm i -g degit 
degit sveltejs/sapper-template my-app
cd my-app
yarn
yarn run dev
```

That will install [degit](https://github.com/Rich-Harris/degit), use it to clone the template, install the dependencies and start serving it on localhost:3000.

You *could* build a Sapper project from scratch, if we had documentation about which files it expects to find (coming soon!) but the template is by far the easiest.

The https://github.com/sveltejs/template-webpack repo you linked to is just Svelte, not Sapper — it's a template for purely client-side static apps, whereas the Sapper one includes SSR, code-splitting, HMR, and all the other stuff.

**Comment by mapmeld** [comment]
Thanks!
