### ISSUE TITLE
prefetchRoutes does nothing

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#380]
https://github.com/sveltejs/sapper/blob/3d39836cfb9f7cfb29f262d8985e9bc518669d50/src/runtime/index.ts#L472

`route.load` isn't a thing. (It was, once.)

**Comment by Crisfole** [comment]
This feels like an easy first-timer bug? Maybe throwing up either a) a failing test case, or b) more information on what needs doing?

**Comment by Rich-Harris** [comment]
It would have been, yes 😀 I had to fix it as part of #406, since the 'shape' of components changed, so I'll close this
