### ISSUE TITLE
Set Dev Port by config

### ISSUE THREAD

**Issue by Crisfole** [sveltejs/sapper#381]
Doesn't look like overriding the dev port is possible:

https://github.com/sveltejs/sapper/blob/c5456d30334c91982d347db29de8af9ea684dd2e/src/api/dev.ts#L107

Not clear where `this.port` is set, but I'd love to see devPort treated the same. Makes containing the code easier.

**Comment by Rich-Harris** [comment]
Good idea! Added a `--dev-port` flag in 0.18.4 — thanks
