### ISSUE TITLE
Server routes return 500 Internal Server Error, no mention in the console

### ISSUE THREAD

**Issue by arggh** [sveltejs/sapper#382]
I'm experiencing strange issues while developing. I try to navigate my app to a route that depends on some JSON data being preloaded from the server. Most of the time it works just fine, but sometimes I get `500 (Internal Server Error)` in the browser's console. At the same time the server's console says everything is fine and dandy, no error messages whatsoever.

The keeps showing a spinner and nothing happens until... approximately 30 or 60 seconds later the route magically gets rendered with the correct data.

I have no idea what's causing this.

<img width="1079" alt="500" src="https://user-images.githubusercontent.com/17210302/44649920-f3f40900-a9ed-11e8-8f70-4d641c23b436.png">

**Comment by akaufmann** [comment]
This happens if you have an error in your template or in your preload, oncreate or data method. If it is in your code you can `try/catch` it until @Rich-Harris finds the location where these errors must be caught and logged.

**Comment by Conduitry** [comment]
Closing this in favor of your recent ticket about improving the error reporting.

**Comment by arggh** [comment]
> Closing this in favor of your recent ticket about improving the error reporting.

@Conduitry they are slightly different, but by all means!

I'll still write down the differences here and link the different but thematically related issues in case somebody tries to fix them all at some point.

In _this_ closed (and rather old) issue the server console didn't indicate any errors at all, even though the client was crashing.

In the mentioned recent ticket ([this one?](https://github.com/sveltejs/sapper/issues/899)) about improving error reporting, I was pointing out that stack traces point only to lines in the `server.js` file.

...or did you mean [this one](https://github.com/sveltejs/sapper/issues/898), about Sapper crashing on startup with a very non-descriptive error message when component compilation fails?
