### ISSUE TITLE
--live reload

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#385]
Since Rollup doesn't support HMR, it makes sense to add livereload functionality to the Sapper dev server. Livereload is a bit more invasive than HMR (though on the flipside it has far fewer caveats...) so it makes sense for it to be off by default. I propose this:

```bash
sapper dev --live
```

While we're at it, may as well add `--hot` (which also entails `--no-hot`) for parity, but I think `--hot` should remain on by default.

**Comment by kylecordes** [comment]
With this constitute a reversal of the default though? Before, by default you got reload (in the form of HMR). A user might expect that afterward, the default should also be to have reload.

(More generally, users tend to judge something, especially in their first/early days of use, by what it does by default. So if it is good for new users to perceive that Sapper offers automatic reload, it should be on by default.)

**Comment by Rich-Harris** [comment]
That's a fair point. Yeah, I think I'll change that.
