### ISSUE TITLE
Layouts components doesn't listen to store props changes

### ISSUE THREAD

**Issue by vladejs** [sveltejs/sapper#399]
I have this common use case of submenus:
```
[routes]
    [account]
       settings.html
       profile.html  
       _layout.html
```
I want to check in both `settings` and `profile` if the `$user` store property gets null somehow (you guessed it, a logout action). 

Currently, I have to put this code on both pages (`settings` an `profile`):
```
import { goto } from 'sapper/runtime'

export default {
  onupdate({ changed, current }) {
    if ( changed.$user && current.$user == null ) {
      goto('/')
    }
  }
}
``` 
If `routes/account/_layout.html` component have access to the store, I could implement the above code once, but it seems that isn't possible right now:
`sapper v0.18.16`

**Comment by Rich-Harris** [comment]
Store props are only merged with component props where Svelte statically determines that the component depends on the prop — in other words, `{$user}` has to be in the markup or in a computed property.

You can either trick it into attaching to the store (not really recommend)...

```js
export default {
  computed: {
    user: ({ $user }) => user
  },

  onupdate({ changed, current }) {
    if (changed.user && current.user == null) {
      goto('/')
    }
  }
}
```

...or bind to the store explicitly:

```js
export default {
  oncreate(){
    const listener = this.store.on('update', ({ changed, current }) => {
      if (changed.user && current.user == null) {
        goto('/');
      } 
    });

    this.on('destroy', listener.cancel);
  }
};
```

**Comment by vladejs** [comment]
Is there any performance difference between your solution, and just put an element on the layout referencing the store? Like so:
```
<div class="layout">
  blabla...
</div>

<input type=hidden bind:value=$user />
```

What should be the best choice?

**Comment by Rich-Harris** [comment]
Computed would be the better choice out of the two, since you're not touching the DOM or generating extra elements.

**Comment by vladejs** [comment]
Perfect. Will use that.
Thank you
