### ISSUE TITLE
Add <link rel="preload"> for needed scripts when exporting

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#402]
Sapper adds preload headers when the server is running, but that doesn't work with `sapper export`

**Comment by Rich-Harris** [comment]
fixed by #568

**Comment by khrome83** [comment]
@Rich-Harris - this appears to be broken now. I am not see this work in the most recent version.

**Comment by MaxMilton** [comment]
@khrome83, how about openning a new issue and adding some info about the regression?

**Comment by khrome83** [comment]
@MaxMilton - I can do that. No real steps to reproduce though. It just does not exist...
