### ISSUE TITLE
Confusing "require is not defined" error with undefined `process.env.UNDEF_ENV_NAME` references in client build

### ISSUE THREAD

**Issue by btakita** [sveltejs/sapper#404]
If there is a reference to a env variable `process.env.UNDEF_ENV_NAME` not defined by `webpack.DefinePlugin` in the client build, the error `require is not defined` occurs.

This happens as soon as a module is imported, even if the function containing the env variable is not invoked.

From the error message, it is not obvious what the cause is.

**Comment by ngockhanhbl** [comment]
i had problem too
