### ISSUE TITLE
Process service-worker.js with webpack?

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#41]
Follow-up to https://github.com/sveltejs/sapper/issues/40. Does it make sense to try and run webpack on `service-worker.js`?

It's a little awkward to do so, since the service worker needs to be rendered *after* the client bundle has been created (as it depends on the assets generated therein). And it would be a shame to add another webpack config. It would also be a shame to include all the unnecessary gubbins webpack would add to the file.

The alternative is to stick with the process we have now, which (at least post-#40) might be a little confusing, since it means `main.js` and `service-worker.js` are subject to different rules.

**Comment by lukeed** [comment]
Recommended: [`sw-precache-webpack-plugin`](https://github.com/goldhand/sw-precache-webpack-plugin)

**Comment by ansarizafar** [comment]
StencilJS is using https://github.com/GoogleChrome/workbox

**Comment by Rich-Harris** [comment]
I've poked at things like sw-precache-webpack-plugin and workbox, and it seems to me that they represent the [toolkit vs non](https://twitter.com/Rich_Harris/status/953005486969966595) debate in microcosm — instead of getting a ready made service worker that you can customise, and do things like adding `console.log(...)` statements so that you understand the mechanics of how service workers work, you get an idiosyncratic set of config options and the message that service workers are weird inscrutable beasts that shouldn't be touched by human hands. Am I wrong?

**Comment by Rich-Harris** [comment]
As of 0.7 service workers *are* processed with webpack, so I'll close this
