### ISSUE TITLE
Decode `req.params`

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#417]
Another thing thrown up by the surprisingly productive issue #347: we should probably apply `decodeURIComponent` to `req.params`. That's what Express does if you have something like this:

```js
app.get('/blog/:slug', (req, res, next) => {
  // req.params.slug is decoded
});
```

I think it's what I'd expect to happen in any case.

**Comment by mrkishi** [comment]
Sapper should probably decode `req.query` keys and values as well -- and also replace `+` with `' '` in these.

**Comment by Conduitry** [comment]
(I haven't checked any code or behavior before writing this comment, but) Wouldn't the underlying Express/Polka/etc. library be responsible for decoding `req.query`?

**Comment by mrkishi** [comment]
I meant the [client-side routing](https://github.com/sveltejs/sapper/blob/499b377bfd71ab0eddf9ef2a3cc0c9083859962b/src/runtime/index.ts#L69) part.

But you bring a good point: currently, server-side rendered components receive the framework's `req.query`, so I believe that yeah, we really should match that behavior in the client-side router.

**Comment by lukeed** [comment]
Express & Polka both use `parseurl` which immediately passes off the request to `url.parse` as soon as there's a query involved, as well as a few other characters, which i know decodes the path. Polka passes off any `query` key from that result into `querystring.parse` which I'm 95% sure decodes.

**Comment by Rich-Harris** [comment]
I've updated the PR so that `req.query` is consistent between client and server. I hadn't come across the `+` thing before, interesting

**Comment by mylastore** [comment]
does anyone knows if express-validation can some how be added? Is there any discussion forums for svelte or sapper?
