### ISSUE TITLE
Extracted CSS sourcemaps don't work

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#421]
They work perfectly when appended as inline data URLs but not when they're separate .map files. Probably just need to tweak the path

**Comment by rof20004** [comment]
How can I remove map files for production? I did this on client and server configurations but not working:

```
output: { ...config.client.output(), sourcemap: dev },
```

**Comment by laurentpayot** [comment]
@rof20004 Personally I just remove them at the end of my npm `build` script, something like:
```bash
rm build/client/*.css.map && sed -i '/^[/][*] sourceMappingURL=/d' build/client/*.css
```

**Comment by rof20004** [comment]
@laurentpayot Thanks, I did this after build or export.

find __sapper__/ -name *.map -type f -delete
