### ISSUE TITLE
Issue with a global Store and preload-functions

### ISSUE THREAD

**Issue by arggh** [sveltejs/sapper#430]
When setting a value in a global Store from the `preload` -function, that value will get reset to `null` on all initial page loads (server side rendered) if that said `preload` -function returns _anything at all_.

Reproduction: https://github.com/arggh/sapper-store-preload-issue

#### Instructions to run

```
npm install
npm run dev
```

1. Open `localhost:3000`
2. Pick a tag from the list
3. Refresh page
4. Observe how the value of `activeTag` switches to `null`

**Comment by Rich-Harris** [comment]
It turns out you're not using the serialized store data in your client app; instead it's getting [reset](https://github.com/arggh/sapper-store-preload-issue/blob/940deb77362d70d8621647dc909bc6a4de5768d5/app/store.js#L3-L5) to null.

Your `app/client.js` should look like this:

```diff
import { init } from 'sapper/runtime.js';
import store from './store';
import { manifest } from './manifest/client.js';

init({
  target: document.querySelector('#sapper'),
  manifest,
- store: () => {
+ store: data => {
+   store.set(data);
    return store;
  }
});
```

**Comment by Rich-Harris** [comment]
(The reason it worked when the last line of `preload` was commented out was that Sapper assumes something might have gone wrong serializing the preloaded data if there's a null value in there, so it runs that particular `preload` again on the client. Because of that, the store was having the correct value set.)

**Comment by arggh** [comment]
Ah. So it wasn't Sapper that changed, it was me refactoring `Store` into it's own module and being quilty of copy-paste, losing the serialized data in the process and not remembering there was one to set on the client.

Thanks for helping me out!

**Comment by arggh** [comment]
Also, thanks for explaining how `preload` works in this scenario! Pretty neat.

**Comment by arggh** [comment]
...follow up question:

If I follow your advice @Rich-Harris strictly in my actual app, Sapper will complain about trying to set read-only values in my store (it has a few computed values) by throwing this: `Uncaught Error: 'activeItems' is a read-only property`. I get past that by supplying the `data` directly to the Store's constructor and not using `set`.

Is this something that deserves it's own issue to be created?

**Comment by Rich-Harris** [comment]
I think the solution there is to be able to do `store.get({ computed: false })` - I believe there's an issue for that already on the main svelte repo as it applies to components

**Comment by jhwheeler** [comment]
@Rich-Harris Can you hydrate stores like this from `sapper.start`? The only available property in the docs is `target`, did this get lost in the move from Svelte v2?

**Comment by antony** [comment]
@jhwheeler https://sapper.svelte.dev/docs#Seeding_session_data

**Comment by jhwheeler** [comment]
Thank you, @antony! It's quite relevant.
