### ISSUE TITLE
polka 0.5.0 error

### ISSUE THREAD

**Issue by matt3224** [sveltejs/sapper#442]
<img width="1005" alt="screen shot 2018-09-18 at 21 58 04" src="https://user-images.githubusercontent.com/2401925/45716153-f9c4b080-bb8d-11e8-9893-6c7651e58ce5.png">

**Comment by lukeed** [comment]
Yeah, I have a PR incoming already for the template. 

Polka 0.5.0 removed the Promise around `.listen` – one of [two breaking changes](https://github.com/lukeed/polka/releases/tag/v0.5.0). Shuffling things around before a 1.0 release.

You can swap out then `then/catch` for traditional `.listen(err => {})` usage.

**Comment by lukeed** [comment]
https://github.com/sveltejs/sapper-template/pull/80
https://github.com/sveltejs/sapper-template/pull/81

**Comment by lukeed** [comment]
Both PRs have been merged, thanks for the reminder 👍 

Check out the diff (of either) for the super simple change you need to make in your app.

Thanks!
