### ISSUE TITLE
Prevent sapper/runtime.js running in Node

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#445]
Occasionally folks trip up by using functions from `sapper/runtime.js` in code that runs on the server — for example using `goto` in `preload` instead of `this.redirect(...)`. Instead of failing with a cryptic error it should tell the user that those functions only run in the client.

**Comment by arxpoetica** [comment]
An alternative might be to align `this.redirect` terminology on the front and back end?

**Comment by Rich-Harris** [comment]
@arxpoetica What do you mean? `this.redirect` *does* behave the same on the server as in the client.

**Comment by arxpoetica** [comment]
vice versa. make `this.redirect` a thing on the client. I'm really just brainstorming. ignore me if it doesn't apply / isn't right. ;)

**Comment by Rich-Harris** [comment]
Closing as `sapper/runtime.js` no longer exists, post-#453
