### ISSUE TITLE
sensible approach to logging

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#45]
Sapper shouldn't try to do the job of dedicated logging middleware, but it should provide some visibility into what's happening. Not sure what established practices are here, probably worth cribbing from Next and Nuxt

**Comment by Rich-Harris** [comment]
Closing this as I'm not exactly sure what I meant by it. Folks can just use `morgan` or whatever in their servers

**Comment by dpmccabe** [comment]
In case anyone else ends up here via search, you need to make sure you load morgan before the sapper middleware, otherwise nothing gets logged:

```js
import sirv from 'sirv';
import express from 'express';
import compression from 'compression';
import morgan from 'morgan';
import * as sapper from '../__sapper__/server.js';

const { PORT, NODE_ENV } = process.env;
const dev = NODE_ENV === 'development';

const app = express();

app.use(
  compression({ threshold: 0 }),
  sirv('static', { dev }),
  morgan('combined'),
  sapper.middleware()
);

app.listen(PORT, err => {
  if (err) console.log('error', err);
});
```
