### ISSUE TITLE
Chunk Error - Uncaught TypeError: t.appendChild is not a function

### ISSUE THREAD

**Issue by btakita** [sveltejs/sapper#463]
Sapper v0.22.9

In a production environment, the following error occurs.

```
chunk.8a717285.js:1 Uncaught TypeError: t.appendChild is not a function
    at r (chunk.8a717285.js:1)
    at chunk.2eac9367.js:1
```

After analyzing the outputs, my best guess is that there's an issue with the import/export naming & aliasing.

The error occurs at https://censible.co/solutions It is only on the censible.co site & I have not encountered it in any of the other deployments.

It does not occur in the staging environment (NODE_ENV='production') or in development.

chunk.8a717285.js excerpt
```javascript
function r(t, n) {t.appendChild(n)}
export {
	r as a, /* This is the function being invoked */
	n as b,
	y as c,
	v as d,
	d as e,
	o as f,
	D as g,
	i as h,
	t as i,
	q as j,
	f as k,
	C as l,
	S as m,
	l as n,
	_ as o,
	T as p,
	w as q,
	O as r,
	p as s,
	N as t,
	A as u,
	E as v,
	k as w,
	B as x,
	F as y,
	j as z,
	g as A,
	u as B,
	m as C,
	e as D,
	c as E,
	h as F,
	a as G,
	b as H,
	s as I
}

```

chunk.2eac9367.js excerpt
```javascript
import { a as t, b as e, c as n, d as o, e as r, f as i, g as s } from './chunk.8a717285.js'
// ...
t(S.prototype, {/* Store prototype */})
```

**Comment by btakita** [comment]
Here are excerpts from the staging environment:

chunk.8a717285.js excerpt
```javascript
function n(t, n) {
	for (var e in n) t[e] = n[e]
	return t
}
export {
	n as a,
	A as b,
	E as c,
	k as d,
	B as e,
	F as f,
	j as g,
	r as h,
	y as i,
	v as j,
	d as k,
	o as l,
	D as m,
	i as n,
	t as o,
	q as p,
	f as q,
	e as r,
	C as s,
	S as t,
	l as u,
	_ as v,
	T as w,
	w as x,
	O as y,
	p as z,
	N as A,
	g as B,
	u as C,
	m as D,
	c as E,
	h as F,
	a as G,
	b as H,
	s as I
}
```

chunk.2eac9367.js excerpt
```javascript
import { a as t, b as e, c as n, d as o, e as r, f as i, g as s } from './chunk.8a717285.js'
t(S.prototype, { /* Store prototype */})
```

Function `n` in staging correctly maps to the `assign` function in svelte.

https://github.com/sveltejs/svelte/blob/master/src/shared/utils.js#L3

```javascript
	function assign(tar, src) {
		for (var k in src) tar[k] = src[k];
		return tar;
	}
```

**Comment by Rich-Harris** [comment]
Very odd. I have to assume this is a Rollup bug — if there's any way you can narrow down the reproduction it would be very helpful. Not sure there's anything that can be done without a repro 😬
