### ISSUE TITLE
Change scrollX & scrollY to pageXOffset & pageYOffset?

### ISSUE THREAD

**Issue by johanalkstal** [sveltejs/sapper#480]
Should these values be changed for the same reasons they were changed in Svelte?

https://github.com/sveltejs/sapper/blob/d3e560325d7c2dd22a32224ff0d57e62d8557691/templates/src/client/app.ts#L104-L105

Old Svelte issue, https://github.com/sveltejs/svelte/issues/1175

**Comment by Rich-Harris** [comment]
Good idea, thanks — fixed in 0.24
