### ISSUE TITLE
Can i change host?

### ISSUE THREAD

**Issue by khaninD** [sveltejs/sapper#485]
@Rich-Harris , Can i change host? By default is localhost, i want use 0.0.0.0

**Comment by jacobbowdoin** [comment]
@khaninD Are you able to post your solution? I've tried making changes to server.js to allow setting the host to 0.0.0.0 and haven't been successful thus far.

**Comment by bato3** [comment]
um... try https://nodejs.org/dist/latest-v9.x/docs/api/net.html#net_server_listen_options_callback

Also better way for production is reverse proxy or even https://www.phusionpassenger.com/

**Comment by jacobbowdoin** [comment]
> Are you able to post your solution? I've tried making changes to server.js to allow setting the host to 0.0.0.0 and haven't been successful thus far.

Thanks for the reply @bato3 - I feel ridiculous. I was trying to open my app on another machine to aid development from `npm run dev` and the only thing needing changed was not server.js but rather identifying my home network as private and not public in network settings.

**Comment by janosh** [comment]
Would be cool if Sapper could log to the console the link through which the dev server can be viewed on other devices. Right now, `sapper dev` only gives
```
> Listening on http://localhost:3000
```
whereas pure Svelte using `rollup -c -w` prints
```
Your application is ready~! 🚀

- Local:      http://0.0.0.0:5000
- Network:    http://10.248.97.251:5000
```
