### ISSUE TITLE
Error in async preload breaks SSR

### ISSUE THREAD

**Issue by mrkishi** [sveltejs/sapper#494]
The server never responds to _page_ routes (server routes work) requests when the preload function fails. It just hangs there until timeout.

**Comment by Rich-Harris** [comment]
Can you give an example? If I throw an error inside `preload` (async or not) it behaves as expected for me, for both client and server rendering.

**Comment by mrkishi** [comment]
Sorry for not including a lot of information. I intended to look further into it when I had time.

Maybe it's not related to `async` but to layout's `preload`? Here's an example in action: https://github.com/mrkishi/sapper-template/commit/01be2b18aba194ddd9187f4ea2532738ca32ffc8.

**Comment by mrkishi** [comment]
Okay, so it's not just `async`. Any `throw`s inside a common layout `preload` will also make the server hang. That's because it enters an infinite loop trying to render the error: `handle_error` calls `handle_page` calls `handle_error`... We probably want to answer to errors when handling an error with a simple 500 error?

**Comment by jarrodldavis** [comment]
@mrkishi and I talked about this in the Discord and agreed that it would be good to have some indication of the `_error` page being rendered when calling `preload`.

**Comment by Conduitry** [comment]
How much of this is still an issue? It looks like #677 should have fixed the infinite preload error.

**Comment by mrkishi** [comment]
This can indeed be closed!

I'll open an issue about providing a better error solution when a page's hitting errors on `handle_error`, though, since we're currently just `pre`ing `Internal server error` which isn't really ideal.
