### ISSUE TITLE
[Request] Hash global.css

### ISSUE THREAD

**Issue by matt3224** [sveltejs/sapper#508]
Hello,

Would it be at all possible to hash the global.css file as i'm currently adding a query string to the url every-time I make a change which i push. Would be super handy to have this be done automatically.

Thank you!

**Comment by MaxMilton** [comment]
Are you referring to the `/static/global.css` file in `sapper-template`? One option would be to import your CSS in a script (e.g. `/src/client.js`) and handle your global styles with webpack/rollup. Sapper will take care of it and inject it into `/dist/client/main.[hash].css`.

There was a similar discussion in <https://github.com/sveltejs/sapper/issues/474>.

**Comment by matt3224** [comment]
Yes i am referring to exactly that. Do you have an example rollup config per chance?

**Comment by matt3224** [comment]
Thank you @MaxMilton I have successfully implemented this!
