### ISSUE TITLE
flatmap-stream found

### ISSUE THREAD

**Issue by vedam** [sveltejs/sapper#520]
hey,
I want to let you know, I found the flatmap-stream-package in my node_modules-folder too.
Pointing to this [event-stream-issue](https://github.com/dominictarr/event-stream/issues/116) going through twitter. Seems to be causing a lot of excitement.

![bildschirmfoto 2018-11-27 um 10 41 22](https://user-images.githubusercontent.com/64245/49072674-02420300-f231-11e8-8601-4f32a53584d9.jpg)

**Comment by nolanlawson** [comment]
Seems fixed by https://github.com/sveltejs/sapper/pull/521

**Comment by vedam** [comment]
cool
