### ISSUE TITLE
Rollup export: Missing css chunk for component

### ISSUE THREAD

**Issue by steinoy** [sveltejs/sapper#522]
Exporting static site using `sapper export --legacy` with rollup causes link to css chunk of shared component to be excluded from the rendered route. This happens if the component is used elsewhere and imported after components unique to the route.

This had me scratching my head today when the styles of a component disappeared from the index route in some cases, but not in others.

Here's an example using the latest rollup template:

https://github.com/steinoy/sapper-template/commit/34a326cb8790a4560ec32b3c4b7ac3b8aa90bbc6

about.html:
```javascript
export default {
	components: {
		Red: '../components/Red.html',
	}
}
```
index.html:
```javascript
export default {
	components: {
		Blue: '../components/Blue.html', // unique
		Red: '../components/Red.html'    // shared
	}
}
```
This causes the css chunk for Red.html missing from index.html. However, changing the order of the imports fixes it:

index.html:
```javascript
export default {
	components: {
		Red: '../components/Red.html',  // shared
		Blue: '../components/Blue.html' // unique
		
	}
}
```
I'm guessing this isn't the intended behaviour? 🤔

**Comment by antony** [comment]
We recently rewrote css handling, so closing this.
