### ISSUE TITLE
oncreate on component is not called on _error page

### ISSUE THREAD

**Issue by johanalkstal** [sveltejs/sapper#526]
Demonstrated by this CodeSandbox,

https://codesandbox.io/s/8l7jxnopvj

- On start page you will get an alert created on the Nav component oncreate method.
- Enter a gibberish url to get the _error page loaded.
- No alert is displayed because oncreate was never called.

How this affects our application is that our Nav component doesn't work on our 404 page causing mobile users unable to navigate away from that page, because the click method bound to the hamburger menu doesn't execute.

**Comment by Conduitry** [comment]
I believe this was fixed (albeit for Svelte 3) in #620.
