### ISSUE TITLE
How static pages with auth-redirect works at client side

### ISSUE THREAD

**Issue by IEfucker** [sveltejs/sapper#548]
I'm newer to sveltejs，but familiar with static page. One major advantage of static page is fast, and trouble with auth-redirect(client-side) is also obvious.

Like an inner page with authentication, static page would be load by browser and show markup after css file is loaded and rendered, then javascript works and judges whether or not current user is authenticated. And immediately redirect to login/inner page would make screen flash. And some hacking method like hide view with style-class before auth checking is not elegance.

Only if one short script could be run at top of html, without loading other heavy js(and css), but it's not implement by any framework, for algorithm of auth-judging may need some other lib, or a long time job.

So I don't think static page with router and auth at client side is a good way. It shall be handle by server side, or use dynamic render page.

This' just my opinion, and sorry for my poor En

**Comment by MaxMilton** [comment]
I'm not sure I see a bug report or feature request here... there is a Svelte discord chat this conversation might be better suited for: https://discord.gg/yy75DKs :slightly_smiling_face:

**Comment by antony** [comment]
It sounds like you are facing a similar architectural issue regarding server and client authentication, as I did. Here's how I do it now:

1. User requests login via client
2. API authenticates user and sets an httpOnly cookie in its response
3. API requests from the client automatically send the httpOnly cookie with each request.

The way that the redirection of unauthenticated users works is by wrapping the Sapper middleware inside `server.js`:

```js
function redirect (req, res, requiresLogin) {
  const url = `${process.env.baseUrl}${req.originalUrl}`
  const location = `${process.env.customerApplicationUrl}${requiresLogin ? '/login?from=' + url : ''}`
  res.writeHead(302, { Location: location })
  return res.end()
}

polka()
  .use(
    compression({ threshold: 0 }),
    sirv('static', { dev }),
    cookieParser(),
    (req, res, next) => {
      const token = req.cookies[process.env.jwtName]

      if (!token) {
        return redirect(req, res, true)
      }

      try {
        const decoded = jwt.decode(token)
        if (
          decoded.role !== 'vendor' &&
          req.path !== '/onboarding' &&
          !req.path.startsWith('/client/')) {
          return redirect(req, res, false)
        }
      } catch (e) {
        return redirect(req, res, true)
      }

      return sapper.middleware({})(req, res, next)
    }
  )
  .listen(PORT, err => {
    if (err) console.log('error', err)
  })
```

**Comment by IEfucker** [comment]
So Sapper has a server?...

Sorry, I thought it's served by nginx without auth.
If there's a server could handle authentication at server-side, it would be great.

**Comment by antony** [comment]
@IEfucker Sapper is a server and a client, it pre-renders components on the server, and rehydrates them on the client. So yeah, it has a server.

It uses Polka which is nearly identical to express, so you can use any authentication mechanism you would use with express.

**Comment by julienchazal** [comment]
@antony does your solution works with exported static site ?

**Comment by antony** [comment]
@julienchazal Everything I've posted above lives in `server.js` which doesn't exist in an exported site, so no. If you want to chat about solutions, come and find us in #sapper on discord.
