### ISSUE TITLE
Support Koa or koa-connect

### ISSUE THREAD

**Issue by focus-at** [sveltejs/sapper#549]
import sirv from 'sirv';
import compression from 'compression';
import * as sapper from '../__sapper__/server.js';

const { PORT, NODE_ENV } = process.env;
const dev = NODE_ENV === 'development';

const Koa = require('koa');
const c2k = require('koa-connect');
const app = new Koa()

app.use(c2k(compression({ threshold: 0 })));
app.use(c2k(sirv('static', { dev })));
app.use(c2k(sapper.middleware()));

app.listen(PORT);

**Comment by focus-at** [comment]
this works for http://localhost:3000/terms path
but http://localhost:3000/ trows Internal Server Error

**Comment by antony** [comment]
@focus-at I don't know anything about Koa I'm afraid, but possibly if you have non-sapper routes in your server, you need to ignore them in the sapper middleware:

```
sapper.middleware({
      ignore: [
        uri => uri.startsWith('/some-non-sapper-route')
      ]
})
```

**Comment by allochi** [comment]
@antony I was looking for this 😄 thanks!

**Comment by focus-at** [comment]
> @focus-at I don't know anything about Koa I'm afraid, but possibly if you have non-sapper routes in your server, you need to ignore them in the sapper middleware:
> 
> ```
> sapper.middleware({
>       ignore: [
>         uri => uri.startsWith('/some-non-sapper-route')
>       ]
> })
> ```

ty for example Antony, as you can see i dont have non-sapper routes now, but next time im add them

**Comment by DanielSokil** [comment]
@Rich-Harris Any reason why `/` does not work?

**Comment by DanielSokil** [comment]
This issue is not only specific to `Koa`, but also applies to other frameworks like https://github.com/jkyberneees/ana

**Comment by vsviridov** [comment]
Here's what worked for me in the `sapper-template` app. Have not tested beyond that.

```
import Koa from "koa";
import connect from "koa-connect";
import koaStatic from "koa-static";
import * as sapper from '../__sapper__/server.js';

const { PORT, NODE_ENV } = process.env;
const dev = NODE_ENV === 'development';

const app = new Koa();

app.use(koaStatic("static"));
app.use(connect((req, res, next) => {
  req.originalUrl = req.url;
  sapper.middleware()(req, res, next);
}));

app.listen(PORT);
```

**Comment by focus-at** [comment]
without koa-connect & req.originalUrl

`
import Koa from "koa";
import * as sapper from '@sapper/server';

const { PORT, NODE_ENV } = process.env;
const dev = NODE_ENV === 'development';

const app = new Koa();

app.use(async (ctx, next) => {
	ctx.respond = false;
	await sapper.middleware()(ctx.request, ctx.res, next);
});

app.listen(PORT);
`
but i'm not sure what is the best idea

from koajs.com 
> **ctx.respond**
> To bypass Koa's built-in response handling, you may explicitly set ctx.respond = false;. Use this if you want to write to the raw res object instead of letting Koa handle the response for you.
> 
> Note that using this is not supported by Koa. This may break intended functionality of Koa middleware and Koa itself. Using this property is considered a hack and is only a convenience to those wishing to use traditional fn(req, res) functions and middleware within Koa.

**Comment by antony** [comment]
The previous comment is the best workaround to do this right now.

There may be value in opening a new issue to make Sapper middleware less greedy, but right now, wrapping it allows you to have non-sapper routes on the same handler.
