### ISSUE TITLE
Drop Node 6 support?

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#553]
Node 6 is still in LTS, but the main reason Sapper still supports Node 6 — that Lambda and Cloud Functions are stuck on that version — no longer holds (both officially support Node 8). Could make things rather simpler. Would that get in anyone's way?

**Comment by lukeed** [comment]
Depends if wanna jump the gun on LTS. Version 6.x expires this April 🎉 I'll be updating my stuff then.

As mentioned, we _only_ added Node 6 because of lambda/function platforms and they're both solved now.

**Comment by Rich-Harris** [comment]
Switched over from TypeScript to Sucrase and realised that it won't build in Node 6 any more anyway... it's annoying that it's awkward to test that something *runs* in an old version of Node without also *building* it in that version, but it is, and I'm lazy, so bye-bye Node 6
