### ISSUE TITLE
svelte@3-beta.4 causes Unrecognized option 'onwarn'

### ISSUE THREAD

**Issue by thgh** [sveltejs/sapper#571]
I was updating some deps and ran into this: (sapper and rollup version don't matter)

Works: `yarn add svelte@3.0.0-beta.3 && yarn dev`
Fails: `yarn add svelte@3.0.0-beta.4 && yarn dev`
Fails: `yarn add svelte@3.0.0-beta.5 && yarn dev`
```
$ sapper dev
✗ server
Unrecognized option 'onwarn'
✗ client
Unrecognized option 'onwarn'
```

**Comment by Rich-Harris** [comment]
yep, broke this last night — working on a fix as we speak!

**Comment by Rich-Harris** [comment]
fixed now with the latest version of the Rollup plugin
