### ISSUE TITLE
sapper export --legacy breaks pdf static serving

### ISSUE THREAD

**Issue by sgametrio** [sveltejs/sapper#572]
I have not tried yet if export breaks other types of file
Version: `sapper 0.26.0-alpha-8`
## How to reproduce
1. Put some pdf file in static folder.
2. Reference them in your application so that `sapper export --legacy` creates routes for them
3. Try navigating to them. (pdf error or pdf blank)

## Solution
After running `export` replace pdf in `__sapper__/export` with files in your static folder

**Comment by arggh** [comment]
I can confirm this issue is very real, glad I noticed it before things went south!

**Comment by rof20004** [comment]
I confirm this issue too.
