### ISSUE TITLE
service-worker-index.html 404 Not Found for export with base-path

### ISSUE THREAD

**Issue by NikolayMakhonin** [sveltejs/sapper#579]
Hello,

It seems like a error. The link to the ```/service-worker-index.html``` contains a slash at the beginning. And so the absolute path starts from the root of the site, not from the base-path.

```http://localhost:4445/sapper/page/index.html:```
```
<!doctype html>
<head>
    ...
    <base href=/sapper/page />
    ...
```
Network log:
```http://localhost:4445/service-worker-index.html``` - 404 Not Found
because this file is located at the following address: 
```http://localhost:4445/sapper/page/service-worker-index.html```

----
```__sapper__/service-worker.js```
```__sapper__/export/sapper/page/service-worker.js```:
```
...
export const files = [
	"/service-worker-index.html",
	"favicon.png",
	"global.css",
	"great-success.png",
	"manifest.json",
	"polyfills/fetch.iife.js",
	"polyfills/polyfill-custom.js",
	"polyfills/promise-polyfill.min.js",
	"polyfills/url-polyfill.min.js",
	"svelte-logo-192.png",
	"svelte-logo-512.png"
];
...
```

**Comment by Seb35** [comment]
I also observe this: service-worker-index.html searched at /service-worker-index.html instead of /path/service-worker-index.html, but both /path/service-worker-index.html and /path/service-worker.js exist.
