### ISSUE TITLE
can't install on windows 7

### ISSUE THREAD

**Issue by whatsdis** [sveltejs/sapper#58]
uglifyjs-webpack-plugin postinstall is failing on Windows 7.

**Comment by Rich-Harris** [comment]
Sounds like an uglifyjs-webpack-plugin issue! Is there something specific to Sapper causing the problem?

**Comment by tomcon** [comment]
@whatsdis that's really strange as I installed and ran everything fine on Windows 7
Can you post the error message(s)?
