### ISSUE TITLE
Prevent scroll to top when calling goto from method

### ISSUE THREAD

**Issue by cbenz** [sveltejs/sapper#584]
I'd like to prevent scroll to top when I click on a `<button on:click=search()>`, and the `search` method calls `goto("?q=foo")`.

Prevent scroll seems important in order to keep the user focused on the search form which is not at the top of the page.

I would have the same need with a `<select>` element: changing its value would call `goto("?selected=foo")`.

Is it possible?

Cf #376

**Comment by cbenz** [comment]
here's a quick codesandbox showing the issue: https://codesandbox.io/s/16zxv8ovj

**Comment by thgh** [comment]
This could be implemented as an option of goto:
```js
goto('?q=foo', { scroll: false })
```

Implementation
```diff
- return navigate(target, null).then(() => {}); 
+ return navigate(target, null, opts.scroll === false).then(() => {}); 
```
https://github.com/sveltejs/sapper/blob/411e2594af6f46ed73c45c1f0db0746adf20bdb5/runtime/src/app/goto/index.ts#L8

**Comment by flayks** [comment]
+1
