### ISSUE TITLE
Session overrides during hydration

### ISSUE THREAD

**Issue by imbolc** [sveltejs/sapper#588]
I'm not sure if it's a bug. This sends correct html from server, but then overrides session value with `undefined` in the browser:
```html
<script context="module">
    import { fooStore } from "../stores.js"

    export async function preload(page, session) {
        fooStore.set('bar')
    }
</script>
```

I can fix it by adding `return { fooStore }` into `preload`.

**Comment by thgh** [comment]
Preload passes a stringified object to the browser, the object contains the returned value from preload (and more). It doesn't contain the data in stores. Would be interesting though.
