### ISSUE TITLE
Don't bundle Svelte compiler

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/sapper#598]
At least the latest alpha of Sapper is bundling the Svelte compiler (version 3.0.0-beta.3). This avoids issues with changes between compiler versions, but I don't think this is a good idea overall.

**Comment by Conduitry** [comment]
During the pre-release phase of Svelte and Sapper, I think it's reasonable to not be particularly careful about breaking changes or compatibility between different versions of the two projects. I don't foresee more changes in this area of Svelte, but if there are, people will just have to upgrade together.

**Comment by Conduitry** [comment]
It looks like the intention is to not bundle Svelte, but in `rollup.config.js`, we are constructing the `external` array from (in part) `Object.keys(pkg.dependencies)`, which will contain `'svelte'` but not the `'svelte/compiler'` that Svelte 3 now uses.

**Comment by Rich-Harris** [comment]
blurgh. yeah, sounds like we need to update that Rollup config — definitely don't want to bundle the compiler
