### ISSUE TITLE
Cannot navigate from /a/[id] to /b/[id] 

### ISSUE THREAD

**Issue by thgh** [sveltejs/sapper#606]
Repro: https://github.com/thgh/sapper-template/tree/repro-606
Steps:

1. Visit https://todo-xflcnzulor.now.sh/b/same
2. Notice page: `b/same`
3. Click link a/same
4. Notice page is still `b/same` (expected `a/same`)
5. Refresh
6. Page is now `a/same` (correct)

There is two routes
* /a/[id]/index.svelte
* /b/[id]/index.svelte

It seems sapper does not detect when navigating between both.

**Comment by cudr** [comment]
https://github.com/sveltejs/sapper/blob/7be7e1eb9f8c17e8d8b6b6966cb67fe7b54bc9ab/runtime/src/app/app.ts#L257

```
current_branch[i].segment === segment
```
In this case segments are equals, so app don't change page

**Comment by thgh** [comment]
That code is never reached, it short circuits because `part === null`

https://github.com/sveltejs/sapper/blob/7be7e1eb9f8c17e8d8b6b6966cb67fe7b54bc9ab/runtime/src/app/app.ts#L250-L252
