### ISSUE TITLE
Unable to use Custom Elements

### ISSUE THREAD

**Issue by darbymanning** [sveltejs/sapper#609]
I wanted to test custom elements within a Sapper app. This works fine in Svelte by following [instructions in the documentation](https://svelte.technology/guide#custom-elements), but I am not able to successfully create a custom element in Sapper.

In my testing, I've found that initially setting `customElement: true` in the svelte configuration was giving me `No tag name specified` returned when I try to run the dev server. I then tried explicitly defining the tag & props instead, which got my dev server running. However looking in dev tools I'm seeing this error:

```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': "undefined" is not a valid custom element name at http://localhost:3000/client/client.4f7868bb.js:333:16
```

Looking at line 333 of the client.js file, we see:

```
customElements.define("undefined", Layout);
```

It looks like the tag name is somehow not being identified correctly, in spite of being specified both in the svelte compiler configuration and the components export function.

**Comment by matt3224** [comment]
Replication of the issue here: https://github.com/matt3224/sapper-custom-element-bug

I've had to use both the compiler option and the tag property, whereas i think just the tag prop should be enough on its own with customElement: true in the config
