### ISSUE TITLE
(v3) Slot in `_layout` doesn't re-render when forwarded to another component

### ISSUE THREAD

**Issue by unindented** [sveltejs/sapper#614]
Versions where I can repro:

```json
{
  "sapper": "0.26.0-alpha.12",
  "svelte": "3.0.0-beta.20"
}
```

When `_layout.svelte` looks like this, everything renders fine as I navigate around:

```html
<main id="main">
  <slot></slot>
</main>
```

However, if I try to have that slot rendered by a child component, only the initial render works. This would be `_layout.svelte`:

```html
<script>
  import LayoutMain from "../components/LayoutMain.svelte";
</script>

<LayoutMain>
  <slot></slot>
</LayoutMain>
```

And this would be `LayoutMain.svelte`:

```html
<main id="main">
  <slot></slot>
</main>
```

**Comment by njbotkin** [comment]
I think this is safe to close, now.  I pass layout slots to components quite often and there's no problem.
