### ISSUE TITLE
input won't focus with `onMount`

### ISSUE THREAD

**Issue by arxpoetica** [sveltejs/sapper#619]
This seems to be a Sapper-only bug, because it works in the REPL: https://v3.svelte.technology/repl?version=3.0.0-beta.21&gist=425d987fa48b28dcaa9872f88d5986e3

Repro: https://github.com/arxpoetica/gah

Relevant line: https://github.com/arxpoetica/gah/blob/master/src/routes/does-not-work.svelte#L10

Not urgent, but it seemed to be an actual bug? Thanks!

**Comment by Rich-Harris** [comment]
This is for a11y — when navigating, the focus is supposed to reset (which is also the reason that the `autofocus` attribute is discouraged): https://github.com/sveltejs/sapper/blob/master/runtime/src/app/app.ts#L154

The focus reset happens after navigation, so setting the focus in `onMount` will have no effect. If you *really* need to focus the input then the `setTimeout` is necessary, but ideally I'd try and see if there's an alternative that doesn't break a11y guidelines.

**Comment by arxpoetica** [comment]
Got it

**Comment by timothyerwin** [comment]
I had this problem using Svelte...I think this is a basic feature that people would expect to work. I don't agree with Svelte circumventing this in the name of a11y.

**Comment by nickolasgregory** [comment]
Is the focus reset intended to occur when pressing `Escape` on an input too?

If I press `Escape` on a "blank" `input` the input loses focus and I get an error from `client.js`  
I'm wanting to capture this event and clear the input value.

Any thoughts much appreciated.

**Comment by ramiroaisen** [comment]
But what if i need to navigate to a search page after the user press enter in a search input beeing focused...
The input loses focus... that's not really what you would expect in a mobile app for example
Sapper apps doesn't really "navigate" is more an app like feel to the user so we don't need to follow this a11y rule.
Is there a way i force the input to keep focus after navigating?

**Comment by antony** [comment]
@ramiroaisen Rich has mentioned it above:

```
onMount(() => {
  setTimeout(() => {
    yourField.focus()
  }, 1000)
})
```

with the caveat - it breaks a11y, so ideally don't do it.

**Comment by ramiroaisen** [comment]
@Rich-Harris but that tecnique generates a delay and the user just cant keep typing

**Comment by antony** [comment]
@ramiroaisen as you'll understand from Rich's comment above, the behaviour you desire breaks a11y, which is considered of greater importance than allowing a form to be automatically autofocussed.

The behaviour is unlikely to change, so I'd recommend either using the `setTimeout` solution (tweaking the timeout as necessary), or finding another workaround. I haven't tried it but:

```
import { onMount, tick } from 'svelte'

onMount(() => {
  await tick()
  yourField.focus()
})
```

might also work.

**Comment by thricedotted** [comment]
For what it's worth -- `await tick()` doesn't do it, but `setTimeout(callback, 0)` works in both Firefox and Chrome for me.

I'm glad I came across this page, though. I wasn't aware of the accessibility concerns, and while this is still useful for my application, I'll put it behind a user option.
