### ISSUE TITLE
Remove async/await

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#62]
Currently, Sapper requires Node 8, which means you can't run it on AWS Lambda and what-have-you

**Comment by EmilTholin** [comment]
Would you like to remove async/await from the tests as well?

**Comment by Rich-Harris** [comment]
I suppose we'd need to, if we're to guard against regressions. If we're not testing on Node 6 it'd be very easy to accidentally stop supporting it

**Comment by thgh** [comment]
I would vote to use `@std/esm` instead. Not sure what the performance impact would be on Lambda.

**Comment by Rich-Harris** [comment]
@thgh `@std/esm` is just about supporting `import` and `export`, it doesn't have any bearing on whether `async` and `await` can be used. This issue should be closed though, it was fixed in #67
