### ISSUE TITLE
Class name order changes on hydration

### ISSUE THREAD

**Issue by arggh** [sveltejs/sapper#621]
Sapper / Svelte doesn't preserve class name ordering when hydrating.

```html
<div class="illustration"><img src="hero.png"/></div>

<style>
.illustration {
   animation-name: Fade;
   animation-fill-mode: backwards;
   animation-duration: 300ms;
}

@keyframes Fade {
   0% { opacity: 0%; }
   100% { opacity: 100%; }
}
</style>
```

This chunk of code causes `Fade` animation to run twice because the class names are flipped on hydration.

<img width="428" alt="svelte-sapper-issue" src="https://user-images.githubusercontent.com/17210302/55686656-838e6c80-596c-11e9-95cd-1d2ec85b3d9d.png">

**Comment by Rich-Harris** [comment]
What versions are you using? Are you able to create a repro, ideally without Sapper? I can't recreate it locally

**Comment by arggh** [comment]
Hmmh. I think I might know why you can't repro it. In dev tools (presuming Chrome) throttle down the network to `Slow 3G` or `Fast 3G` and give it another try.

I couldn't repro this locally either when it was first reported to me, but it was definitely occurring in production at the time. Let me check....

.....aaaaand I just verified that I too can't reproduce it locally unless I throttle the network to more real life speeds.

Also,

sapper@0.25.0
svelte@2.16.1

**Comment by Rich-Harris** [comment]
I mean that the class name order was consistent between server and client renders. That was with Svelte 3 though, maybe it's been fixed already?

**Comment by arggh** [comment]
Could be, I'm still stuck on v2 :(

We'll find out when I get to upgrade to v3, which shouldn't take long. Keep this open until then?

**Comment by arggh** [comment]
>which shouldn't take long

...was a typical developer's time estimate, it seems.

However, I finally got the upgrade done to v3, and I can confirm this bug is gone 🎉
