### ISSUE TITLE
Request: Option to remove css maps in build

### ISSUE THREAD

**Issue by matt3224** [sveltejs/sapper#629]
Moved from https://github.com/sveltejs/svelte/issues/1842#event-2277622603

Hello,

Would it be possible to have a way to switch off css map files from being generated in npm run build?

I couldn't see a way to do that currently, I hope this is a Svelte thing but happy to close and move to Sapper if that's actually the right place.

Thank you!

**Comment by laurentpayot** [comment]
@matt3224 are you using Sapper with Rollup? If so I opened this issue: https://github.com/sveltejs/sapper/issues/537

**Comment by matt3224** [comment]
@laurentpayot ah yes, i'll close for #537
Thanks
