### ISSUE TITLE
Support for static site generation

### ISSUE THREAD

**Issue by freedmand** [sveltejs/sapper#63]
@Rich-Harris mentioned in a [Hacker News thread](https://news.ycombinator.com/item?id=16057610) that Sapper will eventually have static site export functionality. I've created this issue to track the progress on that and potentially see if there's anything that can be done to jump the gun.

(For my specific use case, I really want to start using Sapper to build progressive static websites that I can deploy with Netlify)

**Comment by Rich-Harris** [comment]
yep! we definitely want to do this. There's actually an issue already open — #9 — so I'll close this in favour of that one
