### ISSUE TITLE
Invalid links on the site "sapper.svelte.technology"

### ISSUE THREAD

**Issue by vladknp** [sveltejs/sapper#630]
### Invalid links on the site "sapper.svelte.technology".
For example, let'go to section "#preloading" and click on the link "default data". This link leads to "https://svelte.dev/guide#default-data"

**Comment by SwaroopH** [comment]
The website hasn't been updated with references to the v3 Svelte's website. @Rich-Harris mentioned on [Discord](https://discordapp.com/channels/457912077277855764/473466028106579978/571174305367588865) it may get updated over the weekend.

**Comment by Conduitry** [comment]
This should be all set now. The old (v2 Svelte) version of the Sapper site now has links to the v2 Svelte site.
