### ISSUE TITLE
Circular Dependency Using @sapper/app

### ISSUE THREAD

**Issue by evanleck** [sveltejs/sapper#631]
I have a component that has `import { page } from '@sapper/app'`. That component is used in the layout and is giving me a warning about a circular dependency on the client and server. It works, but I'm not sure how to fix it or if it's an issue. Any ideas?

```
• client
Circular dependency: src/node_modules/@sapper/app.mjs -> src/node_modules/@sapper/internal/App.svelte -> src/routes/_layout.svelte -> src/components/NavigationItem.svelte -> src/node_modules/@sapper/app.mjs
• server
Circular dependency: src/node_modules/@sapper/app.mjs -> src/node_modules/@sapper/internal/App.svelte -> src/routes/_layout.svelte -> src/components/NavigationItem.svelte -> src/node_modules/@sapper/app.mjs
```

This is using Svelte v3 and starting with the v3 Sapper template.

Thank you!

**Comment by Conduitry** [comment]
Yep, this is a known annoyance. It won't cause any problems with your app. We're going to try to rearrange some things so as to not have circular dependencies, but in the meantime this is harmless.

**Comment by evanleck** [comment]
Cool, thanks!

**Comment by bekliev** [comment]
Same thing happens.
Hope, you will make the warnings dissapear soon 😄

**Comment by pngwn** [comment]
These warnings are silenced in the latest sapper-template. You can see the extra config [here](https://github.com/sveltejs/sapper-template/blob/master/rollup.config.js). The function is on line 14. It is added to the config on lines 57, 79, and 95.

**Comment by bekliev** [comment]
@pngwn Oh, thank you man!

**Comment by bekliev** [comment]
@pngwn Hm... I already have it, but the warnings still appear.
You can check out it here (in my forked repo from sapper-template)):
https://github.com/bekliev/sapper-template/tree/bug-circular-dependency-sapper-app

I event didn't change rollup.config.js.
Forked the repo today.

**Comment by Conduitry** [comment]
I had thought the warning messages always used forward slashes in the paths, even in Windows, but apparently not! We're filtering based on whether the message contains `/@sapper/`, which is why this isn't working for you. I'll update sapper-template to also cover `\@sapper\`.
