### ISSUE TITLE
Getting undefined for local variables

### ISSUE THREAD

**Issue by shavyg2** [sveltejs/sapper#639]
I keep getting undefined for some local variables defined with let.

The binding is working because once i type everything seems in order.

```html
<script>
  
  let username = "enter";
  let password = "password";

  function submit(event) {
    const user = {
      username,
      password
    };
    console.log(user);
  }


</script>

<style>
  .login {
    width: 50vw;
  }
</style>



<form on:submit|preventDefault class="login flex flex-col mx-auto my-2">
  <h2>
    Login
  </h2>

  <label>Username {username}</label>
  <input type="text" bind:value="username" />

  <label>Password</label>
  <input type="password" bind:value="password" />
  <input type="submit" value="Submit" />
</form>
```

it renders from the server with the value of undefined, for the username and the password.
Once the client side is loaded i am able to changed the values so the binding is working completely fine.

Is there a difference when i am loading on the server side that i must use in order to get access to variables defined locally?

**Comment by mrkishi** [comment]
What version are you using?

Starting from a current `sapper-template#rollup-v3`, it will first fail to build, but once fixing the bindings (to `bind:value="{username}"`) it works both server and client-side.

**Comment by shavyg2** [comment]
I downloaded the lastest version rollbar-v3 and everything is working.
i was using rollbar as the instructions said in the getting started. 
All my issues are fixed now.
