### ISSUE TITLE
design logo decisions

### ISSUE THREAD

**Issue by vedam** [sveltejs/sapper#640]
#### Hey sveltenians [sapperiours],
because an updated sapper is round the corner, we need to sort out some design-decisions.
In my very first logo-proposal sapper was treated with a separate color (according to the original svelte-sapper-design).

[svelte-sapper-identity-1.1.pdf](https://github.com/sveltejs/sapper/files/3126843/svelte-sapper-identity-1.1.pdf)

In the meanwhile, and as svelte-rebrush keeps going I'm still not sure whether this is the desired/intended approach any more.
Wouldn't we want to bind sapper a bit more (optically) to svelte (i.e. see comparision "the red one")? They're going hand-in-hand anyways, don't they? Same discord-channel, same twitter-account, same github-account. The current logo is the result of the idea of linking.

Or should it be treated as a standalone solution?
Also manifesting this in a different color-scheme?

I made a comparison visualising different approaches:
[sapper-logo-comparison.pdf](https://github.com/sveltejs/sapper/files/3126873/sapper-logo-comparison.pdf)

and a quick rough-n-dirty color-logo-tweak onto the current svelte-site to give an impression (I know, current svelte-content for now):
![sapper-petrol-home](https://user-images.githubusercontent.com/64245/56888940-87964180-6a75-11e9-921e-05765fd4fb71.jpg)
![sapper-petrol-docs](https://user-images.githubusercontent.com/64245/56888941-87964180-6a75-11e9-806c-73f7cea3d3ad.jpg)
![sapper-petrol-blog](https://user-images.githubusercontent.com/64245/56888942-882ed800-6a75-11e9-8538-6608f5d9359f.jpg)
![sapper-red-home](https://user-images.githubusercontent.com/64245/56888955-8fee7c80-6a75-11e9-96ea-5e29c6908c79.jpg)
![sapper-red-docs](https://user-images.githubusercontent.com/64245/56888956-8fee7c80-6a75-11e9-99fa-d814482f3fe1.jpg)
![sapper-red-blog](https://user-images.githubusercontent.com/64245/56888957-90871300-6a75-11e9-9117-9e66a8c3b400.jpg)

**Comment by jSwtch** [comment]
I suggest identifying the theme of the exisiting logo - what is the instant recognition pattern. Take those elements and remix them into something new. I feel like the Vue / Nuxt team did a good job at this (two colours helps). That said I do find there are some friction points with the existing Svelte logo.

**Comment by vedam** [comment]
We're sticking to the original plan.
