### ISSUE TITLE
Make `target` automatic

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#645]
The `<div id="sapper">` here is slightly cumbersome...

```html
<body>
  <div id="sapper">%sapper.html%</div>
  %sapper.scripts%
</body>
```

...especially paired with this in `client.js`:

```js
sapper.start({
  target: document.querySelector('#sapper')
});
```

It'd be nicer if the HTML sent from the server included something like `<sapper-anchor>`, so that we could just do this...

```html
<body>
  %sapper.html%
  %sapper.scripts%
</body>
```

...and this:

```js
sapper.start();
```

Internally Sapper would do something like

```js
const anchor = document.querySelector('sapper-anchor');
app = new App({
  target: anchor.parentNode,
  anchor,
  // ...
});

anchor.parentNode.removeChild(anchor);
```

**Comment by Rich-Harris** [comment]
Just realised that for hydration, the target element can't have anything other than the app HTML, so it would need to be this...

```html
<body>
  <sapper-app>
    <!-- SSR'd HTML goes here -->
    <div id="app">...</div>
  </sapper-app>
  <script>...</script>
</body>
```

...rather than this:

```html
<body>
  <!-- SSR'd HTML goes here -->
  <div id="app">...</div>
  <sapper-anchor/>
  <script>...</script>
</body>
```

That's a sensible thing to do (since at the moment there are no guarantees that the target element doesn't contain additional stuff), but it could potentially affect layout, so it needs some testing. So I won't try and sneak this in to 0.26.

**Comment by antony** [comment]
Solved in Kit
