### ISSUE TITLE
Mp4 in /static doesn't play

### ISSUE THREAD

**Issue by coolemur** [sveltejs/sapper#646]
I put video.mp4 file in /static directory.

When I try to access the file using http://..... /video.mp4 it's not playing.

Any ideas why ?

(images from same directory are accessible)

**Comment by Conduitry** [comment]
What are you using for serving the static assets? There were issues in the past with some browsers refusing to display videos unless they were accessible via partial content / range requests. If you're using the default sapper-template (which uses `sirv` for serving static assets), it looks like that's only relatively recently supported range requests. Can you try updating to the latest (0.4.0)? We'll also update sapper-template to the latest sirv version

**Comment by coolemur** [comment]
I am using default sapper template with rollup (npx degit sveltejs/sapper-template#rollup).

If I update to latest dependencies, I'm getting an error "component cannot have a default export" on most of the scripts.

```
 compression                           ^1.7.1  →   ^1.7.4 
 polka                                 ^0.4.0  →   ^0.5.2 
 sirv                                  ^0.2.0  →   ^0.4.0 
 sapper                               ^0.24.2  →  ^0.25.1 
 svelte                                ^2.0.0  →   ^3.1.0 
 @babel/core                           ^7.0.0  →   ^7.4.4 
 @babel/plugin-syntax-dynamic-import   ^7.0.0  →   ^7.2.0 
 @babel/plugin-transform-runtime       ^7.0.0  →   ^7.4.4 
 @babel/preset-env                     ^7.0.0  →   ^7.4.4 
 @babel/runtime                        ^7.0.0  →   ^7.4.4 
 chokidar                              ^2.0.4  →   ^2.1.5 
 rollup                                ^1.0.0  →  ^1.10.1 
 rollup-plugin-babel                   ^4.0.2  →   ^4.3.2 
 rollup-plugin-commonjs                ^9.1.6  →   ^9.3.4 
 rollup-plugin-node-resolve            ^4.0.0  →   ^4.2.3 
 rollup-plugin-replace                 ^2.0.0  →   ^2.2.0 
 rollup-plugin-svelte                  ^5.0.1  →   ^5.0.3 
 rollup-plugin-terser                  ^1.0.1  →   ^4.0.4 
```

**Comment by Conduitry** [comment]
Those errors are because you're switching from Svelte 2 to Svelte 3. Can you try just updating `sirv`?

**Comment by coolemur** [comment]
It's working with sirv 0.4.0. Thank you.
