### ISSUE TITLE
how do i get access to my route parameter

### ISSUE THREAD

**Issue by shavyg2** [sveltejs/sapper#648]
I am using v3 and it complains if i do default export.
it says query and params doesn't exist so i can't just use them undeclared.
How do i get access to this.

**Comment by MaxMilton** [comment]
Documentation for the latest Sapper updates is still a work in progress. You can follow along with it's progress in https://github.com/sveltejs/sapper/pull/638 .

To get access to the page store, which contains the objects you want, try:

```html
<script>
  import { page } from '@sapper/app';

  $: console.log($page);
</script>

<p>Page URL queries:</p>
<pre>{JSON.stringify($page.query, null, 2)}</pre>
```

Also, the docs about how stores work is over at https://svelte.dev/docs#svelte_store

**Comment by MaxMilton** [comment]
Also worth noting this might be changing with https://github.com/sveltejs/sapper/pull/642

**Comment by Conduitry** [comment]
This has changed in 0.26.0 final, and is described [here](https://sapper.svelte.dev/docs#Stores)

**Comment by jcollum** [comment]
I wish the docs explained it better. I'm doing this: 

```
  import { stores } from '@sapper/app';
  import HighlightedLink from '../components/HighlightedLink.svelte';

  const { preloading, page, session } = stores(); 
  const { host, path, params, query } = page;
  console.log('page values', host,  path, params, query);
```

All the values are undefined. I am trying to get to the value in the url after the `segment` value, like if I am on `/data/abc` I need the `abc` value. Is there a version of `segment` that is an array?

**Comment by CorfitzMe** [comment]
@jcollum `page` is a subscription. Try to change this line:
```
// Add Dollar sign before page variable
const { host, path, params, query } = $page;
```
`host` may still be undefined.. I actually don't know why that is the case, but the rest should be available to you then.

**Comment by jcollum** [comment]
Thanks. I sorted it out and put up  a gist: https://gist.github.com/jcollum/29211cf188c4174d75e2cf1a90b2cb68

**Comment by kepair** [comment]
Following @jcollum gist, this worked for me:
```
<script>
  import { stores } from '@sapper/app';
  const { page } = stores();
  $: console.log($page.path);
</script>
```
Versions:
"sapper": "^0.27.0",
"svelte": "^3.0.0",

**Comment by jokkebk** [comment]
It seems this is made a bit too complex, I wish there was a magic thingy that would make `export let myparam` work in a route `[myparam].svelte`. Alternative to previous:

```javascript
<script context="module">
	export async function preload(page) {
		return {uid: page.params.myparam};
	}
</script>

<script>
	export let myparam;
</script>
```

**Comment by rotimi-best** [comment]
Given this folder structure `playlist/id/video/id/index.svelte` , how do I get the playlist id in `index.svelte`?

**Comment by imCorfitz** [comment]
> Given this folder structure `playlist/id/video/id/index.svelte` , how do I get the playlist id in `index.svelte`?

In your case, you should make sure to use `[` `]` whenever you want to catch your params. 

e.g. `playlist/id/video/[id].svelte` or `playlist/id/video/[id]/index.svelte`
