### ISSUE TITLE
Tests timing issue

### ISSUE THREAD

**Issue by mrkishi** [sveltejs/sapper#666]
While working on #665 everything was working fine locally but travis failed with `ERR_CONNECTION_REFUSED`: https://travis-ci.org/sveltejs/sapper/builds/528601728.

Since no errors were thrown and I have no commit access, I set up travis on my fork to investigate. I needed a push for travis to recognize the branch so I force pushed, and to my surprise, both builds worked.

Now, looking at `AppRunner` I think `puppeteer` may have launched before the server was up and running.

PR incoming.

**Comment by Rich-Harris** [comment]
> I have no commit access

fixed 😀
