### ISSUE TITLE
Remove .DS_Store (etc?) from service worker manifest

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#667]
If the service worker tries to cache `.DS_Store` on installation, installation will fail

**Comment by NetOperatorWibby** [comment]
I'm getting this error after making changes to my Sapper app:

```
Service worker event waitUntil() was passed a promise that rejected with 'TypeError: Cache got basic response with bad status 404 while trying to add request http://localhost:PORT/.DS_Store'.
```

How do I get it to ignore `.DS_Store`?

**Comment by benmccann** [comment]
Closing this per the discussion in https://github.com/sveltejs/sapper/pull/1095
