### ISSUE TITLE
Seperating html and js file to create svelte file/component

### ISSUE THREAD

**Issue by shavyg2** [sveltejs/sapper#672]
I started using svelte and one of the biggest drawback i have seen from using it, is that with the svelte file i am not really able to use all of the tooling that i am use to, mainly typescript.

So i create a little cli that would join my html and js file to create a svelte file.
https://bitbucket.org/shavyg2/svelte-ts-compiler
No documentation available but the source is.

The reason i did this is that now i can have: 
```
page.html
page.js
```

once this runs through the cli tool it creates a .svelte file.

The good thing about this is that i can now use typescript to create all the logic that i want to with types support / correct imports and syntax highlighting

This is similar to C#
page.xaml and page.xaml.cs

so if you have
```
src/routes/home.js
src/routes/home.html
```

once you run the application this would create the page by looking at the html and the js file.

I have found this productive.

issue is sapper also treats html files just like svelte file

so for my cli i had to place the files in a different folder so it doesn't error, i have conflicting files.
src/page

when i run
```
sveltec --src src/page --dist src/routes
```

this watches and creates my svelte file in routes directory.

If sapper would support this out the box it would be awesome as i would be able to create a svelte file
or a seperated html and js/ts

the files could event be named
page.html and page.html.js

Integrating typescript support would be come much easier and all of the vscode features we love would be available.

**Comment by shavyg2** [comment]
this is true, i have been using
```
<script context="module">
```

inside the html as this is still valid html and also typescript stripes unused variables
so i have been using my imports inside the module script tag as well.

I am really liking svelte, i just don't know if giving up on all the tooling javascript/typescript has developed and not being able to use them is really a direction that is beneficial?

When i have all of the js/ts features i am use to and using svelte it just feels so much better.

Auto complete, automatic import with vscode and vs-code-import plugin, refactoring, move code to a different file.
having all my import statements update automatically as i move my files.

having the problems tab in vscode show me where there is an issue.

ts lens showing me what functions/ variables are not used?

Just a thought

**Comment by benmccann** [comment]
We have TypeScript support now, so I think this has been addressed
