### ISSUE TITLE
Client side doesn't have hot reload

### ISSUE THREAD

**Issue by shavyg2** [sveltejs/sapper#675]
let me know if this is the correct repo to post this or if i should move it to the template

https://github.com/sveltejs/sapper/blob/master/sapper-dev-client.js#L6

module.hot is undefined.

I think this is because of this

https://github.com/sveltejs/sapper-template/blob/79be87c3f5cb90ee1afb2561965597f9e4273d26/webpack.config.js#L25

**Comment by Conduitry** [comment]
As noted in the comment, webpack HMR isn't working in Svelte v3 pending that issue and some hooks provided by the compiler to enable it.

**Comment by shavyg2** [comment]
Ye I am saying that the JavaScript errors because hot is not defined. Are you saying it doesn't matter because there is no hot module reloading regardless?

**Comment by jcollum** [comment]
He's saying use rollup instead of webpack until they fix that bug https://github.com/sveltejs/svelte/issues/2377

**Comment by TrungRueta** [comment]
@jcollum you can just use webpack but disable hot-replacement feature in sapper.
open package.json, at line `dev: "sapper dev"` change to `dev: "sapper dev --no-hot"` to disable hot reload.
Sapper will auto use `live reload` when `hot reload` disabled, and from now on it work 100% same as rollup setup.

**Comment by jcollum** [comment]
Getting rollup going wasn't any big deal.

**Comment by TrungRueta** [comment]
rollup has not hot-replace feature, it only has live-reload, so issue not raised in rollup like webpack

**Comment by antony** [comment]
Closing this since there is an active effort on Svelte to get HMR working which will solve this.
