### ISSUE TITLE
Documentation: Be clear about reactivity of props declared in module context

### ISSUE THREAD

**Issue by antony** [sveltejs/sapper#679]
This was a huge stumbling block for me. From the documentation here:

https://svelte.dev/tutorial/module-exports

it looks like this might work:

```javascript
{date}

<script context="module">
let date
async function preload () {
  date = new Date()
}
</script>

<script>
someMethod () {
  date = new Date()
}
</script>
```

But if you run that, you find that date isn't updating in the UI.

I noticed the example here returns a set of values:

https://sapper.svelte.dev/docs#Preloading

It isn't clear though, where the value `articles` ends up, or why it is being returned in a hash rathe r than assigned.

I had to look at the code here:

https://github.com/sveltejs/sapper-template/blob/master/src/routes/blog/%5Bslug%5D.svelte

To determine that you should export the `post` declaration, and return post as a hash within your preload method. You can then happily see it as a reactive property inside your UI.

It ends up like this:

```javascript
{date}

<script context="module">
export async function preload () {
  return { date: new Date() }
}
</script>

<script>
export let date

someMethod () {
  date = new Date()
}
</script>
```

I don't think this is clear from the current documentation (at least, not in one single place), and therefore could be improved to detail the steps required for declaring a reactive property which is prefilled by preload, and dynamically updated on change.

Sorry if I've not explained this well!

**Comment by jobelenus** [comment]
Seeing this issue just cleared up my understanding. It was unclear how variables in the "script=module" were being "passed/received" in the other script block that interacts with the rest of the component. Understanding that preload relies on a map name matching a variable helps a lot and removes that "this is magic" feeling.

**Comment by staus** [comment]
I don't get it, this just doesn't work for me
```javascript
<script>
  export let content
</script>

<script context="module">
  export async function preload() {
    return { content: 'yo' }
  }
</script>

{content}
```
Any idea of what I'm doing wrong?
It always returns `undefined`. Your breakdown was very helpful otherwise @antony . This is really lacking documentation

**Comment by jobelenus** [comment]
Hrm, I have two differences. One, the script=module is the first script
block, though I'd be surprised if that mattered(?). Second, my preload is
not an async function, but it is returning a promise, so that should not
matter either.

**Comment by staus** [comment]
One small progress I've had is, that it seems to work when I run it in `_layout.svelte`. Maybe I've missed some basic logic that preload won't work from within nested components or something?

**Comment by jobelenus** [comment]
Oh, where is that code living? Maybe only pages get `preload` and not
components... *that* would make sense to me.

**Comment by staus** [comment]
Yeah my code was living within a chunk of the page. It's a long page with 3 different sections, so within each I was thinking to do a preload of their content. Your preloads are at the top level? I'm ok with a limitation like this. Just a little bit difficult to figure it out

**Comment by jobelenus** [comment]
Mine are working on a page, index.svelte

**Comment by staus** [comment]
So weird, I can't get it to work from index.svelte eitehr. Anyway, I put the results in the store and can then access it from the rest of the project. There shouldn't be any drawbacks in that for me as I just need it for the server side rendering of my static cms pages.

**Comment by antony** [comment]
This got me again when I did a small refactor. Whoosh!

**Comment by pngwn** [comment]
This was an issue with the Svelte documentation rather than Sapper. The documentation was updated to mention that values in `context="module"` scrips are not reactive in https://github.com/sveltejs/svelte/pull/3127.

Is there anything else that needs clarifying in the Sapper documentation?

**Comment by Conduitry** [comment]
I don't think so. Maybe if there's other, less reference-y Sapper documentation it would make sense to gently remind people about how Svelte works - but I don't think that sort of thing belongs in the Sapper docs as they exist today.

**Comment by pngwn** [comment]
Okay, great. I'll close this then. If anyone thinks the Sapper or Svelte docs need more clarification they can open a new issue in the relevant repo.

**Comment by rotimi-best** [comment]
> This was an issue with the Svelte documentation rather than Sapper. The documentation was updated to mention that values in `context="module"` scripts are not reactive in [sveltejs/svelte#3127](https://github.com/sveltejs/svelte/pull/3127).
> 
> Is there anything else that needs clarifying in the Sapper documentation?

OMG. This just cost me hours and almost made me start questioning why I am learning svelte, cause I know I could have done this in react a long time ago. phew... I just looked at my script tag and saw the `context="module"`
