### ISSUE TITLE
Support to customize sapper.head and sapper.style to enable AMP pages development

### ISSUE THREAD

**Issue by maulshh** [sveltejs/sapper#687]
Hi all, I'm about to create AMP pages using sapper, in which it couldn't be done unless I tinker with these lines of code in sapper node_modules:

adding `amp-custom` in 
```
styles = (css && css.code ? `<style amp-custom>${css.code}</style>` : '');
```

https://github.com/sveltejs/sapper/blob/master/runtime/src/server/middleware/get_page_handler.ts#L314

and removing `noscript` tags from sapper.head
```
const body = template()
	.replace('%sapper.head%', () => `${head}`)
```

https://github.com/sveltejs/sapper/blob/master/runtime/src/server/middleware/get_page_handler.ts#L324

As I look around, there is no hook middleware functions to alter the rendered html in sapper, and there is no configuration to exclude or customize the rendered output for the style and head in the template.html

I think it would be very nice if there were a way to achieve this. :)

**Comment by jeffreycahyono** [comment]
Hi I also need to create both AMP and non AMP pages with Sapper. Is there any followup on doing this with sapper?

**Comment by skdigital** [comment]
Yes please, in line with nextjs!

**Comment by antony** [comment]
This would be useful to me, too - not for AMP, but because I have some tracking tags that absolutely have to be added in the template. It would be great to be able to interact with how the template is rendered.

**Comment by benmccann** [comment]
SvelteKit (Sapper's successor) has AMP support: https://github.com/sveltejs/kit/blob/master/documentation/docs/12-configuration.md#amp
