### ISSUE TITLE
sapper export: "UnhandledPromiseRejectionWarning: Error: Cannot add to a closed queue"

### ISSUE THREAD

**Issue by btakita** [sveltejs/sapper#689]
This is due to not waiting for all requests to finish in a promise.

See https://github.com/sveltejs/sapper/blob/master/src/api/export.ts#L176

**Comment by halfnelson** [comment]
This was clobbered by https://github.com/sveltejs/sapper/pull/641
the older code use `q.add` which allowed q.close to do the promise.all.

**Comment by kmelve** [comment]
We're hit by this as well, making it impossible to deploy [our starter] on Netlify as a static site. It can be reproduced by deploying it [through sanity.io/create](https://www.sanity.io/create/?template=sanity-io%2Fsanity-template-sapper-blog).

It seems that async stuff in `prefetch` is the culprit? E.g https://github.com/sanity-io/sanity-template-sapper-blog/blob/master/template/web/src/routes/blog/%5Bslug%5D.svelte

**Comment by btakita** [comment]
@kmelve I manually go into the sapper source & [modify](https://github.com/btakita/sapper/commit/a1648345c84b8bccdc92f534b07cff317a3564cd) the `_export` function to make the export work for now. Hopefully this will be fixed soon.

**Comment by btakita** [comment]
I created a temporary version that fixes this issue & https://github.com/sveltejs/sapper/issues/688

Use the following in your `package.json`

`"sapper": "btakita/sapper#0.27.0-fixes"`

**Comment by btakita** [comment]
I created a temporary version that fixes this issue & #688

Use the following in your package.json

"sapper": "btakita/sapper#0.27.0-hotfix"

**Comment by kmelve** [comment]
Excellent @btakita – tnx 🙌

**Comment by antony** [comment]
@kmelve I also believe there is an issue in the default configuration for the deployed app in your sapper starter - even with this hotfix the deploy will fail.

To deploy correctly you need to change the deploy directory from `__sapper__/export` to `web/__sapper__/export`.
