### ISSUE TITLE
Router API

### ISSUE THREAD

**Issue by ansarizafar** [sveltejs/sapper#69]
Please provide Router API for defining routes with code. I personally don't like directory structure based routing. NuxtJs stated with directory based routing but now, NuxtJs also provides a Router API for defining routes.

**Comment by Crisfole** [comment]
I believe that's where the top level server.js file comes in:

Do whatever you want. It's an Express app

**Comment by ansarizafar** [comment]
I am talking about page routes. I also feel that templates folder is also unnecessary, 4xx/5xx routes can also be defined with the router Api.

**Comment by Rich-Harris** [comment]
As of 0.7, 4xx and 5xx routes are just pages in your `routes` directory, and there's a single `app/template.html` file.

Can you be more specific about what kind of API you envisage? One idea is to expose Sapper's internal page rendering API in a way that server routes can use: https://github.com/sveltejs/sapper/issues/137#issuecomment-367731274
