### ISSUE TITLE
Sapper doc hash links not working

### ISSUE THREAD

**Issue by dbrudner** [sveltejs/sapper#696]
My friend Paul noticed this when browsing the sapper docs (https://sapper.svelte.dev/docs) yesterday.

Most (maybe all) of the links that are prefixed with a hash "#" in the docs are broken. It seems like they're lowercase while their intended destinations are capital-cased with underscores or something similar. I was going to open a PR to fix this by changing the actual hashes in the markdown files, but I'm not sure this is the best solution, it looks like it might be easier to modify the site-kit's make_session_slug_processor function (https://github.com/sveltejs/site-kit/blob/master/utils/slug.js#L59), or something similar (didn't explore too much, just alluding to the possibility of a solution other than directly modifying the markdown).

Anyway, sorry for writing all this. Paul told me that "I'm sure project maintainers love receiving issues like this," but I don't care what Paul says, he's an idiot. Thanks for your time.

**Comment by Conduitry** [comment]
These have been fixed on master, but for the time being the site will need to be manually redeployed by Rich.
