### ISSUE TITLE
Preload all Route assets

### ISSUE THREAD

**Issue by lukeed** [sveltejs/sapper#70]
Taken from: https://github.com/sveltejs/sapper/blob/master/lib/index.js#L148

At the very least, styles should be preloaded via the server. I'd argue that fonts & co should be set as a `<link rel=preload/>` by the user from within the template... but the server should send down the bare minimum assets.

**Comment by antony** [comment]
@lukeed the original code for this is gone, so it's difficult to understand the issue.

Was the goal that things like styles and client js should have a rel="preload" attribute? Somebody was suggesting this the other day in chat.

**Comment by lukeed** [comment]
Yup. Fail on my part for linking to master

**Comment by benmccann** [comment]
This sounds like a duplicate of https://github.com/sveltejs/sapper/issues/408

I actually have a PR pending https://github.com/sveltejs/sapper/pull/1269 that will preload the JS, which has been pretty impactful in my testing. I haven't looked at anything beyond that though like CSS, etc.
