### ISSUE TITLE
Global variables

### ISSUE THREAD

**Issue by arttemiuss43** [sveltejs/sapper#702]
Is there any official way to declare and use global variables without importing anything in every component? For instance via prototype like Vue does. Or should we use the stores?

**Comment by Conduitry** [comment]
If they're static things you can define once at compile time, there's rollup-plugin-replace, or whatever the equivalent webpack loader is. Or, if you need global variables that you actually do need to read and write from multiple places, and you don't want to import them everywhere, you could use actual global variables.
