### ISSUE TITLE
Export failed with big data

### ISSUE THREAD

**Issue by arttemiuss43** [sveltejs/sapper#714]
When I export site with more than ~650 pages I have the following error:
```
UnhandledPromiseRejectionWarning: Error: Timed out waiting for http://localhost:3000/blog/title-656
```
After about 40 such errors command fails with exit code 1. 

Is Sapper able to export a big site?

**Comment by bwbroersma** [comment]
After some issues #604 (#641 #690 #698) stuff should work.

I've a project [Allmanak](https://github.com/openstate/allmanak/) with Sapper `0.27.1` which daily builds 22.000+ pages and does some [post processing](https://github.com/openstate/allmanak/blob/master/app/postexport.sh) plus some [nginx mapping](https://github.com/openstate/allmanak/blob/master/nginx/shared/http.conf) and [redirecting](https://github.com/openstate/allmanak/blob/master/nginx/shared/static.conf) based on fixed identifiers.
So `https://www.allmanak.nl/1/Old_name` will redirect to `https://www.allmanak.nl/1/Algemene_Rekenkamer/` which wouldn't be possible with just directories.

**Comment by Conduitry** [comment]
As noted, there have been a number of recent fixes in this area. Please re-open if you are still having problems with the latest version.
