### ISSUE TITLE
Importing commonjs modules: require is not defined

### ISSUE THREAD

**Issue by dmitrykrylov** [sveltejs/sapper#724]
I'm trying to use Prismic headless CMS with Sapper but getting an error when importing `prismic-javascript` module:
```javascript
<script context="module">
  import Prismic from "prismic-javascript";
  // .... It's already doesn't work
</script>
```

Seems that it happens because of rollup configuration of the sapper-template and incorrect setup of `rollup-plugin-commonjs`. The related issue with the possible solution (reordering rollup plugins) is here
https://github.com/rollup/rollup-plugin-commonjs/issues/239

I tried to change the order of plugins, but still can't get it working. How can we actually fix it?

**Comment by dmitrykrylov** [comment]
UPD. I solved the problem with adding a parameter to client rollup config: `resolve({ browser: true }),`

**Comment by skdigital** [comment]
Having the same issues...uff

**Comment by skdigital** [comment]
My clients rollup is already set to browser true. I am still getting an error.

**Comment by skdigital** [comment]
I am getting this as an error now, if I import it normally as per your example 

`The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, a
nd has been rewritten
463:   };
464:   self.fetch.polyfill = true;
465: })(typeof self !== 'undefined' ? self : this);`

**Comment by niklasgrewe** [comment]
i also still have this error. my clients rollup is also already set to browser true...

**Comment by brancusi** [comment]
Sample issue here any solutions on this?
