### ISSUE TITLE
sapper export creates mailto route from <a href='mailto:xxx'>

### ISSUE THREAD

**Issue by ispyinternet** [sveltejs/sapper#725]
As per title!

**Comment by Conduitry** [comment]
Actually, taking a look at this now, and I can't reproduce it. It also looks like [this shouldn't happen](https://github.com/sveltejs/sapper/blob/9dd63ab760cf225dee7b999e454b2786fef0eeb5/src/api/export.ts#L189). Do you have a repro?

**Comment by ispyinternet** [comment]
tbf, its probably down to bad html. This html (which works in a browser) will cause the issue:

```
<a href="mailto:?subject=create your subject&body=make your href
split over 2 lines">test@email.com</a>
```
