### ISSUE TITLE
Issue #717 with nested basepath causes "EISDIR: illegal operation on a directory" 

### ISSUE THREAD

**Issue by ludwigschubert** [sveltejs/sapper#728]
When specifying a nested basepath (`/nested/basepath`) in the middleware config in `server.js` and as an argument to `sapper export`, the export fails with:

```
> Crawling http://localhost:3000/nested/basepath/
       9 B   (404)
> EISDIR: illegal operation on a directory, open '/Users/ludwig/code/sapper-template/__sapper__/export/nested/basepath'
```

This may be related to @Conduitry 's #717. I can reproduce by following [the instructions for base paths from the docs](https://sapper.svelte.dev/docs#Base_URLs). (See [this fork](https://github.com/ludwigschubert/sapper-template/commit/1b59d92b2547f052ffdd6428056b7514d8a4ad23) if needed.) I only observe this behavior for basepaths with more than one level.

I'd love to help this get fixed—lmk if there's something specific I can do to help! :-)

**Comment by Conduitry** [comment]
It looks like this issue isn't specific to exporting. `npm run dev` returns a 404 for http://localhost:3000/nested/basepath/ as does running the build produced by `npm run build`.

**Comment by Conduitry** [comment]
Part of this is a Polka issue - https://github.com/lukeed/polka/issues/36 - which has been fixed in that project's latest prereleases - but there is some other stuff going on as well it seems like.

**Comment by Conduitry** [comment]
I was making a dumb mistake, I don't think there's another bug going on anymore.

@ludwigschubert Can you try this again, upgrading Polka to 1.0.0-next.4?

**Comment by timbarclay** [comment]
I'm having this issue too with even a single base path, not just nested ones. I've tried updating Polka to 1.0.0-next.4 but doesn't seem to make any difference. I only get the issue when using `npm run export`.

My repo is at https://gitlab.com/timbarclay/ayreon-browser though it's basically just the sapper scaffold project with the basepath changed so I can get it to work with Gitlab pages.

**Comment by timbarclay** [comment]
Ah, I've just re-read the OP and looked again at the docs. It seems like adding the --basepath argument to `sapper export` does the trick. So no problem here after all.
