### ISSUE TITLE
Should sapper CLI warn about unknown arguments?

### ISSUE THREAD

**Issue by ludwigschubert** [sveltejs/sapper#729]
I just ran `sapper export --basename […]` a bunch of times before noticing I wanted `basepath` instead.

**Comment by Conduitry** [comment]
In a quick skim through the Sade readme I didn't see anything that would automatically support this - @lukeed is this currently possible? Or does the `opts` argument to an action get the entire object of options - including unknown ones - and we could throw an error at that point?

**Comment by lukeed** [comment]
It's available [through `mri`](https://github.com/lukeed/mri#optionsunknown), which is accessible through `sade.parse` options.

**Comment by lukeed** [comment]
Forgot to address the other half of question sorry (😴was still waking up)

I improved `sade` & `mri`'s coordination for `opts.unknown` handling. Tagged a new `v1.5.0` on sade's side of things as it will now print your custom (or its default) message when an unknown flag was found. Check out the [new docs](https://github.com/lukeed/sade#optsunknown) and/or the [release notes](https://github.com/lukeed/sade/releases/tag/v1.5.0).

If you don't define an `unknown` handler, then all arguments are parsed & passed thru to the command. That part is unchanged

**Comment by Conduitry** [comment]
Fixed in 0.27.5.

**Comment by Conduitry** [comment]
We had to revert this because of `--legacy` being seen as an unknown option. Reopening this. I think this is a bug in Sade but will need to investigate later.

**Comment by Conduitry** [comment]
Re-fixed in 0.27.8

**Comment by lukeed** [comment]
https://github.com/lukeed/sade/commit/ec5e06ddf8caf5e94c9c2d6a2138ee30eb311c78

**Comment by alexdilley** [comment]
I use [dotenv-flow](https://www.npmjs.com/package/dotenv-flow) which can interpret a `--node-env` switch passed to node scripts. Following this change, it's now not possible to pass this argument. I can work around `dotenv-flow` but I just wanted to flag that you may possibly receive noise because of this change since it may not be unusual to want to pass arbitrary options for interpretation by third-party libs.

**Comment by pngwn** [comment]
I don't think it is Sapper's responsibility to handle this case as it comes at the cost of User Experience for Sapper users as in the example listed in this issue. I don't think that passing arbitrary arguments to a CLI would generally be expected to work nor do I believe it is a common practice with Sapper (I could be wrong, but most people probably don't even touch the scripts at all). We can add information about unknown props to the Sapper docs, dealing with any other support issues as they occur shouldn't be a problem.
