### ISSUE TITLE
Cannot run production build in Docker container

### ISSUE THREAD

**Issue by Xchos** [sveltejs/sapper#734]
Hi guys,

I am facing problem. I am trying to run docker container using ECS at AWS. The container always stops with this error:

```
> TODO@0.0.1 start /app
> node __sapper__/build
internal/modules/cjs/loader.js:638
throw err;
^
Error: Cannot find module '/app/__sapper__/build'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
at startup (internal/bootstrap/node.js:283:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TODO@0.0.1 start: `node __sapper__/build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TODO@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

i am using this `Dockerfile`

```
FROM node:10.16.0-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --production

FROM node:10.16.0-alpine
WORKDIR /app
COPY --from=0 /app .
COPY . .

EXPOSE 3000
CMD ["npm", "start"]
```

and this `.dockerignore`:

```
!/Dockerfile
!/package.json
!/package-lock.json
!/__sapper__
/__sapper__/*
!/__sapper__/build
!/static
!/content
```

After build `/app/__sapper__/build` exists. Also if I enter docker container using `docker -it run containerName /bin-bash` i can see all files are presented and if i use npm start everything works just fine with this output:

```
/app # npm start

> TODO@0.0.1 start /app
> node __sapper__/build

Starting server on port 3000
```

Anyone knows how to solve this problem (using `webpack` version)?
Thanks for your advice.

**Comment by Conduitry** [comment]
That `Dockerfile` will only build the Docker image if the Sapper app has already been built. (In the Svelte site, there's a [`Makefile`](https://github.com/sveltejs/svelte/blob/master/site/Makefile) that's responsible for building the app.) Are you sure during your deployment that the Sapper app is getting built before the Docker image is? In the Docker image, what do you have in `/app`?

**Comment by Xchos** [comment]
You hit the nail on the head. Thank you for helping out.

**Comment by resourceldg** [comment]
how did they solve it...
