### ISSUE TITLE
Document sapper-noscroll

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#737]
https://github.com/sveltejs/sapper/issues/376

**Comment by vladejs** [comment]
Is this available on sapper 0.25?
What about `goto('?q=foo', { scroll: false })`

**Comment by Conduitry** [comment]
[Yes.](https://github.com/sveltejs/sapper/issues/376#issuecomment-427535933)

[No.](https://github.com/sveltejs/sapper/pull/613)

**Comment by flayks** [comment]
+1 on @vladejs comment, this option on the `goto()` function would be very helpful!

**Comment by Ashot-KR** [comment]
will `scroll` option for `goto` function be implemented?

**Comment by Jayphen** [comment]
> will `scroll` option for `goto` function be implemented?

Yes, my PR for it has just been approved. It should be coming soon.
