### ISSUE TITLE
Equivalent of onload for Sapper-loaded pages

### ISSUE THREAD

**Issue by freedmand** [sveltejs/sapper#74]
Is there an easy event handler for when Sapper navigates to and loads a page?

For my particular use case, I'm lazy loading images and swapping a blurry image src with a more detailed image src after the document has loaded. This works great using window.onload when I initially navigate to the page or hard refresh, but when navigating from another page within my Sapper app, the onload method is never called. Is there a Sapper equivalent for onload?

**Comment by EmilTholin** [comment]
Hi @freedmand! If I understand you correctly, you [might be talking about this?](https://github.com/sveltejs/sapper/issues/30)

**Comment by freedmand** [comment]
That's exactly it - thanks! I'll close this issue as it's a duplicate of #30.
