### ISSUE TITLE
session option in sapper.middleware does not support Promise

### ISSUE THREAD

**Issue by hitochan777** [sveltejs/sapper#740]
I want to return promise in session option of sapper.middleware. But if I got an error saying 
`Failed to serialize session data: Cannot stringify arbitrary non-POJOs`. It seems that the session option does not support promise. Is there any workaround?

```javascript
polka()
  .use(
    sapper.middleware({
      session: async (req, res) => {
        const obj = await get_some_obj();
        return obj;
      }
    })
  )
```

**Comment by Conduitry** [comment]
I don't _think_ there's a technical reason for this. It looks like we should be able to add an `await` [here](https://github.com/sveltejs/sapper/blob/8baf694e6d80d4ebe2ecdc705397ee19be85d490/runtime/src/server/middleware/get_page_handler.ts#L91). I don't know whether there'd be some other reason not to do this.

**Comment by diurivj** [comment]
This doesn't work yet

**Comment by Catsvilles** [comment]
> I don't _think_ there's a technical reason for this. It looks like we should be able to add an `await` [here](https://github.com/sveltejs/sapper/blob/8baf694e6d80d4ebe2ecdc705397ee19be85d490/runtime/src/server/middleware/get_page_handler.ts#L91). I don't know whether there'd be some other reason not to do this.

In my case I would like to return a promise and pass it to the next component so I can do something like:
{#await promise}
	<Skeleton /> //any kind of loading indicator
{:then res}

Am I'm implementing this wrong? I saw this kind of examples in Svelte's documentation, so I believed this is a good way to do a loader.
