### ISSUE TITLE
Page routes, server routes and status codes

### ISSUE THREAD

**Issue by mrkishi** [sveltejs/sapper#75]
We're currently missing a sensible way to manipulate non-standard _page route_ responses: not founds, redirects and so on.

A `/blog/[slug].html` has no way to return a 404 or 301 depending on the slug -- you'd have to handle it client-side upon initialization.

I'm just getting started with sapper, but here are some ideas that might or not work:

- _Server routes_ could be able to render _page routes_

    `/blog/[slug].js` could then either perform something non-standard or render a `/blog/_[slug].html` page route.

- _Server routes_ could take precedence over _page routes_

    Currently, you can't have both `/blog/[slug].js` and `/blog/[slug].html`. If that was allowed, the server route could have first shot at serving the url, defaulting to the page route otherwise. This would be a more organized version of handling certain urls with `express` above `sapper` middleware. Not exactly pretty.

- _preload_ could have knowledge about response codes

    Instead of only returning data, `preload()` could optionally expect more info about the response, eg. `{ data: {}, status: 301, redirect: '/bleh' }`. This would be handled automatically by sapper both at the server ("SSRing" redirects and 404s) and the client (automatically triggering routes).

    I don't know if that's giving `preload` too much power, but I think it's worth exploring things in that direction. If not `preload`, a similar feature.

    It'd be nice to handle auth this way, too (imagine [RealWorld's settings](https://github.com/sveltejs/realworld/blob/4d3afe1be4b2547a654352a1a3051e8e84df816b/routes/settings/index.html#L40) page redirecting to login by simply changing `preload` a bit, without client/server differences).

Thoughts?

**Comment by necrodome** [comment]
@Rich-Harris any suggestions how to handle this?

**Comment by thgh** [comment]
If `preload` returns a rejected Promise, that could be used as a signal to show an error page instead.

**Comment by Rich-Harris** [comment]
As of 0.7, it's possible to redirect and error inside `preload`:

```js
preload({ params }) {
  if (!loggedIn) {
    return this.redirect(301, '/login');
  }

  if (!isValid(params.id)) {
    return this.error(404, 'Not found');
  }

  return fetch(...).then(...);
}
```
