### ISSUE TITLE
Use fetch in server's authentication middleware

### ISSUE THREAD

**Issue by pnmcosta** [sveltejs/sapper#752]
Hi,

I'm new to sapper and svelte, I'm trying to implement a "relayed" authentication to a API, here's what I got so far:

```
polka()
  .use(
    compression({ threshold: 0 }),
    async (req, res, next) => {

      try {
        // fetch is not exported by sapper! :(
        const res = await sapper.fetch(`${BASE_PATH}/get-user`, { credentials: 'include' });
        if (res.status === 200) {
          const user = await res.json();
          req.user = user;
        }else if(req.path !== '/login') {
          return redirect(req, res)
        }
      } catch (e) {
        console.log(e);
      }

      next();
    },
    sirv('static', { dev }),
    sapper.middleware({
      session: (req, res) => ({
        user: req.user
      })
    })
  )
  .listen(env.APP_PORT, err => {
    if (err) console.log('error', err);
  });
```

This is part of a port i'm doing of a React boilerplate to Svelte/Sapper, see https://github.com/pnmcosta/saas-boilerplate, the API handles the authentation and authorization, I'm trying to make a request to `myapy.domain.com/get-user` using the current request cookies/headers.

Would I be able to reuse https://sapper.svelte.dev/docs#this_fetch from here? Could `@sapper/server` export the fetch method, like it does for the middleware?

Thanks,
P.

**Comment by vladejs** [comment]
I believe you're trying to achieve what passport.js and it's local strategy does for you.

In my case I use passport-local-mongoose to serialize / deserialize the user automatically.

Also, a question. Does redirect correctly redirects you to the given page?

**Comment by pnmcosta** [comment]
> I believe you're trying to achieve what passport.js and it's local strategy does for you.

It's already doing that on the API side, it actually supports tokenless and google auth with passport, see https://github.com/pnmcosta/saas-boilerplate/blob/master/api/server/auth.ts for more reference.

On the APP side (the sapper app) I need to get the user info from `${API_PATH}/get-user` that is a json response with a valid user object.

> In my case I use passport-local-mongoose to serialize / deserialize the user automatically.
Serialization / deserialization has already been done on the API site, the APP should only consume the API and not connect to the database.

Ideally I'd like to have `session.user` populated from the request above, in the sapper components `preload` method, https://sapper.svelte.dev/docs#Preloading so I though reusing the `fetch` method would be neat. I guess I'm just going to use `node-fetch` and manually send the headers as necessary.

**Comment by vladejs** [comment]
I believe that just putting session.user in the header won't suffice.
According to documentation, you must Seed session data (
https://sapper.svelte.dev/docs#Seeding_session_data) from the sapper
midleware.

On preload, session is not a response header, but a server hydrated store
(I think)

>

**Comment by pnmcosta** [comment]
Precisely what I was trying to accomplish with the code above, if you notice the middleware is being initiated with the user from the request.

What is not working yet, is the `fetch` being done on the custom middleware above that.

**Comment by vladejs** [comment]
In my experience, what no worked for me was the persistence of the user  in
the req  object.

I ended up serializing the user in a cookie and accessing the cookie in the
sapper Middleware.

If you console.log the user in your implementation what do you get?

**Comment by pnmcosta** [comment]
i think you're misunderstanding my question, I'm actually wondering about the possibly of the generated sapper module `import * as sapper from '@sapper/server'` to actually also export the internal `fetch` method, so that I could use it in the custom auth middleware.

now in closer inspection, I don't think the internal fetch method will work for me because of how it parses urls and I believe expects the same base path from `127.0.0.1`, see https://github.com/sveltejs/sapper/issues/489, so I'll actually implement a custom wrapper for the API using `node-fecth` anyway.

> In my experience, what no worked for me was the persistence of the user  in the req  object.

Seems to work fine for me, I just tested the code below and it worked as expected:

```
polka()
  .use(
    compression({ threshold: 0 }),
    async (req, res, next) => {
      req.user = { id: 1, name:'foo'};
      next();
    },
    sirv('static', { dev }),
    sapper.middleware({
      session: (req, res) => ({
        user: req.user
      })
    })
  )
  .listen(env.APP_PORT, err => {
    if (err) console.log('error', err);
  });
```

I have access to `session.user` on preload:

```
<script context="module">
  export function preload(_, { user }) {
    console.log('current user: ', user);
  }
</script>
```

**Comment by pnmcosta** [comment]
Closing cause on further inspection using the internal `fetch` is not ideal for my scenario, however it could be for others, but be aware that it should only be used for internal requests (same domain).

**Comment by MatthiasGrandl** [comment]
So does this not work? I'd hate to add another dependency for no reason.
