### ISSUE TITLE
`ReferenceError: fetch is undefined` in component

### ISSUE THREAD

**Issue by TimothyDespair** [sveltejs/sapper#753]
I am almost certain this is something I'm doing wrong and not something wrong, still finding my way around sapper, I'm using the RealWorld example as a rough guide to implementing a basic crud interface. I've got a component called `ProductList` which is more or less equivalent to `ArticleList` in the RealWorld app.

Rather than calling `api.get()` in the example I'm just calling `fetch()` like so:
```js
$: currentPage =
    $page.params && $page.params.page
      ? +$page.params.page - 1 : 0;
  $: {
    const endpoint = 'products'
    let params = `limit=${page_size}&offset=${currentPage * page_size}&valid=${valid}`;

    query = `/api/${endpoint}?${params}`;
  }
  $: query && getData();

  async function getData() {
    products = null;
    let results = await fetch(query);
    products = results.json();
  }
```

This is throwing an unhandled promise rejection on the server, which I don't understand. By my understanding this is client side code, I get that node doesn't implement `fetch()` so it would throw an error, is this an SSR thing? I didn't think I even had SSR enabled. I'm building off of `sapper-template` does it do SSR out of the box?

If so, is there a best practice here in terms of populating this server side? If not hints as to what's going on are greatly appreciated. I've used the same api in a prefetch version with `this.fetch()` and that's working fine, just trying to find the solution to this for pagination. The api is just a `product.json.js` route in sapper if that changes anything.

Sorry if this is something patently obvious going straight over my head. I've been trying to work it out for half an hour or so, thought it wouldn't hurt to ask.

**Comment by hitsthings** [comment]
> I'm building off of sapper-template does it do SSR out of the box?

Yes

> If so, is there a best practice here in terms of populating this server side?

Check out the [Preloading](https://sapper.svelte.dev/docs#Preloading) feature. You can use `this.fetch` from within preload and it'll generally behave as expected.

**Comment by TimothyDespair** [comment]
I used preloading in an original version where everything happened on the page with no components and that worked great, but this is a non-page component. (Like `ArticleList` in the RealWorld example.) According to docs (and my trying just now to add preloading to the component) preloading is only supported for pages not components.

Should I be preloading and handling requests in the page and passing data into components instead? (That kind of makes more sense in some ways.) I just kind of took for granted that the RealWorld example calling the API from the component was probably best practice on that front.

**Comment by larrikinventures** [comment]
> Should I be preloading and handling requests in the page and passing data into components instead? 
I think that's the general idea for ssr to avoid too many requests.

> is there any context variable available inside script tags to just skip fetch server side and let the client render and call the API?
The Sapper template uses webpack or rollup with a predefined value for `process.browser`, so you could `if (process.browser) {...}`. You could also put code in `onMount` and then it'll only run client-side. I'm not a committer here, so others could easily have better options.

**Comment by TimothyDespair** [comment]
Ah, `process.browser` seems obvious now! Easy to forget familiar stuff in a new context.

Thanks for the help guys!
