### ISSUE TITLE
onload doesn't work on production build

### ISSUE THREAD

**Issue by jdesrosiers** [sveltejs/sapper#757]
The `onload` handler is working in the development build, but not the production build.

```html
<svelte:window on:load={() => console.log('loaded')}
```

Using this code, when I run `npm run dev`, the message gets written to the console. When I run `npm run build && npm run start`, nothing gets written to the console.

I'm using the latest version of sapper and svelte.

**Comment by thgh** [comment]
There is a race condition. Sapper is loaded async, in most cases (also in dev) the `load` event will happen before the page is hydrated and before the event listener is added to the window.

It's best to check `readyState`: https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState#Values

**Comment by jdesrosiers** [comment]
I ended up using `onMount` instead.
