### ISSUE TITLE
A href encoded incorrectly

### ISSUE THREAD

**Issue by ispyinternet** [sveltejs/sapper#759]
the following link:

`<a href="https://www.facebook.com/dialog/share?app_id=xxx&href=https%3A%2F%2Ftest.com&display=popup&quote=this+is+test" alt="facebook share">Broken Share link</a>`

incorrectly gets the quote text encoded:

`<a href='https://www.facebook.com/dialog/share?app_id=xxx&href=https%3A%2F%2Ftest.com&display=popup"e=this+is+test' alt="facebook share">Broken Share link</a>`

**Comment by Conduitry** [comment]
Fixed in Svelte 3.5.4. Thanks @thgh!
