### ISSUE TITLE
Issue with structure around CMS rendering

### ISSUE THREAD

**Issue by thomasmorice** [sveltejs/sapper#762]
Hello ,

I can't wrap my head around something. I'm using contentful to get data, and they have a rich text  object that I can retrieve. 

I want to use a component for all the different field in the richtext object, because I want to use image there in a smart way (fetch the image with custom size depending on the browser width/height for example.. 

The problem is that every text element in the richtext object can be separated, if they have bold or italic parts inside, so again, an array of things. 

So therefore, I have to loop into those arrays, and generate tags depending on if the text has `a` `b` `i` whatever.. This seems like a hassle to do in svelte because the tag cannot be dynamic.. I cannot do: 

```
<{$tag}> 
</{$tag}> 
```
I'm curious to see how you would tackle this, I'm thinking about generating the code in a variable inside the script, and then do `{@html markup}` but it's quite ugly to put markup inside tags in javascript.. lots of `if` for starting and closing tags

**Comment by thgh** [comment]
If your richtext object does not contain other components, then the `{@html markup}` approach is fine. No ifs needed: https://www.npmjs.com/package/@contentful/rich-text-html-renderer

(By the way, this is a question, not an issue. Next time you might want to post it on stackoverflow instead)
