### ISSUE TITLE
Reassigning an observable throws TypeError: $$unsubscribe_observableName is not a function

### ISSUE THREAD

**Issue by bvl12** [sveltejs/sapper#781]
When using rxjs' observables, they cannot be reassigned without throwing `TypeError: $$unsubscribe_observableName is not a function`. A minimal example can me found here: https://github.com/bvl12/sapper-observable-error

I know it is preferable to assign observables as constants, but my use case involves getting data from a database, which is not available until onMount and using autosubscriptions with it. I need to initialize the variable that will hold the observable with the data as another observable to prevent svelte from throwing me `observableName is not a store with a 'subscribe' method`

**Comment by Conduitry** [comment]
If you're talking about [this](https://github.com/bvl12/sapper-observable-error/blob/master/src/routes/index.svelte#L7), then dynamic imports return a promise resolving to the module, not the module itself. `observableCreator.myObservable` is going to be undefined.

**Comment by bvl12** [comment]
That import has actually been working fine for me (and showing what I expected when I print them). The issue I am having is that trying to overwrite an rxjs observable throws `TypeError: $$unsubscribe_observableName is not a function` (as it is trying to overwrite the old one), which is making me think that svelte is having an issue unsubscribing at the end of the autosubscription's lifecycle.

**Comment by bvl12** [comment]
closing because this isn't an issue with sapper, and the thread Conduitry linked above is more on-topic.
