### ISSUE TITLE
Stacktrace of exception thrown in server page is swallowed

### ISSUE THREAD

**Issue by cbenz** [sveltejs/sapper#782]
When an exception is thrown in a server page, but not caught in this server page, it is never displayed in the console.

I expect it to be displayed, in dev mode but also in production.
It would help debugging quite a lot!

This is easily explained by [this block of code](https://github.com/sveltejs/sapper/blob/201a0eb2f6b060fb7cd60bbf2e401a7d5d477cb3/runtime/src/server/middleware/get_server_route_handler.ts#L54-L58).

**Comment by Conduitry** [comment]
Released in 0.27.5. Thanks!
