### ISSUE TITLE
Imported data array from index.svelte file and unable to re render after updating it 

### ISSUE THREAD

**Issue by NaveenaSreenivasan** [sveltejs/sapper#787]
I have an array of data called  _**ibill**_   in _**index.svelte**_ . I need this array in another file _**cart.svelte**_.
In cart.svelte I imported as _**import { ibill } from "./index.svelte";**_

 _**ibill**_ array is bound to tabulation in cart.svelte

I do splice operation on this array on button click in cart.svelte.
The function that edits array is present in cart.svelte file.

_**ibill.splice(index,1); 
ibill = ibill**_    // to enable renderering

When doing this the following error is thrown 
_**$$invalidate is not defined**_ as shown in the attached screen shot.

<img width="635" alt="Screenshot 2019-07-03 at 12 34 36 PM" src="https://user-images.githubusercontent.com/38436515/60570398-1f265200-9d8f-11e9-8d2e-6029deb42300.png">
<img width="287" alt="Screenshot 2019-07-03 at 12 34 51 PM" src="https://user-images.githubusercontent.com/38436515/60570394-1e8dbb80-9d8f-11e9-9743-3c746c209fad.png">

Can someone  guide me in this issue ?

**Comment by antony** [comment]
@NaveenaSreenivasan  Please create a [Reproduction in the REPL](https://svelte.dev/repl/hello-world?version=3.6.3) showing your problem and expectation, and come and chat to us in the [chat room](https://svelte.dev/chat) where we will be better placed to help you.

**Comment by NaveenaSreenivasan** [comment]
@antony I am not able to work in https://svelte.dev/repl/hello-world right now. There is some issue with compiler in the site. Please check it.
<img width="1676" alt="Screenshot 2019-07-03 at 2 58 51 PM" src="https://user-images.githubusercontent.com/38436515/60580951-96fe7780-9da3-11e9-8b25-92f7c996e67f.png">

**Comment by Conduitry** [comment]
The REPL has been working again for several days. Since this doesn't sound like a problem with Sapper, and since GitHub issues aren't the right place for support questions like this, please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).

**Comment by nickmanning214** [comment]
I got this error when I accidentally put `on:customEvent={varName=true}` instead of `on:customEvent={()=>varName=true}` in case anyone is googling this
