### ISSUE TITLE
fully replace inner html of <div id="sapper">

### ISSUE THREAD

**Issue by burningTyger** [sveltejs/sapper#790]
It would be nice to place a message in the html template and use the `<div id="sapper">` element to inform users of outdated browsers that his site won't run on their platform. If sapper does load it would just replace this message instead of concatenating as it does now. No more tinkering with browser detection and so on involved. Is my thinking correct on this one?

**Comment by Conduitry** [comment]
I don't think this would get along well with server-side rendering. The message would either be included in the server-rendered page or it wouldn't. If it is present, there would probably be an undesirable flash before hydration kicks in and it's removed. If it isn't present, we wouldn't be able to display it to old browsers.

So, I don't think this is something we want to bless, but you could still implement it yourself by including such a message in your _layout, and then hiding it (using old fashioned CSS, for example) after the promise returned by `sapper.start()` resolves.

**Comment by burningTyger** [comment]
No problem, this is my current solution anyway. Thanks for looking into it.
