### ISSUE TITLE
Improve build option descriptions

### ISSUE THREAD

**Issue by kaleidawave** [sveltejs/sapper#795]
Running `sapper build --help` shows a flag/argument for the output directory but the default is the path to the sapper module

```
--output      Sapper output directory  (default src/node_modules/@sapper)
```
 
Is this correct? Surely it defaults to `__sapper__`???

**Comment by Conduitry** [comment]
Take a look at <https://github.com/sveltejs/sapper/blob/master/src/cli.ts>. The positional `dest` argument defaults to `__sapper__/build`. `--output` is for specifying where generated files that are written prior to bundling go, which does indeed default to `src/node_modules/@sapper`. The description of that option could probably be improved.
