### ISSUE TITLE
inline styles in <head>

### ISSUE THREAD

**Issue by ahfarmer** [sveltejs/sapper#796]
I think a good optimization would be to move the critical CSS from `<link>` tags to a `<style>` tag.

A comment in the sapper template claims that this is done: "[Sapper generates a <style> tag containing critical CSS](https://github.com/sveltejs/sapper/blob/master/site/src/template.html#L19)" but on my site I just see several `<link>` tags.

This is the author of Gatsby talking about how much faster things are with `<style>`:
https://github.com/gatsbyjs/gatsby/issues/145#issuecomment-217691369

And here's my Google pagespeed insights report telling me to inline the CSS: 
<img width="792" alt="Screen Shot 2019-07-09 at 9 41 18 AM" src="https://user-images.githubusercontent.com/597825/60907779-381b8100-a22f-11e9-8591-1779d6fba418.png">

**Comment by Panya** [comment]
It's done, you just need to configure the svelte compiler in your webpack/rollup config. Set `emitCss` to `false`. See https://github.com/sveltejs/svelte-loader#extracting-css for webpack loader and https://github.com/rollup/rollup-plugin-svelte#extracting-css for rollup plugin.

**Comment by Panya** [comment]
Also it's possible to inline the `global.css`.

**Comment by ahfarmer** [comment]
@Panya I'm talking about something a little different. `emitCss: false` stores your CSS as a string within your JavaScript and then adds a `<style>` tag at *runtime*.

I am suggesting that in addition to `emitCss: true` we should have an additional option like `emitCssInline: true`. This would emit the CSS and then instead of creating a `.css` file, it would inject that CSS into a `<style>` tag at *build time*. This is what Gatsby does by default.

**Comment by Panya** [comment]
@ahfarmer It will be inlined in a style tag with `emitCss: false` (with server side rendering). Just try it in the default [sapper-template](https://github.com/sveltejs/sapper-template).

**Comment by ahfarmer** [comment]
@Panya tried it - I see now that `emitCss: false` puts the styles in a script tag at build time. I didn't know it would do that, it is a step in the right direction.

However - the styles are still in the JavaScript as well, so the JS is bloated. The user is downloading the styles twice: once in the `<style>` tag in the HTML and once as a string in the JS.

The ideal loading experience has critical styles in `<style>` in HTML at build time, and all other css in `.css` files for caching and to avoid the double-download.

**Comment by Panya** [comment]
@ahfarmer well, If I not mistaken, Gatsby do the same thing.

**Comment by Panya** [comment]
Also I'm not sure that extract CSS to `.css` files and load it with `<link>` tags will be better in all cases. It will cause additional round trip time to make those requests.

**Comment by ahfarmer** [comment]
I see. I checked Gatsby and you are right - their behavior matches emitCss: false. 

I'm focused on empty cache initial load time.  Taking the CSS out of the JS would definitely improve that, but maybe not by much. 

In my project I'll try emitCss false and run with that and see how it goes. Thanks @Panya

**Comment by jeffreycahyono** [comment]
> Also it's possible to inline the `global.css`.

@Panya Could you enlighten me how to also make global.css inline instead of using <link>?

**Comment by julienchazal** [comment]
@Panya could you explain how to inline global.css please ? 
i tried to put global styles in `_layout.svelte` but they're not inlined if corresponding tags/classes/ids are not in `_layout.svelte`
thx

**Comment by julienchazal** [comment]
@Panya it would be great if you could help us please ;) thx

**Comment by Panya** [comment]
@julienchazal, @jeffreycahyono you can use `:global(...)` for global styles in `_layout.svelte` or use special preprocessor for this (see [svelte-preprocess](https://github.com/kaisermann/svelte-preprocess#global-style-support) for example). Also you can do it manually as a build step (e.g. replace `[[global]]` in `template.html` with content of `global.css`).

**Comment by julienchazal** [comment]
@Panya thanks ! 
i was just figuring it out with `<style global></style>` in `_layout.svelte` ;)

**Comment by julienchazal** [comment]
@Panya @Rich-Harris @Conduitry @lukeed i think this issue should be reopened as as @ahfarmer said : 

> The user is downloading the styles twice: once in the <style> tag in the HTML and once as a string in the JS.

thx !

**Comment by siebeneicher** [comment]
@ahfarmer I had the same intention and found an easy way. I use rollup-plugin-sass with this configuration in the rollup.config.js:

`sass({`
`  includePaths: ["./src/theme", "node_modules"],`
`  output: "static/global.css",`
`  insert: true`
`}),`

The insert:true writes the output into the head of the template. https://www.npmjs.com/package/rollup-plugin-sass#insert

**Comment by ledfordjs** [comment]
I'm also looking to inline my css in the head of the document when it is requested like @ahfarmer. It's odd because this is currently available in https://github.com/sveltejs/sapper/blob/master/runtime/src/server/middleware/get_page_handler.ts#L319
but the else block is never hit because of the build.json having `css.main` but if we change the if statement to `if(build_info.css && build_info.css.main.length)` this will inline the styles in the head on the server before it is sent to the client
