### ISSUE TITLE
redirect after login 

### ISSUE THREAD

**Issue by Boujemaa1** [sveltejs/sapper#799]
Return to the pretected route after authentication:

In pure expressjs server we do this:

`app.use((req, res, next) => {
  // After successful login, redirect back to the intended page
  if (!req.user
    && req.path !== '/login'
    && req.path !== '/signup'
    && !req.path.match(/^\/auth/)
    && !req.path.match(/\./)) {
    req.session.returnTo = req.originalUrl;
  } else if (req.user
    && (req.path === '/account' || req.path.match(/^\/api/))) {
    req.session.returnTo = req.originalUrl;
  }
  next();
});
`
how achieve the same thing in sapper?

**Comment by Conduitry** [comment]
If there's a simple rule for which URLs should be protected, you can still use middleware like that in `src/server.js`, but it is probably better to store the return URL in a query parameter of the redirect URL than in the session.

Alternatively. you can protect a page route by putting a check in its preload function and redirecting to the login page, again with the return URL (which is available to the preload function in its `page` argument) in a query parameter.
