### ISSUE TITLE
Only top level _layout.svelte is being rendered

### ISSUE THREAD

**Issue by stijnvanderlaan** [sveltejs/sapper#801]
I try to override the root `_layout.svelte` with a version in a sub directory, but it only renders the top level:

```
routes/_layout.svelte
routes/index.svelte
routes/admin/_layout.svelte
routes/admin/index.svelte
```

When I navigate to `admin/` it renders with the layout `routes/_layout.svelte`. 
I would expect it to render with the layout `routes/admin/_layout.svelte`.

sapper: v0.27.4
svelte: v3.6.7

**Comment by PatrickG** [comment]
Actually, the "inner" layout is rendered as if it were a route. It's rendered where the `slot`-tag is in your main layout.

On a side note, i hope it stays this way. I need this :)

**Comment by ahfarmer** [comment]
I think the current behavior is expected. There is no reason to assume that routes in the same folder are similar. If they are they can share the same components. 

There is just one _layout.svelte file. Even that one is unnecessary because it is so easy to share common components.

**Comment by pngwn** [comment]
This is not a bug. Nested layouts inherit higher level layouts [as explained in the documentation](https://sapper.svelte.dev/docs#Nested_routes)

**Comment by stijnvanderlaan** [comment]
Thanks for your feedback. I read along the line where inheriting was explained. Still I think it's makes more sense to override the layout. It's a lot more work to add the layout to every page, instead of extending only a couple of layout files with the root layout.

**Comment by BennyHinrichs** [comment]
What do we do when we need a different layout for a route? Is there some easy way to override?

**Comment by joelhickok** [comment]
So if the root `_layout.svelte` is used for all routes, how do I use an alternative layout at the root level for a new path.  For example, I want all paths to use `_layout.svelte` except for `/help` that should use a completely new layout, such as `_layout_help.svelte`.  

One of the routing libraries I've used allows you to throw a `_reset.svelte` file inside a directory, which tells that route to NOT use the parent root layout file.
