### ISSUE TITLE
How to bundle JS/CSS and use in sapper?

### ISSUE THREAD

**Issue by kickthemooon** [sveltejs/sapper#802]
Just started using sapper.

With a usual project using webpack I have my .js/.scss files under src.
They get compiled to my js/css bundles and exported to dist.

With sapped I am a bit confused on how to achieve this.

How to have my .js/.scss compiled and exported to the static directory so I can use it in my _layout?

**Comment by antony** [comment]
Hi, This is a usage question and is better asked in the Discord room https://discord.gg/yESBPS where we can provide better detail.

To point you in the right direction, the https://www.npmjs.com/package/svelte-preprocess is a very good way to start using js/scss with Sapper. You'll be pleased to know that it isn't a two-step process, and you will get live-reloading of your CSS.

**Comment by kickthemooon** [comment]
I try to set it up with svelte-preprocess.
