### ISSUE TITLE
Default _error.svelte page doesn't compile

### ISSUE THREAD

**Issue by Panya** [sveltejs/sapper#817]
**Describe the bug**
If we create a Sapper project and don't create `_error.svelte` file inside `src/routes` directory, Sapper will use internal `src/node_modules/@sapper/internal/error.svelte` page instead. This page is a syntactically invalid Svelte component.

**Logs**
```
'error' is not defined. Consider adding a <script> block with 'export let error' to declare a prop
'status' is not defined. Consider adding a <script> block with 'export let status' to declare a prop
```

**Comment by Conduitry** [comment]
0.27.5 includes your fix. Thank you!
