### ISSUE TITLE
(WebPack) Browser Runtime Exception When Running In Production Mode

### ISSUE THREAD

**Issue by ISNIT0** [sveltejs/sapper#82]
(Really loving Sapper, etc.)

package.json:
![image](https://user-images.githubusercontent.com/5173131/34888538-7f60d6f0-f7c2-11e7-8f8e-cefc85656347.png)

When building and running in production mode:
```bash
NODE_ENV=production npm run build && NODE_ENV=production node server.js
```
I get an exception thrown on page load (attached and pictured) [Sapper-Production-Crash.txt](https://github.com/sveltejs/sapper/files/1626961/Sapper-Production-Crash.txt)
![image](https://user-images.githubusercontent.com/5173131/34888329-cb381ea4-f7c1-11e7-9341-02ac55f2921f.png)

It seems to be related to the "ExtractTextPlugin":
![image](https://user-images.githubusercontent.com/5173131/34888358-dfea90de-f7c1-11e7-9836-46bd58dfcb2c.png)

When manually disabled from the client webpack config the issues disappear.

Removing Component CSS also 'fixes' the issue.

Un-minified exception:
![image](https://user-images.githubusercontent.com/5173131/34888433-32133f28-f7c2-11e7-8b4e-2f1e92931529.png)
[Sapper-Production-Crash-unmin.txt](https://github.com/sveltejs/sapper/files/1626986/Sapper-Production-Crash-unmin.txt)

Unfortunately I don't have much time to look into it further.
Hope this info is helpful.

**Comment by Rich-Harris** [comment]
Can you try with Sapper 0.4? It includes [this PR](https://github.com/sveltejs/sapper/pull/72) which appears to be the same issue

**Comment by ISNIT0** [comment]
Will do either this evening, or tomorrow evening.

**Comment by ISNIT0** [comment]
Can confirm that this has fixed since I last tried (though there seem to be other deployment issues).
I'll close this.
