### ISSUE TITLE
Feature request: change sapper export path

### ISSUE THREAD

**Issue by davidcallanan** [sveltejs/sapper#828]
**Is your feature request related to a problem? Please describe.**
Cannot change export path when using `sapper export`.
The intermediate build path can be changed with `--output` but not the export path.

**Describe the solution you'd like**
Add option `--exportoutput <path>` to the `sapper export` command in the Sapper CLI.

**Describe alternatives you've considered**
Run a platform-specific command afterwards such as `mv __sapper__/export dist.static`

**How important is this feature to you?**
Not very important but useful

**Comment by Conduitry** [comment]
`__sapper__/export` is the default for the positional `dest` argument. It already exists and is not a named option.

```
  Description
    Export your app as static files (if possible)

  Usage
    $ sapper export [dest] [options]
```

Slightly related: #795
