### ISSUE TITLE
Remove hard coded, un-overridable NODE_ENV from development

### ISSUE THREAD

**Issue by Vages** [sveltejs/sapper#834]
**Is your feature request related to a problem? Please describe.**
My project at work uses [the `config` package](https://www.npmjs.com/package/config) to set different environment variables. This uses `NODE_ENV` to select and merge different configuration files. For example, my project has `staging` and `dev` environments, which are both development environments. So to switch between the environments, I set `NODE_ENV` when I run a given command, e.g. `NODE_ENV=staging foo` vs. `NODE_ENV=dev foo`.

I'd like to do the same with Sapper – at least during development, and quite possibly with built apps (even minified ones). However, when I try to run the app with the staging config, using `NODE_ENV=staging npm run dev`, the environment always turns out to be `development`. To the best of my knowledge this is because `NODE_ENV` is overridden in [`dev.ts` inside the `Watcher` class](https://github.com/sveltejs/sapper/blob/master/src/api/dev.ts#L128).

**Describe the solution you'd like**
I'd like to be able to override NODE_ENV as described above. I imagine this could be done in quite the same way as for #241 (changing one line). 

**Describe alternatives you've considered**
I've considered switching configuration/environment variable packages, but I think I'm not the only one having this problem, as `config` is quite popular.

**How important is this feature to you?**
It's a make or break feature for us, so I'll have to fork the project or use `patch-package` if this doesn't get implemented. 

Note: I'm filing this as a request for comments. I might file a PR for this myself, as there doesn't _seem_ to be much work involved. 

**Additional context**
You can confirm/reproduce this by cloning [the Sapper template](https://github.com/sveltejs/sapper-template) and console-logging `process.env.NODE_ENV` somewhere in it.

**Comment by antony** [comment]
@Vages I too use the `config` package, and simply set the variable `NODE_CONFIG_ENV` to match `NODE_ENV`, which takes precedence.

**Comment by Vages** [comment]
Didn't know! In my defense, it's [not exactly on the first page of the docs](https://github.com/lorenwest/node-config/wiki/Configuration-Files). That might be just the solution I'm looking for, @antony. I'll try it out today and close the issue if I can't find any reason to keep it open. :)

**Comment by antony** [comment]
Agreed - it's quite buried, but over time I've learned that Loren has literally thought of every possible scenario that has ever occurred and will ever occur and has a solution for it!

**Comment by Vages** [comment]
Closing because I no longer feel the need for this after @antony's reply. 😄
