### ISSUE TITLE
Allow multiple template.html options

### ISSUE THREAD

**Issue by jeffreycahyono** [sveltejs/sapper#846]
**Is your feature request related to a problem? Please describe.**
I need to produce AMP and non AMP in each pages in routes, for example ```/src/routes/about.svelte``` for non-AMP page and ```/src/routes/about-amp.svelte``` for AMP page. `about.svelte` need to use `src/template.html` and `about-amp.svelte` need to use `src/amp-template.html`

**Describe the solution you'd like**
Each pages in routes can optionally choose which template to use. For example in `about-amp.svelte` there is a statement: ```<svelte:options template="amp-template.html"/>```  

**Describe alternatives you've considered**
Maybe sapper need to have config file like ```sapper.config.js``` that inside it, we can describe rules which pages should use which template

**How important is this feature to you?**
It's important to rebuild our website to support AMP an non-AMP pages

**Comment by antony** [comment]
From a fairly brief read about AMP, it seems like:

* you have to use a subset of HTML - no forms, etc
* you have to use a subset of CSS
* you can't use any javascript

It feels like your "AMP" website would end up being basically a separate site, as you would have extremely limited ability to share any of your components or routes.

What's more, it sounds like you'd have to render the whole thing with SSR and do no client-side hydration, and you'd have no ability to use Svelte's routing, or any of the runtime functions (hash state changes, page/session stores) that it will inject into your page.

Based on this, I feel like this isn't a concern for Sapper, but instead an infrastructural issue, where you'd need to build two individual applications (one Sapper, one without) and co-host them on the same domain/path.

**Comment by jeffreycahyono** [comment]
Agreed.

**Comment by btakita** [comment]
@jeffreycahyono I have a solution to disabling js in https://github.com/sveltejs/sapper/issues/1008

**Comment by aubergene** [comment]
I have this same issue, but not for AMP. Essentially I want to reuse components between a user facing "site" and an admin facing "site" and each should have their own `template.html`. The two "sites" are separate and so it would be perfectly fine if any navigation between them required a full page load as they are two separate SPAs. Any way of doing this currently? Thanks

**Comment by kevmodrome** [comment]
@aubergene Look at how the svelte and sapper sites use https://github.com/sveltejs/site-kit - basically you make a package and you import it in each site separately.

**Comment by antony** [comment]
@aubergene It sounds like you're trying to shoehorn two sites into one. I just made two separate Sapper apps.

**Comment by aubergene** [comment]
Thanks for your good (and prompt) help!
