### ISSUE TITLE
Derived stores don't work with session from @sapper/app

### ISSUE THREAD

**Issue by jakobrosenberg** [sveltejs/sapper#847]
I don't know if this is a feature request or bug report.

There's no way to create a store derived from ``session`` as calling ``const {session} = stores()`` outside of a component produces the error:

``Error: Function called outside component initialization``

**Comment by thgh** [comment]
You can create a function that returns a derived based on the session store, but you can only call that function in a page component script. (Not module context)

**Comment by jakobrosenberg** [comment]
Let me get this straight.
- My `JWT token` is stored in the `session`.
- An authorized http request requires the `JWT token`.
- The `JWT token`is only available in component initiation.
- Therefore authorized request calls aren't immediately available outside of component initiation.

Is there a clean way to add a store method that uses the jwt token? Ie. a hydration request.

**Comment by antony** [comment]
@jakobrosenberg not solving this exact problem but it's not ideal to store your JWT token inside the application. It is better stored as a httpOnly cookie, and the browser will pass it to your API when required.

**Comment by jakobrosenberg** [comment]
@antony Thanks. How would that work with SSR and SSOT for the token?

**Comment by antony** [comment]
Not sure what your concern with SSOT is, but it works well with SSR since your JWT is available in `req.cookies`:

Here's how I do it:

```js
import jwt from 'jsonwebtoken'
import cookieParser from 'cookie-parser'

polka()
  .use(
    ...
    cookieParser(),
    (req, res, next) => {
      return sapper.middleware({
        session: (req) => {
           const token = req.cookies['cookieName']
          const profile = token ? jwt.decode(token) : false
          return { authenticated: !!profile, profile }
        }
      })(req, res, next)
    }
  )
  ...
```

**Comment by peterbabic** [comment]
@jakobrosenberg  Does the preload work with this?

I would also love sessions "outside component initialization", if it is sane.

**Comment by jakobrosenberg** [comment]
@peterbabic 

I don't know. I gave up on Sapper and ported the router to Svelte.

**Comment by janosh** [comment]
Is there any official advice on accessing `session` in a regular JS file, i.e. outside a component?

```
// queries.js: needs access to some API tokens
import { stores } from '@sapper/app'

const { session } = stores()
// Error: Function called outside component initialization
```

**Comment by Conduitry** [comment]
`stores()` needs to be called during some component's initialization because it uses the context API to keep the sessions of the different requests separate during server side rendering.

**Comment by janosh** [comment]
Thanks for clearing that up. So how to access environment variables outside components? [`@rollup/plugin-replace`](https://www.npmjs.com/package/@rollup/plugin-replace)? I have a file of queries that are called in `preload` functions across various components. IIUC, `@rollup/plugin-replace` would only make them accessible after bundling? Does `preload` happen before bundling?
