### ISSUE TITLE
Sapper template on codesandbox doesn't allow changes

### ISSUE THREAD

**Issue by sanderhahn** [sveltejs/sapper#855]
The [codesandbox.io Sapper template](https://codesandbox.io/s/github/codesandbox-app/sapper-template) now seems to open up port 10000 for the `dev_server`. However it is being accessed through `http` and this results in a `Blocked loading mixed active content “http://5f3hw.sse.codesandbox.io:10000/__sapper__”`. PR https://github.com/sveltejs/sapper/pull/854 seems to be able to address this issue.

**Comment by sanderhahn** [comment]
Other server templates seem to reuse the same http connection to open for instance a `faye-websocket` (like the gatsby template). Maybe Sapper can also reuse the same http connection if the `DevServer` code moves to the server itself and is accessible on the same port. This probably  requires some changes to the ipc.

**Comment by antony** [comment]
This should be raised with CodeSandbox, the linked template is broken for a number of reasons, one being that it doesn't have a branch specified, and is a template-template.
