### ISSUE TITLE
--basepath not working

### ISSUE THREAD

**Issue by wighawag** [sveltejs/sapper#862]
**Describe the bug**
when using the basepath option the routes do not get generated

**To Reproduce**
Follow the "get-started" of sapper:
```
npx degit "sveltejs/sapper-template#webpack" my-app
cd my-app

npm install
```

except you modify the script "export" to be
```sapper export --basepath test```

and after running
```npm run export```

you get :
```
...
 Built in 2.7s
> Crawling http://localhost:3000/test/
   1.93 kB   (404) index.html
   1.93 kB   (404) service-worker-index.html

> Finished in 3.5s. Type npx serve __sapper__/export to run the app.
```

It can't find any of the routes

**Comment by Conduitry** [comment]
The `--basepath` option on export doesn't set the basepath the app is served from. It only tells export what path to start at. See https://sapper.svelte.dev/docs#Base_URLs

**Comment by guangbi** [comment]
`sapper export --basepath testdir`

// app/server.js
`
express() // or Polka, or a similar framework
	.use(
		'/testdir', // <!-- add this line
		compression({ threshold: 0 }),
		serve('static'),
		sapper.middleware()
	)
	.listen(process.env.PORT);
`
That would be ok.
