### ISSUE TITLE
Broken URL in error message

### ISSUE THREAD

**Issue by mikemaccana** [sveltejs/sapper#865]
`Error: As of Sapper 0.22, you should not import 'sapper' directly. See https://sapper.svelte.technology/guide#0-21-to-0-22 for more information   `

is a 404. The proper URL is:

`https://sapper.svelte.dev/migrating#0_21_to_0_22`

**Comment by Conduitry** [comment]
`https://sapper-legacy.svelte.dev/guide/#0-21-to-0-22` might be better. I'm not sure. Or maybe we could just remove this, as it's been close to a year since 0.22 was released.

**Comment by mikemaccana** [comment]
The error still shows up when you `require('./@sapper/server');` even if you haven't actually used any previous version.  

I actually still don't know how to require/import `@sapper/server` even after reading the error. Am I supposed to `node --experimental-modules` and use ES6? Or is `require()` supposed to work? I've tried either.

I;m just trying to access `sapper.middleware()`

**Comment by paschalidi** [comment]
Hey you both I would be very happy to work on this :) Please let me know!
