### ISSUE TITLE
More control over the server process

### ISSUE THREAD

**Issue by ramiroaisen** [sveltejs/sapper#875]
Im creating an app with sapper and i do not like to have to call my code from the sapper build, i would prefer to do it in the other way around say:

```
//my-app-entry.js
const sapper = require('sapper.build');
myapp.use(sapper.middleware)

```

and in the console call it this way
`node my-app-entry`

and dont have to do `node  __sapper__/build` to call my entry file

the solution is simple just doing a `module.exports = middleware` at the end of the generated sapper build source

then we would be able to `require()` it from our own entry file 

Sorry for my english and thank you very much!

**Comment by Conduitry** [comment]
You can either have some sort of a reverse proxy in your app which sits in front of the Sapper server, or you can adjust your bundler config so that the server entry point instead points to a file that just exports the middleware function.

**Comment by thgh** [comment]
Example of how to export the server:
https://github.com/thgh/now-sapper/blob/master/README.md#preparation
