### ISSUE TITLE
Server fetch doesn't use same-origin by default

### ISSUE THREAD

**Issue by cyderize** [sveltejs/sapper#881]
I noticed while poking around the server middleware that when fetching, Sapper doesn't seem to send any credentials by default (i.e. credentials: 'omit'). Since whatwg/fetch#585, however, the default in browsers is to have credentials: 'same-origin'.

Is there a reason why this is the case, or should this be changed to be consistent with what browsers now do?

**Comment by Conduitry** [comment]
Fixed in 0.27.14.
