### ISSUE TITLE
CSS background url adds '/client/ to path

### ISSUE THREAD

**Issue by Wolfr** [sveltejs/sapper#887]
Given a new component:

```
<style>

    ul {
        width: 100%;
        background: url('trail.png');
    }

</style>

<img src="trail.png" alt="" />
<ul>
    <slot></slot>
</ul>
```

And an image called trail.png (just a gray dot)

![trail](https://user-images.githubusercontent.com/12690/64621036-44fe5180-d3e5-11e9-8dc0-571cdb2868dc.png)

The HTML one loads but the CSS one doesn't. The image is contained in the `/static` folder.

Expected behavior: both images should load. 

What happens: if you inspect the CSS background URL path in the devtools, you'll see that `/client` is added to the URL. This causes a 404.

**Comment by Conduitry** [comment]
I'm inclined to say that this is not actually a bug, and that you should just be using absolute paths in component styles. I don't think we want Sapper to have to worry about fixing paths within the styles. (And if someone _did_ put their images in `static/client/whatever.png` and referred to it as `url(whatever.png)` in their styles, anything we did to the path would break the image.) Perhaps this could be documented somewhere, but I don't think the behavior should change.

**Comment by Wolfr** [comment]
OK, I see, I just had no idea that I should put images in a `/client` folder inside of assets, this doesn't seem to be in the docs.

It might be obvious if you know Express/Polka or how it the asset logic was set up but I had no idea.

**Comment by antony** [comment]
@Wolfr I don't think putting images in a `client` folder is what @Conduitry is suggesting.

The suggestion is to use absolute paths in component styles:

```jsx
<style>

    ul {
        width: 100%;
        background: url('/trail.png');
    }

</style>

<img src="trail.png" alt="" />
<ul>
    <slot></slot>
</ul>
```

**Comment by Conduitry** [comment]
Yeah, using an absolute path is probably what I would suggest here. I was thinking about #867 when I mentioned the `static/client` thing. Although thinking about that issue again, 'just use absolute paths' might be the simpler solution there as well.

**Comment by Conduitry** [comment]
Potentially relevant old issue: #420

**Comment by pixeline** [comment]
I just found out that if you serve the SPA within a subfolder (as in a GitHub Pages), then an absolute path used in the CSS is not correctly resolved, even if the `<base href="/path"/>`is correct. It is correctly resolved if the image is used as an `<img>` tag.

**Comment by sballgirl11** [comment]
Having issues with this as well, even the exact absolute path does not work. Can't get background-image in css styles to load, but img tag works fine.

**Comment by artemjackson** [comment]
> I'm inclined to say that this is not actually a bug, and that you should just be using absolute paths in component styles.

It does not work if project is hosted not from the domain root.

E.g. website which exported with  `--basepath=sapper-site` and which sits on www.example.com/sapper-site.
In this particular case absolute url like `url("/img/cool-img.jpg")` will follow to www.example.com/img/cool-img.jpg instead of desired www.example.com/sapper-site/img/cool-img.jpg

UPD:
I confirm and rewrote @pixeline words

**Comment by xiaohk** [comment]
I also have the same issue as @pixeline and @artemjackson pointed out. I guess the current solution would be using a variable in the path? For example, `src='{base}/img/test.png'`, and set `base = ''` or `base='/sapper-site'`.

**Comment by antony** [comment]
The way I've got this working is to use relative **or** absolute paths, with relative being relative to the directory that the component is in. I.e. as if we were running on your local machine, without bundling.
