### ISSUE TITLE
Include `sapper dev --legacy`

### ISSUE THREAD

**Issue by ADantes** [sveltejs/sapper#889]
**Is your feature request related to a problem? Please describe.**
`sapper build --legacy` and `sapper export --legacy` both produce builds that, with the correct polyfills included, work in Internet Explorer 11.  `sapper dev` does not provide an equivalent so, when working on IE11 styling issues, I have to do a fulfill rebuild after each change.

**Describe the solution you'd like**
I'd like to see a `--legacy` flag added to dev, that would mimic the behaviour that currently exists for build and export.

**How important is this feature to you?**
Drastically saves time and annoyance when fixing IE specific styling issues or just testing legacy builds in general.

**Comment by antony** [comment]
We're rethinking legacy for Kit, so closing this.
