### ISSUE TITLE
Export and relative URL

### ISSUE THREAD

**Issue by rap2hpoutre** [sveltejs/sapper#89]
After exporting the default [sapper-template](https://github.com/sveltejs/sapper-template) with the `npx sapper export` command, I would like to use it somewhere in a subfolder. It works if I serve it via http://example.org (with nginx or similar) but not if I host it in a subfolder http://example.org/my-sapper-website (example: if I want to host it on Github Pages). It's because all URL starts with slashes in `routes` and `templates`. I could change all the URL to make them relatives (removing the slash in HTML), but I not sure it's the right way.

Is there a way to export for hosting in subfolder without rewriting all the routes files?

_Sorry if it's not the right place to ask this kind of questions, maybe I should have posted on Stackoverflow_

**Comment by EmilTholin** [comment]
Hi @rap2hpoutre! That's a good point. There is currently no way to make the relative URLs absolute.

It might be worth exploring if the CLI could be expanded to take an argument to specify a root URL, which could be added to relative URLS when [the `a` tags are extracted](https://github.com/sveltejs/sapper/blob/master/lib/utils/export.js#L69-L78).

`sapper export --rooturl=http://example.org/my-sapper-website`

**Comment by Rich-Harris** [comment]
I'm going to close this issue in favour of #180, as it's something that also applies to non-exported sites, so we should have a fix that covers both scenarios
