### ISSUE TITLE
Compilation errors in components could be handled with a bit more grace

### ISSUE THREAD

**Issue by arggh** [sveltejs/sapper#898]
**Describe the bug**
If my app's component compilation fails, I'm greeted with this error message from Sapper (dev):

```
Error: Cannot find module '/Users/arggh/app/__sapper__/dev/server/server.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```
It's quite confusing and doesn't tell me anything valuable.

**To Reproduce**
Create a syntax error for example in one of your components.

**Expected behavior**
I'd expect to get notified about the compilation error in any of my Svelte components.

**Information about your Sapper Installation:**
- OS X 10.12

- Sapper version: 0.27.8

- Svelte version: 3.12.1

- Rollup

**Severity**
Annoying and confusing. Slows down development.

**Comment by ehrencrona** [comment]
I can not reproduce this behavior on `master`. Creating e.g. a route containing only `<broken` or 

```
<script>
foo bar
</script>
```

gives errors with sufficient information when running the dev server or when building.
