### ISSUE TITLE
Don't write service-worker.js to filesystem in dev mode

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#90]
Added this in 0.5 so that `sapper export` could easily access the service-worker.js file, but it causes problems when deploying to Now because you don't have access to the filesystem.

Will revert that so I can redeploy svelte.technology, but this will mean that `sapper export` no longer includes the service worker. In other words I'm about to deliberately introduce a bug 🐛

**Comment by TehShrike** [comment]
Now allows you to write to tmp, if that is viable?

**Comment by Rich-Harris** [comment]
Could do, but it's not really necessary — I was only doing that because it was an easy way for `sapper export` to read the service worker. Just need to rejig things a bit so that we can grab it straight from memory
