### ISSUE TITLE
Unexpected behavior: script without "module" does not run on client on slug change.

### ISSUE THREAD

**Issue by LittleToky** [sveltejs/sapper#909]
**Describe the bug**
I've copied realword (https://github.com/sveltejs/realworld) and added store. In script without "module" of /article/[slug] I tried to write slug into store. I've displayed this data from store in parent layout and in /article/[slug]. SSR works as expected, but then there is no changes in data displayed from store while I'm navigating between article/[slug] pages with different slugs.
Script  without "module" is running only once, not on every slug change.

**To Reproduce**
https://github.com/LittleToky/realworld
Please, navigate to /article/vgmnh-sfh2se. Then press green button - it increments another value in store - we can see immediate changes in both - parent layout and route.
Then click different green links - so we change slug - the only change on page is where I take slug directly from script with "module". I've placed console.log in script without "module" and it runs only when I first navigate to the route. As all this script. As my code that writes slug into the store.

**Expected behavior**
I expected slug change will lead to script without "module" run. (console.log, store should change -> text in yellow boxes should change) 

**Severity**
It blocks usage of Sapper entirely as I can't realize basic functionality.

**Comment by thgh** [comment]
Only changing slug does not remount the component, only rerender.
Solution: https://github.com/LittleToky/realworld/commit/2ec0d010acd0dfef5518fc30b4686422d050ec8e#r35189013
Docs: https://svelte.dev/docs#3_$_marks_a_statement_as_reactive

**Comment by LittleToky** [comment]
Oh thank you so much! It works! You just saved me!
