### ISSUE TITLE
Best practices for SQL integration?

### ISSUE THREAD

**Issue by mwilliams1188** [sveltejs/sapper#915]
Loving the idea of Sapper so far, but am struggling to find answers for some best practices stuff. I'm currently migrating a simple express project.

Is there currently some sort of best practice for integrating a sql db? Just to get something working I threw a db.js file in the root folder, and am doing a db query in the preload. I'm sure there's a better way to do this, just not sure. This is not a public facing project fwiw.

1. Should I be creating a route and throwing the db logic in there instead?
2. Is there a specific place I should be throwing db.js? Should there be a libs or helpers folder or something?

Sorry if these are noob questions and thanks in advance for the input.

`<script context="module">
  import * as db from '../db.js'
  import moment from 'moment'

	export async function preload({ params, query }) {
    let monday = moment().startOf('isoweek').format('YYYY-MM-DD')
		const data = await db.mySqlPromise(`SELECT * FROM table`)

		return { events: data }
	}
</script>

<script>
  import Buttons from '../components/Buttons.svelte'
	export let events
</script>`

**Comment by thgh** [comment]
1. Yes, you should create an API (e.g. `src/routes/api/things.js`) that will run your query serverside. Then use `this.fetch` inside `preload` to call your API.
2. In our company we standardized on `src/lib/` for helpers, integrations, ...
