### ISSUE TITLE
[CLI]: have a dedicated command to show up local environment information

### ISSUE THREAD

**Issue by jamesgeorge007** [sveltejs/sapper#918]
**Is your feature request related to a problem? Please describe.**
It is a common practice nowadays to have those CLI utilities be shipped with a dedicated `info` command which would ease the bug submission procedure.

**Describe the solution you'd like**
`sapper info`

**How important is this feature to you?**
Manually fetching the required local environment information seems cumbersome at least IMO.

**Additional context**
N/A

**Comment by jamesgeorge007** [comment]
I would happily submit a PR :+1:

**Comment by sw-yx** [comment]
you can also just include an instruction `npx envinfo --system --npmPackages svelte* --binaries --browsers`

**Comment by Conduitry** [comment]
Yeah I'd be more inclined to add a line about 'please include the output of ...' in the issue template rather than adding this to the CLI.
