### ISSUE TITLE
AssertionError in test/apps/layout

### ISSUE THREAD

**Issue by sw-yx** [sveltejs/sapper#926]
**Describe the bug**
weird assertion error when running tests on the current master

**Logs**

```
113 passing (41s)
  1 failing

  1) layout
       only recreates components when necessary:

      AssertionError [ERR_ASSERTION]: [ 'y: bar 1 z: baz 1 goto foo/bar/qux goto foo/abc/def child segment: baz' ] deepEqual [ 'y: bar 1',
  'z: baz 1',
  'goto foo/bar/qux',
  'goto foo/abc/def',
  'child segment: baz' ]
      + expected - actual

       [
      -  "y: bar 1 z: baz 1 goto foo/bar/qux goto foo/abc/def child segment: baz"
      +  "y: bar 1"
      +  "z: baz 1"
      +  "goto foo/bar/qux"
      +  "goto foo/abc/def"
      +  "child segment: baz"
       ]
      
      at Context.it (test/apps/layout/test.ts:33:10)
      at process._tickCallback (internal/process/next_tick.js:68:7)



error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**

`yarn test`

**Expected behavior**

all tests should pass

**Information about your Sapper Installation:**
current master

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Sapper entirely?

hard to contribute if tests fail

**Suspected cause**

this line of code:

```js

		await r.sapper.start();
		const text2 = await r.text('#sapper');
		assert.deepEqual(text2.split('\n').map(str => str.trim()).filter(Boolean), [
			'y: bar 1',
			'z: baz 1',
			'goto foo/bar/qux',
			'goto foo/abc/def',
			'child segment: baz'
		]);
```

`text2` has the value `"y: bar 1 z: baz 1 goto foo/bar/qux goto foo/abc/def child segment: baz"` instead of the actual array. i dont know what is going on here.

**Comment by Conduitry** [comment]
I do see this when installing dependencies with Yarn (which I'm assuming is what you're doing, since you're running tests with `yarn test`). So presumably some dependency update results in this error. But you should be installing with npm so that the installation respects the lockfile - and when I do that, the tests pass.

**Comment by sw-yx** [comment]
ohhh ok. gotcha.

**Comment by sw-yx** [comment]
@Conduitry you dont seem to have a CONTRIBUTING doc but this one might be a good one to note.
