### ISSUE TITLE
this.fetch does not respect access control headers

### ISSUE THREAD

**Issue by vjerci** [sveltejs/sapper#929]
**Describe the bug**
When using ssr, this.fetch does not respect access control headers.
Now most of the browsers obviously respect those headers.
On consequitve nav(partial data refersh) i was getting typerrror while on first page load/page would load normally.

**Expected behavior**
Have it resepect those headers.

**Information about your Sapper Installation:**
- Sapper version : 0.27.8

**Severity**
It is minor bug/feature request, but as a newbie to both sapper and svelte it caused me to pull my hair out. 

**Additional context**
Consistency might make a better dev experience

**Comment by aubergene** [comment]
On first load the result of the `<script context="module">` is embedded in the html of the page, so that you don't have to wait for an extra fetch before being able to render JavaScript. I'm guessing that is why you don't see any fetch errors because the fetch isn't happening.

**Comment by benmccann** [comment]
I think this was fixed in Sapper 0.27.14: https://github.com/sveltejs/sapper/blob/master/CHANGELOG.md#02714
