### ISSUE TITLE
Server restarts twice on page save

### ISSUE THREAD

**Issue by aubergene** [sveltejs/sapper#935]
Using the [Rollup template](https://github.com/sveltejs/sapper-template-rollup) I create a new project. I add `console.log('Server restarting')` to `server.js` and when I save a change to `index.svelte` I will see `Server restarting` appear twice.

**Comment by benmccann** [comment]
This is possibly a duplicate of https://github.com/sveltejs/sapper/issues/949?

**Comment by aubergene** [comment]
Just tested with `0.27.0` and it was no longer an issue
