### ISSUE TITLE
Make layout know if it's in error page or home page

### ISSUE THREAD

**Issue by hgl** [sveltejs/sapper#948]
**Is your feature request related to a problem? Please describe.**
I asked this question on [SO](https://stackoverflow.com/questions/58463102/how-does-layout-svelte-know-if-its-in-the-error-page), but doesn't get much attentions.

I want to style the page differently in home and error page, but `segment` is `undefined` in both pagas.

**Describe the solution you'd like**
Either make segment return different values (e.g., `""` vs `undefined`), or another variable saying if the current is error or not.

I lean toward the former.

**How important is this feature to you?**
Giving different layouts to home and error page layout is pretty common I think, and given there doesn't seem to be a workaround, I feel it's pretty important.

**Comment by intrikate** [comment]
On a side note, the `page` store from `@sapper/app` may offer a (slightly hacky) workaround. That being said, the problem surely seems common enough to warrant a better solution. I’d go as far as to say `_error.svelte` should not inherit the common layout by default (we can still import and use it explicitly if we want to).

**Comment by silllli** [comment]
There’s a pull request https://github.com/sveltejs/sapper/pull/962

**Comment by thebells1111** [comment]
PR #1250 may be the solution to this. It separates the `_layout` styling from the `_error` styling.

**Comment by Conduitry** [comment]
`$page.error` is now available in 0.28.9.
