### ISSUE TITLE
Unable to use Prisma2 photon inside server.js

### ISSUE THREAD

**Issue by soullivaneuh** [sveltejs/sapper#959]
**Describe the bug**

I installed prisma2 to have a database alongside my Sapper setup.

Prisma2 works well and Photon works with a single js file ran with `node`.

But if I add a photon connection inside the `server.js`:

```javascript
import sirv from 'sirv';
import polka from 'polka';
import compression from 'compression';
// eslint-disable-next-line import/no-unresolved
import * as sapper from '@sapper/server';

const { PORT, NODE_ENV } = process.env;
const dev = NODE_ENV === 'development';

// PRISMA PHOTON INIT
import { Photon } from '@generated/photon';
const photon = new Photon();
photon.connect();

polka() // You can also use Express
  .use(
    compression({ threshold: 0 }),
    sirv('static', { dev }),
    sapper.middleware(),
  )
  .listen(PORT, (err) => {
    // eslint-disable-next-line no-console
    if (err) console.log('error', err);
  });
```

It crash because of missing `linux-glibc-libssl1.1.0` photon binary.

The photon binary is indeed installed in the `node_modules` path:

```
❯ find . -name '*linux-glibc-libssl1.1.0*'
./node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0
./node_modules/prisma2/build/query-engine-linux-glibc-libssl1.1.0
./node_modules/@generated/photon/runtime/query-engine-linux-glibc-libssl1.1.0
```

I suspect the photon binary to not be copied on the `__sapper__`, causing the issue.

Maybe it is just a wrong usage, and a documentation update would be great in that case. :+1: 

**Logs**

```
Make sure to adjust the generator configuration in the schema.prisma file:,
(node:223) UnhandledPromiseRejectionWarning: Error: Photon binary for current platform linux-glibc-libssl1.1.0 could not be found.,
Photon looked in null but couldn't find it.,
  provider      = "photonjs",
generator photon {,
  binaryTargets = ["native"],
Please run prisma2 generate for your changes to take effect.,
    at NodeEngine.getPrismaPath (webpack:///./node_modules/@generated/photon/runtime/index.js?:13045:23),
},
Read more about deploying Photon: https://github.com/prisma/prisma2/blob/master/docs/core/generators/photonjs.md,
Note, that by providing `native`, Photon automatically resolves `linux-glibc-libssl1.1.0`.,
(node:223) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.,
(node:223) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**To Reproduce**

- Install a fresh sapper template (I use the webpack variant)
- Install prisma2: https://github.com/prisma/prisma2/blob/master/docs/getting-started.md

**Expected behavior**

The photon connection should occur, like it does on a standard js file.

**Information about your Sapper Installation:**
- Your operating system: Linux sweethome 4.19.79-1-MANJARO #1 SMP PREEMPT Fri Oct 11 19:57:09 UTC 2019 x86_64 GNU/Linux
- Your hosting environment: Local
- Sapper version (Please check you can reproduce the issue with the latest release!)
- Svelte version: 0.27
- If it is an exported (npm run export) or dynamic application: dynamic
- Whether your application uses Webpack or Rollup: Webpack

**Severity**

Quite high severity as we can't do anything with Prisma if this is not resolved.

I didn't find any workaround to get it working so far.

**Additional context**

See also https://github.com/prisma/prisma2/issues/818

It is considered as a bug for Prisma2, but it looks like more a Sapper problem.

**Comment by joshnuss** [comment]
Doesn't seem to be an issue with the latest versions of sapper and prisma2.

```
yarn list "sapper|@prisma/cli|@prisma/client"
├─ @prisma/cli@2.0.0-beta.5
├─ @prisma/client@2.0.0-beta.5
└─ sapper@0.27.13
```

# Installing Prisma2 with Sapper

## Setup project

```bash
npx degit sveltejs/sapper-template sapper-prisma2
cd sapper-prisma2
yarn
yarn add -D @prism/cli
yarn add @prism/client # must **not** be a dev dependency
npx primsa generate
```

## Setup environment

In `prisma/.env`:

```
# Adjust for your machine
DATABASE_URL="postgresql://postgres:postgres@localhost:5432/sapper-prisma2?schema=public"
```

## Add a schema

In `prisma/schema.prisma`, add a model:

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id       Int      @default(autoincrement()) @id
  email    String   @unique
}
```

## Generate migration

```
npx prisma migrate save --experimental
``` 

## Migrate up

```
npx prisma migrate up --experimental
```

## Access the database

Database is accessible from anywhere, for example in a route:

```javascript
// src/routes/register.json.js
import { PrismaClient } from '@prisma/client'

const db = new PrismaClient()

export async function post(req, res) {
   const user = await db.user.create({data: JSON.parse(req.body)})     

   res.statusCode = 200
   res.end(JSON.stringify(user))
}
```

**Comment by soullivaneuh** [comment]
I had to changes my plan since this issue so I don't use Prisma anymore.

If you can't reproduce my issue, you may close it.

**Comment by benmccann** [comment]
@soullivaneuh can you close this issue since it's not relevant anymore?
