### ISSUE TITLE
Preload session argument is undefined on page load

### ISSUE THREAD

**Issue by gigatoride** [sveltejs/sapper#961]
The following code doesn't work properly on page load:

```svelte
<script context="module">
	export async function preload(page, session) {
                console.log(session) // undefined on page load!
		const res = await this.fetch(`private/needsession`); // user session needed for this get request
		const article = await res.json();
		return { article };
	}
</script>
```

Sapper version:  0.27.9

I'm trying to make a get request by the user session using preload

Another example with [realworld](https://github.com/sveltejs/realworld/blob/1fd502855b6c4fcfe130d40b78beb7e7e5fa746c/src/routes/profile/%5Buser%5D/%5Bview%5D.svelte#L7) same issue occurs

**Comment by thebells1111** [comment]
Did you pass the` session` to `sapper.middleware` in your `server.js` file?

`session` is generated on the server by the `session` option passed to `sapper.middleware`

On the server, you can populate session by passing an option to sapper.middleware:

```
// src/server.js
express() // or Polka, or a similar framework
	.use(
		serve('static'),
		authenticationMiddleware(),
		sapper.middleware({
			session: (req, res) => ({
				user: req.user
			})
		})
	)
	.listen(process.env.PORT);
```

**Comment by gigatoride** [comment]
@thebells1111 
What I mean is the preload session is already defined on normal navigation. but on page load. sometimes it doesn't,

Some related issues #594  #588 

I'm still investigating this.

**Comment by pngwn** [comment]
Do you have a minimal repro for this?

**Comment by gigatoride** [comment]
I'm not sure if it is a bug yet. currently unable to reproduce the issue.
as I've been using a beta version of Firefox, maybe a cache issue not sure yet.

I will close this issue for now.
