### ISSUE TITLE
Programmatically start/stop Sapper server

### ISSUE THREAD

**Issue by joedakroub** [sveltejs/sapper#964]
Is it possible to programmatically start the Sapper dev server opposed to calling `npm run dev`?

I’d like to be able to load specific Sapper apps from a dashboard, so I need to be able to start a server for whatever app is selected.

**Comment by Conduitry** [comment]
It's not really documented currently other than looking at the code, but you can `require('sapper/api')` and get access to the programmatic API exported from [here](https://github.com/sveltejs/sapper/blob/master/src/api.ts).

**Comment by janosh** [comment]
Had to call it as

```js
import { dev } from 'sapper/api.js'
dev({})
```

(the file `.js` extension was non-optional) as just calling `dev()` would throw

```
  TypeError {
    message: 'Cannot read property \'cwd\' of undefined',
  }

  › new Watcher (node_modules/sapper/dist/dev.js:29:19)
  › dev (node_modules/sapper/dist/dev.js:26:12)
```

Would be cool if this API was async to be able to `await dev({})`.
