### ISSUE TITLE
Dynamic import of CSS breaks inline CSS

### ISSUE THREAD

**Issue by julienchazal** [sveltejs/sapper#965]
**Describe the bug**
When using dynamic import of a css file, `<style>` tag containing critical CSS is no more generated in the `<head>` of the HTML, instead a CSS file is emitted, despite the `emitCss: false` option 
On every route `main.xxxx.css`is emitted, and `maps.xxxx.css`is emitted on `/maps`route.

**Logs**
```bash
Generated an empty bundle
```

**To Reproduce**
```js
// rollup.config.js
...
	svelte({
                preprocess,
                emitCss: false,
		dev,
		hydratable: true
	}),
...
```

```js
// component.svelte
 onMount(async () => {
    await import( 'leaflet.markercluster/dist/MarkerCluster.css').then(module => {});
})
```

**Expected behavior**
`main.xxxx.css` should not be emitted (it's ok to emit `maps.xxx.css` though)
`main.xxx.css`is not emitted when using classic `import`:
```js
    import 'leaflet.markercluster/dist/MarkerCluster.css';
```

**Information about your Sapper Installation:**
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Brave Version 0.70.121 Chromium: 78.0.3904.70 (Build officiel) (64 bits)

- Your operating system: (e.x. OS X 10, Ubuntu Linux 19.10, Windows XP, etc)
MacOs 10.14.3

- Your hosting environment: (i.e. Local, GCP, AWS, Now, etc...)
Local

- Sapper version (Please check you can reproduce the issue with the latest release!)
sapper@^0.27.0:
  version "0.27.9"

- Svelte version (Please check you can reproduce the issue with the latest release!)
svelte@^3.0.0:
  version "3.12.1"

- If it is an exported (npm run export) or dynamic application.
Dynamic (SSR)

- Whether your application uses Webpack or Rollup
Rollup

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Sapper entirely?
Not severe

Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**
```js
// rollup.config.js
import resolve from 'rollup-plugin-node-resolve';
import replace from 'rollup-plugin-replace';
import commonjs from 'rollup-plugin-commonjs';
import svelte from 'rollup-plugin-svelte';
import sveltePreprocess from 'svelte-preprocess';
import babel from 'rollup-plugin-babel';
import { terser } from 'rollup-plugin-terser';
import config from 'sapper/config/rollup.js';
import pkg from './package.json';
import svgicons from 'rollup-plugin-svg-icons'

const mode = process.env.NODE_ENV;
const dev = mode === 'development';
const legacy = !!process.env.SAPPER_LEGACY_BUILD;
const tailwind = require("./tailwind.js");
const purgecss = require('@fullhuman/postcss-purgecss')({

	// Specify the paths to all of the template files in your project
	content: [
		'./src/**/*.html',
		'./src/**/*.svelte'
	],

	// Include any special characters you're using in this regular expression
	defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || []
});

const preprocessDev = sveltePreprocess({
	postcss: {
		plugins: [
			require("tailwindcss")(tailwind),
			require("postcss-nested"),
			require('postcss-preset-env')({
				/* use stage 3 features + css nesting rules */
				stage: 3,
				features: {
					'nesting-rules': true
				}
			}),
		]
	}
});
const preprocessProd = sveltePreprocess({
	postcss: {
		plugins: [
			require("tailwindcss")(tailwind),
			require('postcss-nested'),
			require('postcss-preset-env'),
			purgecss
		]
	}
});

let preprocess = dev ? preprocessDev : preprocessProd;

const onwarn = (warning, onwarn) => (warning.code === 'CIRCULAR_DEPENDENCY' && /[/\\]@sapper[/\\]/.test(warning.message)) || onwarn(warning);
const dedupe = importee => importee === 'svelte' || importee.startsWith('svelte/');

export default {
	client: {
		input: config.client.input(),
		output: config.client.output(),
		plugins: [
			replace({
				'process.browser': true,
				'process.env.NODE_ENV': JSON.stringify(mode)
			}),
			// svgicons({
			// 	inputFolder: 'src/svg',
			// 	output: 'src/components/SpriteSvg.svelte',
			// 	// by default svgo is disabled, to turn it on - pass config object (or just empty object)
			// 	svgo: {
			// 		removeDoctype: true
			// 	}
			// }),
			svelte({
                preprocess,
                emitCss: false,
				dev,
				hydratable: true
			}),
			resolve({
				browser: true,
				dedupe
			}),
			commonjs(),
			legacy && babel({
				extensions: ['.js', '.mjs', '.html', '.svelte'],
				runtimeHelpers: true,
				exclude: ['node_modules/@babel/**'],
				presets: [
					['@babel/preset-env', {
						targets: '> 0.25%, not dead'
					}]
				],
				plugins: [
					'@babel/plugin-syntax-dynamic-import',
					['@babel/plugin-transform-runtime', {
						useESModules: true
					}]
				]
			}),
			!dev && terser({
				module: true
			})
		],

		onwarn,
	},

	server: {
		input: config.server.input(),
		output: config.server.output(),
		plugins: [
			replace({
				'process.browser': false,
				'process.env.NODE_ENV': JSON.stringify(mode)
			}),
			svelte({
				preprocess,
				generate: 'ssr',
				emitCss: false,
				dev
			}),
			resolve({
				dedupe
			}),
			commonjs()
		],
		external: Object.keys(pkg.dependencies).concat(
			require('module').builtinModules || Object.keys(process.binding('natives'))
		),

		onwarn,
	},

	serviceworker: {
		input: config.serviceworker.input(),
		output: config.serviceworker.output(),
		plugins: [
			resolve(),
			replace({
				'process.browser': true,
				'process.env.NODE_ENV': JSON.stringify(mode)
			}),
			commonjs(),
			!dev && terser()
		],

		onwarn,
	}
};
```

**Comment by julienchazal** [comment]
Hello @pngwn , what does "pending clarification" means please ?

**Comment by pngwn** [comment]
It just means I haven't quite worked out what the issue is fully: whether it is a bug, feature request or just requires support. We had a few pages of unlabelled and I went through them last night to try to work out which were bugs/feature/requests/support questions. I'll be revisiting the ones I'm unsure about (like this one) when I get the time, providing no-one beats me to it.

**Comment by pngwn** [comment]
But to follow up, can you explain this a little more clearly? If you are dynamically importing a `css` file it expected that that module will be handled by rollup directly and not svelte. 

The `emitCss` options in rollup-plugin-svelte` and `svelte-loader`  relates to emitting the CSS in component style tags, it doesn't interfere with default bundler behaviour. Dynamic imports, like static imports, are handled by rollup. Svelte does not resolve dependencies, that is delegated to whichever bundler you are using

**Comment by benmccann** [comment]
Recent versions of Sapper have rewritten the CSS handling. I think you can at least dynamically import a JS file that does nothing but import the CSS. I think that means it's probably well enough supported that we wouldn't spend more time on this.
