### ISSUE TITLE
Integrate svelte/sapper with existing express/typescript project

### ISSUE THREAD

**Issue by swallace21** [sveltejs/sapper#966]
Looking through the various issues, I am trying to find a way to integrate Svelte/Sapper with an existing Express/Typescript back-end.

I am totally fine not using typescript in svelte components or client-side.

Great work on svelte btw!

**Comment by FractalHQ** [comment]
[This repo](https://github.com/pyoner/svelte-typescript) is the only way I've managed to get working with both sapper and typescript.
