### ISSUE TITLE
Component rendering accesses store variables before they are ready

### ISSUE THREAD

**Issue by antony** [sveltejs/sapper#967]
**Describe the bug**
If I try something like:

```
<h1>Hello {$session.user.name}</h1>

<script>
import { stores } from '@sapper/app'
</script>
```

in my routes or components, I will get "cannot read property user of null", if I navigate from some other page to that page, unless I refresh/reload that specific page by itself.

**Logs**
```
index.html:6 Uncaught (in promise) TypeError: Cannot read property 'profile' of undefined
    at create_fragment (index.html:6)
    at init (index.mjs:1287)
    at new Index (index.html:27)
    at create_if_block_1$1 (App.svelte:25)
    at Array.create_default_slot_1 (App.svelte:24)
    at create_slot (index.mjs:55)
    at create_fragment (_layout.93388159.js:21)
    at init (index.mjs:1287)
    at new Layout (_layout.93388159.js:142)
    at Object.update [as p] (App.svelte:23)
```

**To Reproduce**
1. Attempt to access a sapper store value in the html part of a route or component.
2. navigate *to* the page via an existing link

**Expected behavior**
I would expect the stores to be populated before the html tries to render, or a better way to access the store value.

**Information about your Sapper Installation:**

- Sapper version 0.27.9 (latest)
- Dynamic app
- Rollup

**Severity**
The workaround is fairly verbose and is one of those gotchas which has no rational explanation, so fairly annoying.

**Comment by antony** [comment]
I think this bug extends further.

If I use $session anywhere in my code in the page navigated to, it is never populated. It's just undefined for the duration.

This means that you can't reliably use $session in a Sapper app.

I'll create a reproduction later on.

**Comment by pngwn** [comment]
This is pretty weird. Are you sure there isn't anything else going on?

If I recall the sapper realword app uses `$session` values directly in the template and everything seems to work even if you navigate to these pages from other pages.

**Comment by antony** [comment]
I guess creating the repro will tell me for sure. It's definitely odd, since I feel like this must have worked at some point.

**Comment by antony** [comment]
As @pngwn had rightly supposed - I've tracked this down to me being over-zealous in parsing out /client/ requests when populating the session in `server.js` from a cookie. So I was actually getting an empty session from the server.

Panic over.
