### ISSUE TITLE
Is it possible to run preload once for completely static html generate when "sapper export" was used?

### ISSUE THREAD

**Issue by emrahyumuk** [sveltejs/sapper#972]
I want to fetch website data from an api. I fetch data on preload and sapper export feature generates static html files. I serve __sapper_/export folder. But it call preload function every routing. I dont want to call api after export. It must be completely static. is it possible on sapper?

**Comment by sw-yx** [comment]
no. but you can save it to disk in a temporary file and then read from that file

**Comment by Conduitry** [comment]
If `preload` is calling `this.fetch` and that's getting a file at a local path, that response will also be saved when export is crawling the site. If the data is coming from a remote server, you can make a local endpoint that proxies to the remote endpoint, and have `this.fetch` request that.

**Comment by janosh** [comment]
This seems like a common enough use case that Sapper should have an API for that. Maybe the ability to `export async function staticPreload() { ... }` alongside the regular `preload` from `<script context="module">`. Perhaps not worth implementing with `svelte-kit` right around the corner. Will that have the means for static preloading?
