### ISSUE TITLE
Project structure for mobile and desktop version?

### ISSUE THREAD

**Issue by zabavnikov** [sveltejs/sapper#977]
Hello!
Has anyone already done something similar? Share your experience. 😊
Thank you!

**Comment by pngwn** [comment]
Please use [stackoverflow](https://stackoverflow.com/) with a [svelte](https://stackoverflow.com/questions/tagged/svelte) or [sapper](https://stackoverflow.com/questions/tagged/sapper) tag or come and ask in our [chatroom](https://svelte.dev/chat) for support requests.

That said apart from the simple rules explained in the documentation, you are free to organise your projects however you wish.
