### ISSUE TITLE
SCSS Support Sapper Rollup (inline styles/entry point imports)

### ISSUE THREAD

**Issue by lucas-hugdahl** [sveltejs/sapper#980]
I am sharing this because I haven't found any docs on this and it took me a while to figure it out myself. When using the rollup-plugin-scss in Sapper+Svelte (or maybe any rollup project?), the examples for the plugin say to set the output path to something like this in your rollup.config:
`scss({
   output: `bundle.css`,
}),`

At first that didn't work so I changed it to this to see what would happen:
`scss({
   output: `static/bundle.css`,
}),`

This worked most of the time on the dev server. The issue with this is that when you build your app, your resources are no longer coming from the 'static' directory. I figured this was the case when my build didn't have any CSS. The output path needs to be dynamic for both the client config and the server config in the rollup.config. Below are my working output paths. With this, you can import SCSS files into your entry points as well as write SCSS in your svelte components.  Hope this saved someone some time! 
```
//client config obj in rollup.config
scss({
   output: `${config.client.output()}/vendors.css`,
}),  

//server config obj in rollup.config
scss({
   output: `${config.server.output()}/vendors.css`,
}),  
```

**Comment by PierBover** [comment]
Actually it's `config.client.output().dir`.

**Comment by webfrank** [comment]
Hi, with this configuration how do you handle sass inside components?

Do you use:
`<style language="scss">
...
</style>`

tag?

**Comment by PierBover** [comment]
Yeah.

See this Rollup config:

It's not using Sapper but the idea is the same. You use preprocess and pass it to the Svelte compiler.

https://github.com/PierBover/svelte-ssr-example/blob/master/rollup.config.js#L13-L22
