### ISSUE TITLE
Session management with JWT api auth (FeatherJS)

### ISSUE THREAD

**Issue by soullivaneuh** [sveltejs/sapper#987]
I am trying to setup a Sapper project, communicating with a FeatherJS API.

Authentication backend is managed by Feather itself.

I managed client authentication, storing a JWT token on the localStorage, and found a way to re-authenticate on each page load from `_layout.svelte`.

```html
<!-- _layout.svelte -->
<script>
  import Nav from "../components/Nav.svelte";
  import client from '../feathers';
  import { account } from '../stores';

  export let segment;

  const login = async () => {
    try {
      await client.reAuthenticate();
      const { user } = await client.get('authentication');
      account.set(user);
    } catch (e) {}
  }

  login();
</script>
```

```html
<!-- Nav.svelte -->
<script>
  import client from '../feathers';
  import { account } from '../stores';

  let user = null;
  account.subscribe(value => user = value);

  const logout = async () => {
    await client.logout();
    account.set(null);
  }
</script>

<main>
      {#if user}
        {user.email}
        <Button on:click={logout}>Deconnexion</Button>
      {:else}
        <Button href="login">Se connecter</Button>
      {/if}
</main>
```

All seems to work great, except I have page flashes on load, as the connection is done after.

The [doc](https://sapper.svelte.dev/docs#Preloading) is quite light about module preloading and you still have this todo:

> TODO this needs further documentation. Perhaps a server API section?

It would be great to have some integration sample with FeatherJS or equivalent.

I tried this way:

```html
<script context="module">
  import client from '../feathers';

  export async function preload(page, session) {
    let user = null;
    try {
      await client.reAuthenticate();
      const { user } = await client.get('authentication');
    } catch (e) {}

    return { user };
	}
</script>

<script>
  import Nav from "../components/Nav.svelte";
  import { account } from '../stores';

  let user;
  account.set(user);
  export let segment;
</script>
```

But of course, it does not work, certainly because the token is on the local-storage.

Waiting a more detailed documentation, do you have some tips to give about this kind of situation?

**Comment by khpatel4991** [comment]
You have to put selective logic for client and server side implementation. On Client Side when `typeof window !== undefined` read localStorage and query. While on Server, you feather serverside logic of evaluating a session.

**Comment by pngwn** [comment]
Looks like a support and documentation issue. You may have more luck over in our[chatroom](https://svelte.dev/chat).

**Comment by sw-yx** [comment]
@khpatel4991 remember to put `undefined` in a string :)

**Comment by antony** [comment]
@soullivaneuh I wrote part of my talk on this here: https://antony.github.io/svelte-meetup-talk-oct-2019/#6

and there is working implementation here: https://github.com/antony/svelte-meetup-talk-oct-2019/tree/master/sample-app

Have a look at those, and as @pngwn says, find me on discord for further assistance.

**Comment by sw-yx** [comment]
oo nice. antony was this talk recorded?

**Comment by antony** [comment]
@sw-yx It was - but I've not got around to editing it yet, and I realised mid-talk that I was trying to cover a lot of ground so it might be a bit rushed! I'll see what I can do about getting it online though.
