### ISSUE TITLE
ServiceWorking not working in app created with degit sveltejs/sapper-template#rollup

### ISSUE THREAD

**Issue by mvolkmann** [sveltejs/sapper#988]
Steps to reproduce

1. npx degit sveltejs/sapper-template#rollup demo
2. cd demo
3. npm install
4. npm run build
5. npm run start
6. browse localhost:3000 in Chrome
7. open devtools
8. click "Audit" tab
9. press "Run audits" button
10. In "Progressive Web App" section of the report, will see the following:

Current page does not respond with a 200 when offline
start_url does not respond with a 200 when offline
Unable to fetch start URL via service worker.

I expected a clean PWA report showing that ServiceWorker works with no code changes.

**Information about your Sapper Installation:**

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
Chrome Version 78.0.3904.87 (Official Build) (64-bit)

- Your operating system: (e.x. OS X 10, Ubuntu Linux 19.10, Windows XP, etc)
macOS Mojave 10.14.6

- Your hosting environment: (i.e. Local, GCP, AWS, Now, etc...)
Local

- Sapper version (Please check you can reproduce the issue with the latest release!)
0.27.9

- Svelte version (Please check you can reproduce the issue with the latest release!)
3.13.0

- If it is an exported (npm run export) or dynamic application.
dynamic

- Whether your application uses Webpack or Rollup
Rollup

**Severity**
It is blocking me from creating a PWA using Sapper.

**Comment by neoel** [comment]
Weird, i can't reproduce. It does say that index is served when offline in my case

**Comment by ADantes** [comment]
I came across this same issue, but did find a solution.  There were two problems to work through and I'll leave this as a note for anyone else stuck in the same place.

1) Lighthouse doesn't appear to disable the developer settings.  If you have "Bypass for network" enabled under Application > Service Workers and "Disable Cache" under Network, Lighthouse seems to always report this step as a failure.

2) There's a commented out block in the service worker referencing "/service-worker-index.html".  This needs to be uncommented, but "/service-worker-index.html" also needs to be added to the `to_cache` array declared at the top.  Without that second step, there seems to be no path where "/service-worker-index.html" would actually end up in cache.

**Comment by mvolkmann** [comment]
For me this issue seems to be fixed. Following the steps I list in the first post here, the only issues reported in the PWA section of the audit are "Does not redirect HTTP traffic to HTTPS" and "Does not provide a valid apple-touch-icon".

**Comment by mvolkmann** [comment]
This seems to be fixed now.
