### ISSUE TITLE
Ruby on Rails webpack Svelte

### ISSUE THREAD

**Issue by nikolaokonesh** [sveltejs/sapper#989]
Hi! I use Ruby on Rails, and i install 
rails new apps --wepback=svelte

How install sapper.js?

**Comment by magiknono** [comment]
Use rails api back and sapper front. 
Or sapper for landing page/marketing page and a rails app for thé rest

**Comment by pngwn** [comment]
Please use [stackoverflow](https://stackoverflow.com/) with a [svelte](https://stackoverflow.com/questions/tagged/svelte) or [sapper](https://stackoverflow.com/questions/tagged/sapper) tag or come and ask in our [chatroom](https://svelte.dev/chat) for support requests.
