### ISSUE TITLE
Deploying Sapper app to server, particularly IIS/Windows Server with iisnode

### ISSUE THREAD

**Issue by rodoch** [sveltejs/sapper#998]
Javascript on the server is relatively new to me, so this might totally be my own ignorance, but one area in the Sapper docs I find lacking is the info about server deployment (as opposed to the Now deployment instructions, which couldn't be simpler). I found myself wondering what folders I needed to deploy to the server, whether the static folder should be stored inside the \_\_sapper\_\_/build directory or at the project root etc. 

In any case, this is not so much an issue as just a piece of advice I wanted to leave for anyone who is searching this repo for answers in the future, like I was yesterday. I'm running a Sapper app on IIS/Windows Server with [iisnode](https://github.com/Azure/iisnode). 

There are three things you need to get a Sapper app running with iisnode: 

1. Directory structure. You need the following minimal directory structure in the physical file path of your website on IIS.

```
- __sapper__/
- static/
- package.json
- package-lock.json
```

The src directory is not required. If you don't want to copy your node_modules folder you can just navigate to this directory on the server and run `npm install` and one will be generated. iisnode will automatically create an iisnode directory when you first run the application also. We will add some additional files to this directory in the next steps.

2. As per iisnode instructions, add a web.config file to the website root (i.e. / and *not* the /__sapper/build/ directory). A minimal working config is given below. The issnode handler means that iisnode will handle incoming requests. The rewrite rule is necessary to forward all requests to the Sapper server script. The app.js script mentioned in the config does not exist yet, we will create that in the next step.

```xml
<?xml version="1.0" encoding="utf-8"?> 
<configuration>
  <system.webServer>
    <handlers>
      <add name="iisnode" path="app.js" verb="*" modules="iisnode"/>
     </handlers>
     <rewrite>
      <rules>
       <rule name="app">
         <match url="/*" />
         <action type="Rewrite" url="app.js"/>
        </rule>
      </rules>
    </rewrite>
    <httpErrors existingResponse="PassThrough" />
  </system.webServer>
</configuration>
```

3. Add an app.js file to the root directory. It contains a one-line script:

```js
require('./__sapper__/build/index.js');
```

This is not how you normally do things in Sapper but the way IIS, iisnode and Sapper interact seem to make it necessary. See this [GitHub issue](https://github.com/tjanczuk/iisnode/issues/338) for more information.

Your final directory structure, after you have run your app for the first time, will look like this:

```
- __sapper__/
- iisnode/
- node_modules/
- static/
- app.js
- package.json
- package-lock.json
- web.config
```

**Comment by antony** [comment]
This would probably be better written in the docs rather than a github issue. Your effort is appreciated, but this isn't really a suitable place for this.

Would you be interested in opening a PR on the docs/site for this?

**Comment by rodoch** [comment]
I would be happy to do this if there is an interest there. I know framework docs tend try and avoid getting stuck in the mud with platform-specific implementation details so I'll try and keep it brief and general, but useful. I feel the current approach is a bit 'just do this' for new users, it that makes sense. I will mark this as closed and open a new PR later in the month.
